/** Platform-wide authored educational sets. Sources checked 2026-09-08; no clinical reviewer is claimed. */
const ox=(section)=>`https://openstax.org/books/anatomy-and-physiology-2e/pages/${section}`
export const FOUNDATION_TOPICS=[
 ['cells','Cell essentials','3-2-the-cytoplasm-and-cellular-organelles',[
  ['Nucleus','Compartment containing most cellular DNA'],['Ribosome','Site of protein translation'],['Mitochondrion','Organelle associated with aerobic ATP production'],['Lysosome','Organelle containing digestive enzymes'],['Cytosol','Fluid portion of the cytoplasm'],['Golgi','Apparatus that modifies and sorts proteins'],['Vesicle','Small membrane-bound transport compartment'],['Cristae','Folds of the inner mitochondrial membrane']]],
 ['heart','Heart and circulation','19-1-heart-anatomy',[
  ['Atrium','Heart chamber that receives returning blood'],['Ventricle','Heart chamber that pumps blood into an artery'],['Aorta','Main artery leaving the left ventricle'],['Tricuspid','Valve between the right atrium and ventricle'],['Mitral','Valve between the left atrium and ventricle'],['Septum','Partition separating right and left heart chambers'],['Myocardium','Muscular layer of the heart wall'],['Pericardium','Sac enclosing the heart']]],
 ['nerves','Nerve signals','12-2-nervous-tissue',[
  ['Neuron','Cell specialised for transmitting nervous signals'],['Axon','Neuronal process conducting signals away from the cell body'],['Dendrite','Branched neuronal process that commonly receives signals'],['Myelin','Insulating sheath surrounding many axons'],['Synapse','Junction where a neuron communicates with a target'],['Soma','Cell body of a neuron'],['Glia','Supporting cells of nervous tissue'],['Schwann','Cell that forms peripheral nervous system myelin']]],
 ['kidney','Kidney foundations','25-4-microscopic-anatomy-of-the-kidney',[
  ['Nephron','Functional unit of the kidney'],['Glomerulus','Capillary tuft where renal filtration begins'],['Podocyte','Specialised cell surrounding glomerular capillaries'],['Filtrate','Fluid that has crossed the glomerular filtration barrier'],['Cortex','Outer region of the kidney'],['Medulla','Inner region containing renal pyramids'],['Loop','Nephron segment descending into and ascending from the medulla'],['Capsule','Structure surrounding the glomerulus and collecting filtrate']]],
 ['breathing','Breathing basics','22-3-the-process-of-breathing',[
  ['Diaphragm','Principal muscle of quiet inspiration'],['Inspiration','Movement of air into the lungs'],['Expiration','Movement of air out of the lungs'],['Ventilation','Bulk movement of air into and out of the lungs'],['Compliance','Ease with which the lungs expand'],['Pressure','Force per unit area that helps drive airflow'],['Volume','Amount of space occupied by gas'],['Elasticity','Tendency of lung tissue to recoil after stretching']]],
 ['digestion','Digestive processes','23-2-digestive-system-processes-and-regulation',[
  ['Ingestion','Entry of food into the mouth'],['Mastication','Mechanical breakdown of food by chewing'],['Peristalsis','Propulsive waves of smooth muscle contraction'],['Segmentation','Intestinal contractions that mix contents'],['Absorption','Movement of digested nutrients into blood or lymph'],['Defecation','Elimination of faeces from the body'],['Digestion','Mechanical and chemical breakdown of food'],['Bolus','Mass of chewed food prepared for swallowing']]],
 ['bone','Bone structure','6-3-bone-structure',[
  ['Osteon','Cylindrical structural unit of compact bone'],['Osteocyte','Mature bone cell within a lacuna'],['Lacuna','Small space housing a bone cell'],['Canaliculi','Tiny channels connecting bone cell spaces'],['Periosteum','Connective tissue covering the outer bone surface'],['Diaphysis','Shaft of a long bone'],['Epiphysis','End region of a long bone'],['Trabeculae','Supporting plates and struts of spongy bone']]],
 ['muscle','Muscle contraction','10-3-muscle-fiber-contraction-and-relaxation',[
  ['Actin','Major protein of the thin myofilament'],['Myosin','Motor protein of the thick myofilament'],['Troponin','Regulatory protein complex that binds calcium'],['Tropomyosin','Protein that covers actin binding sites at rest'],['Sarcomere','Contractile unit between two Z discs'],['Calcium','Ion that initiates exposure of actin binding sites'],['ATP','Energy carrier needed for cross-bridge cycling'],['Relaxation','Return towards the resting state after activation ends']]],
 ['endocrine','Endocrine pancreas','17-9-the-endocrine-pancreas',[
  ['Insulin','Pancreatic hormone that lowers blood glucose'],['Glucagon','Pancreatic hormone that raises blood glucose'],['Islets','Clusters of endocrine cells in the pancreas'],['Beta','Pancreatic islet cell type that secretes insulin'],['Alpha','Pancreatic islet cell type that secretes glucagon'],['Glycogen','Storage polymer of glucose'],['Glucose','Blood sugar regulated by insulin and glucagon'],['Somatostatin','Hormone secreted by pancreatic delta cells']]],
 ['tissues','Tissue families','4-1-types-of-tissues',[
  ['Epithelium','Tissue covering surfaces and lining cavities'],['Connective','Tissue family that supports and binds other tissues'],['Muscle','Tissue family specialised for contraction'],['Nervous','Tissue family specialised for electrical communication'],['Histology','Study of the microscopic organisation of tissues'],['Ectoderm','Embryonic germ layer giving rise to epidermis and nervous tissue'],['Mesoderm','Embryonic germ layer giving rise to muscle and much connective tissue'],['Endoderm','Embryonic germ layer forming much of the digestive tract lining']]],
].map(([id,title,section,terms])=>({id,title,source:{label:'OpenStax · Anatomy and Physiology 2e',url:ox(section)},terms:terms.map(([term,def],i)=>({id:`foundation-${id}-${i}`,term,def,ar:'',defAr:'',category:'Directional & anatomy'}))}))
const sequenceData=[
 ['pulmonary-flow','Pulmonary circulation','19-1-heart-anatomy','Trace blood from the right ventricle to the left atrium.',['Right ventricle','Pulmonary trunk','Pulmonary arteries','Pulmonary capillaries','Pulmonary veins','Left atrium']],
 ['systemic-flow','Systemic circulation','20-2-blood-flow-blood-pressure-and-resistance','Trace the systemic circuit from the left ventricle.',['Left ventricle','Aorta','Systemic arteries','Arterioles','Systemic capillaries','Venules','Veins','Right atrium']],
 ['cardiac-signal','Cardiac conduction','19-2-cardiac-muscle-and-electrical-activity','Order these landmarks in normal cardiac conduction.',['Sinoatrial node','Atrial myocardium','Atrioventricular node','Atrioventricular bundle','Bundle branches','Purkinje fibres']],
 ['filtrate-route','Through the nephron','25-4-microscopic-anatomy-of-the-kidney','Trace filtrate from the renal corpuscle towards a collecting duct.',['Capsular space','Proximal convoluted tubule','Descending limb','Ascending limb','Distal convoluted tubule','Collecting duct']],
 ['food-route','The food journey','23-2-digestive-system-processes-and-regulation','Order the major regions traversed by swallowed food.',['Mouth','Pharynx','Oesophagus','Stomach','Small intestine','Large intestine','Rectum','Anal canal']],
 ['protein-export','A secreted protein’s route','3-2-the-cytoplasm-and-cellular-organelles','Follow a protein destined for secretion.',['Translation at rough ER ribosomes','Processing within the rough ER','Transport vesicle to the Golgi','Sorting in the Golgi apparatus','Secretory vesicle reaches the cell surface','Fusion and release by exocytosis']],
 ['signal-route','Along a typical neuron','12-2-nervous-tissue','Trace the usual flow of information through a neuron.',['Input at dendrites','Integration at the cell body','Action potential begins at the trigger zone','Propagation along the axon','Signal reaches axon terminals','Communication with the next cell']],
 ['breath-in','Quiet inspiration','22-3-the-process-of-breathing','Order the changes that bring air into the lungs.',['Diaphragm contracts','Thoracic volume increases','Lungs expand','Alveolar pressure falls below atmospheric pressure','Air flows into the lungs']],
 ['crossbridge','One cross-bridge cycle','10-3-muscle-fiber-contraction-and-relaxation','Start with ATP binding to an attached myosin head.',['ATP binds to myosin','Myosin detaches from actin','ATP hydrolysis energises the head','Myosin binds an exposed actin site','Phosphate release accompanies the power stroke','ADP leaves the myosin head']],
 ['handwash','Handwashing essentials',null,'Order the broad phases of soap-and-water handwashing.',['Wet hands','Apply soap','Thoroughly rub palms, backs, between fingers, thumbs and fingertips','Rinse away the soap','Dry with a single-use towel','Use the towel to close a manual tap']],
]
const mechanismData=[
 ['inspiration','Why air enters the lungs','22-3-the-process-of-breathing',['Diaphragm contraction enlarges the thorax','Lung volume increases','Alveolar pressure becomes lower than atmospheric pressure','Air flows inward down the pressure gradient']],
 ['expiration','Elastic recoil','22-3-the-process-of-breathing',['Inspiratory muscles relax during quiet breathing','Elastic tissues recoil','Lung volume decreases','Alveolar pressure rises above atmospheric pressure','Air flows out']],
 ['insulin','After blood glucose rises','17-9-the-endocrine-pancreas',['Blood glucose rises after a meal','Pancreatic beta cells increase insulin release','Insulin promotes glucose uptake and storage','Blood glucose moves back towards its regulated range']],
 ['glucagon','Between meals','17-9-the-endocrine-pancreas',['Blood glucose falls','Pancreatic alpha cells release glucagon','The liver increases glucose production and release','Blood glucose rises towards its regulated range']],
 ['depolarisation','The rising action potential','12-4-the-action-potential',['Depolarisation reaches threshold','Voltage-gated sodium channels open','Sodium enters the neuron','Membrane potential becomes more positive']],
 ['repolarisation','Returning from the spike','12-4-the-action-potential',['Sodium channels inactivate near the peak','Voltage-gated potassium conductance rises','Potassium leaves the neuron','Membrane potential becomes more negative']],
 ['contraction','Calcium starts contraction','10-3-muscle-fiber-contraction-and-relaxation',['Cytosolic calcium increases','Calcium binds to troponin','Tropomyosin moves away from binding sites','Myosin can bind to actin','Cross-bridge cycling produces force']],
 ['relaxation','Calcium and relaxation','10-3-muscle-fiber-contraction-and-relaxation',['Muscle fibre stimulation stops','Calcium is pumped into the sarcoplasmic reticulum','Calcium dissociates from troponin','Tropomyosin covers actin binding sites','Cross-bridge cycling diminishes and the fibre relaxes']],
 ['adh','Conserving water','25-8-endocrine-regulation-of-kidney-function',['ADH acts on collecting duct principal cells','Aquaporin-2 channels are inserted into the apical membrane','Water permeability of the duct increases','More water is reabsorbed along the osmotic gradient','Urine becomes more concentrated']],
 ['fibrin','Stabilising a clot','18-5-hemostasis',['Coagulation reactions activate factor X','Prothrombinase converts prothrombin to thrombin','Thrombin converts fibrinogen to fibrin','Fibrin is cross-linked','A stabilised fibrin network supports the clot']],
]
const makeOrder=(rows,kind)=>rows.map(([id,title,section,promptOrSteps,steps])=>({id:`foundation-${kind}-${id}`,kind,title,subjectId:'fnd',topic:title,summary:'A short foundation sequence.',source:{label:section?'OpenStax · Anatomy and Physiology 2e':'WHO · Hand hygiene',url:section?ox(section):'https://www.who.int/publications/m/item/how-to-handwash',reviewedBy:'Source checked by Codex · not clinically peer reviewed',reviewedAt:'2026-09-08'},prompt:steps?promptOrSteps:'Arrange this simplified cause-and-effect pathway.',steps:(steps??promptOrSteps).map((text,i)=>({id:`step-${i}`,text})),explanation:steps?'Follow the route shown by the source. This exercise simplifies the pathway to its listed landmarks.':'Each step explains the next in this simplified physiological mechanism.'}))
export const FOUNDATION_ORDER_PACKS=[...makeOrder(sequenceData,'clinical_sequence'),...makeOrder(mechanismData,'mechanism_chain')]
const safety=[
 ['stroke','Stroke warning signs','stroke/', ['Sudden one-sided facial droop with arm weakness','New slurred speech with sudden weakness'],['Well person attending planned blood-pressure follow-up','Well person requesting stroke-prevention education']],
 ['chest','Possible heart attack','heart-attack/', ['Persistent chest pressure with sweating and nausea','Chest tightness spreading to the jaw with breathlessness'],['Asymptomatic person attending scheduled cholesterol review','Well person requesting information about exercise']],
 ['allergy','Severe allergic reaction','anaphylaxis/', ['Sudden tongue swelling and difficulty breathing after a sting','Collapse shortly after exposure to a known allergen'],['Well person practising with an auto-injector trainer','Well person checking their allergy action plan']],
 ['infection','Recognising possible sepsis','sepsis/', ['Suspected infection with new confusion and rapid breathing','Infection symptoms with blue or blotchy skin and marked deterioration'],['Well person attending a planned vaccination appointment','Recovered person attending arranged follow-up with no new symptoms']],
 ['asthma','Asthma deterioration','asthma/', ['Breathing worsens despite the maximum reliever dose in the action plan','Severe asthma symptoms with no reliever inhaler available'],['Well person attending a scheduled inhaler-technique check','Symptom-free person reviewing their written action plan']],
 ['meningitis','Meningitis warning signs','meningitis/', ['Fever, severe headache and neck stiffness','Fever with a non-blanching rash and increasing drowsiness'],['Well person asking about meningitis vaccination','Well person seeking general infection-prevention advice']],
 ['pregnancy','Ectopic pregnancy emergencies','ectopic-pregnancy/symptoms/', ['Possible pregnancy with sudden severe abdominal pain and fainting','Possible pregnancy with sharp abdominal pain and marked dizziness'],['Well person requesting preconception advice','Asymptomatic person attending a routine antenatal visit']],
 ['dka','Possible ketoacidosis','diabetic-ketoacidosis/', ['Diabetes with vomiting, deep breathing and fruity breath','Diabetes with high ketones and increasing drowsiness'],['Well person practising ketone-meter use','Well person discussing an established sick-day plan']],
 ['bleeding','Upper gastrointestinal bleeding','vomiting-blood/', ['Vomiting blood with dizziness and cold clammy skin','Vomiting blood with black stools and rapid breathing'],['Well person reviewing a previously agreed medication list','Asymptomatic person attending planned nutrition counselling']],
 ['spine','Back pain red flags','back-pain/', ['Back pain with new loss of bladder control and saddle numbness','Back pain with weakness or numbness in both legs and bowel changes'],['Well person requesting advice on workplace posture','Pain-free person attending a planned exercise review']],
]
export const FOUNDATION_RED_FLAG_PACKS=safety.map(([id,title,path,urgent,routine])=>({id:`foundation-red_flag_sort-${id}`,kind:'red_flag_sort',title,subjectId:'fnd',topic:title,summary:'Recognise an emergency signal in a clearly defined learning scenario.',prompt:'Sort these scenarios into emergency assessment or a planned, non-acute visit. Do not wait for every warning sign to appear.',source:{label:'NHS · symptoms and emergency guidance',url:`https://www.nhs.uk/conditions/${path}`,reviewedBy:'Source checked by Codex · not clinically peer reviewed',reviewedAt:'2026-09-08'},lanes:{urgent:'Emergency assessment',routine:'Planned non-acute visit'},findings:[...urgent.map((text,i)=>({id:`urgent-${i}`,text,lane:'urgent',rationale:'These warning signs warrant immediate emergency assessment. Do not delay for the full set of symptoms.'})),...routine.map((text,i)=>({id:`routine-${i}`,text,lane:'routine',rationale:'This scenario explicitly describes a well person without acute symptoms. New symptoms would require reassessment.'}))]}))
