#!/usr/bin/env python3
"""Regenerate PRE-EXTRACTED.md from whatever is currently cached in scripts/alexandria/pagetext/.

Not one of the copied Kasr tools — a small local helper for this lane's manifest-of-what's-cached
deliverable (LANE-BRIEF.md §4 "Part A" step 2). Safe to re-run any time after caching more
sources; it only reads the cache and the four Alexandria manifests, never writes to either.
"""
import glob
import json
import os
import re
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
MANIFEST_DIR = os.path.join(REPO, "docs/Alexandria-Source-Imports/manifest")
CACHE = os.path.join(HERE, "..", "pagetext")
OUT = os.path.join(HERE, "PRE-EXTRACTED.md")

WORD = re.compile(r"[^\W\d_]{3,}", re.UNICODE)


def load_sources():
    by_id = {}
    for name in ("au-y1-sources.json", "au-y2-sources.json", "au-y3-sources.json",
                 "au-general-sources.json"):
        path = os.path.join(MANIFEST_DIR, name)
        if not os.path.exists(path):
            continue
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        for s in data["sources"]:
            by_id[s["sourceId"]] = s
    return by_id


def main():
    by_id = load_sources()
    rows = []
    for path in sorted(glob.glob(os.path.join(CACHE, "*.json"))):
        doc = json.load(open(path, encoding="utf-8"))
        sid = doc["sourceId"]
        meta = by_id.get(sid, {})
        text = "".join(doc["pages"])
        words = len(WORD.findall(text))
        rows.append({
            "moduleId": meta.get("moduleId"),
            "category": meta.get("category"),
            "sourceId": sid,
            "mode": doc["mode"],
            "pages": len(doc["pages"]),
            "words": words,
            "emptyPages": len(doc.get("emptyPages", [])),
            "unreadablePages": len(doc.get("unreadablePages", [])),
            "path": meta.get("corpusRelativePath"),
        })

    rows.sort(key=lambda r: (str(r["moduleId"]), str(r["category"]), -r["words"]))
    blank = [r for r in rows if r["words"] == 0]

    lines = []
    lines.append("# Pre-extracted page text — cache manifest")
    lines.append("")
    lines.append("Generated by `scripts/alexandria/extract/build_pre_extracted.py` from whatever is")
    lines.append("currently in `scripts/alexandria/pagetext/`. Re-run it after caching more sources with")
    lines.append("`scripts/alexandria/extract/pagetext.py` to refresh this table — it never writes to the")
    lines.append("cache or the manifests, only reads them.")
    lines.append("")
    lines.append("Word count = regex `[^\\W\\d_]{3,}` matches over the concatenated page text (the same")
    lines.append("metric `pagetext.py`'s own readability check uses).")
    lines.append("")
    lines.append("| moduleId | category | sourceId | mode | pages | words | empty | unreadable | file |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append("| %s | %s | %s | %s | %d | %d | %d | %d | %s |" % (
            r["moduleId"], r["category"], r["sourceId"], r["mode"], r["pages"], r["words"],
            r["emptyPages"], r["unreadablePages"], r["path"]))

    lines.append("")
    lines.append("## Blank papers (0 words extracted)")
    lines.append("")
    if blank:
        for r in blank:
            lines.append("- `%s` (%s, %s) -- %s" % (r["sourceId"], r["moduleId"], r["category"], r["path"]))
    else:
        lines.append("None. Every cached source extracted at least some words.")

    lines.append("")
    lines.append("## Totals by module")
    lines.append("")
    by_mod = defaultdict(lambda: {"n": 0, "native": 0, "ocr": 0, "words": 0})
    for r in rows:
        m = by_mod[r["moduleId"]]
        m["n"] += 1
        m["native"] += r["mode"] == "native"
        m["ocr"] += r["mode"] == "ocr"
        m["words"] += r["words"]
    lines.append("| moduleId | papers cached | native | ocr | total words | min words on any one paper |")
    lines.append("|---|---|---|---|---|---|")
    for mod in sorted(by_mod, key=lambda x: (x is None, x)):
        m = by_mod[mod]
        mins = min((r["words"] for r in rows if r["moduleId"] == mod), default=0)
        lines.append("| %s | %d | %d | %d | %d | %d |" % (mod, m["n"], m["native"], m["ocr"], m["words"], mins))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s (%d rows, %d blank)" % (OUT, len(rows), len(blank)))


if __name__ == "__main__":
    main()
