package com.nishany.android.feature.root

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.nishany.android.AppGraph
import kotlinx.coroutines.launch

/** The disclaimer's actual copy -- shared by the first-launch gate below and the read-only re-view Settings offers under About, so the two can never drift apart. */
@Composable
fun AiDisclaimerContent() {
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        Text("Nishany uses AI", style = MaterialTheme.typography.titleLarge)
        Text(
            "Explanations, hints, and some review features in this app are generated by AI models, not written by a person for your question specifically.",
            style = MaterialTheme.typography.bodyMedium,
        )
        Text(
            "AI can be wrong, including about medicine. Always check anything that matters for your exams or your patients against your course material.",
            style = MaterialTheme.typography.bodyMedium,
        )
        Text(
            "What you type to the assistant is sent to Nishany's AI provider to generate a response; it is not used to publish or share your identity.",
            style = MaterialTheme.typography.bodySmall,
        )
    }
}

/**
 * Shown once, on the first signed-in launch after `aiConsentAt` is still
 * null -- see [AiConsentGate]. Accepting calls `POST /api/me/consent/ai` and
 * only then lets the caller through; there is no "skip" here; a student who
 * declines simply hasn't opened the app yet, in the sense that matters for
 * this gate.
 */
@Composable
fun AiDisclaimerScreen(onAccept: () -> Unit, accepting: Boolean) {
    Scaffold { padding ->
        Column(
            modifier = Modifier.padding(padding).fillMaxSize().padding(24.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp),
        ) {
            AiDisclaimerContent()
            Spacer(modifier = Modifier.weight(1f))
            Button(onClick = onAccept, enabled = !accepting, modifier = Modifier.fillMaxWidth()) {
                Text(if (accepting) "Saving…" else "I understand, continue")
            }
        }
    }
}

/** The same copy, re-openable any time from Settings' About section -- view-only, since accepting again records nothing new. */
@Composable
fun AiDisclaimerDialog(onDismiss: () -> Unit) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("AI in Nishany") },
        text = { AiDisclaimerContent() },
        confirmButton = { TextButton(onClick = onDismiss) { Text("Close") } },
    )
}

/**
 * Wraps [content], holding it back behind [AiDisclaimerScreen] exactly once:
 * on a signed-in launch where `GET /api/me`'s `profile.aiConsentAt` is still
 * null.
 *
 * The check runs once per arrival at the signed-in shell (`LaunchedEffect(Unit)`
 * inside a composable that itself only enters composition once per sign-in),
 * not on every foreground -- a student who has accepted stays accepted for
 * the rest of this session without a repeat network round trip.
 *
 * A failed check -- offline, a dropped connection -- fails open: [content]
 * draws normally rather than stranding an offline student behind a gate that
 * cannot resolve. The gate exists to record consent before the assistant is
 * used, not to block the rest of the offline-first app over it.
 */
@Composable
fun AiConsentGate(graph: AppGraph, content: @Composable () -> Unit) {
    var checked by remember { mutableStateOf(false) }
    var needsConsent by remember { mutableStateOf(false) }
    var accepting by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()

    LaunchedEffect(Unit) {
        val profile = runCatching { graph.api.me().profile }.getOrNull()
        needsConsent = profile != null && profile.aiConsentAt == null
        checked = true
    }

    when {
        !checked -> Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { CircularProgressIndicator() }

        needsConsent -> AiDisclaimerScreen(
            accepting = accepting,
            onAccept = {
                accepting = true
                scope.launch {
                    // Best-effort: a failed write here is not worth blocking
                    // on a second time -- the next launch's check will simply
                    // ask again, which is the same as any other lost write to
                    // a document this app doesn't queue offline.
                    runCatching { graph.api.consentAi() }
                    needsConsent = false
                    accepting = false
                }
            },
        )

        else -> content()
    }
}
