package com.nishany.android.core.reader

import kotlin.math.floor
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.min

/** A point in page space. [pressure] is captured for future use but never stored -- [encode] writes x and y only, matching web and iOS. */
data class InkPoint(val x: Double, val y: Double, val pressure: Double? = null)

/**
 * A stroke, small enough to store thousands of.
 *
 * A byte-compatible port of `src/lib/reader/strokeCodec.ts` (mirrored by iOS
 * `Core/Reader/StrokeCodec.swift`). Three stages, each cheap and reversible:
 *
 * 1. **Simplify** -- Ramer-Douglas-Peucker, which typically removes half the
 *    samples with no visible change to the line.
 * 2. **Quantise** -- multiply by 4096 and round. One unit is about 0.05mm on
 *    A4: finer than a nib, and far finer than anyone can see.
 * 3. **Delta-encode** -- each point as its offset from the last.
 *
 * The result stays a plain array of small integers, exactly as the other two
 * clients store it, so a stroke drawn here decodes correctly on web/iOS and
 * vice versa. See `StrokeCodecTest` for a cross-checked vector generated by
 * running the actual `src/lib/reader/strokeCodec.ts` in Node.
 */
object StrokeCodec {

    /** 1/4096 of a page width. Below the resolution of any pen or any eye. */
    const val QUANTUM: Double = 4096.0

    /**
     * Matches JavaScript's `Math.round`, which is `floor(x + 0.5)` -- half
     * rounds *up*, toward positive infinity. Kotlin's `kotlin.math.round`
     * rounds half to even, so it must not be used here: the two would
     * disagree on exactly `-n.5`, and two encoders producing different
     * integers for the same stroke is the kind of drift that makes a later
     * comparison mysteriously fail.
     */
    fun quantise(value: Double): Int = floor(value * QUANTUM + 0.5).toInt()

    fun dequantise(value: Int): Double = value / QUANTUM

    /** `[x0, y0, dx1, dy1, ...]` -- the shape stored on an ink object's `p`. */
    fun encode(points: List<InkPoint>): List<Int> {
        if (points.isEmpty()) return emptyList()
        val out = ArrayList<Int>(points.size * 2)
        var lastX = 0
        var lastY = 0
        for ((index, point) in points.withIndex()) {
            val x = quantise(point.x)
            val y = quantise(point.y)
            if (index == 0) {
                out.add(x)
                out.add(y)
            } else {
                out.add(x - lastX)
                out.add(y - lastY)
            }
            lastX = x
            lastY = y
        }
        return out
    }

    fun decode(encoded: List<Int>): List<InkPoint> {
        val points = ArrayList<InkPoint>()
        var x = 0
        var y = 0
        var index = 0
        while (index + 1 < encoded.size) {
            if (index == 0) {
                x = encoded[0]
                y = encoded[1]
            } else {
                x += encoded[index]
                y += encoded[index + 1]
            }
            points.add(InkPoint(dequantise(x), dequantise(y)))
            index += 2
        }
        return points
    }

    /**
     * Move an encoded stroke without decoding it. Only the first pair is
     * absolute -- every other entry is an offset from the one before -- so
     * moving a whole stroke is two additions, whatever its length.
     */
    fun translate(encoded: List<Int>, dx: Double, dy: Double): List<Int> {
        if (encoded.size < 2) return encoded
        val out = encoded.toMutableList()
        out[0] = out[0] + quantise(dx)
        out[1] = out[1] + quantise(dy)
        return out
    }

    /**
     * Ramer-Douglas-Peucker. `epsilon` is in page-space units, so it means
     * the same thing on every document: 0.0006 of a page width is well under
     * a pixel at 4x zoom.
     */
    fun simplify(points: List<InkPoint>, epsilon: Double = 0.0006): List<InkPoint> {
        if (points.size <= 2) return points

        val keep = BooleanArray(points.size)
        keep[0] = true
        keep[points.size - 1] = true

        // Iterative rather than recursive: a long stroke is thousands of
        // samples, and the recursion depth is data-dependent.
        val stack = ArrayDeque<Pair<Int, Int>>()
        stack.addLast(0 to points.size - 1)
        while (stack.isNotEmpty()) {
            val (start, end) = stack.removeLast()
            var furthest = -1
            var distance = epsilon

            var index = start + 1
            while (index < end) {
                val candidate = pointToSegment(points[index], points[start], points[end])
                if (candidate > distance) {
                    distance = candidate
                    furthest = index
                }
                index++
            }

            if (furthest == -1) continue
            keep[furthest] = true
            stack.addLast(start to furthest)
            stack.addLast(furthest to end)
        }

        return points.filterIndexed { i, _ -> keep[i] }
    }

    /** Perpendicular distance from a point to a segment, or to its nearer end. */
    fun pointToSegment(point: InkPoint, a: InkPoint, b: InkPoint): Double {
        val dx = b.x - a.x
        val dy = b.y - a.y
        val lengthSquared = dx * dx + dy * dy
        if (lengthSquared == 0.0) return hypot(point.x - a.x, point.y - a.y)

        var t = ((point.x - a.x) * dx + (point.y - a.y) * dy) / lengthSquared
        t = min(max(t, 0.0), 1.0)
        return hypot(point.x - (a.x + t * dx), point.y - (a.y + t * dy))
    }

    /** The bounding box of a stroke, padded by half its width -- cached on every ink object so culling and hit-testing can reject a mark without decoding its points. */
    fun bounds(points: List<InkPoint>, padding: Double = 0.0): List<Double> {
        val first = points.firstOrNull() ?: return listOf(0.0, 0.0, 0.0, 0.0)
        var minX = first.x
        var minY = first.y
        var maxX = first.x
        var maxY = first.y
        for (point in points.drop(1)) {
            minX = min(minX, point.x)
            minY = min(minY, point.y)
            maxX = max(maxX, point.x)
            maxY = max(maxY, point.y)
        }
        return listOf(minX - padding, minY - padding, maxX + padding, maxY + padding)
    }
}
