/**
 * `101 ISK > Anatomy > Upper Limb > Joints of Upper Limb` — the question books' MCQs.
 *
 * Twenty-three rows, but far fewer distinct questions: the books ask "which
 * type is this joint" in four near-identical wordings and "the elbow joint
 * is" twice. That repetition is the point of reading a question book at all,
 * and it says plainly what this faculty examines here — joint type first,
 * permitted movement second, and only then the two ligaments it cares about,
 * the radial collateral and the anular.
 *
 * `elbow-joint-type-bones-ligaments` is not minted here. It already exists,
 * from the 2025 end-of-year paper, and its definition below is copied verbatim
 * so re-emitting it changes nothing except adding these occurrences to its
 * exam signal.
 *
 * Ten answers are overridden. The DEP BOOK rows in this leaf carry answers the
 * extractor read off the page margin rather than a key, and several of them
 * are flatly wrong — "the elbow joint is: ball and socket" is one. Every
 * override says so rather than absorbing it.
 */
import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Joints of Upper Limb',
  modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
  articleId: 'ART-101-ANA-ELBOW-JOINT',

  concepts: [
    {
      key: 'elbow-joint-type-bones-ligaments',
      label: 'The elbow is a synovial hinge between humerus, ulna and radius, held by collateral ligaments',
      definition: 'The elbow is a synovial joint of hinge type, between the trochlea and capitulum of the humerus above and the trochlear notch of the ulna and the head of the radius below. The radial collateral ligament runs from the lateral epicondyle to the anular ligament; the ulnar collateral ligament is triangular, running from the medial epicondyle in anterior, posterior and oblique bands to the coronoid process and olecranon.',
      objective: 'Classify the elbow joint, name its articulating bony parts, and describe its collateral ligaments.',
      pitfall: 'Including the superior radio-ulnar joint in the elbow. It shares the capsule but is a separate pivot joint, and the anular ligament belongs to it.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
      type: 'structural_description',
    },
    {
      key: 'upper-limb-joint-types-by-articular-surfaces',
      label: 'Each joint of the upper limb is classified by the shape of its articular surfaces, and no two neighbouring joints share a type',
      definition: 'The shoulder joint is synovial ball-and-socket; the elbow is a synovial hinge; the superior and inferior radio-ulnar joints are synovial pivots; the wrist (radiocarpal) joint is synovial ellipsoid, also called condyloid; the carpometacarpal joint of the thumb is a synovial saddle joint; the acromioclavicular joint is a plane joint; the sternoclavicular joint is a saddle joint. The metacarpophalangeal joints are condyloid and the interphalangeal joints are hinges.',
      objective: 'Classify each joint of the upper limb by type, and name a joint that exemplifies each type.',
      pitfall: 'Grouping the wrist with the elbow because both bend. The elbow is a uniaxial hinge and does nothing else; the wrist is a biaxial ellipsoid and adds abduction and adduction.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
      type: 'classification',
    },
    {
      key: 'upper-limb-joint-movements-follow-from-type',
      label: 'The movements possible at an upper limb joint follow from its type and the number of its axes',
      definition: 'A hinge joint — the elbow, the interphalangeal joints — is uniaxial and permits flexion and extension only, never abduction or adduction. A pivot joint is uniaxial for rotation: at the superior and inferior radio-ulnar joints that rotation is pronation and supination. An ellipsoid joint such as the wrist is biaxial and permits flexion, extension, abduction and adduction, and therefore circumduction. The condyloid metacarpophalangeal joints permit the same four. The shoulder girdle moves at the sternoclavicular and acromioclavicular joints in elevation, depression, protraction, retraction and circumduction.',
      objective: 'Say which movements are possible at a given upper limb joint, and which the shape of that joint forbids.',
      pitfall: 'Placing pronation at the wrist. Pronation and supination happen at the two radio-ulnar joints; the hand follows the radius, which is what makes the movement look as though it were at the wrist.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
      type: 'functional_relationship',
    },
    {
      key: 'anular-ligament-attachments-and-radial-head',
      label: 'The anular ligament rings the head of the radius but is attached only to the ulna, which is what lets the head spin',
      definition: 'The anular ligament is attached to the anterior and posterior margins of the radial notch of the ulna, and with that notch forms an osseofibrous ring — about four fifths of it ligament — that encircles the head of the radius and holds it against the ulna. It is attached to no part of the radius. Its upper border blends with the capsule and the ligaments of the elbow joint, and its lower border is free and embraces the neck. It belongs to the superior radio-ulnar joint, not to the elbow and not to the wrist.',
      objective: 'Give the attachments and relations of the anular ligament, and explain why it may not be attached to the radius.',
      pitfall: 'Attaching it to the head or the neck of the radius. Any attachment to the radius would stop the head rotating inside the ring, and pronation and supination would be lost.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
      type: 'structure_function_relationship',
    },
    {
      key: 'sternoclavicular-joint-disc-and-supports',
      label: 'The sternoclavicular joint is a saddle joint with a complete fibrocartilaginous disc, held down by the costoclavicular ligament',
      definition: 'The sternoclavicular joint is a synovial saddle joint between the medial end of the clavicle and the manubrium sterni with the first costal cartilage — above the sternal angle, not at it. A complete fibrocartilaginous articular disc divides its cavity into two compartments and is the chief factor preventing medial displacement of the clavicle. Its supports are the anterior and posterior sternoclavicular, the interclavicular and the costoclavicular ligaments. The acromioclavicular joint is the plane joint at the other end of the clavicle, and it is that joint the coracoclavicular ligament supports.',
      objective: 'Give the type, the articular disc and the supporting ligaments of the sternoclavicular joint, and separate them from those of the acromioclavicular joint.',
      pitfall: 'Giving the coracoclavicular ligament as its support. The two names differ by one syllable and belong to opposite ends of the clavicle: coraco- to the acromioclavicular joint, costo- to the sternoclavicular.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Joints of Upper Limb',
      type: 'structural_description',
    },
    {
      key: 'shoulder-joint-movements-and-their-muscles',
      label: 'Each movement of the shoulder joint has a principal muscle, and neighbouring muscles do opposite things',
      definition: 'Flexion of the arm is by the anterior fibres of deltoid, the clavicular head of pectoralis major, coracobrachialis and biceps. Extension is by latissimus dorsi, the principal extensor, with teres major and the posterior fibres of deltoid. Adduction is by pectoralis major, latissimus dorsi and teres major \u2014 the three muscles of the intertubercular groove. Medial rotation is by pectoralis major, latissimus dorsi, teres major, subscapularis and the anterior (clavicular) fibres of deltoid. Lateral rotation is by infraspinatus, teres minor and the posterior fibres of deltoid. Supraspinatus takes part in no rotation at all, and serratus anterior acts on the scapula rather than on the joint.',
      objective: 'Name the principal muscle of each movement of the shoulder joint and say which movement a named muscle produces.',
      pitfall: 'Treating deltoid as one muscle. Its anterior fibres flex and medially rotate and its posterior fibres extend and laterally rotate, so deltoid is a correct answer for four opposite movements and a wrong one for each of the other four.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Shoulder Region',
      type: 'structure_function_relationship',
    },
  ],

  questions: [
    {
      key: 'the-radial-collateral-ligament-choose-the-correct-answer-39257210',
      conceptKey: 'elbow-joint-type-bones-ligaments',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give the distal attachment of the radial collateral ligament and say which stress it resists.',
      answerOverride: 'B',
      answerOverrideReason: 'The source printed no key. The radial collateral ligament runs from the lateral epicondyle to the anular ligament, and it is the only one of the four statements that is true; A and C are the classic misreadings of that attachment and D swaps it with the ulnar collateral.',
      explanations: {
        A: 'Picked by students who assume a collateral ligament must reach the bone below it. It deliberately does not: an attachment to the neck of the radius would tether the radial head and abolish pronation and supination.',
        B: 'Correct. The radial collateral ligament passes from the lateral epicondyle to blend with the anular ligament, so it stabilises the elbow without ever gripping the radius.',
        C: 'Tempting because the superior radio-ulnar joint does share the elbow capsule, so the two seem continuous. The ligament is described as ending in the anular ligament, and that is the attachment the question wants.',
        D: 'The wrong side of the joint. It is the ulnar collateral ligament, on the medial side, that resists abduction — a valgus force; the radial collateral resists adduction.',
      },
    },
    {
      key: 'the-radial-collateral-ligament-choose-the-correct-answer-dep-5019bf1f',
      conceptKey: 'elbow-joint-type-bones-ligaments',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give the distal attachment of the radial collateral ligament and say which stress it resists.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries A from a margin mark rather than a key, and A is wrong: the radial collateral ligament is attached to the anular ligament and to no part of the radius. The identical row `the-radial-collateral-ligament-choose-the-correct-answer-39257210`, asked four times, printed no key at all.',
      explanations: {
        A: 'The margin of this copy of the page marks A, which is how the wrong answer reached the bank. Attaching the ligament to the neck of the radius would tether the radial head and abolish pronation and supination.',
        B: 'Correct. From the lateral epicondyle the ligament ends in the anular ligament, stabilising the elbow while leaving the radial head free to spin.',
        C: 'Tempting because the superior radio-ulnar joint shares the elbow capsule. The described attachment is nevertheless to the anular ligament.',
        D: 'The wrong side. Abduction — valgus — is resisted by the ulnar collateral ligament on the medial side.',
      },
    },
    {
      key: 'annular-ligament-choose-the-correct-answer-f4e27611',
      conceptKey: 'anular-ligament-attachments-and-radial-head',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give the attachments and the borders of the anular ligament.',
      answerOverride: 'D',
      answerOverrideReason: 'The source printed no key. D is the one statement that is true as written; A misplaces the ring on the neck rather than the head and understates it, and B and C attach the ligament to bone it never touches.',
      explanations: {
        A: 'Half right, which is what makes it dangerous. The ligament does form most of an osseofibrous ring, but that ring encircles the head of the radius, not the neck, and the ligament makes up about four fifths of it, the radial notch of the ulna the rest.',
        B: 'Picked by students who remember an attachment near the upper radius and reach for the tuberosity. The attachments are to the anterior and posterior margins of the radial notch of the ulna.',
        C: 'The attachment the ligament cannot have. It surrounds the head of the radius without being fixed to it, and that freedom is exactly what allows the head to rotate during pronation and supination.',
        D: 'Correct. The upper border blends with the capsule and the ligaments of the elbow joint, including the radial collateral; only the lower border is free.',
      },
    },
    {
      key: 'annular-ligament-choose-the-correct-answer-dep-book-8eed2748',
      conceptKey: 'anular-ligament-attachments-and-radial-head',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give the attachments and the borders of the anular ligament.',
      answerOverride: 'D',
      answerOverrideReason: 'The bank carries A, which cannot stand: the ring the ligament forms is around the head of the radius, not the neck. D is true as written, and the duplicate row `annular-ligament-choose-the-correct-answer-f4e27611`, asked twice, printed no key to contradict it.',
      explanations: {
        A: 'The answer the extractor read off this page, and the reason this row is overridden. The ring is around the head of the radius; a ring around the neck would slip off under traction, which is the mechanism of a pulled elbow in a child.',
        B: 'A reach for the nearest named landmark on the upper radius. The ligament is attached to the margins of the radial notch of the ulna instead.',
        C: 'The attachment the ligament must not have, since the radial head has to spin freely inside it during pronation and supination.',
        D: 'Correct. The upper border blends with the capsule and ligaments of the elbow; the lower border is free around the neck.',
      },
    },
    {
      key: 'one-of-the-following-is-not-a-ligament-of-wrist-joint-dep-bo-d4b1c46d',
      conceptKey: 'anular-ligament-attachments-and-radial-head',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Attribute the anular ligament to the superior radio-ulnar joint and not to the wrist.',
      answerOverride: 'D',
      answerOverrideReason: 'The bank carries A, but the medial (ulnar) collateral ligament is a genuine ligament of the wrist. The anular ligament belongs to the superior radio-ulnar joint at the other end of the forearm, so D is the one that is not a wrist ligament.',
      explanations: {
        A: 'A real wrist ligament — the medial or ulnar collateral, from the styloid process of the ulna to the triquetral and pisiform. The bank marks it, and that is the error this override corrects.',
        B: 'A real wrist ligament — the lateral or radial collateral, from the styloid process of the radius to the scaphoid.',
        C: 'A real wrist ligament — the palmar radiocarpal, one of the anterior and posterior ligaments that bind the radius to the carpus.',
        D: 'The one that is not, and the answer. The anular ligament is at the elbow, holding the head of the radius against the ulna; students place it at the wrist because it sounds like a retinaculum and because the wrist is where they last met a ring of fibrous tissue.',
      },
    },
    {
      key: 'regarding-movements-of-joints-39f1039b',
      conceptKey: 'upper-limb-joint-movements-follow-from-type',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Say which movements the shoulder girdle, the wrist and the elbow do and do not permit.',
      explanations: {
        A: 'The examiner’s answer. The shoulder girdle moves at the sternoclavicular and acromioclavicular joints in elevation, depression, protraction and retraction, and the sum of those around the sternoclavicular saddle is circumduction of the lateral end of the clavicle.',
        B: 'The commonest error in this leaf. Pronation happens at the superior and inferior radio-ulnar joints; because the hand is carried on the radius, the movement looks as if it happened at the wrist.',
        C: 'Forbidden by the shape of the joint. The elbow is a uniaxial hinge, so it flexes and extends and does nothing else; what feels like side-to-side play at the elbow is rotation of the shoulder.',
        D: 'True as printed — the metacarpophalangeal joints are condyloid and do flex and extend — so it fails to discriminate, and the key nonetheless rests on A. A student who chose this has the anatomy right, and the item needs a faculty eye rather than the student’s.',
      },
    },
    {
      key: 'regarding-movements-of-joints-dep-book-vi-p-y-4fa118f2',
      conceptKey: 'upper-limb-joint-movements-follow-from-type',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Say which movements the shoulder girdle, the wrist and the elbow do and do not permit.',
      answerOverride: 'A',
      answerOverrideReason: 'The bank carries C, which is impossible: the elbow is a uniaxial hinge and cannot abduct or adduct. The identical row `regarding-movements-of-joints-39f1039b`, asked three times, is keyed A, and A is the option this override restores.',
      explanations: {
        A: 'Correct, and the key of the three-times-asked copy of this question. Circumduction of the lateral end of the clavicle is the sum of the shoulder girdle’s elevation, depression, protraction and retraction.',
        B: 'Pronation belongs to the two radio-ulnar joints, not the wrist. The hand follows the radius, which is what makes the movement seem to be at the wrist.',
        C: 'The answer the extractor took from this page, and the reason for the override. A hinge has one axis; abduction and adduction at the elbow are anatomically impossible.',
        D: 'True as printed, since the metacarpophalangeal joints are condyloid and flex and extend. It does not discriminate, and the examiner’s key rests on A.',
      },
    },
    {
      key: 'regarding-movements-of-joints-circumduction-can-occur-at-the-826dcbeb',
      conceptKey: 'upper-limb-joint-movements-follow-from-type',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option A has been swallowed into the stem — the line "Circumduction can occur at the shoulder girdle" is printed as part of the question, leaving only B, C and D as options, and the contract is four to five. The question is intact at `regarding-movements-of-joints-39f1039b`, which is the copy to use. Rescanning this page would recover it, but there is nothing here the other copy lacks.',
    },
    {
      key: 'movements-of-abduction-and-adduction-are-possible-at-the-fol-7d06d276',
      conceptKey: 'upper-limb-joint-movements-follow-from-type',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Identify the one joint in the forearm and wrist with two axes.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries C, but a pivot joint has a single axis and permits rotation only. The wrist is the sole biaxial joint among the four offered, so B is the only possible answer.',
      explanations: {
        A: 'A uniaxial hinge. Flexion and extension are all the elbow has; any apparent side-to-side movement comes from the shoulder.',
        B: 'Correct. The wrist is ellipsoid and biaxial, so beyond flexion and extension it abducts and adducts — the movements clinically called radial and ulnar deviation.',
        C: 'The answer the extractor took from the page, and the reason for the override. The superior radio-ulnar joint is a pivot: the radial head spins within the anular ligament on one axis, producing pronation and supination and nothing else.',
        D: 'The inferior radio-ulnar joint is the other pivot of the same pair, moving with the superior one in pronation and supination only.',
      },
    },
    {
      key: 'which-is-correct-about-lumbrical-muscles-2021-d4e6f9de',
      conceptKey: 'upper-limb-joint-movements-follow-from-type',
      difficulty: 'Hard', questionType: 'Movements',
      learningObjective: 'State what the lumbricals do at the metacarpophalangeal and interphalangeal joints, and separate the two.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. The lumbricals arise from flexor digitorum profundus and insert into the dorsal extensor expansion, so they flex the metacarpophalangeal joints and extend the interphalangeal joints; C is the only option that states either correctly.',
      explanations: {
        A: 'The wrong flexor. The lumbricals arise from the tendons of flexor digitorum profundus, the deep tendons that pass on through to the distal phalanges; superficialis splits and never reaches them.',
        B: 'True of the lateral two only. The medial two lumbricals are supplied by the deep branch of the ulnar nerve, which is why an ulnar lesion, not a median one, produces the clawed ring and little fingers.',
        C: 'Correct. Passing in front of the axis of the metacarpophalangeal joint, the lumbrical flexes it; the same muscle then extends the interphalangeal joints through the extensor expansion.',
        D: 'The exact reverse of what the extensor expansion insertion produces. Lumbricals extend the interphalangeal joints; losing that action is what lets the profundus claw the fingers.',
      },
    },
    {
      key: 'the-elbow-joint-is-b2ab4933',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the elbow joint by the shape of its articular surfaces.',
      explanations: {
        A: 'Correct. The trochlea of the humerus and the trochlear notch of the ulna interlock as a pulley in a groove, which is a hinge and permits flexion and extension alone.',
        B: 'Ellipsoid is the wrist. Students swap the two because both joints bend in the same direction, but the wrist adds a second axis the elbow has not.',
        C: 'Bicondylar is the knee and the temporomandibular joint. The elbow has a capitulum as well as a trochlea, which makes it look like two condyles until you notice the radius, not the ulna, meets the capitulum.',
        D: 'Ball and socket is the shoulder, and the shoulder is the joint most students name first when they are thinking about the upper limb rather than the elbow.',
      },
    },
    {
      key: 'the-elbow-joint-is-dep-book-em-em-em-em-em-e91afb8c',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the elbow joint by the shape of its articular surfaces.',
      answerOverride: 'A',
      answerOverrideReason: 'The bank carries D — ball and socket — which is the shoulder, not the elbow. The identical row `the-elbow-joint-is-b2ab4933` is keyed A, and the elbow is a hinge on every account this module teaches.',
      explanations: {
        A: 'Correct. Trochlea in trochlear notch is a hinge, and it moves on one axis only.',
        B: 'Ellipsoid is the wrist. The two are swapped because both bend the same way; only the wrist has a second axis.',
        C: 'Bicondylar belongs to the knee. The elbow’s capitulum makes it look like a second condyle until you notice it takes the radius rather than the ulna.',
        D: 'The answer printed on this page, and the reason for the override. Ball and socket is the shoulder — the joint students name when they are thinking of the upper limb in general rather than of the elbow.',
      },
    },
    {
      key: 'the-wrist-joint-is-e9954a1c',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the wrist joint by the shape of its articular surfaces.',
      explanations: {
        A: 'Hinge is the elbow. It is the wrist’s second axis — the abduction and adduction of radial and ulnar deviation — that rules a hinge out.',
        B: 'Correct. The oval lower end of the radius with the articular disc receives an oval carpal surface, which is an ellipsoid, or condyloid, joint: biaxial.',
        C: 'Bicondylar belongs to the knee, where two separate condyles articulate side by side. The wrist has one continuous oval surface.',
        D: 'Ball and socket is the shoulder. It would give the wrist rotation, and the wrist has none of its own — what looks like rotation there is pronation and supination of the forearm.',
      },
    },
    {
      key: 'the-wrist-joint-is-dep-book-64334350',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the wrist joint by the shape of its articular surfaces.',
      explanations: {
        A: 'Hinge is the elbow. The wrist has a second axis the elbow lacks.',
        B: 'Correct. An oval radial surface in an oval carpal one is an ellipsoid joint, biaxial and therefore capable of circumduction.',
        C: 'Bicondylar belongs to the knee, which has two separate condyles rather than one continuous oval.',
        D: 'Ball and socket is the shoulder, and would wrongly give the wrist a rotation of its own; the rotation felt there comes from the radio-ulnar joints.',
      },
    },
    {
      key: 'one-of-the-following-joints-of-the-upper-limb-is-synovial-bi-c2a29b3a',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Match the description "synovial biaxial ellipsoid" to the one upper limb joint it fits.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries A, but the elbow is a uniaxial hinge and cannot be a biaxial ellipsoid. The wrist is the module’s worked example of an ellipsoid joint, so B is the answer; the elbow rows in this same leaf are keyed to hinge, which makes A self-contradictory.',
      explanations: {
        A: 'The answer this page carries, and the reason for the override. The elbow is a uniaxial synovial hinge; the same question book keys it as a hinge elsewhere in this leaf.',
        B: 'Correct. The wrist is the ellipsoid joint of the upper limb: two axes, giving flexion and extension with abduction and adduction, and so circumduction.',
        C: 'The acromioclavicular joint is a plane joint, where two flat surfaces glide. It is small and easy to leave unclassified, which is what makes it a usable distractor.',
        D: 'The carpometacarpal joint of the thumb is a saddle joint, and it is biaxial — which is exactly why it is offered here. Saddle and ellipsoid share the axis count but not the surface shape.',
      },
    },
    {
      key: 'regarding-types-of-the-joints-of-upper-limb-choose-correct-a-631197f6',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the one correctly classified joint out of four upper limb joints.',
      answerOverride: 'A',
      answerOverrideReason: 'The source printed no key. Only A classifies its joint correctly: the elbow is a synovial hinge. The other three each name a real joint and give it the wrong type.',
      explanations: {
        A: 'Correct. Trochlea in trochlear notch, one axis, flexion and extension: a synovial hinge.',
        B: 'The right joint and the wrong type. The carpometacarpal joint of the thumb is a saddle, and it is that saddle shape that gives the thumb its opposition; a pivot would give it rotation about a single axis instead.',
        C: 'The radio-ulnar joints are pivots. Ball and socket is offered because both permit rotation, but a pivot rotates about one axis and a ball and socket about three.',
        D: 'The right joint and the wrong type again. The wrist is ellipsoid; the saddle in the upper limb is the thumb’s carpometacarpal joint, one option above.',
      },
    },
    {
      key: 'regarding-the-types-of-the-joints-of-the-upper-limb-choose-t-03e3086a',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the one correctly classified joint out of four upper limb joints.',
      answerOverride: 'A',
      answerOverrideReason: 'The source printed no key. The elbow is a synovial hinge, and it is the only one of the four statements whose type matches its joint.',
      explanations: {
        A: 'Correct. The elbow is a synovial hinge, uniaxial, flexing and extending only.',
        B: 'The thumb’s carpometacarpal joint is a saddle, not a pivot. The saddle is what allows opposition, which no pivot could produce.',
        C: 'The radio-ulnar joints are pivots. Both a pivot and a ball and socket rotate, which is the resemblance the option trades on, but a pivot has one axis and a ball and socket three.',
        D: 'The wrist is ellipsoid. Saddle belongs to the thumb, one option above, and swapping the two is the trap this question is built around.',
      },
    },
    {
      key: 'regarding-types-of-the-joints-of-upper-limb-choose-correct-a-59d372b5',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      excludeReason: 'The stem has absorbed option A verbatim — it ends "a- The elbow joint Is synovial hinge joint." — so the question announces its own answer before the options are read. Four options survive, so this is a mangled stem rather than a lost option; the same question is clean at `regarding-types-of-the-joints-of-upper-limb-choose-correct-a-631197f6` and `regarding-the-types-of-the-joints-of-the-upper-limb-choose-t-03e3086a`, so rescanning would recover nothing new.',
      exclude: true,
      explanations: {},
    },
    {
      key: 'regarding-the-types-of-joints-of-the-upper-limb-mark-one-cor-2a45433e',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the one correctly classified joint out of four upper limb joints.',
      explanations: {
        A: 'The superior radio-ulnar joint is a pivot. Ball and socket is offered because the radial head is round, but it spins on one axis inside the anular ligament rather than moving on three.',
        B: 'The acromioclavicular joint is a plane joint of two flat gliding surfaces. The saddle of the upper limb is the thumb’s carpometacarpal joint.',
        C: 'The elbow is a hinge. Pivot is the type of the two radio-ulnar joints, and the superior one shares the elbow capsule — which is precisely why students hand the elbow its type.',
        D: 'Correct. The wrist is a synovial ellipsoid joint, biaxial, flexing, extending, abducting and adducting.',
      },
    },
    {
      key: 'regarding-types-of-joints-of-upper-limb-mark-one-correct-sta-575d4f11',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the one correctly classified joint out of four upper limb joints.',
      answerOverride: 'D',
      answerOverrideReason: 'The source printed no key. The identical question at `regarding-the-types-of-joints-of-the-upper-limb-mark-one-cor-2a45433e` is keyed D, and the wrist is indeed the ellipsoid joint of the limb; the other three statements each give a real joint the wrong type.',
      explanations: {
        A: 'The superior radio-ulnar joint is a pivot. The round radial head suggests a ball, but it turns on one axis inside the anular ligament.',
        B: 'The acromioclavicular joint is a plane joint. The saddle joint of the upper limb is the thumb’s carpometacarpal.',
        C: 'The elbow is a hinge. Pivot is borrowed from the superior radio-ulnar joint, which shares the elbow’s capsule and so is easily read as part of it.',
        D: 'Correct. The wrist is ellipsoid — biaxial, so it flexes, extends, abducts and adducts.',
      },
    },
    {
      key: 'regarding-types-of-foints-of-upper-limb-mark-one-correct-sta-575487e8',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the one correctly classified joint out of four upper limb joints.',
      answerOverride: 'D',
      answerOverrideReason: 'The source printed no key, and OCR has turned "joints" into "foints" in the stem without touching the options. The keyed copy of this question, `regarding-the-types-of-joints-of-the-upper-limb-mark-one-cor-2a45433e`, gives D, and the wrist is the ellipsoid joint of the upper limb.',
      explanations: {
        A: 'The superior radio-ulnar joint is a pivot: one axis, giving pronation and supination.',
        B: 'The acromioclavicular joint is plane. Saddle is the thumb’s carpometacarpal joint.',
        C: 'The elbow is a hinge. The pivot in that neighbourhood is the superior radio-ulnar joint, which shares the capsule.',
        D: 'Correct. The wrist is a biaxial ellipsoid joint.',
      },
    },
    {
      key: 'sternoclavicular-joint-choose-the-correct-answer-dep-book-ac-2b272b3e',
      conceptKey: 'sternoclavicular-joint-disc-and-supports',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give the type, the disc and the supports of the sternoclavicular joint, and distinguish them from the acromioclavicular joint.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries A, but the sternoclavicular joint is a saddle joint, not a hinge. Its complete fibrocartilaginous articular disc is the feature this module teaches about it, and B is the only true statement of the four.',
      explanations: {
        A: 'The answer printed on this page, and the reason for the override. The sternoclavicular joint is a synovial saddle joint; calling it a hinge would confine the clavicle to one axis when in fact it elevates, depresses, protracts, retracts and circumducts.',
        B: 'Correct. A complete fibrocartilaginous disc divides the cavity into two compartments, and it is the chief structure preventing the clavicle being driven medially onto the sternum.',
        C: 'Off by one level. The angle of Lewis — the sternal angle — is where the second costal cartilage meets the sternum, below this joint; the sternoclavicular joint is on the manubrium with the first costal cartilage.',
        D: 'The other end of the clavicle. The coracoclavicular ligament supports the acromioclavicular joint; the ligament that anchors the clavicle down here is the costoclavicular, and the two names differ by a syllable.',
      },
    },
    {
      key: 'an-example-of-ball-and-socket-joint-is-dep-book-2018-2019-803005bc',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only three options survived — sternoclavicular, wrist, and a garbled inferior tibiofibular — and the contract is four to five. Worse, none of the three is a ball-and-socket joint, so the option carrying the answer, presumably the shoulder or the hip, is one of the ones that was lost. Rescanning the page would recover it and the question is worth having.',
    },
    {
      key: 'which-of-the-following-flexes-the-arm-at-the-glenohumeral-jo-5d65872a',
      conceptKey: 'shoulder-joint-movements-and-their-muscles',
      difficulty: 'Easy', questionType: 'Movements',
      learningObjective: 'Name a flexor of the shoulder joint, and say what each of the other three muscles offered does at that joint instead.',
      answerOverride: 'a',
      answerOverrideReason: 'The 2021 paper printed no key and the recovered answer sheet has no entry for this source, so the answer comes from the department book, which gives flexion of the shoulder to the clavicular head of pectoralis major, the anterior fibres of deltoid and coracobrachialis, assisted by the long head of biceps. Pectoralis major is the only one of the four options on that list: latissimus dorsi extends, subscapularis rotates medially and infraspinatus rotates laterally.',
      explanations: {
        a: 'Correct. The clavicular head of pectoralis major flexes the arm at the glenohumeral joint. The muscle as a whole also adducts and medially rotates, and its sternocostal head extends the flexed arm \u2014 so the same muscle appears as the answer to several opposite questions, which is why the department examines it so often.',
        b: 'Latissimus dorsi is the principal extensor of the shoulder, the exact opposite of what the stem asks. It is picked by students who remember it as a powerful mover of the arm without remembering the direction.',
        c: 'Subscapularis is a rotator cuff muscle on the front of the scapula, and its action at the joint is medial rotation. Lying in front of the joint makes it look like a flexor, which is the trap.',
        d: 'Infraspinatus is the cuff muscle behind the scapula and rotates the arm laterally. Like subscapularis it steadies the humeral head in the glenoid cavity, and that stabilising role is not a movement.',
      },
    },
    {
      key: 'the-glenohumeral-joint-is-classified-as-cd-hinge-joint-js-pi-eaa75f5b',
      conceptKey: 'upper-limb-joint-types-by-articular-surfaces',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'From the ringed 2024 script: the candidate\u2019s pen crossed the option letters, so `options` is empty and the four joint types are inside the stem \u2014 hinge, pivot, ball-and-socket, saddle \u2014 with the answer among them broken to "\u2018pall-and-socket joint". The stem also runs on into the next question ("6/1l superior tru rom the Nk of"). The department book classifies the shoulder as a synovial polyaxial ball-and-socket joint; the item needs a rescan of an unringed copy before a student can pick that.',
    },
    {
      key: 'the-elbow-joint-is-classified-as-a-ball-and-socket-joint-p-r-c0991752',
      conceptKey: 'elbow-joint-type-bones-ligaments',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'From the ringed 2024 script, with `options` empty: the four joint types are inside the stem and the pen has taken the letters, leaving "_\u00ae ball and socket joint P&ringe joint \u00a9. pivot joint d? saddle joint" \u2014 the correct option, hinge, is the one most damaged. The department book makes the elbow a synovial hinge. This is the same question the question books ask, and this file already carries a sittable copy of it; the sat printing still deserves a rescan because a sat paper outranks a question book.',
    },
  ],
}
