/**
 * `101 ISK > Anatomy > Upper Limb > Muscles of the Back` — the question books'
 * MCQs.
 *
 * Twenty-nine rows and about a dozen distinct questions. What the repetition
 * says is narrow and consistent: this faculty examines the back muscles almost
 * entirely through the scapula — which border a muscle grips, which movement
 * it produces, which nerve reaches it, and what goes missing when it is
 * paralysed. Upward rotation of the scapula is asked five times, the borders
 * of the scapula five times, and the nerve supply four.
 *
 * Four concepts are reused rather than minted:
 * `scapular-rotation-abduction-beyond-90-muscles`,
 * `shoulder-girdle-movements-muscles`,
 * `long-thoracic-nerve-serratus-anterior-winging` and
 * `axillary-nerve-injury-shoulder-dislocation` all exist from the sat papers,
 * and their definitions below are copied verbatim so re-emitting them adds
 * these occurrences to their exam signal and changes nothing else. The last of
 * those is the concept that owns "flat shoulder", and it lives in the Nerve
 * Supply leaf; the questions stay here because that is the leaf the books file
 * them under, and the shared key means the two leaves feed one concept rather
 * than two.
 *
 * Nineteen answers are overridden and this is the heavy leaf for it. Nine rows
 * printed no key at all. The other ten carry a key that is wrong, and the
 * errors are not random: seven of them mark option A. On the DEP BOOK pages
 * the extractor was reading a margin, not an answer line, and a margin mark
 * lands on the first option far more often than chance allows.
 */
import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Muscles of the Back',
  modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
  articleId: 'ART-101-ANA-MUSCLES-OF-THE-BACK',

  concepts: [
    {
      key: 'trapezius-attachments-actions-and-shoulder-drop',
      label: 'Trapezius suspends the shoulder girdle, and its three sets of fibres each move the scapula differently',
      definition: 'Trapezius is a flat triangular muscle of the back arising from the external occipital protuberance, the medial third of the superior nuchal line, the ligamentum nuchae and the spines of the seventh cervical and all the thoracic vertebrae with their supraspinous ligaments. It is inserted into the lateral third of the clavicle, the acromion and the upper border of the crest of the spine of the scapula. Its upper fibres elevate the scapula, its middle fibres retract it, its lower fibres depress it, and its upper and lower fibres together rotate the glenoid cavity upwards. Because the muscle suspends the shoulder girdle from the skull and the vertebral column, its paralysis lets the whole shoulder sag — a dropped shoulder.',
      objective: 'Give the attachments of trapezius, the action of each of its three sets of fibres, and the deformity its paralysis produces.',
      pitfall: 'Expecting a paralysed trapezius to flatten the shoulder. It drops the shoulder; flattening is deltoid wasting after an axillary nerve injury, and the two deformities are asked side by side in these books.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
      type: 'structure_function_relationship',
    },
    {
      key: 'latissimus-dorsi-attachments-and-actions',
      label: 'Latissimus dorsi reaches from the iliac crest to the floor of the bicipital groove, and it extends, adducts and medially rotates the arm',
      definition: 'Latissimus dorsi arises from the spines of the lower six thoracic vertebrae, from the thoracolumbar fascia and through it from the lumbar and sacral spines, from the posterior third of the outer lip of the iliac crest, from the lower three or four ribs and from the inferior angle of the scapula. Its fibres converge and twist to insert into the floor of the bicipital groove of the humerus. It extends, adducts and medially rotates the arm, and with the arm fixed above the head it raises the trunk — which is why it is called the climbing muscle. It takes no part in flexion, abduction or lateral rotation.',
      objective: 'Give the origins and insertion of latissimus dorsi and state its three actions on the arm.',
      pitfall: 'Giving the nuchal ligament as an origin. That belongs to trapezius, which overlaps latissimus dorsi on the back; latissimus dorsi never reaches above the sixth thoracic spine.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
      type: 'structure_function_relationship',
    },
    {
      key: 'scapular-border-muscle-attachments-medial-versus-lateral',
      label: 'Four muscles grip the medial border of the scapula and the teres muscles take the lateral border',
      definition: 'The medial border of the scapula receives levator scapulae above the root of the spine, rhomboideus minor at the root of the spine and rhomboideus major below it on the dorsal aspect, and serratus anterior along the whole length of its costal aspect. The lateral border gives origin to teres minor from the upper two thirds of its dorsal surface and to teres major from the lower third and the inferior angle, with the long head of triceps arising just above it from the infraglenoid tubercle.',
      objective: 'Name the muscles attached to the medial border of the scapula and those attached to the lateral border, and assign any named muscle to the correct one.',
      pitfall: 'Placing serratus anterior on the lateral border because it runs laterally round the chest. It attaches along the costal surface of the medial border, and it is that grip which lets it hold the medial border against the chest wall.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
      type: 'structural_description',
    },
    {
      key: 'triangle-of-auscultation-boundaries',
      label: 'The triangle of auscultation is bounded by trapezius, latissimus dorsi and the medial border of the scapula',
      definition: 'The triangle of auscultation lies on the back below and medial to the scapula. It is bounded medially by the lateral border of trapezius, below by the upper border of latissimus dorsi and laterally by the medial border of the scapula. Its floor is formed by rhomboideus major and the sixth and seventh ribs with the intercostal space between them, and because so little muscle covers the chest wall there, breath sounds are unusually clear over it — which is what names it. The lumbar triangle is a separate space lower down, bounded by latissimus dorsi, external oblique and the iliac crest.',
      objective: 'Name the three boundaries and the floor of the triangle of auscultation and explain why it is named for listening.',
      pitfall: 'Bringing teres major into it. Teres major is a lateral-border muscle running to the humerus and forms the lower boundary of the triangular spaces of the axilla instead — a different triangle on a different aspect of the scapula.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
      type: 'structural_description',
    },
    {
      key: 'scapular-muscle-nerve-supply-accessory-dorsal-scapular-thoracodorsal',
      label: 'Every muscle that moves the scapula takes a named nerve, and only trapezius takes one from outside the brachial plexus',
      definition: 'Trapezius is supplied motor by the spinal root of the accessory nerve, the eleventh cranial nerve, with C3 and C4 carrying sensation — the one muscle acting on the shoulder girdle that is not supplied from the brachial plexus. Levator scapulae and the two rhomboids take the dorsal scapular nerve from the C5 root; levator scapulae also receives C3 and C4 directly. Serratus anterior takes the long thoracic nerve, C5, C6 and C7. Latissimus dorsi takes the thoracodorsal nerve, C6, C7 and C8, from the posterior cord. Teres major takes the lower subscapular nerve and teres minor the axillary nerve.',
      objective: 'Name the nerve supplying each muscle that acts on the scapula, and identify the one that does not come from the brachial plexus.',
      pitfall: 'Answering the accessory nerve without saying which root. It is the spinal root that supplies trapezius; the cranial root joins the vagus and goes to the larynx and the pharynx, and both roots are offered as options in these books.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Muscles of the Back',
      type: 'functional_relationship',
    },
    {
      key: 'scapular-rotation-abduction-beyond-90-muscles',
      label: 'Beyond ninety degrees the scapula rotates, by trapezius and serratus anterior',
      definition: 'Abduction of the arm beyond about ninety degrees cannot happen at the shoulder joint, because the greater tuberosity meets the coraco-acromial ligament; the arm is raised further by the scapula rotating on the chest wall so the glenoid cavity faces upwards. That rotation is produced by the upper and lower fibres of trapezius, supplied motor by the spinal root of the accessory nerve with sensory C3 and C4, acting with the lower five digitations of serratus anterior, supplied by the nerve to serratus anterior (long thoracic nerve, nerve of Bell). Serratus anterior is also the powerful protractor of the scapula and fixes it against the chest wall, so its paralysis wings the scapula.',
      objective: 'Name the muscles that rotate the scapula to carry abduction beyond ninety degrees, and give the nerve supply and action of each.',
      pitfall: 'Answering with deltoid and supraspinatus. Those carry abduction to ninety degrees; past it the question is about the shoulder girdle, and the answer is trapezius and serratus anterior.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Shoulder Region',
      type: 'structure_function_relationship',
    },
    {
      key: 'shoulder-girdle-movements-muscles',
      label: 'The shoulder girdle elevates, depresses, protracts, retracts and rotates, each by a named set of muscles',
      definition: 'The shoulder girdle moves at the acromio-clavicular and sterno-clavicular joints. Elevation is by the upper fibres of trapezius with levator scapulae. Depression is by pectoralis minor, with subclavius steadying the clavicle and preventing excessive movement. Protraction is by serratus anterior, the main and powerful protractor, assisted by pectoralis minor. Retraction is by the middle fibres of trapezius with the rhomboids. Rotation so the glenoid cavity faces upward is by the upper and lower fibres of trapezius with the lower five digitations of serratus anterior, which is what lets the arm be raised overhead; rotation so the glenoid faces downward is by levator scapulae with rhomboideus minor.',
      objective: 'Name the movements of the shoulder girdle and the muscles that produce each, including both directions of scapular rotation.',
      pitfall: 'Treating rotation as one movement. Upward and downward rotation of the glenoid have different muscles, and it is upward rotation — trapezius with serratus anterior — that carries abduction past ninety degrees.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T03-S02-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Shoulder Region',
      type: 'structure_function_relationship',
    },
    {
      key: 'long-thoracic-nerve-serratus-anterior-winging',
      label: 'Injury to the long thoracic nerve at mastectomy paralyses serratus anterior, winging the scapula',
      definition: 'The long thoracic nerve (C5, C6, C7) runs on the surface of serratus anterior on the medial wall of the axilla, where it is exposed during axillary clearance. Serratus anterior rotates the scapula upward and holds its medial border against the chest wall, so its paralysis prevents abduction of the arm above the shoulder and lets the medial border stand off — a winged scapula.',
      objective: 'Explain why a mastectomy patient cannot abduct above the shoulder, and name the deformity that accompanies it.',
      pitfall: 'Blaming the axillary nerve. That would weaken abduction to ninety degrees and numb the regimental badge area; it is loss of scapular rotation above the shoulder, with winging, that names the long thoracic nerve.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Axilla',
      type: 'clinical_correlation',
    },
    {
      key: 'axillary-nerve-injury-shoulder-dislocation',
      label: 'Shoulder dislocation endangers the axillary nerve, costing deltoid and teres minor',
      definition: 'The axillary (circumflex) nerve, C5 and C6, winds round the surgical neck of the humerus through the quadrangular space, where dislocation of the shoulder, fracture of the surgical neck and crutch pressure all endanger it. It supplies deltoid and teres minor. Its injury loses abduction of the shoulder through the range deltoid provides, from fifteen to ninety degrees, flattens the rounded contour of the shoulder as deltoid wastes, and numbs a patch of skin over the lower half of the deltoid.',
      objective: 'Name the nerve endangered by shoulder dislocation, the muscles it supplies, and the movement, deformity and sensory loss its injury produces.',
      pitfall: 'Reporting total loss of abduction. Supraspinatus still initiates the first fifteen degrees and the scapular rotators still act above ninety; it is the middle range that goes.',
      subject: 'msk', primary: 'DIS-ANA-T02', secondary: ['SYS-MSK-T01-S01-M03'],
      modulePath: '101 ISK > Anatomy > Upper Limb > Nerve Supply of Upper Limb & Nerve Injuries',
      type: 'clinical_correlation',
    },
  ],

  questions: [
    {
      key: 'upward-rotation-of-the-scapula-in-raising-the-arm-above-head-d361147f',
      conceptKey: 'scapular-rotation-abduction-beyond-90-muscles',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Name the pair of muscles that rotates the glenoid cavity upwards to let the arm be raised overhead.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. Upward rotation of the scapula is produced by the upper and lower fibres of trapezius acting with the lower digitations of serratus anterior, so C is the only pairing that can raise the arm above the head.',
      explanations: {
        A: 'Latissimus dorsi pulls the arm and the inferior angle of the scapula downwards; it opposes this movement rather than producing it. Students pick it because it is the other large back muscle and because it does attach to the scapula.',
        B: 'Serratus anterior is half right, which is what makes this the strongest distractor. The rhomboids are the wrong partner — they rotate the glenoid cavity downwards, so they would undo exactly what serratus anterior is doing.',
        C: 'Correct. Trapezius, pulling the acromion up and behind, and serratus anterior, pulling the inferior angle forwards and laterally, form a couple that swings the glenoid cavity upwards.',
        D: 'Teres minor is a rotator cuff muscle acting on the humerus at the shoulder joint, not on the scapula. Nothing that inserts into the humerus can rotate the scapula it arises from.',
      },
    },
    {
      key: 'paralysis-of-the-following-muscle-leads-to-shoulder-drop-a604fe6d',
      conceptKey: 'trapezius-attachments-actions-and-shoulder-drop',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Attribute a dropped shoulder to loss of the muscle that suspends the shoulder girdle.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. Trapezius suspends the shoulder girdle from the skull and the vertebral spines, so it is the only one of the four whose paralysis lets the shoulder sag.',
      explanations: {
        A: 'Pectoralis major runs from the chest wall to the humerus and never reaches the scapula or the clavicle in a way that supports them. Losing it weakens adduction and medial rotation of the arm, not the height of the shoulder.',
        B: 'Latissimus dorsi pulls the shoulder down when it acts. Its paralysis would if anything raise the shoulder slightly, which is the opposite of what the question describes.',
        C: 'Correct. Trapezius holds the whole girdle up from the occiput and the vertebral spines; when the spinal accessory nerve is cut in the posterior triangle the shoulder drops.',
        D: 'Deltoid hangs from the girdle rather than supporting it. Its paralysis flattens the rounded contour of the shoulder — a different sign, and the one these books ask about immediately alongside this question.',
      },
    },
    {
      key: 'the-following-muscle-is-attached-to-lateral-border-of-scapul-0cbd514c',
      conceptKey: 'scapular-border-muscle-attachments-medial-versus-lateral',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Assign each named scapular muscle to the medial or the lateral border.',
      answerOverride: 'B',
      answerOverrideReason: 'The source printed no key. Teres major arises from the lower third of the lateral border and the inferior angle; the other three all take the medial border, so B is the only possible answer.',
      explanations: {
        A: 'Serratus anterior runs laterally round the chest, which is why students place it on the lateral border. Its attachment is along the costal surface of the medial border, and that grip is what holds the medial border flat against the ribs.',
        B: 'Correct. Teres major arises from the lower third of the dorsal surface of the lateral border and from the inferior angle.',
        C: 'Levator scapulae attaches to the medial border above the root of the spine — the top of the medial border, not the lateral one.',
        D: 'Rhomboideus major attaches to the medial border below the root of the spine, immediately beneath rhomboideus minor.',
      },
    },
    {
      key: 'the-following-muscle-is-attached-to-the-lateral-border-of-th-5793f03c',
      conceptKey: 'scapular-border-muscle-attachments-medial-versus-lateral',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Assign each named scapular muscle to the medial or the lateral border.',
      explanations: {
        A: 'Serratus anterior is a medial-border muscle despite running laterally round the chest. It attaches along the costal surface of the medial border.',
        B: 'Correct, and the key. Teres major arises from the lower third of the lateral border and the inferior angle of the scapula.',
        C: 'Levator scapulae takes the upper part of the medial border, above the root of the spine.',
        D: 'Rhomboideus major takes the medial border below the root of the spine.',
      },
    },
    {
      key: 'a-physical-sign-known-as-winged-scapula-tests-loss-of-functi-5a8d683e',
      conceptKey: 'long-thoracic-nerve-serratus-anterior-winging',
      difficulty: 'Easy', questionType: 'Clinical application',
      learningObjective: 'Name the muscle whose paralysis wings the scapula and say what it normally does.',
      explanations: {
        A: 'Rhomboid major does hold the medial border towards the vertebral column, so its loss can produce a slight winging — but the classical, examinable winged scapula is serratus anterior, and the two are told apart by the movement lost: rhomboid weakness costs retraction, serratus weakness costs abduction above the shoulder.',
        B: 'Levator scapulae elevates the scapula and rotates the glenoid cavity downwards. Its loss weakens shrugging, not the flat contact of the medial border with the chest.',
        C: 'Latissimus dorsi attaches to the inferior angle only in passing on its way to the humerus, and its paralysis costs extension and adduction of the arm.',
        D: 'Correct, and the key. Serratus anterior holds the medial border of the scapula against the chest wall; when the long thoracic nerve is injured the border lifts away like a wing, most obviously when the patient pushes against a wall.',
      },
    },
    {
      key: 'actions-of-the-latissimus-dorsi-3280bd1e',
      conceptKey: 'latissimus-dorsi-attachments-and-actions',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'State the three actions of latissimus dorsi and recognise that flexion, abduction and lateral rotation are none of them.',
      answerOverride: 'E',
      answerOverrideReason: 'The source printed no key. Latissimus dorsi extends, adducts and medially rotates the arm; each of A, B and C names the exact opposite of one of those, so D cannot stand and E is the only possible answer.',
      explanations: {
        A: 'The opposite action. Latissimus dorsi extends the arm — its insertion into the floor of the bicipital groove lies in front of the joint but its whole belly lies behind it, and it pulls the humerus backwards and downwards.',
        B: 'The opposite again. It adducts the arm powerfully, bringing it against the trunk, which is what makes it the climbing muscle.',
        C: 'The opposite a third time. The fibres twist as they converge so that the muscle medially rotates the humerus.',
        D: 'Attractive to a student who is not sure of any single option and hopes the inclusive answer is safest. It cannot be right when all three of the statements it gathers are false.',
        E: 'Correct. None of the three actions offered belongs to latissimus dorsi; it extends, adducts and medially rotates.',
      },
    },
    {
      key: 'actions-of-the-latissimus-dorsi-ipka-e19718f5',
      conceptKey: 'latissimus-dorsi-attachments-and-actions',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'State the three actions of latissimus dorsi and recognise that flexion, abduction and lateral rotation are none of them.',
      answerOverride: 'E',
      answerOverrideReason: 'The source printed no key. Latissimus dorsi extends, adducts and medially rotates the arm, so each of A, B and C is the reverse of a true action, D is impossible, and E stands.',
      explanations: {
        A: 'Latissimus dorsi extends the arm rather than flexing it; the belly lies behind the shoulder joint and pulls the humerus backwards.',
        B: 'It adducts rather than abducts — pulling the raised arm down against the trunk is exactly what it is built for.',
        C: 'It medially rotates, because its fibres twist through a right angle before reaching the floor of the bicipital groove.',
        D: 'The refuge of a student unsure of any single statement. Three false statements do not become true by being gathered together.',
        E: 'Correct. Not one of the three offered actions belongs to this muscle.',
      },
    },
    {
      key: 'aii-of-the-following-muscles-attach-to-medial-border-of-scap-9727e05a',
      conceptKey: 'scapular-border-muscle-attachments-medial-versus-lateral',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Identify the one muscle among four that takes the lateral border of the scapula rather than the medial.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. Levator scapulae, rhomboideus major and serratus anterior all attach to the medial border; teres major arises from the lateral border and the inferior angle, so it is the exception.',
      explanations: {
        A: 'True, so not the exception. Levator scapulae attaches to the medial border above the root of the spine.',
        B: 'True, so not the exception. Rhomboideus major attaches to the medial border below the root of the spine.',
        C: 'The exception, and the answer. Teres major arises from the lower third of the lateral border and the inferior angle, and runs forwards to the humerus.',
        D: 'True, so not the exception, and the option most often mistaken for the answer because the muscle is named for the ribs rather than the scapula. Serratus anterior attaches along the whole costal surface of the medial border.',
      },
    },
    {
      key: 'mark-one-true-origin-of-latissimus-dorsi-muscle-2019-d6252199',
      conceptKey: 'latissimus-dorsi-attachments-and-actions',
      difficulty: 'Hard', questionType: 'Structure and function',
      learningObjective: 'Give a true bony origin of latissimus dorsi and separate it from the origins of trapezius.',
      answerOverride: 'D',
      answerOverrideReason: 'The bank carries C, and C is trapezius\'s origin, not this muscle\'s: latissimus dorsi has no attachment to the ligamentum nuchae and does not reach above the sixth thoracic spine. The posterior third of the outer lip of the iliac crest is a direct, standard origin of latissimus dorsi, so D is the true statement.',
      explanations: {
        A: 'Half true and therefore the hardest distractor. Latissimus dorsi reaches the lumbar spines through the thoracolumbar fascia rather than directly, and its own vertebral origin is the spines of the lower six thoracic vertebrae — not the lumbar spines as a direct attachment, and not all of them.',
        B: 'The wrong ribs. The muscle arises from the lower three or four ribs, interdigitating there with external oblique; the middle four ribs belong to serratus anterior territory.',
        C: 'The answer the bank carries, and the reason for the override. The ligamentum nuchae is an origin of trapezius, the muscle that overlies latissimus dorsi on the upper back — which is precisely why the two get exchanged.',
        D: 'Correct. Latissimus dorsi arises directly from the posterior third of the outer lip of the iliac crest, the lowest and most lateral of its bony origins.',
      },
    },
    {
      key: 'most-muscles-acting-on-shoulder-girdle-upper-limb-joints-are-83ec5ede',
      conceptKey: 'scapular-muscle-nerve-supply-accessory-dorsal-scapular-thoracodorsal',
      difficulty: 'Moderate', questionType: 'Nerve supply',
      learningObjective: 'Identify the one shoulder-girdle muscle supplied from outside the brachial plexus.',
      answerOverride: 'A',
      answerOverrideReason: 'The bank carries D, but rhomboid major takes the dorsal scapular nerve, which is a branch of the C5 root of the brachial plexus. Trapezius alone among the four is supplied by a cranial nerve — the spinal root of the accessory — so A is the exception the stem asks for.',
      explanations: {
        A: 'The exception, and the answer. Trapezius takes its motor supply from the spinal root of the accessory nerve, the eleventh cranial nerve, which reaches it through the posterior triangle of the neck; C3 and C4 add only sensation.',
        B: 'Teres minor is supplied by the axillary nerve from the posterior cord — a brachial plexus branch, so not the exception.',
        C: 'Latissimus dorsi is supplied by the thoracodorsal nerve, also from the posterior cord, so not the exception.',
        D: 'The answer the extractor took from this page, and the reason for the override. Rhomboid major takes the dorsal scapular nerve, which arises from the C5 root of the brachial plexus itself — students mark it because a nerve named for the scapula sounds unlike the named cords and trunks they have memorised.',
      },
    },
    {
      key: 'one-of-the-following-actions-is-done-by-the-latissimus-dorsi-666c5afc',
      conceptKey: 'latissimus-dorsi-attachments-and-actions',
      difficulty: 'Easy', questionType: 'Movements',
      learningObjective: 'Pick the action latissimus dorsi actually performs from among its three opposites.',
      answerOverride: 'D',
      answerOverrideReason: 'The bank carries A, which is one of the three actions latissimus dorsi cannot perform. It extends, adducts and medially rotates the arm, so D is the only true statement offered.',
      explanations: {
        A: 'The answer the extractor read off this page, and the reason for the override. Latissimus dorsi is an extensor: its bulk lies behind the shoulder joint and it drags the humerus backwards and down.',
        B: 'Abduction belongs to supraspinatus and deltoid. Latissimus dorsi does the reverse and adducts the arm forcibly against the trunk.',
        C: 'Lateral rotation belongs to infraspinatus and teres minor. The twist in the latissimus tendon makes it a medial rotator instead.',
        D: 'Correct. Extension of the arm is one of the three actions of latissimus dorsi, alongside adduction and medial rotation.',
      },
    },
    {
      key: 'one-of-the-following-is-not-attached-to-the-medial-border-of-bc50f83b',
      conceptKey: 'scapular-border-muscle-attachments-medial-versus-lateral',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Separate the medial-border muscles of the scapula from the lateral-border ones.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries D, but rhomboideus major is one of the classic medial-border attachments, below the root of the spine. Teres minor arises from the upper two thirds of the dorsal surface of the lateral border, so B is the muscle that is not attached to the medial border.',
      explanations: {
        A: 'Attached to the medial border, above the root of the spine, so not the answer.',
        B: 'Correct. Teres minor arises from the upper two thirds of the dorsal surface of the lateral border and runs to the greater tuberosity of the humerus — a lateral-border muscle throughout.',
        C: 'Attached to the medial border along the whole of its costal surface, so not the answer, even though the muscle itself lies on the side of the chest.',
        D: 'The answer the extractor took from this page, and the reason for the override. Rhomboideus major is attached to the medial border below the root of the spine; it is one of the four muscles the stem is testing, not the exception to them.',
      },
    },
    {
      key: 'one-of-the-following-muscles-elevates-the-shoulder-at-the-sh-a658aaf7',
      conceptKey: 'shoulder-girdle-movements-muscles',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Name the fibres of trapezius that elevate the shoulder girdle and distinguish them from those that retract it.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries A, but latissimus dorsi depresses the shoulder rather than elevating it. Elevation of the shoulder girdle is by the upper fibres of trapezius with levator scapulae, so B is the answer.',
      explanations: {
        A: 'The answer the extractor read off this page, and the reason for the override. Latissimus dorsi pulls the shoulder downwards and backwards; it is a depressor, not an elevator.',
        B: 'Correct. The upper fibres of trapezius run downwards and laterally from the skull and the upper spines to the clavicle and acromion, so their pull lifts the whole girdle — the shrug.',
        C: 'Rhomboid minor retracts the scapula and rotates the glenoid cavity downwards. It runs almost horizontally, so it cannot lift.',
        D: 'The middle fibres of trapezius run horizontally from the spines to the acromion and spine of the scapula and therefore retract rather than elevate. This is the sharpest distractor in the item, because it is the same muscle with a different fibre direction.',
      },
    },
    {
      key: 'paralysis-of-the-following-muscle-leads-to-at-shoulder-dep-b-e7467d8c',
      conceptKey: 'axillary-nerve-injury-shoulder-dislocation',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Attribute a flattened shoulder contour to wasting of the muscle that makes that contour.',
      answerOverride: 'D',
      answerOverrideReason: 'The bank carries A, taken from this copy\'s margin. Deltoid is the muscle that gives the shoulder its rounded contour, so it is the only one whose paralysis flattens it; pectoralis major lies on the front of the chest and its loss changes the axillary fold, not the shoulder\'s outline.',
      explanations: {
        A: 'The answer the extractor took from this page, and the reason for the override. Pectoralis major forms the anterior axillary fold; losing it hollows the front of the chest and the armpit, not the top of the shoulder.',
        B: 'Latissimus dorsi forms the posterior axillary fold. Its paralysis costs extension and adduction of the arm and leaves the shoulder contour untouched.',
        C: 'Trapezius paralysis drops the shoulder — the shoulder sits lower but keeps its rounded outline. These books ask both signs in adjacent questions and the pair is exactly what the item tests.',
        D: 'Correct. Deltoid caps the shoulder and is what makes it round; when the axillary nerve is injured the muscle wastes, the acromion becomes prominent and the shoulder looks flat, even square.',
      },
    },
    {
      key: 'paralysis-of-the-following-muscle-leads-to-flat-shoulder-dep-beea5638',
      conceptKey: 'axillary-nerve-injury-shoulder-dislocation',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Attribute a flattened shoulder contour to wasting of the muscle that makes that contour.',
      answerOverride: 'D',
      answerOverrideReason: 'The source printed no key. Deltoid gives the shoulder its rounded contour, so its wasting after an axillary nerve injury is what flattens it; none of the other three contributes to that outline.',
      explanations: {
        A: 'Pectoralis major forms the anterior axillary fold at the front of the chest, not the cap of the shoulder.',
        B: 'Latissimus dorsi forms the posterior axillary fold; its loss is felt in extension and adduction of the arm.',
        C: 'Trapezius paralysis drops the whole shoulder without changing its shape — the neighbouring sign, asked in the neighbouring question.',
        D: 'Correct. Deltoid is the rounded contour of the shoulder, and once it wastes the underlying acromion stands out and the shoulder looks flat.',
      },
    },
    {
      key: 'paralysis-of-the-following-muscle-leads-to-shoulder-drop-dep-d13f4a35',
      conceptKey: 'trapezius-attachments-actions-and-shoulder-drop',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Attribute a dropped shoulder to loss of the muscle that suspends the shoulder girdle.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key in a form the extractor could read; option D carries the tail of a margin answer list, "3-c 2-e 1-c", which is page furniture rather than this item\'s key and has been ignored. Trapezius suspends the shoulder girdle from the skull and the vertebral spines, so C is the answer on the anatomy alone.',
      explanations: {
        A: 'Pectoralis major runs from the chest wall to the humerus and takes no part in holding the girdle up.',
        B: 'Latissimus dorsi pulls the shoulder down when it acts, so its loss cannot be the cause of a drooping shoulder.',
        C: 'Correct. Trapezius suspends the clavicle and scapula from the occiput and the vertebral spines; when the spinal accessory nerve is divided the shoulder sags.',
        D: 'Deltoid hangs from the girdle rather than carrying it. Its paralysis flattens the shoulder instead of dropping it.',
      },
    },
    {
      key: 'patient-was-unable-to-retract-his-scapula-because-of-paralys-026c3b15',
      conceptKey: 'shoulder-girdle-movements-muscles',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Name the muscles that retract the scapula alongside the middle fibres of trapezius.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. Retraction of the scapula is by the middle fibres of trapezius with the rhomboids; the stem names trapezius and asks for its partner, which can only be C.',
      explanations: {
        A: 'Infraspinatus is a rotator cuff muscle running from the scapula to the humerus. It laterally rotates the arm and moves the scapula not at all.',
        B: 'Levator scapulae elevates the scapula and rotates the glenoid cavity downwards. It runs too vertically to draw the scapula backwards.',
        C: 'Correct. The rhomboids run downwards and laterally from the vertebral spines to the medial border, so their pull draws the scapula backwards and medially — retraction, with the middle fibres of trapezius.',
        D: 'Serratus posterior superior is a muscle of respiration attached to the ribs, not to the scapula. It is offered because its name contains "serratus" and because it lies in this region.',
      },
    },
    {
      key: 'patient-was-unable-to-retract-his-scapula-because-of-paralys-ad7f20e7',
      conceptKey: 'shoulder-girdle-movements-muscles',
      difficulty: 'Moderate', questionType: 'Clinical application',
      learningObjective: 'Name the muscles that retract the scapula alongside the middle fibres of trapezius.',
      explanations: {
        A: 'Infraspinatus acts on the humerus, laterally rotating the arm; it does not move the scapula.',
        B: 'Levator scapulae elevates the scapula and rotates the glenoid downwards, and its line of pull is nearly vertical.',
        C: 'Correct, and the key. The rhomboids draw the medial border of the scapula backwards and medially with the middle fibres of trapezius.',
        D: 'Serratus posterior superior attaches to the ribs and belongs to respiration. It is offered for its name and its position, not for anything it does to the scapula.',
      },
    },
    {
      key: 'rotation-of-the-scapula-in-raising-the-arm-above-head-upward-115c17ef',
      conceptKey: 'scapular-rotation-abduction-beyond-90-muscles',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Name the pair of muscles that rotates the glenoid cavity upwards to let the arm be raised overhead.',
      answerOverride: 'C',
      answerOverrideReason: 'The bank carries A, read off this copy\'s margin, and latissimus dorsi opposes upward rotation rather than producing it. The identical question at `upward-rotation-of-the-scapula-in-raising-the-arm-above-head-d361147f`, asked three times, printed no key; the anatomy gives C, trapezius with serratus anterior.',
      explanations: {
        A: 'The answer the extractor took from this page, and the reason for the override. Latissimus dorsi drags the inferior angle of the scapula downwards and the arm with it — the reverse of the movement in the stem.',
        B: 'Serratus anterior is the right half of the pair, which makes this the strongest distractor. The rhomboids rotate the glenoid cavity downwards, so they cancel rather than assist it.',
        C: 'Correct. Trapezius lifting the acromion and serratus anterior pulling the inferior angle forwards form the couple that turns the glenoid cavity upwards.',
        D: 'Teres minor inserts into the humerus and acts at the shoulder joint. It cannot rotate the bone it arises from.',
      },
    },
    {
      key: 'the-following-muscle-is-attached-to-lateral-border-of-scapul-dbcce599',
      conceptKey: 'scapular-border-muscle-attachments-medial-versus-lateral',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Assign each named scapular muscle to the medial or the lateral border.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries A, but serratus anterior attaches along the costal surface of the medial border, not the lateral. The identical row `the-following-muscle-is-attached-to-the-lateral-border-of-th-5793f03c`, asked twice, is keyed B, and teres major is the lateral-border muscle.',
      explanations: {
        A: 'The answer the extractor read off this page, and the reason for the override. Serratus anterior runs laterally round the chest but grips the costal surface of the medial border — which is exactly how it holds that border flat against the ribs.',
        B: 'Correct. Teres major arises from the lower third of the lateral border and from the inferior angle.',
        C: 'Levator scapulae takes the medial border above the root of the spine.',
        D: 'Rhomboid major takes the medial border below the root of the spine.',
      },
    },
    {
      key: 'the-trapezius-and-latissimus-dorsi-muscles-share-in-the-boun-bed3a5ea',
      conceptKey: 'triangle-of-auscultation-boundaries',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Name the space on the back bounded by trapezius, latissimus dorsi and the medial border of the scapula.',
      answerOverride: 'B',
      answerOverrideReason: 'The source printed no key. The triangle of auscultation is the only one of the four bounded by both named muscles: trapezius medially, latissimus dorsi below and the medial border of the scapula laterally.',
      explanations: {
        A: 'The upper triangular space is in the axilla, bounded by teres minor, teres major and the long head of triceps, and it transmits the circumflex scapular vessels. Neither named muscle reaches it.',
        B: 'Correct. Trapezius forms its medial boundary, latissimus dorsi its lower one and the medial border of the scapula its lateral one, with rhomboideus major and the sixth and seventh ribs in the floor.',
        C: 'The lumbar triangle does have latissimus dorsi as a boundary, which is what makes this the strongest distractor. Its other boundaries are external oblique and the iliac crest — far below anything trapezius reaches.',
        D: 'The lower triangular space is also in the axilla, bounded by teres major, the long head of triceps and the humerus, and it transmits the radial nerve and profunda brachii vessels.',
      },
    },
    {
      key: 'thoracodorsal-nerve-supply-the-following-muscle-2019-97e45d7c',
      conceptKey: 'scapular-muscle-nerve-supply-accessory-dorsal-scapular-thoracodorsal',
      difficulty: 'Moderate', questionType: 'Nerve supply',
      learningObjective: 'Match the thoracodorsal nerve to the one muscle it supplies.',
      answerOverride: 'C',
      answerOverrideReason: 'The bank carries A, but teres major is supplied by the lower subscapular nerve. The thoracodorsal nerve is the nerve to latissimus dorsi — it is named for that muscle\'s position on the back — so C is the answer.',
      explanations: {
        A: 'The answer the extractor read off this page, and the reason for the override. Teres major is supplied by the lower subscapular nerve. The confusion is understandable: all three nerves — upper subscapular, thoracodorsal and lower subscapular — arise in that order from the posterior cord and run within centimetres of each other on the posterior axillary wall.',
        B: 'Trapezius takes the spinal root of the accessory nerve, from outside the brachial plexus altogether.',
        C: 'Correct. The thoracodorsal nerve, C6 to C8 from the posterior cord, is the nerve to latissimus dorsi and is the structure at risk when the posterior axillary wall is cleared in a mastectomy.',
        D: 'Rhomboid minor takes the dorsal scapular nerve from the C5 root.',
      },
    },
    {
      key: 'trapezius-muscle-is-supplied-by-the-nerve-2024-ipka-dep-book-a8ae0663',
      conceptKey: 'scapular-muscle-nerve-supply-accessory-dorsal-scapular-thoracodorsal',
      difficulty: 'Moderate', questionType: 'Nerve supply',
      learningObjective: 'Name the nerve supplying trapezius and specify which root of the accessory nerve it is.',
      answerOverride: 'B',
      answerOverrideReason: 'The bank carries D, but the dorsal scapular nerve supplies the rhomboids and levator scapulae, not trapezius. Trapezius takes the spinal root of the accessory nerve, so B is the answer; the stem records this item as asked in six separate books, which makes getting it right worth the override.',
      explanations: {
        A: 'The trap the item is built around, and the reason both accessory options are offered. The cranial root of the accessory nerve joins the vagus and is distributed to the muscles of the larynx and pharynx; it never reaches trapezius.',
        B: 'Correct. The spinal root of the accessory nerve arises from the upper five cervical segments, enters the skull through the foramen magnum, leaves through the jugular foramen and crosses the posterior triangle of the neck to supply sternomastoid and trapezius.',
        C: 'The long thoracic nerve supplies serratus anterior, which lies on the opposite wall of the axilla.',
        D: 'The answer the extractor took from this page, and the reason for the override. The dorsal scapular nerve supplies the rhomboids and levator scapulae — the muscles lying deep to trapezius, which is very likely how the two came to be exchanged.',
        E: 'The thoracodorsal nerve supplies latissimus dorsi, the muscle immediately below trapezius on the back.',
      },
    },
    {
      key: 'triangle-of-auscultation-is-associated-with-all-of-the-follo-68904fa7',
      conceptKey: 'triangle-of-auscultation-boundaries',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Name the boundaries and floor of the triangle of auscultation and identify the structure that has nothing to do with it.',
      answerOverride: 'B',
      answerOverrideReason: 'The source printed no key. Latissimus dorsi, trapezius and the medial border of the scapula are its three boundaries and rhomboid major is its floor; teres major belongs to the axillary triangular spaces and is the exception.',
      explanations: {
        A: 'True, so not the exception. The upper border of latissimus dorsi forms the lower boundary of the triangle.',
        B: 'The exception, and the answer. Teres major runs from the lateral border of the scapula to the humerus and bounds the triangular spaces of the axilla instead — a different set of triangles on the other aspect of the scapula, which is what makes the option tempting.',
        C: 'True, so not the exception. Rhomboid major forms part of the floor of the triangle, beneath the space rather than around it.',
        D: 'True, so not the exception. The lateral border of trapezius forms the medial boundary.',
        E: 'True, so not the exception. The medial border of the scapula forms the lateral boundary, and it is the scapula being drawn forwards that opens the triangle enough to listen through.',
      },
    },
    {
      key: 'actions-of-the-latissimus-dorsi-ipka-y-y-a83d9202',
      conceptKey: 'latissimus-dorsi-attachments-and-actions',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option B was lost in extraction, and this is the one kind of question a missing option cannot survive: option D reads "All of the above", so a student would be asked to judge a list the page no longer prints in full. The bank\'s key of A is wrong besides — latissimus dorsi does not flex the arm. Two intact copies exist, `actions-of-the-latissimus-dorsi-3280bd1e` and `actions-of-the-latissimus-dorsi-ipka-e19718f5`, so a rescan of this page would recover nothing the leaf does not already have.',
    },
    {
      key: 'triangle-of-auscultation-is-associated-with-all-of-the-follo-c70b57f7',
      conceptKey: 'triangle-of-auscultation-boundaries',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option A has been swallowed into the stem — "a- Latissimus dorsi" is printed as part of the question, so the stem a student would read names one of the answers. Four options remain, but the item is corrupt rather than short. The intact copy is `triangle-of-auscultation-is-associated-with-all-of-the-follo-68904fa7`; rescanning this page would recover the item, and there is nothing in it the other copy lacks.',
    },
    {
      key: 'upward-rotation-of-the-scapula-in-raising-the-arm-above-head-4850069c',
      conceptKey: 'scapular-rotation-abduction-beyond-90-muscles',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option C was lost, leaving three options — and C is the correct answer, so this copy cannot be sat at all rather than merely being short. A rescan recovers it; the copy already intact is `upward-rotation-of-the-scapula-in-raising-the-arm-above-head-d361147f`, which the books ask three times.',
    },
    {
      key: 'upward-rotation-of-the-scapula-in-raising-the-arm-above-head-78223b7d',
      conceptKey: 'scapular-rotation-abduction-beyond-90-muscles',
      difficulty: 'Moderate', questionType: 'Movements',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The same loss on a second copy of the same page: option C, the correct answer, is missing and only A, B and D survive. Recoverable by rescanning, but the intact copy at `upward-rotation-of-the-scapula-in-raising-the-arm-above-head-d361147f` already carries the question.',
    },
    {
      key: 'which-one-of-the-following-statements-regarding-the-dorsal-s-14742344',
      conceptKey: 'scapular-muscle-nerve-supply-accessory-dorsal-scapular-thoracodorsal',
      difficulty: 'Hard', questionType: 'Nerve supply',
      learningObjective: 'Not sittable as printed.',
      explanations: {},
      exclude: true,
      excludeReason: 'A reviewer problem, not a scan problem: every option is legible and two of them are defensible. Option B, "It supplies the rhomboids major muscle", is true on this faculty\'s own teaching — the dorsal scapular nerve is the nerve to the rhomboids. Option C, the printed key, is true only on the variant reported in reference anatomy where the C5 contribution to the long thoracic nerve leaves the dorsal scapular nerve. A rescan changes nothing; the item needs one of the two statements rewritten before a student can be asked to choose between them. Option A is false twice over (the nerve is C5 and comes from the brachial plexus, not C6 from the cervical plexus) and option D is false because the nerve does help supply levator scapulae.',
    },
  ],
}
