/**
 * `101 ISK > Anatomy > Basis of Anatomy > Skeletal system` — the question books' MCQs.
 *
 * The largest of the eight Basis leaves, and the one where the books are most
 * repetitive. A hundred and one rows carry this leaf tag; about forty are
 * genuinely this chapter, the rest are carpal bones, the clavicle and the
 * forearm bones (Upper Limb leaves), bone marrow (Histology > Blood) and
 * collagen types (Histology > Connective Tissue). Those are left to their
 * authors — a question is not about the skeletal system merely because a bone
 * is named in it.
 *
 * What the faculty examines here is narrow and completely predictable. Classify
 * a named bone by shape: the patella, the scapula, the ribs and the sinuses are
 * asked with the same four options each time, and between them they cover four
 * of the six classes. Name a region of the long bone from its description.
 * Name what grows it. Say which of two ossification processes a bone uses.
 * Place a named site in one of three cartilages. Twenty-two rows are sittable
 * and twenty-one are not — and two of the twenty-one are excluded only because
 * the scan lost an option and the import contract is four to five, not because
 * anything about them is unclear.
 *
 * Three answers conflict with the department book and are overridden with the
 * conflict written out. The worst is `the-compact-bone-with-a-central-medullary-
 * cavity-is-called`, keyed — in both of its copies — to metaphysis, when the
 * book's own definition of the diaphysis is "a tube of compact bone with a
 * central medullary cavity". A wrong key repeated twice is still a wrong key,
 * and the repetition is recorded rather than treated as evidence.
 *
 * `bone-shapes-six-classes-with-examples` and `pneumatic-bone-air-cavities-and-
 * their-uses` are kept apart deliberately. The books ask one question about
 * what a pneumatic bone *is* and another about what its air cavity is *for*,
 * and the second is answered from the sinus, not from the classification.
 */
import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Skeletal system',
  modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
  articleId: 'ART-101-ANA-SKELETAL-SYSTEM',

  concepts: [
    {
      key: 'skeleton-axial-versus-appendicular',
      label: 'The axial skeleton is the skull, hyoid, sternum, ribs and vertebral column; the appendicular skeleton is the limbs and their girdles',
      definition: 'By position the skeleton divides in two. The axial skeleton is the skull, the mandible, the hyoid bone, the sternum, the ribs and the vertebral column — the central axis of the body. The appendicular or peripheral skeleton is the bones of the upper and lower limbs, and includes the girdles by which the limbs hang from the axis: the clavicle and scapula above, the hip bone below.',
      objective: 'Assign a named bone to the axial or the appendicular skeleton.',
      pitfall: 'Putting the clavicle and scapula with the axial skeleton because they lie on the trunk. They are the pectoral girdle, part of the upper limb; the sternum they meet is the axial bone.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'classification',
      aliases: ['Peripheral skeleton'],
    },
    {
      key: 'bone-shapes-six-classes-with-examples',
      label: 'Bones fall into six shape classes, and the department book names one worked example of each',
      definition: 'By shape there are six classes of bone. A long bone has two expanded ends and a shaft. A short bone — the carpal and tarsal bones — is spongy bone under a thin shell of compact bone. A flat bone — the skull cap, the scapula, the ribs — is two thin plates of compact bone with a spongy layer between; in the skull the plates are the outer and inner tables and the spongy layer is the diploe. A pneumatic bone contains air cavities, chiefly the skull bones around the nose. An irregular bone, such as a vertebra, has an irregular shape with projecting processes and is built like a short bone. A sesamoid bone is a small nodule of bone embedded in a muscle tendon; the patella, in the tendon of quadriceps femoris, is the largest.',
      objective: 'Classify a named bone into one of the six shape classes, and give the book\'s example of each class.',
      pitfall: 'Calling the patella a short bone because it is small and rounded. Its class is decided by where it sits — inside a tendon — not by its size.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'classification',
      aliases: ['Classification of bones by shape'],
    },
    {
      key: 'pneumatic-bone-air-cavities-and-their-uses',
      label: 'The air cavities of a pneumatic bone lighten the skull, give the voice resonance and warm inspired air — they do not strengthen it',
      definition: 'A pneumatic bone contains air. The bones concerned are mainly the skull bones surrounding the nose — the maxilla, the frontal — so their air cavities are called the paranasal sinuses. A bone may hold one large cavity, as the maxillary sinus does, or many small air cells, as the mastoid does. The cavities decrease the weight of the skull, give resonance to the voice, and are lined by a highly vascular mucosa that warms inspired air.',
      objective: 'State the three uses of the air cavity in a pneumatic bone, and say what it does not do.',
      pitfall: 'Adding strength to the list. A cavity can only take bone away; what air buys is lightness, resonance and a warm airway, and strength is what it costs.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'structure_function_relationship',
      aliases: ['Paranasal sinuses'],
    },
    {
      key: 'long-bone-regions-epiphysis-diaphysis-metaphysis',
      label: 'A long bone is an epiphysis at each end, a diaphysis between them, and a metaphysis where the two meet',
      definition: 'The epiphyses are the expanded upper and lower ends of a long bone; they carry the articular surfaces and are covered with hyaline cartilage. The diaphysis is the shaft — a tube of compact bone with a central medullary cavity, lined by endosteum, filled with bone marrow and covered by the periosteum. In a growing bone the two are separated by a disc of hyaline cartilage, the epiphyseal cartilage. The metaphysis lies just beneath that cartilage and is the most active part of the long bone.',
      objective: 'Name the region of a long bone from a description of it, and give what each region contains.',
      pitfall: 'Confusing the metaphysis with the diaphysis. The metaphysis is the narrow, highly active zone under the growth plate; the diaphysis is the whole hollow shaft below it.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'structural_description',
      aliases: ['Parts of a long bone'],
    },
    {
      key: 'long-bone-grows-in-length-at-the-epiphyseal-plate',
      label: 'A long bone lengthens at its epiphyseal plates and widens from the periosteum, and the end that ossifies later is the growing end',
      definition: 'A long bone increases in length from the epiphysial plates of cartilage, by proliferation of their cells, and increases in width from the osteoblasts in the inner layer of the periosteum. The epiphyseal plate at one end ossifies earlier than the other; the end whose plate ossifies later goes on growing longer and is called the growing end. The nutrient artery enters the shaft obliquely and runs away from the growing end. Fusion of epiphysis with diaphysis is under hormonal control and happens in females about two years earlier than in males.',
      objective: 'Name the structure that lengthens a long bone, the one that widens it, and say what makes one end the growing end.',
      pitfall: 'Answering "metaphysis" because the book calls it the most active part of the bone. Activity is not the same as growth: the cartilage cells of the plate divide, and the metaphysis is the bone left behind as they do.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'structure_function_relationship',
      aliases: ['Growing end', 'Epiphysial plate'],
    },
    {
      key: 'ossification-membranous-versus-cartilaginous',
      label: 'A bone forms either directly in a connective tissue membrane or by replacing a cartilage model, and which one it did is fixed for each bone',
      definition: 'Bones form by one of two processes. In intra-membranous ossification bone develops directly from a connective tissue membrane of mesenchyme, beginning at one or more centres; the clavicle and the skull cap form this way. In intra-cartilaginous (endochondral) ossification the mesenchyme first becomes a cartilage model, which is then changed into bone; the long bones, the vertebrae, the ribs and the base of the skull form this way.',
      objective: 'Say by which of the two processes a named bone ossifies, and give the book\'s examples of each.',
      pitfall: 'Reading the clavicle as a long bone and therefore cartilaginous. It is the standing exception the examiner uses: shaped like a long bone, but ossified in membrane.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'classification',
      aliases: ['Endochondral ossification', 'Intramembranous ossification'],
    },
    {
      key: 'cartilage-three-types-and-their-sites',
      label: 'The three cartilages are told apart by their matrix, and each has its own list of sites',
      definition: 'Cartilage is a rubbery, tough and resilient connective tissue with no blood vessels, nerves or lymphatics, nourished by diffusion from the vessels of the perichondrium. Hyaline cartilage has a translucent, glass-like matrix with numerous small rounded cells and is the most widespread: developing bones in the fetus, the epiphyseal plates, the articular cartilage of joints, the costal cartilages and xiphoid process, and the larynx except the epiglottis together with the tracheal rings. It is the only one that ossifies in old age. White fibrocartilage has an opaque matrix rich in collagen bundles and few cells, and is found in the intervertebral discs. Yellow elastic fibrocartilage has a yellow matrix rich in elastic fibres and abundant cells, and is found in the tip of the nose, the auricle of the ear and the epiglottis.',
      objective: 'Name the type of cartilage at a given site, and give the matrix that distinguishes each type.',
      pitfall: 'Putting the epiglottis with the rest of the larynx. The larynx is hyaline except the epiglottis, which is yellow elastic — and the exception is what gets asked.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'classification',
      aliases: ['Hyaline cartilage', 'White fibrocartilage', 'Yellow elastic fibrocartilage'],
    },
    {
      key: 'long-bone-arterial-supply-nutrient-metaphyseal-epiphyseal-periosteal',
      label: 'A long bone takes four sets of arteries, and the shaft is divided between two of them \u2014 nutrient artery inside, periosteal arteries outside',
      definition: 'A long bone is supplied by four sets of arteries. The nutrient (diaphyseal) artery enters the middle of the shaft through an oblique nutrient foramen, runs away from the growing end, and supplies the inner two-thirds of the shaft. The periosteal arteries enter from the periosteum and supply the outer third of the shaft. The metaphyseal arteries enter through minute foramina and supply the metaphyses. The epiphyseal arteries supply the epiphyses, and after the epiphyseal plate ossifies they anastomose with the metaphyseal arteries \u2014 which is why the growing bone and the adult bone have different patterns of blood supply across the growth plate.',
      objective: 'Name the four arterial sources of a long bone, say what fraction of the shaft each of the two shaft arteries supplies, and state the direction the nutrient artery takes.',
      pitfall: 'Reading "nutrient" as supplying the whole shaft. It supplies the inner two-thirds; the outer third comes from the periosteum, which is why stripping the periosteum during surgery devascularises the surface of the bone even though the nutrient artery is intact.',
      subject: 'msk', primary: 'DIS-ANA-T01', secondary: [],
      modulePath: '101 ISK > Anatomy > Basis of Anatomy > Skeletal system',
      type: 'structure_function_relationship',
      aliases: ['Nutrient artery', 'Diaphyseal artery', 'Periosteal arteries', 'Metaphyseal arteries', 'Epiphyseal arteries', 'Blood supply of bone'],
    },
  ],

  questions: [
    {
      key: 'appendicular-skeleton-is-formed-of-86e697b1',
      conceptKey: 'skeleton-axial-versus-appendicular',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'State what the appendicular skeleton is made of.',
      answerOverride: 'B',
      answerOverrideReason: 'This copy printed no key. Its three-option twin `appendicular-skeleton-includes-dep-book-ac-ad-ac-ad-ad-ad-99ec3dc9` is keyed to the same statement, "Bones of the limbs", and the department book defines the appendicular (peripheral) skeleton as the bones of the upper and lower limbs.',
      explanations: {
        A: 'The skull and mandible are the top of the axial skeleton — the central axis, not the appendages hung from it.',
        B: 'Correct. Appendicular means the appendages: the bones of the upper and lower limbs, girdles included.',
        C: 'Ribs and sternum are axial. They form the thoracic cage around the axis; the fact that the upper limb attaches to the sternum through the clavicle does not make the sternum a limb bone.',
        D: 'The vertebral column is the axis itself, and the option a student picks by reading "appendicular" as "attached to".',
      },
    },
    {
      key: 'appendicular-skeleton-includes-dep-book-ac-ad-ac-ad-ad-ad-99ec3dc9',
      conceptKey: 'skeleton-axial-versus-appendicular',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The same question as `appendicular-skeleton-is-formed-of-86e697b1`, keyed B ("Bones of the limbs"), but printed with only three options — the vertebral-column distractor is missing. The complete copy is imported and carries this row\'s key. Kept so the key is not lost with the row.',
    },
    {
      key: 'which-of-the-following-bones-forms-part-of-the-axial-skeleto-0eaf1181',
      conceptKey: 'skeleton-axial-versus-appendicular',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Pick the axial bone from a list of three pectoral girdle and limb bones.',
      explanations: {
        A: 'The clavicle is the anterior bar of the pectoral girdle and belongs to the upper limb, however much of it lies across the front of the chest.',
        B: 'The ulna is a forearm bone, appendicular beyond argument.',
        C: 'Correct. The sternum is one of the six components of the axial skeleton the book lists, with the skull, mandible, hyoid, ribs and vertebral column.',
        D: 'The scapula is the posterior half of the pectoral girdle. It lies on the thoracic cage without joining it, which is exactly why it moves with the limb and not with the axis.',
      },
    },
    {
      key: 'the-patella-is-a-f83afe92',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the patella by shape.',
      explanations: {
        A: 'Short bones are the carpals and tarsals — spongy bone in a thin compact shell, filling a region rather than sitting in a tendon. The patella is picked as short by students going on its size.',
        B: 'A long bone has two epiphyses and a shaft. The patella has neither.',
        C: 'A flat bone is two compact plates with spongy bone between; the scapula and ribs are the examples. The patella is flattened in profile, which is the whole of the resemblance.',
        D: 'Correct. The patella is a nodule of bone embedded in the tendon of quadriceps femoris in front of the knee — the largest sesamoid bone in the body — and its job is to reduce friction between that tendon and the bone beneath.',
      },
    },
    {
      key: 'the-patella-is-a-dep-book-em-ac-p-a-short-bone-p-vi-b-long-b-0a7b48e9',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `the-patella-is-a-f83afe92`, same four options and the same key D, with the first two options also duplicated into the stem. The clean copy, asked twice, is imported.',
    },
    {
      key: 'the-scapula-is-a-1b78cb9c',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the scapula by shape.',
      explanations: {
        A: 'Short bones are cuboidal and packed together in the wrist and ankle. The scapula is a broad plate.',
        B: 'A long bone has a shaft and two ends. The scapula has processes — spine, acromion, coracoid — but no shaft.',
        C: 'Correct. The scapula is one of the book\'s three examples of a flat bone, with the skull cap and the ribs: two thin plates of compact bone with a spongy layer between.',
        D: 'A sesamoid bone lies inside a tendon. The scapula gives tendons their origin instead of being carried in one.',
      },
    },
    {
      key: 'the-scapula-is-a-dep-book-ec87c49a',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `the-scapula-is-a-1b78cb9c` with the same four options and the same key C. The copy asked twice is imported.',
    },
    {
      key: 'the-ribs-are-fa240d9c',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Classify the ribs by shape.',
      explanations: {
        A: 'A short bone is roughly cubical. A rib is a long curved strip, and nothing about it is short except its thickness.',
        B: 'The commonest error here, because a rib is manifestly long. Length is not what defines a long bone: a long bone has two expanded epiphyses and a marrow-filled shaft, and a rib has neither.',
        C: 'Correct. The ribs are flat bones — two thin plates of compact bone with spongy bone between, which is also why the sternum and the ribs hold red marrow in adult life.',
        D: 'A sesamoid bone is embedded in a tendon. The ribs are joined to the vertebrae behind and the costal cartilages in front.',
      },
    },
    {
      key: 'the-ribs-are-ais-short-bone-ca90c5ba',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A second copy of `the-ribs-are-fa240d9c` with the first option swallowed by the stem ("ais Short bone"), the fourth distractor swapped for "Pneumatic bones", and no key. The keyed copy, asked twice, is imported.',
    },
    {
      key: 'which-of-the-following-bones-is-a-flat-bone-357a89f6',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Pick the flat bone from four bones of the upper limb and its girdle.',
      answerOverride: 'B',
      answerOverrideReason: 'Asked twice and keyed on neither page. The department book names the scapula as one of its three examples of a flat bone, and none of the other three options is flat: the humerus and ulna are long bones and the clavicle, though it ossifies in membrane, is classed as a long bone.',
      explanations: {
        A: 'The humerus is the type example of a long bone — two epiphyses and a shaft with a medullary cavity.',
        B: 'Correct. The scapula is a flat bone: two thin plates of compact bone with a spongy layer between them.',
        C: 'The ulna is a long bone of the forearm.',
        D: 'The clavicle is the trap. It is the one bone that ossifies in membrane like a flat bone of the skull, yet it is classed by shape as a long bone; membrane ossification and flat shape are two different classifications and this option asks for the second.',
      },
    },
    {
      key: 'which-of-the-following-bones-is-a-at-bone-dep-book-81c23e86',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `which-of-the-following-bones-is-a-flat-bone-357a89f6` with the same four options and no key either. Neither copy was keyed, so importing both would only put the same unkeyed item in front of a student twice.',
    },
    {
      key: 'which-of-the-following-bones-is-classi-ed-as-a-at-bone-2024-20685aa3',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Keyed A and correctly so — the scapula is the book\'s flat bone, the femur is long and the carpals short — but only three options survived, and the import contract is four to five. The same objective is imported through `which-of-the-following-bones-is-a-flat-bone-357a89f6` and `one-of-the-following-is-a-at-bone-dep-book-2017-965afb8e`, so nothing is lost by holding this printing back until its fourth option is rescanned.',
    },
    {
      key: 'one-of-the-following-is-a-at-bone-dep-book-2017-965afb8e',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Pick the flat bone from an irregular, a long and a short bone.',
      answerOverride: 'B',
      answerOverrideReason: 'The 2017 source printed no key. The department book names the skull cap as one of its three flat bones, and files the other three options elsewhere: the vertebra under irregular bones, the humerus under long, the scaphoid under short.',
      explanations: {
        A: 'The vertebra is the book\'s example of an irregular bone — irregular in shape with projecting processes, and built inside like a short bone.',
        B: 'Correct. The cap of the skull is a flat bone: outer and inner tables of compact bone with the diploe between them.',
        C: 'The humerus is a long bone.',
        D: 'The scaphoid is a carpal bone, and the carpals are the book\'s example of short bones.',
      },
    },
    {
      key: 'one-of-the-following-is-a-flat-bone-5cf9c5c4',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only two options survived — "Vertebra" and "Humerus" — and neither is a flat bone, so the answer is one of the two options that were lost. The complete copy is `one-of-the-following-is-a-at-bone-dep-book-2017-965afb8e`, whose missing option turns out to be the cap of the skull.',
    },
    {
      key: 'one-of-the-following-is-an-irregular-bone-dep-book-2018-5ad3fbce',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Pick the irregular bone from a long, a flat and a group of long bones.',
      explanations: {
        A: 'The clavicle is classed as a long bone, and is the bone this leaf keeps using to separate ossification from shape.',
        B: 'The scapula is flat. It has an awkward outline, which is what makes students read "irregular" into it — but irregularity of outline is not the class; projecting processes on a solid, short-bone-like body are.',
        C: 'The metacarpals are miniature long bones, each with a base, a shaft and a head.',
        D: 'Correct. The vertebra is the book\'s worked example of an irregular bone.',
      },
    },
    {
      key: 'which-of-the-following-bones-is-a-sesamoid-bone-2024-441bd6ea',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Recognise a sesamoid bone among the carpal bones.',
      explanations: {
        A: 'Correct. The pisiform sits in the tendon of flexor carpi ulnaris, which is what a sesamoid bone is — a nodule of bone within a tendon. It is the one carpal bone that qualifies.',
        B: 'The scaphoid is a true carpal bone in the proximal row, articulating with the radius. Its being small and rounded is the whole of its resemblance to a sesamoid.',
        C: 'The triquetral is a proximal-row carpal bone, articulating with the articular disc.',
        D: 'The hamate is a distal-row carpal bone. Its hook gives attachment to the flexor retinaculum, which is a tendon-related fact that makes it a tempting misread — but the bone lies in the carpus, not in a tendon.',
      },
    },
    {
      key: 'the-sinuses-are-dcc93df0',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name the class of bone that contains the paranasal sinuses.',
      explanations: {
        A: 'Short bones are the carpals and tarsals, and hold no air.',
        B: 'Long bones have a marrow cavity, not an air cavity, and none of them is pneumatic.',
        C: 'The flat bones of the skull cap are the nearest true answer, and the reason this distractor works: the skull has both, but its air-filled bones surround the nose rather than roofing the brain.',
        D: 'Correct. A bone containing air is a pneumatic bone, and the air cavities of the skull bones around the nose are the paranasal sinuses.',
      },
    },
    {
      key: 'the-paranasal-sinuses-are-c8f2180d',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The same question as `the-sinuses-are-dcc93df0` with "paranasal" spelled out and the same four options, and no key. The keyed copy is imported.',
    },
    {
      key: 'the-paranasal-sinuses-are-dep-book-102fa50f',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A third copy of the same question, this one missing its fourth option — which is the answer, "Pneumatic bones". The keyed copy `the-sinuses-are-dcc93df0` is imported.',
    },
    {
      key: 'one-of-the-following-is-not-a-function-of-pneumatic-bone-202-495570c1',
      conceptKey: 'pneumatic-bone-air-cavities-and-their-uses',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Give what the air cavity of a pneumatic bone does, and identify the property it costs.',
      explanations: {
        A: 'A genuine function. The sinus is lined by a highly vascular mucosa, and inspired air passing the nose is warmed by it.',
        B: 'Correct as the exception, and the answer. Hollowing a bone cannot make it stronger; the air is bought at the cost of substance, which is why a blow to the face fractures the maxilla and the orbital floor so readily.',
        C: 'A genuine function. The air cavities resonate, and this is why the voice changes when a sinus fills during a cold.',
        D: 'A genuine function, and the one most often given first: the cavities decrease the weight of the skull that the neck has to balance.',
      },
    },
    {
      key: 'the-expanded-upper-and-lower-ends-of-the-long-bone-are-calle-dc6a14b9',
      conceptKey: 'long-bone-regions-epiphysis-diaphysis-metaphysis',
      difficulty: 'Easy', questionType: 'Definition',
      learningObjective: 'Name the expanded ends of a long bone.',
      explanations: {
        A: 'Correct. The epiphyses are the expanded upper and lower ends, used for articulation and covered with hyaline cartilage.',
        B: 'The epiphyseal plate is the disc of hyaline cartilage *between* epiphysis and diaphysis in a growing bone, not the end itself. One letter of Greek separates them and the plate is inside the bone.',
        C: 'The diaphysis is the shaft between the two ends.',
        D: 'The metaphysis is the zone of the shaft immediately under the epiphyseal cartilage — close to the end, which is what makes it the strongest distractor, but not the end.',
      },
    },
    {
      key: 'the-expanded-upper-and-lower-ends-of-the-long-bone-are-calle-1e385acc',
      conceptKey: 'long-bone-regions-epiphysis-diaphysis-metaphysis',
      difficulty: 'Easy', questionType: 'Definition',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `the-expanded-upper-and-lower-ends-of-the-long-bone-are-calle-dc6a14b9` that lost its fourth option and printed no key. The complete, keyed copy, asked twice, is imported.',
    },
    {
      key: 'the-compact-bone-with-a-central-medullary-cavity-is-called-ef1ee8d4',
      conceptKey: 'long-bone-regions-epiphysis-diaphysis-metaphysis',
      difficulty: 'Moderate', questionType: 'Definition',
      learningObjective: 'Name the region of a long bone that is a tube of compact bone around a medullary cavity.',
      answerOverride: 'C',
      answerOverrideReason: 'The bank carries D, "Metaphysis", and so does the second copy of this question — and both conflict with the department book, whose definition of the diaphysis is word for word the stem of this question: "a tube of compact bone with a central medullary cavity lined with endosteum and filled with bone marrow". The metaphysis is defined separately as the part just beneath the epiphyseal cartilage. A key repeated on two pages is still one wrong key, and the conflict is recorded rather than absorbed.',
      explanations: {
        A: 'The epiphysis is the expanded end. It is spongy bone under a shell, with no medullary cavity.',
        B: 'The epiphyseal plate is cartilage, not bone at all.',
        C: 'Correct, and the override. The diaphysis is the shaft: a tube of compact bone around a central medullary cavity lined with endosteum and filled with marrow.',
        D: 'The answer printed in both copies of this question in the books, and the reason for the override. The metaphysis is the short, highly active segment just under the epiphyseal cartilage; it is part of the shaft, but it is not the description in the stem.',
      },
    },
    {
      key: 'the-compact-bone-with-a-central-medullary-cavity-is-called-d-eaa5a88e',
      conceptKey: 'long-bone-regions-epiphysis-diaphysis-metaphysis',
      difficulty: 'Moderate', questionType: 'Definition',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `the-compact-bone-with-a-central-medullary-cavity-is-called-ef1ee8d4` with the same four options and the same key, D. Kept rather than deleted because the fact that *both* printings key this question to the metaphysis is itself the evidence behind the override on the imported copy — the error is the books\', not one scan\'s.',
    },
    {
      key: 'the-part-which-is-responsible-for-the-growth-of-long-bones-i-4f16aefb',
      conceptKey: 'long-bone-grows-in-length-at-the-epiphyseal-plate',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Name the part of a long bone that lengthens it.',
      explanations: {
        A: 'The epiphysis is the end that the plate pushes away; it is carried along by the growth rather than producing it.',
        B: 'Correct. The bone increases in length from the epiphysial plates of cartilage, by proliferation of their cells.',
        C: 'The diaphysis is what the growth adds to. It lengthens, but it does not do the lengthening.',
        D: 'The metaphysis is called the most active part of the long bone, which is exactly why it is chosen. Its activity is turning newly made cartilage into bone; the cell division that adds length happens in the plate above it.',
      },
    },
    {
      key: 'the-part-which-is-responsible-for-the-growth-of-long-bones-i-1a44af45',
      conceptKey: 'long-bone-grows-in-length-at-the-epiphyseal-plate',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `the-part-which-is-responsible-for-the-growth-of-long-bones-i-4f16aefb` with the same four options and the same key B. One copy is enough.',
    },
    {
      key: 'the-part-which-is-responsible-for-the-growth-of-long-bones-i-119622d5',
      conceptKey: 'long-bone-grows-in-length-at-the-epiphyseal-plate',
      difficulty: 'Easy', questionType: 'Structure and function',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A third copy, badly scanned: the stem reads "In length is galled" and the first option has been folded into it. No key. The clean copy is imported.',
    },
    {
      key: 'longitudinal-growth-in-a-growing-bone-passes-through-which-o-678b8773',
      conceptKey: 'long-bone-grows-in-length-at-the-epiphyseal-plate',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Name the structure through which a growing bone lengthens, and separate it from the scar it leaves.',
      answerOverride: 'c',
      answerOverrideReason: 'The 2024 source printed no key. The department book states that long bones increase in length from the epiphysial plates of cartilage by proliferation of their cells, which makes C the answer; D names what is left after that plate has ossified and growth has stopped.',
      explanations: {
        a: 'The metaphysis is where the new cartilage is replaced by bone, and the book calls it the most active part of the long bone — which is why it draws the answer. Growth passes *out of* it; it does not begin there.',
        b: 'The diaphysis is the shaft. It gains length at its ends and gains width from the periosteum, but it generates neither.',
        c: 'Correct. The epiphyseal plate of hyaline cartilage divides and is replaced from below, and that is the whole mechanism of growth in length.',
        d: 'The epiphyseal line is the plate after it has ossified — the mark left when growth has finished. Choosing it is choosing the end of the process rather than the process.',
      },
    },
    {
      key: 'intra-cartilagenous-ossification-occurs-in-0aa0905f',
      conceptKey: 'ossification-membranous-versus-cartilaginous',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name a bone that ossifies by replacing a cartilage model.',
      explanations: {
        A: 'The roof of the skull ossifies in membrane, directly from mesenchyme, with no cartilage model. It is printed twice in this question, as A and again as C.',
        B: 'The clavicle is the book\'s other example of membranous ossification, and the classic trap: it looks like a long bone and long bones are cartilaginous, but the clavicle is not.',
        C: 'The skull cap is the same structure as option A under another name. Two identical options cannot both be the answer, which is a way to eliminate the pair.',
        D: 'Correct. The vertebrae are on the book\'s intra-cartilaginous list with the long bones, the ribs and the base of the skull: mesenchyme first becomes a cartilage model, and the model is then replaced by bone.',
      },
    },
    {
      key: 'one-of-the-following-bones-undergoes-membranous-ossi-cation-54374a95',
      conceptKey: 'ossification-membranous-versus-cartilaginous',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name the bone of the upper limb that ossifies in membrane.',
      explanations: {
        A: 'Correct. The clavicle is one of the book\'s two examples of intra-membranous ossification, with the skull cap — and the only limb bone that forms this way.',
        B: 'The radius is a long bone and ossifies in cartilage, like every other bone of the limbs except the clavicle.',
        C: 'The humerus ossifies in cartilage.',
        D: 'The ulna ossifies in cartilage. A, B, C and D are all bones of the upper limb, which is what makes this question a test of the exception rather than of the rule.',
      },
    },
    {
      key: 'one-of-the-following-bones-undergoes-membranous-ossification-5bdcde3f',
      conceptKey: 'ossification-membranous-versus-cartilaginous',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A second copy of `one-of-the-following-bones-undergoes-membranous-ossi-cation-54374a95` with the same four options and no key. The keyed copy is imported.',
    },
    {
      key: 'intra-membranous-ossification-occurs-in-13e57d29',
      conceptKey: 'ossification-membranous-versus-cartilaginous',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Badly scanned and unkeyed: the stem reads "Intra:membranous", the options carry stray marks ("Clavicle.. ١", "Base.of the skull. | ,", "Diaphiysis") and the option letters are out of order. The answer would be the clavicle, but a row whose option block is this disturbed cannot be trusted to have kept its options with its stem. Recoverable by rescanning the page.',
    },
    {
      key: 'hyaline-cartilage-is-present-in-5e0e0c14',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name a site of hyaline cartilage among sites of the other two types.',
      answerOverride: 'C',
      answerOverrideReason: 'The source printed no key. The department book lists the articular cartilage of joints among the sites of hyaline cartilage, and files the other three options elsewhere: the epiglottis and the auricle under yellow elastic fibrocartilage, the intervertebral disc under white fibrocartilage.',
      explanations: {
        A: 'The epiglottis is yellow elastic fibrocartilage — the standing exception to "the larynx is hyaline", and the reason this option is printed first.',
        B: 'The auricle of the ear is yellow elastic fibrocartilage, which is what lets it be folded and spring back.',
        C: 'Correct. The articular cartilage covering the surfaces of a synovial joint is hyaline, as are the epiphyseal plates, the costal cartilages and the developing bones of the fetus.',
        D: 'The intervertebral disc is white fibrocartilage — an opaque matrix packed with collagen bundles, built to take compression rather than to glide.',
      },
    },
    {
      key: 'hyaline-cartilage-is-present-in-dep-book-1846aa9a',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `hyaline-cartilage-is-present-in-5e0e0c14` in which the answer option has been replaced by bleed-through from a neighbouring question: option C reads "Ribs and sternum", which belongs to the appendicular-skeleton item on the same page. An option set contaminated that way cannot be trusted even where it looks intact.',
    },
    {
      key: 'white-fibrocartilage-is-present-in-4411e857',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name the site of white fibrocartilage among sites of the other two types.',
      explanations: {
        A: 'The epiglottis is yellow elastic fibrocartilage.',
        B: 'The auricle of the ear is yellow elastic fibrocartilage.',
        C: 'Articular cartilage is hyaline. It is the most tempting wrong answer here because a joint surface takes load, and load is what fibrocartilage is for — but the surface has to be smooth, and collagen bundles are not.',
        D: 'Correct. The intervertebral disc is the department book\'s one named site of white fibrocartilage, and unlike hyaline it does not ossify in old age.',
      },
    },
    {
      key: 'white-brocartilage-is-present-in-dep-book-p-vi-a-epiglottis-10f60675',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `white-fibrocartilage-is-present-in-4411e857` with the same four options, the first also duplicated into the stem, and no key. The keyed copy is imported.',
    },
    {
      key: 'white-fibrocartilage-is-present-in-one-of-the-followings-74ff5282',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Two options survived — the epiglottis and the auricle of the ear — and both are yellow elastic fibrocartilage, so the answer is among the options that were lost. `white-brocartilage-is-present-in-one-of-the-following-2019-a-c053d231` is the complete printing of this variant and is imported instead.',
    },
    {
      key: 'white-brocartilage-is-present-in-one-of-the-following-2019-a-c053d231',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Name the site of white fibrocartilage when a hyaline site of the thoracic wall is offered alongside.',
      explanations: {
        A: 'The epiglottis is yellow elastic fibrocartilage.',
        B: 'The auricle of the ear is yellow elastic fibrocartilage.',
        C: 'Correct. The intervertebral disc is the book\'s named site of white fibrocartilage.',
        D: 'Costal cartilage is hyaline, and it is the distractor that separates this printing from the others: a student who has learnt only "fibrocartilage takes load" will reach for the cartilage that carries the ribcage.',
      },
    },
    {
      key: 'an-example-of-white-brocartilage-dep-book-2017-bd174730',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Moderate', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Two reasons, and either would be enough. Only three options survived against an import contract of four to five; and of the three, two are defensible — the chapter names the intervertebral disc as its site of white fibrocartilage, which is the printed key A, but the symphysis pubis in option C is fibrocartilage as well, and the chapter\'s silence about it is not the same as denying it. The same objective is imported through `white-fibrocartilage-is-present-in-4411e857` and `white-brocartilage-is-present-in-one-of-the-following-2019-a-c053d231`, whose option sets do not have that problem.',
    },
    {
      key: 'yellow-elastic-fibrocartilage-is-present-in-f8cb13b6',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name the site of yellow elastic fibrocartilage among sites of the other two types.',
      explanations: {
        A: 'Developing bone in the fetus is a hyaline cartilage model, waiting to be replaced.',
        B: 'Correct. The auricle of the ear is yellow elastic fibrocartilage, with the tip of the nose and the epiglottis.',
        C: 'Articular cartilage is hyaline.',
        D: 'The symphysis pubis is fibrous rather than elastic, and is offered here because "yellow elastic fibrocartilage" contains the word fibrocartilage — the classic misreading of the name.',
      },
    },
    {
      key: 'yellow-elastic-brocartilage-is-present-in-dep-book-76241a77',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A "(DEP BOOK)" reprint of `yellow-elastic-fibrocartilage-is-present-in-f8cb13b6` with the same four options and no key. The keyed copy is imported.',
    },
    {
      key: 'yellow-elastic-fibrocartilage-is-present-in-developing-bone-e6e80e10',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'A third copy of the same question, with its first option folded into the stem, its third option lost and no key. The keyed copy is imported.',
    },
    {
      key: 'the-type-of-cartilage-in-the-tip-of-the-nose-is-dep-book-em-3e166997',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Name the type of cartilage at the tip of the nose.',
      explanations: {
        A: 'Hyaline cartilage is in the developing bones, the epiphyseal plates, the joint surfaces, the costal cartilages and the larynx below the epiglottis — never in the nasal tip.',
        B: 'White fibrocartilage is the intervertebral disc. It is built to resist compression, and a nose tip that resisted compression would not spring back.',
        C: 'Correct. The tip of the nose is yellow elastic fibrocartilage, with the auricle of the ear and the epiglottis — the three places that have to bend and recoil.',
        D: 'The tip of the nose is cartilage, which is exactly why it has no bony landmark and why it moves when pressed. Chosen by students who confuse the soft, mobile tip with the absence of a skeleton.',
      },
    },
    {
      key: 'the-following-artery-supplies-the-inner-part-of-the-shaft-of-eaebb4b4',
      conceptKey: 'long-bone-arterial-supply-nutrient-metaphyseal-epiphyseal-periosteal',
      difficulty: 'Moderate', questionType: 'Structure and function',
      learningObjective: 'Assign each part of a long bone to the artery that supplies it, and divide the shaft between the nutrient and the periosteal arteries.',
      answerOverride: 'c',
      answerOverrideReason: 'The 2020 paper printed no key and the recovered answer sheet does not cover this source, so the answer comes from the department book, which states that the nutrient artery enters the middle of the shaft and supplies the inner two-thirds of it, while the periosteal arteries supply the outer third. The paper calls that vessel the diaphyseal artery and the book calls it the nutrient artery; the two names are the same vessel \u2014 the artery of the diaphysis \u2014 and no other option names anything in the interior of the shaft.',
      explanations: {
        a: 'The epiphyseal arteries supply the expanded ends of the bone, and only after the epiphyseal plate has ossified do they anastomose with the metaphyseal arteries. Before that they are shut off from the shaft entirely, which is the anatomical reason a growing bone and an adult bone behave differently.',
        b: 'The periosteal arteries are the other half of this question and the commonest wrong answer, because they are the vessels of the shaft a student pictures first. They supply the outer third; the stem asks for the inner part.',
        c: 'Correct. The nutrient, or diaphyseal, artery enters through the oblique nutrient foramen at the middle of the shaft, runs away from the growing end, and supplies the inner two-thirds of the shaft.',
        d: 'The metaphyseal arteries enter through minute foramina to supply the metaphysis, the narrow, highly active zone just under the epiphyseal cartilage. That is a region of the bone, not a part of the shaft\u2019s interior.',
      },
    },
    {
      key: 'which-is-an-example-of-hyaline-cartilage-ke-intervertebral-d-f913d2aa',
      conceptKey: 'cartilage-three-types-and-their-sites',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'From the ringed 2024 script: the candidate\u2019s pen crossed the option letters, so `options` is empty and the four sites survive only inside the stem \u2014 intervertebral discs, symphysis pubis, epiphyses, auricle of the ear. The department book lists the epiphyseal plates of long bones among the sites of hyaline cartilage, and puts the discs and the symphysis under fibrocartilage and the auricle under elastic cartilage, so the item is a clean three-way test of the cartilage types. Nothing in a seed can restore options to a bank row; a rescan of an unringed copy recovers it.',
    },
    {
      key: 'which-of-the-following-bones-is-a-sesamoid-bone-om-pisiform-4736bf4c',
      conceptKey: 'bone-shapes-six-classes-with-examples',
      difficulty: 'Easy', questionType: 'Classification',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Filed here rather than in `hand.ts`, where the slice put it on the word "pisiform": the question is a bone-classification question and this leaf owns both the concept and the question-book copy of it, `which-of-the-following-bones-is-a-sesamoid-bone-2024-441bd6ea`. It comes from the ringed 2024 script with `options` empty \u2014 the four carpal bones are inside the stem, which then runs on into question 97 about the gomphosis with four more options. The pisiform is the sesamoid, lying in the tendon of flexor carpi ulnaris; a rescan of an unringed copy recovers both questions.',
    },
  ],
}
