/**
 * Build the validator source index for the Helwan University corpus.
 *
 *   node --experimental-strip-types scripts/helwan/build-source-index.ts
 *
 * `scripts/validate-content-batch.mjs` resolves the source index beside a
 * university's import batches. Helwan's intake is held in one content-addressed
 * manifest, so this file translates that manifest into the validator schema
 * without minting or changing any source identity.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const REPO = process.cwd()
const MANIFEST = 'docs/Helwan-Source-Imports/manifest/helwan-y1-3-sources.json'
const OUT = 'docs/Helwan-Source-Imports/evidence/corpus-source-index.json'

interface ManifestSource {
  sourceId: string
  corpusRelativePath: string
  sha256: string
  processingStatus: string | null
  textLayer: string | null
  pageCount: number | null
  fileType: string
  exclusionReason: string | null
}

interface ManifestDoc {
  generatedOn: string
  sources: ManifestSource[]
}

const manifest = JSON.parse(readFileSync(join(REPO, MANIFEST), 'utf8')) as ManifestDoc

// A source ID is content-addressed, so multiple rows with one ID are the same
// bytes filed at several true paths. Preserve every path instead of allowing
// manifest order to choose an arbitrary winner.
const paths = new Map<string, Set<string>>()
for (const source of manifest.sources) {
  const seen = paths.get(source.sourceId) ?? new Set<string>()
  seen.add(source.corpusRelativePath)
  paths.set(source.sourceId, seen)
}

const sources: Record<string, unknown> = {}
let excluded = 0
let ambiguous = 0
for (const source of manifest.sources) {
  if (source.exclusionReason && !sources[source.sourceId]) excluded += 1
  const all = [...(paths.get(source.sourceId) ?? [])].sort()
  if (all.length > 1 && !sources[source.sourceId]) ambiguous += 1
  sources[source.sourceId] = {
    sourceRelativePath: all.length === 1 ? all[0] : null,
    sourceRelativePaths: all,
    sha256: source.sha256,
    processingStatus: source.processingStatus,
    textLayer: source.textLayer,
    pageCount: source.pageCount ?? null,
    fileType: source.fileType,
    languages: [],
    exclusionReason: source.exclusionReason ?? null,
  }
}

mkdirSync(dirname(join(REPO, OUT)), { recursive: true })
writeFileSync(join(REPO, OUT), `${JSON.stringify({
  note: 'Every source ID in the Helwan University Years 1-3 corpus manifest. '
    + 'A batch naming a src_ ID absent here is naming a source the governed corpus does not contain. '
    + 'Generated by scripts/helwan/build-source-index.ts — do not hand-edit.',
  generatedFrom: MANIFEST,
  manifestGeneratedOn: manifest.generatedOn,
  count: Object.keys(sources).length,
  sources,
}, null, 1)}\n`)

console.log(JSON.stringify({
  sources: Object.keys(sources).length,
  paths: manifest.sources.length,
  excluded,
  ambiguous,
  out: OUT,
}, null, 1))
