/**
 * Which article teaches which concept, read out of the articles themselves.
 *
 *   node --experimental-strip-types scripts/kasr/build-article-links.ts
 *
 * `writtenBlock` omits `library_ids` entirely when its lookup returns
 * undefined, so a question whose concept is missing from the map is emitted
 * with no article at all and the batch reports "nothing teaches this question's
 * answer" — even when the article exists and names the concept perfectly well.
 * The map is therefore load-bearing, and it has been maintained by hand.
 *
 * A hand-maintained map is the same fact written twice: once in the article's
 * `related_concepts`, once here. The two drift, and they drift silently,
 * because nothing compares them. This reads the articles and derives the map,
 * so there is one source and the question of which copy is right cannot arise.
 *
 * Writes `scripts/kasr/seeds/article-links.json`. A concept taught by more than
 * one article keeps them all: the coverage check asks whether a question's
 * concept names an article the question also cites, and a concept examined from
 * two sides is genuinely taught by both.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ARTICLES = 'docs/Kasr-Source-Imports/article'
const CONCEPTS = 'docs/Kasr-Source-Imports/concept'
const OUT = 'scripts/kasr/seeds/article-links.json'

const field = (block: string, label: string) =>
  block.match(new RegExp(`^## ${label}\\s*\\n([\\s\\S]*?)(?=\\n## |$)`, 'm'))?.[1].trim() ?? ''

const list = (value: string) =>
  value.split(/[|;\n]/).map((one) => one.trim()).filter(Boolean)

const blocks = (dir: string) =>
  readdirSync(dir).filter((name) => name.endsWith('.md')).flatMap((name) =>
    readFileSync(join(dir, name), 'utf8').split(/^\s*---\s*$/m).map((block) => ({ block, file: name })))

/** conceptId -> the articles that name it, and the articles it names back. */
const byConcept = new Map<string, Set<string>>()
const link = (conceptId: string, articleId: string) => {
  const found = byConcept.get(conceptId) ?? new Set<string>()
  found.add(articleId)
  byConcept.set(conceptId, found)
}

const articleIds = new Set<string>()
for (const { block } of blocks(ARTICLES)) {
  const id = field(block, 'id')
  if (!id) continue
  articleIds.add(id)
  for (const conceptId of list(field(block, 'related_concepts'))) link(conceptId, id)
}

// The other direction. A concept may name its article rather than the reverse,
// and `conceptImport.ts` reads that column straight into `articleIds`, so it is
// as real a link as the article's own list.
const conceptIds = new Set<string>()
for (const { block } of blocks(CONCEPTS)) {
  const id = field(block, 'id')
  if (!id) continue
  conceptIds.add(id)
  for (const articleId of list(field(block, 'article_ids'))) link(id, articleId)
}

const dangling = [...byConcept.entries()].flatMap(([conceptId, articles]) =>
  [...articles].filter((articleId) => !articleIds.has(articleId))
    .map((articleId) => `${conceptId} -> ${articleId}`))

const links = Object.fromEntries(
  [...byConcept.entries()]
    .filter(([conceptId]) => conceptIds.has(conceptId))
    .map(([conceptId, articles]) => [conceptId, [...articles].filter((one) => articleIds.has(one)).sort()])
    .filter(([, articles]) => (articles as string[]).length)
    .sort(([a], [b]) => (a as string).localeCompare(b as string)),
)

writeFileSync(OUT, JSON.stringify({
  note: 'Generated by scripts/kasr/build-article-links.ts from the article and concept batches. Do not edit by hand.',
  // Said in the file because it cannot be checked by anything that reads it.
  // The coverage check asks whether an article CLAIMS a concept, never whether
  // it TEACHES it — and another lane nearly wired a notochord concept to an
  // article mentioning the notochord twelve times without once saying it
  // becomes the nucleus pulposus, which is the concept. Coverage would have
  // gone green and sent a student to an article that does not answer the
  // question. A wrong wiring is invisible and permanent.
  warning: 'Each link is a claim by an author that the two are related, not evidence the article answers the concept. Read the article for the concept before treating a link as verified. The untaught list below is the half you can trust unread — an absence cannot be a wrong wiring.',
  concepts: Object.keys(links).length,
  articles: articleIds.size,
  links,
}, null, 1) + '\n')

const taught = Object.keys(links).length
console.log(`${articleIds.size} articles teach ${taught} of ${conceptIds.size} concepts -> ${OUT}`)

const untaught = [...conceptIds].filter((id) => !links[id])
if (untaught.length) {
  console.log(`\n${untaught.length} concept(s) no article names, and which no question can therefore cite:`)
  for (const id of untaught.slice(0, 20)) console.log(`  ${id}`)
  if (untaught.length > 20) console.log(`  … and ${untaught.length - 20} more`)
}
if (dangling.length) {
  console.log(`\n${dangling.length} link(s) to an article that is authored nowhere:`)
  for (const one of dangling.slice(0, 10)) console.log(`  ${one}`)
}
