/**
 * Build every 101 ISK batch from the papers registered below.
 *
 * One command for the whole module, so adding a paper is adding a seed file and
 * a line here — never a new script with its own idea of what a field means.
 *
 *   node --experimental-strip-types scripts/kasr/build-batches.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { mintConceptId, partsKey, type Paper, type Seed } from './seeds/types.ts'
import { batchFile, conceptBlock, writtenBlock } from './emit.ts'
import { PAPER as EOY_2025 } from './seeds/101-eoy-2025.ts'
import { ARTICLE_FOR_CONCEPT } from './seeds/articles.ts'

/** Every paper that has been read. Order is priority order, highest first. */
const PAPERS: Paper[] = [EOY_2025]

const OUT = 'docs/Kasr-Source-Imports'
const slug = (paper: Paper) =>
  `101-ISK-${paper.source.tier === 'end_of_year' ? 'EOY' : 'EOM'}-${paper.source.sittingYear}`

/**
 * Concepts, deduplicated by canonical key across every paper.
 *
 * Two papers asking the same thing are one concept with two occurrences, not
 * two concepts. The alternative splits a student's mastery across duplicates
 * and inflates the blueprint weight of whatever happens to be asked often.
 */
function concepts() {
  const byKey = new Map<string, { paper: Paper, seed: Seed, repeats: string[] }>()

  for (const paper of PAPERS) {
    for (const seed of paper.seeds) {
      const found = byKey.get(seed.key)
      if (!found) { byKey.set(seed.key, { paper, seed, repeats: [] }); continue }
      // The first paper's reading wins — papers are registered in priority
      // order — and the later one is recorded as another occurrence.
      found.repeats.push(
        `${paper.source.id} | ${paper.source.tier} | ${paper.source.sittingYear} | p${seed.page} | 101 ISK`)
    }
  }

  const blocks = [...byKey.values()].map(({ paper, seed, repeats }) =>
    conceptBlock(paper.source, seed, repeats))

  const repeated = [...byKey.values()].filter((entry) => entry.repeats.length).length
  const header = `Concepts for 101 ISK, from every paper read so far.

${PAPERS.map((paper) => `  ${paper.source.file} — ${paper.source.tier.replace(/_/g, ' ')} ${paper.source.sittingYear}, ${paper.seeds.length} questions`).join('\n')}

${byKey.size} concepts from ${PAPERS.reduce((sum, paper) => sum + paper.seeds.length, 0)} questions.
${repeated} of them were asked on more than one paper, and carry an exam_signal
line per sitting: repetition is the strongest blueprint evidence this corpus
holds, and it only exists once the papers are read together.

Placement is on the discipline view (DIS-ANA, DIS-HIS, DIS-EMB), which is where
basic-science material belongs; the system view is a secondary placement where
one genuinely applies. \`module_subject\` carries the Kasr curriculum position,
which does not belong in the canonical tree.

Generated by scripts/kasr/build-batches.ts — edit the seeds in scripts/kasr/seeds/.`

  mkdirSync(`${OUT}/concept`, { recursive: true })
  const file = `${OUT}/concept/101-ISK-concepts.md`
  writeFileSync(file, batchFile(header, blocks))
  return { file, count: byKey.size, repeated }
}

/** Written questions, one batch per paper: an occurrence belongs to its sitting. */
function written(paper: Paper) {
  const blocks = paper.seeds.map((seed) =>
    writtenBlock(paper, seed, ARTICLE_FOR_CONCEPT[mintConceptId(seed.subject, seed.key)]))
  const total = paper.seeds.reduce((sum, seed) => sum + seed.marks, 0)
  const bySection = paper.source.sections
    .map((section) => `${paper.seeds.filter((seed) => seed.section === section).length} in ${section}`)
    .join(', ')

  const header = `${paper.source.file} as sittable written questions.

Kasr Al Ainy, module 101 ISK, ${paper.source.tier.replace(/_/g, ' ')} ${paper.source.sittingYear}.
Manifest ID ${paper.source.id}. ${paper.seeds.length} questions, ${total} marks: ${bySection}.

Transcribed, not derived — \`derived_from\` is blank throughout. The rule that a
written question may only be derived from another written question governs the
practice variants that come later, not these.

Each question carries one part worth the paper's own total, with the elements the
examiner named as its expected points. \`markWritten\` apportions the marks across
those points, so a student's score agrees with the mark on the page without
anyone inventing a per-element split the examiner never printed.

Status is Draft: these need a faculty reviewer to confirm the mark schemes before
students sit them.

Provenance is in \`source_citation\` and \`author_notes\`, which the student ledger
strips. A student is never told which paper a question came off.

Generated by scripts/kasr/build-batches.ts.`

  mkdirSync(`${OUT}/question`, { recursive: true })
  const file = `${OUT}/question/${slug(paper)}-written.md`
  writeFileSync(file, batchFile(header, blocks))
  return { file, count: paper.seeds.length, marks: total }
}

for (const paper of PAPERS) {
  for (const seed of paper.seeds) {
    if (!paper.schemes[partsKey(seed)]) {
      throw new Error(`${paper.source.file}: ${partsKey(seed)} has no mark scheme`)
    }
  }
}

const c = concepts()
console.log(`${c.count} concepts (${c.repeated} repeated across papers) -> ${c.file}`)
for (const paper of PAPERS) {
  const w = written(paper)
  console.log(`${w.count} written questions, ${w.marks} marks -> ${w.file}`)
}
