import { useMemo,useState,type ReactNode } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { ArrowDown,ArrowUp,ArrowLeft,ArrowRight,Check,RotateCcw } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { PageContainer,PageHeader } from '@/components/shell/Page'
import { useT } from '@/lib/i18n'
import { FOUNDATION_TOPICS,FOUNDATION_ORDER_PACKS,FOUNDATION_RED_FLAG_PACKS,type FoundationTopic } from '../../../server/shared/foundationGames.js'
import { FOUNDATION_SPOTTERS,type FoundationSpotter } from '../../../server/shared/foundationSpotters.js'
import type { OrderedMiniGamePack,RedFlagSortPack } from '@/data/minigamePacks'
import { scoreOrderedSteps,shuffledStepIds,scoreRedFlagSort } from '@/data/minigamePacks'
import { TermGridPlayer } from '@/components/termgrid/TermGridPage'
import { TermMatchPlayer } from './TermMatchPage'
import { buildBoard,type MatchBoard } from '@/data/termMatch'
import { MaristanaModel } from '@/components/maristanas/MaristanaModel'
import './foundationGames.css'
export type FoundationGameKind='term-grid'|'term-match'|'spotter'|'clinical-sequence'|'mechanism-chain'|'red-flag-sort'|'maristanas'
const titles:Record<FoundationGameKind,string>={'term-grid':'Term Grid','term-match':'Term Match',spotter:'Spotter','clinical-sequence':'Clinical Sequence','mechanism-chain':'Mechanism Chain','red-flag-sort':'Red Flag Sort',maristanas:'Build Maristanas'}
function OrderRound({pack}:{pack:OrderedMiniGamePack}){
  const t=useT(),[ids,setIds]=useState(()=>shuffledStepIds(pack,37491)),[checked,setChecked]=useState(false)
  const move=(index:number,delta:number)=>{const next=[...ids];[next[index],next[index+delta]]=[next[index+delta],next[index]];setIds(next);setChecked(false)}
  const score=scoreOrderedSteps(pack,ids)
  return <><p className="foundation-prompt">{pack.prompt}</p><ol className="foundation-order">{ids.map((id,i)=><li key={id} data-correct={checked?pack.steps[i].id===id:undefined}><span className="foundation-position">{i+1}</span><span>{pack.steps.find(step=>step.id===id)?.text}</span><div><button aria-label={`${t('Move up')}: ${pack.steps.find(step=>step.id===id)?.text}`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button aria-label={`${t('Move down')}: ${pack.steps.find(step=>step.id===id)?.text}`} disabled={i===ids.length-1} onClick={()=>move(i,1)}><ArrowDown size={16}/></button></div></li>)}</ol><Button variant="primary" onClick={()=>setChecked(true)}>{t('Check order')}</Button>{checked&&<div className="foundation-feedback" role="status"><strong>{score.exactPositions} / {ids.length} {t('in the right position')}</strong><p>{pack.explanation}</p>{score.exactPositions!==ids.length&&<details><summary>{t('Show the sequence')}</summary><ol>{pack.steps.map(step=><li key={step.id}>{step.text}</li>)}</ol></details>}</div>}</>
}
function RedFlagRound({pack}:{pack:RedFlagSortPack}){
  const t=useT(),[answers,setAnswers]=useState<Record<string,'urgent'|'routine'>>({}),[checked,setChecked]=useState(false)
  // Interleave lanes so the source order does not reveal the answers.
  const findings=[pack.findings[2],pack.findings[0],pack.findings[3],pack.findings[1]]
  const score=scoreRedFlagSort(pack,answers)
  return <><p className="foundation-prompt">{pack.prompt}</p><div className="foundation-scenarios">{findings.map(finding=><fieldset key={finding.id}><legend>{finding.text}</legend><div>{(['urgent','routine'] as const).map(lane=><button key={lane} aria-pressed={answers[finding.id]===lane} onClick={()=>{setAnswers({...answers,[finding.id]:lane});setChecked(false)}}>{pack.lanes[lane]}</button>)}</div>{checked&&<p>{answers[finding.id]===finding.lane?<Check size={14}/>:null} {finding.rationale} {answers[finding.id]!==finding.lane&&`${t('Answer')}: ${pack.lanes[finding.lane]}`}</p>}</fieldset>)}</div><Button variant="primary" disabled={Object.keys(answers).length!==findings.length} onClick={()=>setChecked(true)}>{t('Check answers')}</Button>{checked&&<p className="foundation-feedback" role="status">{score.correct} / {findings.length} {t('correct')}</p>}</>
}
function SpotterRound({pack}:{pack:FoundationSpotter}){
  const t=useT(),[round,setRound]=useState(0),[answer,setAnswer]=useState<string|null>(null),[correct,setCorrect]=useState(0),target=pack.structures[round]
  if(!target)return <div className="foundation-finish"><h3>{t('Set complete')}</h3><p>{correct} / {pack.structures.length} {t('correct')}</p><Button onClick={()=>{setRound(0);setAnswer(null);setCorrect(0)}}>{t('Try again')}</Button></div>
  return <><p className="foundation-prompt">{t('Identify the structure at the numbered pin.')} <span>{round+1} / {pack.structures.length}</span></p><div className="foundation-spotter"><div className="foundation-diagram"><img src={pack.image} alt={`${pack.title} — ${t('unlabelled teaching schematic')}`} width="600" height="400"/><span className="foundation-pin" style={{left:`${target.x*100}%`,top:`${target.y*100}%`}}>{round+1}</span></div><div className="foundation-options">{[...pack.structures].sort((a,b)=>a.label.localeCompare(b.label)).map(structure=><button key={structure.id} disabled={answer!==null} aria-pressed={answer===structure.id} onClick={()=>{setAnswer(structure.id);if(structure.id===target.id)setCorrect(v=>v+1)}}>{structure.label}</button>)}{answer&&<div className="foundation-feedback" role="status"><strong>{t(answer===target.id?'Correct':'Keep learning')} · {target.label}</strong><Button variant="primary" iconRight={ArrowRight} onClick={()=>{setRound(v=>v+1);setAnswer(null)}}>{t(round===pack.structures.length-1?'Finish set':'Next structure')}</Button></div>}</div></div></>
}
function HospitalRound({pack}:{pack:FoundationTopic}){
  const t=useT(),[index,setIndex]=useState(0),[answer,setAnswer]=useState<string|null>(null),[score,setScore]=useState(0),target=pack.terms[index]
  const choices=useMemo(()=>target?[target,...pack.terms.filter(term=>term.id!==target.id).slice(index%3,index%3+3)].sort((a,b)=>a.term.localeCompare(b.term)):[],[pack,index,target])
  return <div className="foundation-hospital"><div><MaristanaModel name={pack.title} stage={Math.round(score/pack.terms.length*25)}/><p className="text-sm text-ink-2">{t('Practice build')} · {score} / {pack.terms.length} {t('knowledge blocks')}</p></div><section>{target?<><p className="foundation-prompt">{target.def}</p><div className="foundation-options">{choices.map(choice=><button key={choice.id} disabled={answer!==null} aria-pressed={answer===choice.id} onClick={()=>{setAnswer(choice.id);if(choice.id===target.id)setScore(v=>v+1)}}>{choice.term}</button>)}</div>{answer&&<div className="foundation-feedback" role="status"><strong>{t(answer===target.id?'Correct':'Answer')}: {target.term}</strong><Button variant="primary" onClick={()=>{setIndex(v=>v+1);setAnswer(null)}}>{t('Continue')}</Button></div>}</>:<><h3 className="font-serif text-2xl">{t('Practice build complete')}</h3><p>{score} / {pack.terms.length} {t('correct. Each answer added to your practice hospital.')}</p><p className="text-sm text-ink-2 mt-3">{t('Practice builds are separate from earned credits in your main hospital.')}</p><Button className="mt-3" onClick={()=>{setIndex(0);setScore(0);setAnswer(null)}}>{t('Rebuild')}</Button></>}</section></div>
}
export function FoundationGameLibrary({kind,children}:{kind:FoundationGameKind;children:ReactNode}){
  const t=useT(),[params,setParams]=useSearchParams(),[advanced,setAdvanced]=useState(false),[generation,setGeneration]=useState(0)
  const sets=kind==='spotter'?FOUNDATION_SPOTTERS:kind==='red-flag-sort'?FOUNDATION_RED_FLAG_PACKS:kind==='clinical-sequence'||kind==='mechanism-chain'?FOUNDATION_ORDER_PACKS.filter(pack=>pack.kind===kind.replaceAll('-','_')):FOUNDATION_TOPICS
  const requested=params.get('set'),pack=sets.find(item=>item.id===requested)??null
  const setPack=(id:string|null)=>{setParams(current=>{const next=new URLSearchParams(current);if(id)next.set('set',id);else next.delete('set');return next});setGeneration(0)}
  if(advanced)return <><div className="foundation-advanced-back"><Button variant="ghost" iconLeft={ArrowLeft} onClick={()=>setAdvanced(false)}>{t('Back to ready games')}</Button></div>{children}</>
  const seed=37491+generation
  const topic=pack as FoundationTopic
  const board=kind==='term-match'&&pack?buildBoard(topic.terms,'definition',seed):null
  return <PageContainer className="foundation-library"><PageHeader title={t(titles[kind])} description={t('Short medical games. Shared foundations. A little progress with every round.')} back={{fallback:'/app/minigames'}}/><div className="foundation-toolbar"><span>{t('10 ready sets · all universities')}</span><Button variant="ghost" size="sm" onClick={()=>setAdvanced(true)}>{t(kind==='maristanas'?'Open my main hospital':kind==='spotter'?'University slides':'More practice options')}</Button></div>{pack?<><header className="foundation-game-header"><Button variant="ghost" size="sm" iconLeft={ArrowLeft} onClick={()=>setPack(null)}>{t('All sets')}</Button><h2>{pack.title}</h2><Button variant="secondary" size="sm" iconLeft={RotateCcw} onClick={()=>setGeneration(v=>v+1)}>{t('Restart')}</Button></header><div className="foundation-play" key={`${kind}-${pack.id}-${generation}`}>
    {kind==='term-grid'?<TermGridPlayer category={`foundation-${topic.id}`} seed={seed} terms={topic.terms.map(term=>({term:term.term,clue:term.def}))} onReplay={()=>setGeneration(v=>v+1)}/>:kind==='term-match'&&board&&!board.refusal?<TermMatchPlayer board={board as MatchBoard&{refusal:null}} onReplay={()=>setGeneration(v=>v+1)}/>:kind==='spotter'?<SpotterRound pack={pack as FoundationSpotter}/>:kind==='red-flag-sort'?<RedFlagRound pack={pack as RedFlagSortPack}/>:kind==='maristanas'?<HospitalRound pack={topic}/>:<OrderRound pack={pack as OrderedMiniGamePack}/>}
    </div><p className="foundation-source"><a href={pack.source.url} target="_blank" rel="noreferrer">{pack.source.label} ↗</a></p></>:<div className="foundation-set-list">{sets.map((item,i)=><button key={item.id} onClick={()=>setPack(item.id)}>{kind==='spotter'?<img src={(item as FoundationSpotter).image} alt=""/>:<span className="foundation-set-number">{i+1}</span>}<span><strong>{item.title}</strong><small>{t(kind==='spotter'?'4 structures · teaching schematic':kind==='maristanas'?'8 questions · practice hospital':kind==='term-grid'?'8 clues · crossword':kind==='term-match'?'8 pairs · terms and definitions':kind==='red-flag-sort'?'4 scenarios · recognise warning signs':'Order the pathway')}</small></span><ArrowRight size={18}/></button>)}</div>}<footer className="foundation-footer"><Link to="/app/study-rooms">{t('Study with your room')} <ArrowRight size={14}/></Link></footer></PageContainer>
}
