import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Pericardium",
  modulePath: "104 CPS > Anatomy > Pericardium",
  articleId: "ART-104-ANA-PERICARDIUM-SINUSES",

  concepts: [
    {
      key: "pericardium.transverse-and-oblique-sinuses",
      label: "The transverse sinus is a through-passage between the arterial and venous ends of the heart; the oblique sinus is a blind recess behind the left atrium, open only below",
      definition: "The visceral layer of serous pericardium sends two tube-like extensions over the roots of the great vessels: an anterior tube enclosing the ascending aorta and pulmonary trunk together, and a posterior tube enclosing parts of the superior and inferior venae cavae and the four pulmonary veins. Between these two tubes lies the transverse sinus, a passage connecting the right and left sides of the pericardial cavity between the arterial end of the heart in front and the venous end behind — bounded above and behind by the right pulmonary artery and below and behind by the superior vena cava and the two atria, mainly the left; a finger passed behind the ascending aorta and pulmonary trunk and in front of the lower superior vena cava traverses it. The oblique sinus is a blind recess extending upwards between the back of the left atrium in front and the fibrous pericardium behind, closed above by the pericardial reflection onto the left atrium and open below into the main pericardial cavity between the inferior vena cava and the lower left pulmonary vein.",
      objective: "Describe how to reach the transverse sinus and the oblique sinus with a finger, and name what closes the oblique sinus above.",
      pitfall: "Confusing which sinus is a through-passage and which is a dead end — a finger in the transverse sinus can pass from right to left, while a finger in the oblique sinus stops blind at its upper end, behind the left atrium, not the right.",
      subject: "cvs",
      primary: "DIS-ANA-T04",
      secondary: [],
      modulePath: "104 CPS > Anatomy > Pericardium",
      type: "structural_description",
      aliases: ["Transverse sinus", "Oblique sinus"],
    },
    {
      key: "pericardium.nerve-and-blood-supply",
      label: "The fibrous and parietal serous pericardium are supplied by the phrenic nerves and are pain-sensitive; the visceral layer (epicardium) shares the heart's own autonomic supply and is pain-insensitive but ischaemia-sensitive",
      definition: "The fibrous pericardium and the parietal layer of serous pericardium are supplied by the phrenic nerves, which carry somatic sensation and make this pericardium sensitive to pain, as in pericarditis; their arterial supply is from the internal thoracic arteries and their pericardiacophrenic and musculophrenic branches and from the descending aorta, with venous drainage through the azygos system. The visceral layer of serous pericardium, the epicardium, is supplied like the rest of the heart by autonomic sympathetic and parasympathetic fibres and is insensitive to pain but sensitive to ischaemia; its blood supply is from the right and left coronary arteries, draining by the coronary sinus.",
      objective: "Contrast the nerve supply of the fibrous and parietal pericardium with that of the visceral layer, and state which layer is pain-sensitive.",
      pitfall: "Assuming the whole pericardium is pain-sensitive because pericarditis hurts — only the fibrous and parietal layers (phrenic nerve) carry pain; the visceral layer (epicardium) feels ischaemia, not pain.",
      subject: "cvs",
      primary: "DIS-ANA-T04",
      secondary: [],
      modulePath: "104 CPS > Anatomy > Pericardium",
      type: "mechanism",
      aliases: ["Pericardium nerve supply", "Pericardium blood supply"],
    },
    {
      key: "pericardium.fibrous-and-serous-layers",
      label: "The fibrous pericardium is a conical sac fixed to the sternum by the sternopericardial ligaments; its parietal serous layer lines it internally and reflects onto the heart as the visceral layer (epicardium)",
      definition: "The pericardium has two coats. The fibrous pericardium is a strong, conical sac with an apex directed upwards, blending at the level of the sternal angle with the outer coats of the great vessels, and a base directed downwards, adherent to the central tendon of the diaphragm — the reverse orientation of the heart itself; its anterior surface is fixed to the sternum by the superior and inferior sternopericardial ligaments. The serous pericardium is a closed sac invaginated from above and behind by the heart and the roots of its great vessels: a parietal layer lines the fibrous pericardium, and a visceral layer covers the heart as the epicardium, the two separated by the pericardial cavity, a potential space holding only a thin film of fluid.",
      objective: "Name the two coats of the pericardium and state which layer of the serous pericardium lines the fibrous pericardium versus which one covers the heart itself.",
      pitfall: "Assuming the visceral layer lines the fibrous pericardium — it is the parietal layer that lines the fibrous pericardium; the visceral layer instead covers the heart directly as the epicardium.",
      subject: "cvs",
      primary: "DIS-ANA-T04",
      secondary: [],
      modulePath: "104 CPS > Anatomy > Pericardium",
      type: "structural_description",
      aliases: ["Fibrous pericardium", "Serous pericardium", "Sternopericardial ligaments"],
    },
  ],

  questions: [
    {
      key: "about-the-transverse-sinus-of-the-serous-pericardium-mark-on-cba8c86e",
      conceptKey: "pericardium.transverse-and-oblique-sinuses",
      difficulty: "Hard",
      questionType: "Recall of the correct statement",
      learningObjective: "Locate the transverse sinus between the arterial end of the heart in front and the venous end behind.",
      explanations: {
        A: "This is the correct answer, and the standard simplified description of this relationship. The transverse sinus lies between the arterial pedicle (ascending aorta and pulmonary trunk) in front and the venous structures (SVC and the roof of the left atrium) behind, formed where the serous pericardium reflects around the great vessels — a finger passed behind the ascending aorta and pulmonary trunk and in front of the lower SVC traverses it from right to left.",
        B: "This option describes something closer to the oblique sinus, which sits behind the left atrium — the transverse sinus's own anterior boundary is the arterial pedicle (ascending aorta and pulmonary trunk), and its posterior boundary is the venous structures (SVC and the atria), not the left atrium's anterior wall paired with the great arteries in this way.",
        C: "The transverse sinus is a potential space, not a conduit for a coronary artery — the right coronary artery runs externally in the coronary (atrioventricular) sulcus, on the heart's own surface, unrelated to this pericardial sinus.",
        D: "The coronary sinus lies in the posterior coronary sulcus, related to the region of the oblique sinus, not contained within the transverse sinus — a venous channel on the heart's surface rather than a structure passing through this space.",
        E: "The circumflex artery runs in the coronary sulcus around the heart's external surface as a branch of the left coronary artery — it does not pass through the pericardial transverse sinus, which carries no vessel at all through its own passage.",
      },
    },
    {
      key: "concerning-the-oblique-sinus-of-the-serous-pericardium-indic-e475ffbf",
      conceptKey: "pericardium.transverse-and-oblique-sinuses",
      difficulty: "Hard",
      questionType: "Recall of the accepted statement",
      learningObjective: "State that the oblique sinus lies behind the left atrium, bounded by the reflections onto the pulmonary veins and venae cavae.",
      explanations: {
        A: "The oblique sinus lies behind the left atrium, not in front of it — it is a blind recess extending upwards between the back of the left atrium (in front of the sinus) and the fibrous pericardium (behind it).",
        B: "This is the correct answer. The oblique sinus sits behind the left atrium and is bounded by the pericardial reflections onto the four pulmonary veins (two right, two left) as well as the SVC and IVC — closed above where the reflection covers the left atrium's posterior surface, and open only below into the main pericardial cavity.",
        C: "This restates part of the true boundary (the pulmonary veins) but omits that the sinus's closure and shape also depend on the SVC and IVC reflections named in the fuller, correct description — the detail that distinguishes the accepted statement from this partial one.",
        D: "The oblique sinus does not lodge the great cardiac vein — that vein runs in the anterior interventricular groove and then the coronary sulcus to drain into the coronary sinus, on the heart's surface rather than within this pericardial recess.",
        E: "The oblique sinus does not transmit the posterior interventricular artery — that artery runs on the heart's diaphragmatic surface in the posterior interventricular groove, not through this blind pericardial recess.",
      },
    },
    {
      key: "is-fused-to-fibrous-pericardium-xxx-bad2bb8e",
      conceptKey: "pericardium.fibrous-and-serous-layers",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the parietal layer of serous pericardium as the layer that lines the fibrous pericardium.",
      explanations: {
        A: "The epicardium is the visceral layer of serous pericardium, covering the heart itself — it is not the layer fused to the fibrous pericardium; that is the parietal layer, on the opposite side of the pericardial cavity.",
        B: "The myocardium is the heart's muscular wall, deep to the epicardium — it has no direct relationship to the fibrous pericardium, which lies external to the whole serous pericardial sac.",
        C: "The visceral layer of serous pericardium covers the heart directly, as the epicardium — it is separated from the fibrous pericardium by the pericardial cavity, not fused to it.",
        D: "This is the correct answer. The parietal layer of the serous pericardium lines the internal surface of the fibrous pericardium, the two effectively fused together, while the visceral layer (epicardium) covers the heart on the cavity's opposite side.",
      },
    },
    {
      key: "regarding-the-oblique-sinus-of-the-pericardium-one-of-the-fo-82078841",
      conceptKey: "pericardium.transverse-and-oblique-sinuses",
      difficulty: "Hard",
      questionType: "Recall of the true statement",
      learningObjective: "State that the oblique sinus opens below into the main pericardial cavity.",
      explanations: {
        A: "The oblique sinus is a blind recess between the left atrium (not the right atrium) anteriorly and the fibrous pericardium posteriorly — the right atrium plays no part in bounding this sinus.",
        B: "This is the correct answer. The oblique sinus is closed above, by the pericardial reflection onto the back of the left atrium, but open below into the main pericardial cavity, between the IVC and the lower left pulmonary vein.",
        C: "The entrance to the oblique sinus is not bounded by the SVC and the lower left pulmonary vein together in this way — its boundaries are the pericardial reflections onto the SVC, the two right pulmonary veins and the IVC on the right, and onto the two left pulmonary veins on the left, closed above by the reflection onto the left atrium.",
        D: "The oblique sinus is related on its right side to the right pulmonary veins (via the pericardial reflections onto them), not to the right pulmonary veins on its left side — sides are swapped in this distractor.",
      },
    },
    {
      key: "regarding-the-pericardium-select-true-statement-390d3b02",
      conceptKey: "pericardium.fibrous-and-serous-layers",
      difficulty: "Moderate",
      questionType: "Recall of the true statement",
      learningObjective: "Name the sternopericardial ligaments as the structures fixing the fibrous pericardium to the sternum.",
      explanations: {
        A: "This is the correct answer. The fibrous pericardium's anterior surface is fixed to the sternum by the superior and inferior sternopericardial ligaments, helping anchor the pericardial sac within the middle mediastinum.",
        B: "The fibrous pericardium in fact fuses with the outer coats of the great vessels, including the superior vena cava, at the level of the sternal angle — it does not spare the SVC from this fusion.",
        C: "The parietal layer of the serous pericardium is supplied by the phrenic nerves and is pain-sensitive, as in pericarditis — it is not without nerve supply; it is the visceral layer (epicardium) that is pain-insensitive.",
        D: "The transverse sinus does not separate the four pulmonary veins from one another — those veins, together with the SVC and IVC, form part of the posterior tube bounding the sinus's venous-end wall; it is the oblique sinus that lies among the pulmonary veins' reflections.",
      },
    },
    {
      key: "regarding-the-pericardium-the-following-statements-are-corre-1ceda27b",
      conceptKey: "pericardium.nerve-and-blood-supply",
      difficulty: "Hard",
      questionType: "Recall of a false statement",
      learningObjective: "Identify the false statement about the phrenic nerve's relationship to the fibrous pericardium.",
      explanations: {
        A: "True, and so not the answer sought. The fibrous pericardium fuses with the outer coats of the great vessels at the level of the sternal angle, where its upward-directed apex blends with them.",
        B: "True, and so not the answer sought. The parietal and visceral layers of the serous pericardium are continuous with each other at the points where the visceral layer reflects off the great vessels onto the parietal layer — the same continuity every serous membrane's two layers share.",
        C: "This is the false statement, and the correct answer. The phrenic nerves run alongside the fibrous pericardium's lateral surface, together with the pericardiacophrenic vessels, on their way to the diaphragm — they are companions of the pericardium, not embedded within the substance of its wall.",
        D: "True, and so not the answer sought. The transverse sinus lies exactly there — between the ascending aorta and pulmonary trunk anteriorly (the arterial end) and the SVC and atria posteriorly (the venous end).",
      },
    },
    {
      key: "regarding-the-function-of-the-pericardium-one-of-the-followi-25ea0a87",
      conceptKey: "pericardium.transverse-and-oblique-sinuses",
      difficulty: "Hard",
      questionType: "Recall",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The stem asks which statement about pericardial function is incorrect, and the editorial-no-printed-key answer names C (\"the oblique sinus allows expansion of oesophagus during swallowing\"). The department book's own article (ART-104-ANA-PERICARDIUM-SINUSES) states this as a TRUE clinical function verbatim — \"the oblique sinus... lets... the oesophagus expand during swallowing without pericardial constraint\" — as does option A (fibrous pericardium protects the heart) and option D (transverse sinus allows distension of the ascending aorta), both also confirmed true by the same source. With A, C and D all true per the source, the genuinely false statement is almost certainly the option lost to OCR extraction (this row shows no option B at all), so keying C would teach a true fact as false. Excluded per ANSWER-KEY GAPS rather than keyed against the source.",
    },
  ],
}
