import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "The Internal Thoracic and Intercostal Arteries",
  modulePath: "104 CPS > Anatomy > Intercostal Spaces",
  articleId: "ART-104-ANA-INTERCOSTAL-MUSCLES-NERVES-VESSELS",

  concepts: [
    {
      // Reuse: canonical_key already pinned in
      // docs/Kasr-Source-Imports/concept/104-CPS-anatomy-concepts.md (line 997).
      key: "internal-thoracic-artery.origin-course-and-branches",
      label: "The internal thoracic artery arises from the first part of the subclavian artery, descends behind the upper six costal cartilages, and terminates opposite the sixth space by dividing into the superior epigastric and musculophrenic arteries",
      definition: "The internal thoracic artery arises from the first part of the subclavian artery in the root of the neck, descends behind the upper six costal cartilages half an inch from the sternal margin, and ends opposite the sixth space by dividing into the superior epigastric and musculophrenic arteries. Along the way it gives the pericardiacophrenic artery (with the phrenic nerve, to pericardium, pleura and diaphragm), six pairs of anterior intercostal branches, perforating branches to the skin and the medial breast, and pericardial, sternal and mediastinal twigs. The superior intercostal artery, by contrast, is not one of its branches — it arises instead from the costocervical trunk, a separate subclavian branch, and supplies the first two intercostal spaces that the internal thoracic artery's own branches never reach.",
      objective: "State the internal thoracic artery's origin, the level of its termination, and its two terminal branches.",
      pitfall: "Crediting the internal thoracic artery with supplying all eleven intercostal spaces via its anterior branches, or with giving off the superior intercostal artery. It supplies only the upper six spaces directly (the seventh to ninth via its musculophrenic branch); the superior intercostal artery is a separate costocervical-trunk vessel supplying the first two spaces instead.",
      subject: "cvs",
      primary: "DIS-ANA-T04",
      secondary: [],
      modulePath: "104 CPS > Anatomy > Intercostal Spaces",
      type: "structural_description",
      aliases: ["Internal mammary artery", "Superior epigastric artery", "Musculophrenic artery", "Pericardiacophrenic artery"],
    },
    {
      // New concept: the intercostal arteries' own sources by space and side,
      // synthesised from three already-sourced facts that no single existing
      // concept states together — the descending thoracic aorta's own branch
      // list (ART-104-ANA-PULMONARY-TRUNK-AND-AORTA), that same article's own
      // "lose_the_mark" note on the upper two spaces, and the internal
      // thoracic artery's anterior-branch pattern (ART-104-ANA-INTERCOSTAL-
      // MUSCLES-NERVES-VESSELS) — no fact here is invented, only collected.
      key: "intercostal-arteries.sources-by-space-and-side",
      label: "Posterior intercostal arteries come from two sources by space — the superior intercostal artery (1st-2nd) and the descending thoracic aorta (3rd-11th) — while anterior intercostal arteries come from the internal thoracic artery directly (upper six spaces) or its musculophrenic branch (7th-9th)",
      definition: "The eleven posterior intercostal arteries on each side come from two different sources by space: the first and second arise from the superior intercostal artery, itself an indirect (costocervical-trunk) branch of the subclavian artery, while the third to eleventh arise directly from the descending thoracic aorta, which also gives a subcostal pair below the last space. The anterior intercostal arteries instead come from the internal thoracic system: the upper six spaces receive them directly from the internal thoracic artery itself, while the seventh to ninth receive them from its terminal musculophrenic branch — so no single vessel supplies every anterior intercostal space directly. The right third posterior intercostal artery additionally gives off the right bronchial artery, supplying the bronchial tree and lung stroma on that side.",
      objective: "State which posterior intercostal arteries come from the superior intercostal artery and which from the descending thoracic aorta, and name the vessel that supplies the anterior intercostal arteries of the seventh to ninth spaces.",
      pitfall: "Crediting the descending thoracic aorta with ALL eleven posterior intercostal arteries, or the internal thoracic artery with ALL nine anterior ones. The first two posterior arteries come from the superior intercostal artery instead, and the seventh to ninth anterior arteries come from the internal thoracic artery's musculophrenic branch rather than the parent vessel itself.",
      subject: "cvs",
      primary: "DIS-ANA-T04",
      secondary: [],
      modulePath: "104 CPS > Anatomy > Intercostal Spaces",
      type: "structural_description",
      aliases: ["Superior intercostal artery", "Posterior intercostal artery origin", "Costocervical trunk", "Right bronchial artery"],
    },
  ],

  questions: [
    {
      key: "concerning-the-external-intercostal-muscle-choose-the-incorr-7f6cb920",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Not sittable as printed.",
      learningObjective: "Not sittable as printed.",
      explanations: {},
      exclude: true,
      excludeReason: "Option C's claim (\"the typical thoracic vertebra articulates with the numerically corresponding [rib]\") is general vertebral-column osteology, which ART-104-ANA-THORACIC-CAGE explicitly places outside this chapter's scope (\"the department book's thorax section gives no developmental account of the ribs, sternum or vertebral column as such; that content belongs to general osteology\"). With the book's own thoracic-wall chapter silent on how a typical thoracic vertebra's body and transverse process each articulate with the ribs, this option's truth value cannot be established from the source the lane is scoped to.",
    },
    {
      key: "concerning-the-intercostal-and-subcostal-arteries-which-of-t-24b9b038",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Recall",
      learningObjective: "State that the first two posterior intercostal arteries are indirect branches of the costocervical trunk, via the superior intercostal artery.",
      explanations: {
        A: "The intercostal ARTERY does not lie highest in the costal groove — the VAN order places the vein uppermost, the artery in the middle and the nerve lowest of the three neurovascular structures.",
        B: "This is the correct answer. The first and second posterior intercostal arteries do not come from the descending thoracic aorta at all; they are indirect branches of the costocervical trunk, reaching each space via the superior intercostal artery, itself a subclavian-artery branch.",
        C: "The upper two posterior intercostal arteries are indirect branches of the COSTOCERVICAL trunk, not the thyrocervical trunk — the two trunks are separate branches of the subclavian artery, and swapping them is a classic distractor.",
        D: "Not all anterior intercostal arteries are direct branches of the internal thoracic artery — the seventh to ninth spaces instead receive theirs from its terminal musculophrenic branch, an indirect route.",
        E: "The subcostal artery is a direct branch of the DESCENDING THORACIC aorta, not the abdominal aorta — it arises just above the diaphragm, before the aorta itself becomes abdominal.",
      },
    },
    {
      key: "concerning-the-internal-thoracic-artery-select-correct-answe-749f950e",
      conceptKey: "internal-thoracic-artery.origin-course-and-branches",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that the internal thoracic artery's two terminal branches are the superior epigastric and musculophrenic arteries.",
      explanations: {
        A: "The internal thoracic artery arises from the FIRST part of the subclavian artery, not the second — the first part lies medial to scalenus anterior, where several of the subclavian's other named branches also originate.",
        B: "The internal thoracic artery supplies the upper SIX intercostal spaces directly (with the seventh to ninth reached indirectly via its musculophrenic branch), not the upper nine.",
        C: "This is the correct answer. The internal thoracic artery ends opposite the sixth intercostal space by dividing into its two terminal branches, the superior epigastric and the musculophrenic artery.",
        D: "The internal thoracic artery terminates opposite the SIXTH intercostal space, not the fifth — one space lower than this option states.",
      },
    },
    {
      key: "concerning-the-posterior-intercostal-arteries-select-the-cor-80aa271c",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that posterior intercostal arteries have two sources by space: the superior intercostal artery (1st-2nd) and the descending aorta (3rd-11th).",
      explanations: {
        A: "The posterior intercostal arteries do not arise from the internal thoracic artery at all — that vessel instead supplies the ANTERIOR intercostal arteries, a separate system entirely.",
        B: "Not ALL posterior intercostal arteries arise from the descending thoracic aorta — the first two instead come from the superior intercostal artery, a costocervical-trunk branch of the subclavian artery.",
        C: "This is the correct answer. The posterior intercostal arteries come from two sources depending on the space: the first two from the superior intercostal artery, and the third to eleventh directly from the descending thoracic aorta.",
        D: "The posterior intercostal arteries never arise from the internal thoracic artery — only their anterior counterparts do; the posterior vessels' two sources are the superior intercostal artery and the descending aorta.",
      },
    },
    {
      key: "eleventh-1-regarding-the-external-intercostal-muscle-indicat-9a181d08",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Recall of a false statement",
      learningObjective: "State that not all posterior intercostal arteries arise from the descending thoracic aorta — the first two come from the superior intercostal artery instead.",
      explanations: {
        A: "True of the external intercostal muscle, so not the wrong statement sought — it is the most superficially placed of the three intercostal muscle layers.",
        B: "True of the external intercostal muscle's fibre direction, so not the wrong statement sought — obliquely downwards and forwards.",
        D: "True of the external intercostal muscle's extent, so not the wrong statement sought — it runs from the tubercle of the rib above to the costochondral junction, where the anterior intercostal membrane takes over.",
        C: "This is the wrong statement, and the answer. Not all posterior intercostal arteries are branches of the descending thoracic aorta: the first and second come from the superior intercostal artery, a costocervical-trunk branch of the subclavian artery, and only the third to eleventh come directly from the descending thoracic aorta.",
      },
    },
    {
      key: "one-of-the-following-is-not-a-branch-of-the-internal-thoraci-db5ffa2e",
      conceptKey: "internal-thoracic-artery.origin-course-and-branches",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "State that the superior intercostal artery is not a branch of the internal thoracic artery, but of the costocervical trunk.",
      explanations: {
        A: "The pericardiacophrenic artery is a genuine internal thoracic artery branch, running with the phrenic nerve to the pericardium, pleura and diaphragm — so not the answer sought.",
        B: "The superior epigastric artery is one of the internal thoracic artery's own two terminal branches — so not the answer sought.",
        C: "The musculophrenic artery is the internal thoracic artery's other terminal branch — so not the answer sought.",
        D: "This is the correct answer. The superior intercostal artery is NOT a branch of the internal thoracic artery — it instead arises from the costocervical trunk, a separate branch of the subclavian artery, and supplies the first two intercostal spaces the internal thoracic artery's own branches never reach.",
      },
    },
    {
      key: "regarding-the-intercostal-arteries-one-is-true-15556e57",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Recall",
      learningObjective: "State that the right third posterior intercostal artery gives off the right bronchial artery.",
      explanations: {
        A: "Not ALL posterior intercostal arteries arise from the descending aorta — the first two instead come from the superior intercostal artery, a costocervical-trunk branch of the subclavian artery.",
        B: "The intercostal artery does not lie superior to both the vein and the nerve — the VAN order places the vein above the artery, and the artery above the nerve, so the artery is superior only to the nerve, not to the vein as well.",
        C: "Not ALL anterior intercostal arteries arise from the internal thoracic artery directly — the seventh to ninth spaces instead receive theirs from its musculophrenic branch, an indirect route.",
        D: "This is the correct answer. The right third posterior intercostal artery gives off the right bronchial artery, which supplies the bronchial tree and lung stroma on that side — the left lung instead receives two bronchial arteries directly from the descending thoracic aorta.",
      },
    },
    {
      key: "regarding-the-internal-mammary-artery-the-following-statemen-fae6e956",
      conceptKey: "internal-thoracic-artery.origin-course-and-branches",
      difficulty: "Hard",
      questionType: "Recall of a false statement",
      learningObjective: "Identify the unconfirmed claim about the internal thoracic vein's own side relative to its artery.",
      explanations: {
        A: "True, so not the exception. The internal mammary (internal thoracic) artery is a branch of the first part of the subclavian artery.",
        B: "True, so not the exception. The intercostal nerves cross in front of the internal thoracic vessels near the sternum, on their way to becoming the anterior cutaneous branches.",
        C: "This is the exception, and the answer, reached by elimination: the department book's own account does not state which side of the artery its accompanying vein runs on, so \"the lateral side\" cannot be confirmed as correct — unlike the other four statements, each of which the source directly supports.",
        D: "True, so not the exception. Perforating branches of the internal thoracic (internal mammary) artery share in the arterial supply of the breast.",
        E: "True, so not the exception. The internal thoracic artery ends opposite the sixth intercostal space.",
      },
    },
    {
      key: "regarding-the-internal-thoracic-artery-one-is-false-fdbf7a43",
      conceptKey: "internal-thoracic-artery.origin-course-and-branches",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "State that the internal thoracic artery terminates opposite the sixth intercostal space, not the fifth.",
      explanations: {
        A: "True, so not the answer sought. The internal thoracic artery arises from the first part of the subclavian artery.",
        B: "True, so not the answer sought. The internal thoracic artery supplies the upper six intercostal spaces directly, via its anterior intercostal branches.",
        C: "True, so not the answer sought. The internal thoracic artery gives off the superior epigastric artery as one of its two terminal branches.",
        D: "This is the false statement, and the answer. The internal thoracic artery terminates opposite the SIXTH intercostal space, not the fifth, where it divides into the superior epigastric and musculophrenic arteries.",
      },
    },
    {
      key: "regarding-the-ribs-one-of-the-following-statements-is-wrong-1d20d8ae",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Not sittable as printed.",
      learningObjective: "Not sittable as printed.",
      explanations: {},
      exclude: true,
      excludeReason: "Option D (\"It passes in the costal groove between the intercostal artery and vein\") describes intercostal NERVE position, not any statement about the ribs — an evident cross-contamination from a different bank row during extraction (the same fragment, in a cleaner form, appears attached to a genuinely nerve-focused question elsewhere in this bank). With the printed \"wrong statement\" answer key pointing at an option that does not belong to this question's own topic, and options A/B (rib and cartilage classification) themselves general osteology the department book's thoracic-wall chapter declines to cover, no coherent single-question determination can be made from the source.",
    },
    {
      key: "regarding-the-thoracic-skeleton-the-following-statements-are-62092e50",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Not sittable as printed.",
      learningObjective: "Not sittable as printed.",
      explanations: {},
      exclude: true,
      excludeReason: "All four options concern general rib and vertebral-column osteology (first-rib tubercle/angle coincidence, scalenus medius insertion, typical-vertebra/rib articulation, annulus fibrosus thickness) that ART-104-ANA-THORACIC-CAGE explicitly places outside this chapter's scope — the department book's own thorax section \"gives no developmental account of the ribs, sternum or vertebral column as such; that content belongs to general osteology.\" With the source declining to cover any of the four claims, no answer can be established from it.",
    },
    {
      key: "the-1st-posterior-intercostal-artery-is-a-branch-from-72492885",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that the first posterior intercostal artery is a branch of the costocervical trunk.",
      explanations: {
        A: "The subcostal artery supplies below the last (eleventh) intercostal space, not the first — the two are at opposite ends of the intercostal artery sequence.",
        B: "The musculophrenic artery is a terminal branch of the internal thoracic artery, supplying the lower ANTERIOR intercostal spaces (seventh to ninth) — it plays no part in the posterior intercostal system at all.",
        C: "This is the correct answer. The first (and second) posterior intercostal artery is an indirect branch of the costocervical trunk, reaching the space via the superior intercostal artery — the descending thoracic aorta only takes over as the source from the third space onward.",
        D: "The internal thoracic artery supplies the ANTERIOR intercostal arteries of the upper spaces, not the posterior ones — the posterior system's two sources are the superior intercostal artery and the descending thoracic aorta.",
      },
    },
    {
      key: "the-9th-anterior-intercostal-artery-is-a-branch-from-3bef8271",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that the ninth anterior intercostal artery is a branch of the musculophrenic artery.",
      explanations: {
        A: "This is the correct answer. The ninth space's anterior intercostal artery comes from the musculophrenic artery, the internal thoracic artery's own terminal branch that supplies the seventh to ninth spaces once the parent vessel itself has ended opposite the sixth space.",
        B: "The subcostal artery supplies below the eleventh intercostal space — it plays no part in the anterior intercostal system, which is supplied entirely from the internal thoracic side.",
        C: "The internal thoracic artery supplies the upper six spaces' anterior intercostal arteries DIRECTLY, but it has already ended, by dividing into its two terminal branches, before reaching the ninth space.",
        D: "The superior intercostal artery supplies the first two spaces' POSTERIOR intercostal arteries, not the ninth space's anterior one — the two systems (anterior via internal thoracic, posterior via superior intercostal/descending aorta) are separate.",
      },
    },
    {
      key: "regarding-intercostal-spaces-choose-the-correct-statement-a-7ff13aa0",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Not sittable as printed.",
      learningObjective: "Not sittable as printed.",
      explanations: {},
      exclude: true,
      excludeReason: "Near-duplicate of regarding-intercostal-spaces-choose-the-correct-statement-5b563ce5, but the extraction has merged two option statements (posterior intercostal artery origin, and anterior intercostal vein drainage) into a single corrupted slot rather than keeping them as separate lettered options. The tested fact this row otherwise shares — internal intercostal fibre direction — is already authored cleanly from the sibling row's own well-formed option set; kept that one and excluded this corrupted duplicate.",
    },
    {
      key: "the-internal-mammary-artery-arises-from-bc7138a7",
      conceptKey: "internal-thoracic-artery.origin-course-and-branches",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "State that the internal mammary (internal thoracic) artery arises from the subclavian artery.",
      explanations: {
        A: "The costocervical trunk is itself a branch of the subclavian artery, giving the superior intercostal artery — a separate vessel from the internal thoracic artery, which arises directly from the subclavian's own first part.",
        B: "The vertebral artery is another first-part branch of the subclavian artery, supplying the posterior cerebral circulation — it has no relation to the thoracic wall.",
        C: "The transverse cervical artery arises from the thyrocervical trunk (or directly from the subclavian's third part in some patterns), supplying the neck and shoulder region — not the thoracic wall.",
        D: "The brachiocephalic artery is the subclavian artery's own parent vessel on the right side, well proximal to any of the subclavian's own branches — the internal thoracic artery arises from the subclavian, not from the brachiocephalic artery directly.",
        E: "This is the correct answer. The internal mammary (internal thoracic) artery arises from the first part of the subclavian artery, in the root of the neck, before descending behind the upper six costal cartilages into the thorax.",
      },
    },
    {
      key: "regarding-the-intercostal-nerve-mark-one-correct-statement-39200e19",
      conceptKey: "intercostal-arteries.sources-by-space-and-side",
      difficulty: "Hard",
      questionType: "Not sittable as printed.",
      learningObjective: "Not sittable as printed.",
      explanations: {},
      exclude: true,
      excludeReason: "Two options are each independently confirmed by the department book: A (\"it runs between the internal and innermost intercostal muscles\", matching the neurovascular bundle's own described plane) and E (\"the subcostal nerve runs in the anterior abdominal wall\", matching the source's own statement that the twelfth/subcostal nerve \"runs entirely in the abdominal wall\"). A single \"mark ONE correct statement\" answer cannot be established when the source itself supports two of the offered options.",
    },
  ],
}
