import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Histology Cardiovascular System — General Vessel Wall Plan",
  modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
  articleId: "ART-104-HIS-HEART-AND-VESSEL-WALL",

  concepts: [
    {
      key: "blood-vessel-wall.general-three-tunic-plan",
      label: "Most blood vessel walls are three tunics: intima, media and adventitia, each adapted to the vessel's function",
      definition: "Wall of most blood vessels is formed of three layers from inside outwards. Tunica intima is innermost and in direct contact with blood: an endothelium of simple squamous epithelium on its basal lamina, providing a smooth surface for flow and a thin barrier for exchange; a subendothelium of loose areolar connective tissue supporting it; and, in arteries only, an internal elastic lamina of condensed, fenestrated elastic fibres that prevents complete occlusion. Tunica media is the middle layer, variable amounts of circularly arranged smooth muscle (which regulates flow by contracting and also manufactures the media's own extracellular components), elastic fibres that allow distension, and reticular fibres and proteoglycans between the muscle cells. Tunica adventitia is the outermost loose connective tissue connecting the vessel to its surroundings: longitudinal collagen fibres that resist overdistension, a few circular elastic fibres, vasa vasorum (small vessels, chiefly in large veins, nourishing the vessel wall itself) and nervi vasorum (autonomic nerves controlling the smooth muscle). An external elastic lamina may lie between media and adventitia, fenestrated like the internal one, and the fenestrae in both allow nutrients to diffuse into the wall.",
      objective: "Name the three tunics of a blood vessel wall in order and state what each layer contributes to the vessel's function.",
      pitfall: "Damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "structural_description",
      aliases: ["Tunica intima, media and adventitia", "General plan of the blood vessel wall"],
    },
    {
      key: "tunica-adventitia.vasa-vasorum-and-composition",
      label: "The tunica adventitia's vasa vasorum — 'vessels of the vessels' — nourish the outer wall of large vessels, are more frequent in veins than arteries, and sit alongside longitudinal type I collagen that resists overdistension",
      definition: "Vasa vasorum are small nutrient blood vessels, literally 'vessels of the vessels', that penetrate from the tunica adventitia to nourish the outer part of a large vessel's own wall — the adventitia and outer media — because that outer tissue is too far from the lumen for diffusion from the blood inside to reach it; the inner wall (intima, inner media) is nourished directly by luminal diffusion instead. This need is specific to large vessels: small arteries and veins have thin enough walls that diffusion from the lumen suffices for the whole thickness, so they carry no vasa vasorum at all. Vasa vasorum are more frequent and more deeply penetrating in the walls of veins than of arteries of comparable size, since less-oxygenated venous blood makes the venous wall rely more on this dedicated external supply. Alongside vasa vasorum, the tunica adventitia's other main constituent is longitudinal type I collagen fibres, which resist overdistension of the vessel, together with a few circular elastic fibres and nervi vasorum, the autonomic nerves driving the media's smooth muscle.",
      objective: "State what vasa vasorum are, why only large vessels need them, why they favour veins over arteries, and name type I collagen as the tunica adventitia's other defining constituent.",
      pitfall: "Placing vasa vasorum in the tunica media or intima. Their defining location is the tunica adventitia (extending only partly into the outer media in large vessels); the inner wall is nourished by diffusion from the lumen directly, which is exactly why only the outer wall needs its own dedicated vessels.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "structural_description",
      aliases: ["Vasa vasorum", "Nervi vasorum", "Tunica adventitia composition"],
    },
  ],

  questions: [
    {
      key: "allow-distension-of-arteries-540e87f4",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute the tunica media's elastic fibres to arterial distension, as distinct from the smooth muscle that regulates flow.",
      explanations: {
        A: "Plainly that the elastic fibres of the tunica media allow distension of the arteries. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        B: "Smooth muscle regulates blood flow by contracting, and builds the media's own extracellular components — distension is the elastic fibre's job, not the muscle's.",
        C: "Reticular fibres lie between the smooth muscle cells as a supportive scaffold; they are credited with support, not with allowing distension.",
        D: "Collagen fibres sit in the tunica adventitia and, being longitudinally arranged, resist overdistension rather than permit it — the opposite function.",
      },
    },
    {
      key: "is-innermost-layer-in-contact-with-blood-8f8e6d95",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the tunica intima as the vessel wall's innermost layer, in direct contact with blood.",
      explanations: {
        A: "Tunica media is the middle layer, separated from the blood by the intima — it is not in direct contact with it.",
        B: "Plainly that the tunica intima is the innermost layer, in direct contact with the blood. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Tunica adventitia is the outermost coat, connecting the vessel to the surrounding tissue, furthest from the blood.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "prevent-vessel-over-distension-8f85ff7b",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute the tunica adventitia's longitudinal collagen fibres to preventing vessel overdistension.",
      explanations: {
        A: "Elastic fibres, in the tunica media, allow distension — the opposite function to the one the stem describes.",
        B: "Smooth muscle fibres regulate flow by contracting and build the media's own extracellular components; preventing overdistension is not their stated role.",
        C: "Reticular fibres support the smooth muscle cells structurally within the media; they are not credited with resisting overdistension.",
        D: "The longitudinally arranged collagen fibres of the tunica adventitia prevent vessel overdistension. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
      },
    },
    {
      key: "provide-smooth-surface-for-easily-blood-flow-e2ac2ee7",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute a smooth surface for blood flow to the tunica intima's endothelium.",
      explanations: {
        A: "Tunica media regulates flow by smooth-muscle contraction; the smooth surface for flow itself is the intima's endothelium, not the media.",
        B: "The tunica intima's endothelium provides a smooth surface for easy blood flow, and forms a thin layer letting fluids, gases and metabolites pass. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Tunica adventitia is the outer connective-tissue coat, with no contact with the flowing blood at all.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "regulate-blood-flow-produce-extracell-component-of-t-media-f26f7959",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute both flow regulation and the tunica media's own extracellular components to its smooth muscle fibres.",
      explanations: {
        A: "Elastic fibres allow distension of the media, but they are not credited with regulating flow or manufacturing the media's other extracellular components.",
        B: "The tunica media's smooth muscle fibres regulate blood flow by their contraction, and also produce all the extracellular components of the tunica media. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Reticular fibres lie between the smooth muscle cells as a structural scaffold — they are a product, not the producing cell, and play no role in flow regulation.",
        D: "Collagen fibres sit chiefly in the adventitia, resisting overdistension — they neither regulate flow nor manufacture the media's own components.",
      },
    },
    {
      key: "t-media-is-formed-of-all-the-following-except-0ad4222c",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that nervi vasorum belong to the tunica adventitia, not the tunica media's own composition.",
      explanations: {
        A: "True of the tunica media, so not the exception — circularly arranged smooth muscle fibres are its main component.",
        B: "True, so not the exception. Elastic fibres in the media allow distension of the vessel.",
        C: "The exception, and the answer. Nervi vasorum are the autonomic nerves of the tunica adventitia, controlling smooth-muscle contraction from outside the media — they belong to the adventitia, not as a component of the media itself. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        D: "True, so not the exception. Reticular fibres and proteoglycans lie between the smooth muscle cells of the media.",
      },
    },
    {
      key: "the-function-of-the-internal-elastic-lamina-is-to-f18912da",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina's function is to prevent complete occlusion of the vessel lumen.",
      explanations: {
        A: "Regulating blood flow by contraction is the tunica media's smooth muscle, not the internal elastic lamina, which is a passive elastic sheet.",
        B: "Nourishing the vessel wall is the role of vasa vasorum in the adventitia, not the internal elastic lamina.",
        C: "The internal elastic lamina's condensed, fenestrated elastic tissue keeps the lumen from fully collapsing, preventing complete occlusion of the vessel. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a related but separate mechanism.",
        D: "The internal elastic lamina differentiates tunica intima from tunica media, not media from adventitia — that boundary, where present, is the external elastic lamina's role.",
      },
    },
    {
      key: "thrombus-formation-and-obstruction-of-blood-flow-occurs-when-4934a455",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that endothelial damage, exposing the subendothelial connective tissue, is what triggers thrombus formation and vessel obstruction.",
      explanations: {
        A: "Disrupted elastic fibres reduce a vessel's ability to distend and recoil, but this is not the trigger for platelet aggregation and thrombus formation.",
        B: "Damage to the endothelium exposes the subendothelial connective tissue beneath it, which induces platelet aggregation, then thrombus formation, then obstruction of flow — the vessel wall's normal protective plan read as a mechanism of disease.",
        C: "A rise in collagen within the media of arterioles is a chronic structural change (vascular remodelling), not the acute trigger for thrombus formation.",
        D: "A fall in elastic fibres within the media of arterioles reduces compliance over time; it is not what triggers acute thrombus formation.",
      },
    },
    {
      key: "endothelium-of-tunica-intima-is-2046124d",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the endothelium of the tunica intima as simple squamous epithelium.",
      explanations: {
        A: "Simple cuboidal epithelium lines glandular ducts and tubules, not the vessel lumen.",
        B: "The endothelium lining every blood vessel's tunica intima is simple squamous epithelium — a single layer of flattened cells giving a smooth, low-friction surface for flow and a thin barrier for exchange.",
        C: "Stratified cuboidal epithelium lines structures such as sweat gland ducts, not the vascular lumen.",
        D: "Stratified squamous epithelium lines surfaces built for abrasion resistance, such as the epidermis or oesophagus, not the thin exchange surface a vessel lumen needs.",
      },
    },
    {
      key: "fenestrated-elastic-membrane-in-t-media-or-t-adventitia-6e131dc9",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the external elastic lamina as the fenestrated elastic membrane that may sit between the tunica media and tunica adventitia.",
      explanations: {
        A: "Nervi vasorum are the autonomic nerves of the tunica adventitia driving smooth-muscle tone, not an elastic membrane.",
        B: "An external elastic lamina may sit between the tunica media and tunica adventitia, fenestrated like the internal elastic lamina, letting nutrients reach the wall by diffusion through its gaps.",
        C: "Vasa vasorum are small nourishing blood vessels of the adventitia, not an elastic membrane.",
        D: "The subendothelium is loose connective tissue supporting the endothelium in the tunica intima, not a fenestrated elastic membrane at the media-adventitia boundary.",
      },
    },
    {
      key: "internal-elastic-lamina-is-developed-in-the-tunica-intima-of-11ac0429",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina, found in the tunica intima, is a feature of arteries rather than veins, capillaries or lymphatics.",
      explanations: {
        A: "The internal elastic lamina is a condensed, fenestrated sheet of elastic tissue that develops in the tunica intima of arteries only, keeping the lumen from fully collapsing. A common trap: damage to the endothelium, not the lamina itself, is what exposes the subendothelium and triggers thrombosis.",
        B: "Veins characteristically lack a well-developed internal elastic lamina, unlike arteries.",
        C: "Capillaries are a single endothelial layer with no distinct tunica intima, media or adventitia, and so no internal elastic lamina.",
        D: "Lymphatic vessels, like capillaries, are simple-walled and carry no distinct internal elastic lamina.",
      },
    },
    {
      key: "only-in-arteries-forming-fenestrated-like-layer-1a5838b5",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the internal elastic lamina as the fenestrated layer found only in arteries.",
      explanations: {
        A: "Endothelium lines every vessel type, arteries and veins alike, so it is not the layer found only in arteries.",
        B: "Subendothelium supports the endothelium in the tunica intima of vessels generally, not a layer confined to arteries.",
        C: "Vasa vasorum nourish the walls of large vessels, both arteries and veins, so they are not confined to arteries.",
        D: "The internal elastic lamina — a condensed, fenestrated elastic sheet — develops in the tunica intima of arteries only, not in veins, capillaries or lymphatics. A common trap: damage to the endothelium, not the lamina, is what exposes the subendothelium and triggers thrombosis.",
      },
    },
    {
      key: "prevent-complete-occlusion-of-arteries-during-contraction-d1029fb3",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina prevents complete occlusion of an artery's lumen when its tunica media contracts.",
      explanations: {
        A: "Endothelium provides a smooth flow surface and exchange barrier; it does not keep the lumen from collapsing during medial contraction.",
        B: "Subendothelium is loose connective tissue supporting the endothelium; it plays no role in resisting occlusion during contraction.",
        C: "Vasa vasorum nourish the outer vessel wall from the adventitia; they have no mechanical role in preventing luminal occlusion.",
        D: "The internal elastic lamina's condensed, fenestrated elastic tissue keeps the lumen from fully collapsing even when the tunica media's smooth muscle contracts, preventing complete occlusion. A common trap: damage to the endothelium, not the lamina, is what exposes the subendothelium and triggers thrombosis.",
      },
    },
    {
      key: "the-endothelial-cells-of-the-blood-vessels-are-present-in-bc33152e",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Locate endothelial cells within the tunica intima, the innermost layer of a blood vessel wall.",
      explanations: {
        A: "Endothelial cells sit in the tunica intima, the innermost layer in direct contact with blood, resting on a basal lamina.",
        B: "There is no distinct layer between tunica intima and tunica media that houses endothelium; the internal elastic lamina occupies that boundary in arteries, not endothelial cells.",
        C: "Tunica adventitia is the outermost connective-tissue coat, with no contact with the blood and no endothelium.",
        D: "Tunica media is smooth muscle, elastic and reticular fibres — the middle, contractile layer — not the endothelial layer.",
      },
    },
    {
      key: "thick-rich-in-elastic-collagen-fiber-81d11216",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the subendothelium, in a large vessel, as a layer that can be relatively thick and rich in elastic and collagen fibres.",
      explanations: {
        A: "Endothelium is a single layer of flattened cells, not a thick, fibre-rich layer.",
        B: "In large vessels the subendothelium, though loose connective tissue, can be relatively substantial and carries both elastic and collagen fibres supporting the endothelium above it.",
        C: "The internal elastic lamina is a condensed elastic sheet, not a layer characteristically described as collagen-rich.",
        D: "The external elastic lamina, like the internal, is elastic tissue proper, not a mixed elastic-and-collagen-rich layer.",
      },
    },
    {
      key: "tunica-media-of-blood-vessels-continuous-the-following-1b8c608a",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that elastic fibres, alongside smooth muscle, are a component of the tunica media.",
      explanations: {
        A: "Elastic fibres run through the tunica media between the smooth-muscle cells, allowing the vessel to distend under pressure.",
        B: "Endothelium belongs to the tunica intima, not the media.",
        C: "Vasa vasorum belong to the tunica adventitia (extending only partly into the outer media in large vessels), not the media generally.",
        D: "The internal elastic lamina marks the intima-media boundary; it is not itself a component distributed through the media.",
      },
    },
    {
      key: "internal-elastic-lamina-is-well-developed-in-the-tunica-inti-5c46764e",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option C's text merges two distinct choices ('Capillaries' and a bled-over 'c. Lymphatic') into a single surviving key, and no fourth option (Lymphatic, on its own letter) survives extraction — leaving only 3 distinguishable options (A, B, merged-C), below the platform's 4-to-5-option import contract. The same fact, with all 4 options intact, is already established by this leaf's own internal-elastic-lamina-is-developed-in-the-tunica-intima-of-11ac0429 question.",
    },
    {
      key: "tunica-media-of-blood-vessels-constitutes-the-following-f2ad81c4",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The bank's own extraction never recovered an answer (answerConfidence: none), and option A's text is itself corrupted, appending a bled-over 'B- Endothelium' fragment wrapped in RTL Arabic direction marks, with no clean, separate B option surviving — leaving an unkeyed item with a merged option, below the 4-to-5-option import contract. Per the ANSWER-KEY GAPS ruling, a question with neither a printed nor a confidently recoverable key is left unkeyed and unauthored rather than guessed.",
    },
    {
      key: "regarding-the-blood-vessels-0-a-smooth-muscle-contraction-in-4cd2175e",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The stem itself absorbed what should have been option A's text ('Smooth muscle contraction in vein wall restricts venous return to heart'), leaving only options B, C and D as selectable choices — 3 options, below the platform's 4-to-5-option import contract, with no seed-level field able to split the stem's bled-over clause back into a proper option A.",
    },
    {
      key: "the-wall-of-the-arterioles-lacks-8ee6a84b",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The extraction merges two option pairs into two surviving keys — option A carries both 'External elastic lamina' and a bled-over 'B- Internal elastic lamina', and option C carries both 'Smooth muscle fibers' and a bled-over 'D- Elastic fibers' — leaving only 2 distinguishable choices for what should be a 4-option item, well below the platform's 4-to-5-option import contract.",
    },
    {
      key: "regarding-vasa-vasorum-1-48262f8b",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Give the literal meaning of 'vasa vasorum' as vessels of the vessel, nourishing the outer wall of large vessels.",
      explanations: {
        A: "Vasa vasorum sit predominantly in the tunica adventitia, extending only partly into the outer media — not primarily within the media itself.",
        B: "'Vasa vasorum' translates literally as 'vessels of the vessels' — small nutrient vessels penetrating a large vessel's own wall, since the outer wall is too far from the lumen for diffusion alone to nourish it.",
        C: "Vasa vasorum are a feature of large vessels generally, both arteries and veins, not specifically small veins, whose thin walls are nourished by diffusion alone.",
        D: "Vasa vasorum nourish the outer part of a large vessel's wall (adventitia and outer media); the inner part is nourished directly by diffusion from luminal blood.",
      },
    },
    {
      key: "small-blood-vessel-in-t-adventitia-that-supply-nutrients-to-890a892f",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify vasa vasorum as the small vessels in the tunica adventitia that nourish the vascular wall.",
      explanations: {
        A: "Nervi vasorum are the autonomic nerves of the adventitia driving smooth-muscle tone, not blood vessels supplying nutrients.",
        B: "The external elastic lamina is an elastic membrane at the media-adventitia boundary, not a nutrient-supplying blood vessel.",
        C: "Vasa vasorum are the small blood vessels of the tunica adventitia that penetrate the wall to nourish it, needed because the outer wall of a large vessel is too far from luminal blood for diffusion alone.",
        D: "Subendothelium is loose connective tissue in the tunica intima supporting the endothelium, not a nutrient vessel of the adventitia.",
      },
    },
    {
      key: "the-tunica-adventitia-of-a-blood-vessel-contains-collagen-fi-05c26980",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option C's text merges two distinct choices ('Collagen fiber type III' and a bled-over 'D- Collagen fiber type IV') into a single surviving key, leaving only 3 distinguishable options (A, B, merged-C) — below the platform's 4-to-5-option import contract.",
    },
    {
      key: "the-vasa-vasorum-are-d41dcc76",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Locate vasa vasorum in the tunica adventitia of large arteries, not the media, intima, or small vessels.",
      explanations: {
        A: "Small arteries have thin enough walls to be nourished entirely by diffusion from the lumen and carry no vasa vasorum.",
        B: "Vasa vasorum are found in the tunica adventitia of large vessels, whose thick walls are too far from luminal blood for diffusion alone to nourish the outer layers.",
        C: "Vasa vasorum are not confined to the media of any one named vessel such as the basilar artery; their defining location is the tunica adventitia of large vessels generally.",
        D: "The tunica intima, closest to the lumen, is nourished directly by diffusion from luminal blood and needs no vasa vasorum.",
      },
    },
    {
      key: "tunica-adventitia-of-arteries-constitutes-the-following-e4d71a3b",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name vasa vasorum as a defining constituent of the tunica adventitia of arteries.",
      explanations: {
        A: "Endothelium is the defining component of the tunica intima, not the adventitia.",
        B: "Vasa vasorum are a defining constituent of the tunica adventitia, penetrating from this outer layer to nourish the outer wall.",
        C: "Smooth muscle fibres are predominantly a tunica media feature; only occasional longitudinal bundles extend into the adventitia of some large vessels, a secondary feature rather than its defining constituent.",
        D: "The internal elastic lamina marks the intima-media boundary, not a component of the adventitia.",
      },
    },
    {
      key: "tunica-adventitia-of-large-arteries-constitutes-the-followin-7bbcddac",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name vasa vasorum as a defining constituent of the tunica adventitia of large arteries.",
      explanations: {
        A: "Endothelium is the defining component of the tunica intima, not the adventitia.",
        B: "Vasa vasorum are a defining constituent of the tunica adventitia of large arteries, penetrating from this outer layer to nourish the outer wall.",
        C: "Smooth muscle fibres are predominantly a tunica media feature; only occasional longitudinal bundles extend into the adventitia of some large vessels, a secondary feature rather than its defining constituent.",
        D: "The internal elastic lamina marks the intima-media boundary, not a component of the adventitia.",
      },
    },
    {
      key: "vasa-vasorum-c6082c8b",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Moderate",
      questionType: "Recall of a true statement",
      learningObjective: "Confirm all three facts about vasa vasorum together: more frequent in veins, nourishing the deeper media, and present in the adventitia.",
      explanations: {
        A: "True, so not the sole answer alone. Vasa vasorum are more frequent and more deeply penetrating in the walls of veins than arteries of comparable size, since less-oxygenated venous blood makes the venous wall rely more on this dedicated supply.",
        B: "True, so not the sole answer alone. Vasa vasorum extend inward from the adventitia to nourish the deeper (outer) tissue of the tunica media that diffusion from the lumen cannot reach.",
        C: "True, so not the sole answer alone. Vasa vasorum are found predominantly in the tunica adventitia.",
        D: "Correct: all three statements above are individually true facts about vasa vasorum, so 'all of the above' is the answer.",
      },
    },
    {
      key: "vasa-vasorum-is-present-in-dff3929b",
      conceptKey: "tunica-adventitia.vasa-vasorum-and-composition",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Locate vasa vasorum in the tunica adventitia, not the intima or media.",
      explanations: {
        A: "The tunica intima is closest to the lumen and is nourished directly by diffusion from luminal blood, needing no vasa vasorum.",
        B: "Vasa vasorum sit predominantly in the tunica adventitia, extending only partly into the outer tunica media — not the media as their primary site.",
        C: "Vasa vasorum are present in the tunica adventitia, the outermost layer, from which they penetrate inward to nourish the outer wall of large vessels.",
        D: "Vasa vasorum are a genuine feature of large-vessel walls, present in the tunica adventitia — 'none of the above' is therefore incorrect.",
      },
    },
  ],
}
