import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Histology Cardiovascular System — Artery Classification",
  modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
  articleId: "ART-104-HIS-ARTERIES-AND-VEINS",

  concepts: [
    {
      key: "artery-classification.elastic-muscular-and-arteriolar-types",
      label: "Arteries are classed as large elastic, medium muscular or small arterioles, distinguished chiefly by their tunica media",
      definition: "Arteries fall into three histological classes. Large elastic (conducting) arteries — the aorta and its large branches — carry blood from the heart; they have very wide lumina and thick walls, an intima with a thin, inconspicuous internal elastic lamina, and a thick media of 40 to 70 circularly arranged fenestrated elastic membranes (increasing with age) with some smooth muscle, collagen and proteoglycan. Medium-sized muscular (distributing) arteries, the most common type, deliver blood to organs; their intima carries a prominent internal elastic lamina that distinguishes them from elastic arteries, and their thick media is almost entirely circular smooth muscle with elastic fibres between the cells, often with a recognisable external elastic lamina. Small arteries (arterioles), the smallest branches of muscular arteries, regulate flow to the capillaries; their wall thins gradually with diameter — a thin subendothelium and a disappearing internal elastic lamina, only one or two smooth-muscle layers in the media, and a very thin, ill-defined adventitia.",
      objective: "Name the three histological classes of artery, give one example of each, and say what distinguishes their tunica intima and media.",
      pitfall: "Using the presence of an internal elastic lamina alone to separate the classes. All three have some form of it; what separates elastic from muscular arteries is that the muscular artery's IEL is prominent and distinct from the media, where the elastic artery's is not — its media is already made of the same elastic membranes.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "classification",
      aliases: ["Elastic artery", "Muscular artery", "Arteriole classification", "Types of arteries"],
    },
  ],

  questions: [
    {
      key: "all-characters-of-basilar-arteries-except-a2a3bf98",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Recognise a muscular (medium-sized) artery's tunica intima and adventitia by its prominent internal elastic lamina and its only recognisable, not sharply clear, external elastic lamina.",
      explanations: {
        A: "True of a muscular artery, so not the exception. The internal elastic lamina is prominent in medium-sized muscular arteries — it is what distinguishes them from elastic arteries, whose IEL is thin and inconspicuous.",
        B: "True of a muscular artery's media, so not the exception — a thin tunica media is incorrect; muscular arteries have a thick media of almost entirely circular smooth muscle.",
        C: "The exception, and the answer. A muscular artery's external elastic lamina is merely 'recognisable' in many muscular arteries, not a sharply defined, 'clear' layer — this option's stronger description overstates the actual anatomy. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "True of a muscular artery's adventitia, so not the exception — it is a thin, loose connective-tissue coat, in contrast to the thick media that dominates the wall.",
      },
    },
    {
      key: "all-characters-of-medium-arteries-except-724680ef",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that medium (muscular) arteries carry more smooth muscle and less elastic tissue in their media than elastic arteries, not the reverse.",
      explanations: {
        A: "True, so not the exception. Muscular arteries supply most muscular and organ arteries, which is where this type is found.",
        B: "The exception, and the answer. Medium arteries have more smooth muscle fibres and less elastic fibres in the tunica media than elastic arteries — this option reverses that relationship. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "True, so not the exception. A prominent internal elastic lamina and a recognisable external elastic lamina are exactly what identifies a muscular artery.",
        D: "True, so not the exception. The tunica media, almost entirely circular smooth muscle, is the thickest layer of a medium artery's wall.",
      },
    },
    {
      key: "all-characters-of-medium-sized-artery-except-a1d1c716",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a medium artery does not collapse and holds no blood after death, unlike a medium vein.",
      explanations: {
        A: "True of a medium artery, so not the exception — a thick wall around a narrow, rounded lumen is exactly how a medium artery compares against a vein's wide, thin-walled lumen.",
        B: "The exception, and the answer. Collapsing and holding blood after death are characteristics of a vein; the medium artery's are the opposite — it does not collapse and has no blood in it after death. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "True, so not the exception. A clear internal elastic lamina and the absence of valves are both artery, not vein, features.",
        D: "True, so not the exception. The artery's tunica intima is thick and rich in elastic fibres, in contrast with the vein's thin, elastic-poor intima.",
      },
    },
    {
      key: "is-the-commonest-type-of-arteries-00813a7c",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name medium-sized (muscular) arteries as the commonest type of artery.",
      explanations: {
        A: "Large elastic arteries are limited to the aorta and its large branches — these are not the commonest type.",
        B: "Medium-sized muscular arteries are the most common type of artery, delivering blood to organs. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Small arteries (arterioles) are the smallest branches of muscular arteries, regulating flow into capillaries — not the commonest type.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "the-thickest-layer-in-large-elastic-arteries-is-49c219c7",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the tunica media, with its 40-70 fenestrated elastic membranes, as the thickest layer of a large elastic artery's wall.",
      explanations: {
        A: "Tunica intima is described as the thinnest layer of a large elastic artery such as the aorta, not the thickest.",
        B: "The tunica media of a large elastic artery is the thickest layer, formed of 40 to 70 circularly arranged fenestrated elastic membranes. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Tunica adventitia is a thin, loose connective-tissue coat in a large elastic artery — not the thickest layer.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "all-characters-of-t-media-except-6df57b9b",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the aorta's tunica media, not its intima, is where the 40-70 fenestrated elastic membranes lie.",
      explanations: {
        A: "True of the aorta's tunica media, so not the exception — numerous fenestrated elastic membranes are its main component.",
        B: "True, so not the exception. These membranes number 40 to 70 circularly arranged layers in adults, and increase with age.",
        C: "True, so not the exception. The fenestrae in these elastic layers are important to facilitate substance diffusion.",
        D: "The exception, and the answer. This describes the tunica intima, not the tunica media — the intima is loose connective tissue and, in the aorta specifically, its internal elastic lamina is not prominent, the opposite of the media's own thick, elastic-membrane-dominated structure. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
      },
    },
    {
      key: "medium-sized-artery-is-characterized-by-60b39a97",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Identify medium-sized muscular arteries as the most numerous, widely distributed artery type, found all over the body supplying individual organs and regions.",
      explanations: {
        A: "It is the tunica media, not the adventitia, that is the thick, defining layer of a medium artery's wall — its adventitia is comparatively thin.",
        B: "The 40-70 elastic membrane feature belongs to large elastic arteries such as the aorta, not medium muscular arteries, whose media is dominated by smooth muscle instead.",
        C: "A continuous, non-fenestrated endothelium is shared by essentially every artery, so it does not specifically identify the medium type.",
        D: "Medium-sized muscular arteries are the most common, widely distributed artery type, forming the many named arteries supplying individual organs and regions — in contrast to the few large elastic arteries and the much smaller arterioles. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
      },
    },
    {
      key: "in-medium-sized-arteries-internal-elastic-lamina-is-f147fcea",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina is very clear (prominent) in medium-sized muscular arteries, unlike its indistinct appearance in elastic arteries.",
      explanations: {
        A: "The internal elastic lamina in a muscular artery is not thin — it is a thick, well-defined sheet, which is exactly what makes it prominent against the media.",
        B: "In medium-sized muscular arteries the internal elastic lamina is very clear — a thick, wavy, sharply defined boundary sheet separating intima from media. A common trap: using the presence of an internal elastic lamina alone to separate the classes, rather than how prominent and distinct it is from the media.",
        C: "An unclear internal elastic lamina describes the elastic artery, whose lamina cannot be told apart from the media's own many elastic membranes — the opposite of the muscular artery this question asks about.",
        D: "The internal elastic lamina does take up elastic stains readily in a muscular artery; staining failure is not why it might ever appear unclear.",
      },
    },
    {
      key: "tunica-media-of-medium-sized-arteries-is-mainly-formed-of-749f7ae1",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that smooth muscle fibres, not elastic fibres, dominate the tunica media of a medium-sized (muscular) artery.",
      explanations: {
        A: "Elastic fibres dominate the tunica media of large elastic arteries, not medium muscular arteries — the naming itself distinguishes the two types by which tissue dominates the media.",
        B: "The tunica media of a medium-sized (muscular) artery is mainly formed of circularly arranged smooth muscle fibres, with elastic fibres present only between the muscle cells. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Collagen fibres are a minor component of the media, chiefly associated with the tunica adventitia's own longitudinal bundles, not the dominant tissue of a muscular artery's media.",
        D: "Ground substance is the amorphous matrix between cells and fibres, not the tissue that defines or dominates the muscular artery's media.",
      },
    },
    {
      key: "muscular-arteries-are-characterized-by-all-the-following-exc-fe4d102c",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a muscular artery's tunica media, not its adventitia, is the thicker, dominant layer of the wall.",
      explanations: {
        A: "True of a muscular artery, so not the exception — a continuous endothelial lining is the norm for arteries generally.",
        B: "True, so not the exception. The endothelium rests on a thin, continuous basement membrane, as in arteries generally.",
        C: "The exception, and the answer. It is the tunica media, not the adventitia, that is the thicker, dominant layer of a muscular artery's wall — a thin adventitia relative to a thick, muscular media is exactly what marks this type out, the reverse pattern from a vein. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "True, so not the exception. A prominent internal elastic lamina and a recognisable external elastic lamina both belong to the muscular artery.",
      },
    },
    {
      key: "muscular-arteries-are-related-to-e5dd3ce8",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Equate the term 'muscular artery' with the medium-sized artery class, as distinct from large elastic arteries and arterioles.",
      explanations: {
        A: "Large arteries are the elastic (conducting) type — the aorta and its major branches — defined by concentric elastic laminae, not by a muscle-dominated media.",
        B: "'Small sized arteries' describes arterioles, the smallest branches, not the medium muscular type this question asks about.",
        C: "'Muscular artery' is the alternative name for the medium-sized artery class, whose media is dominated by circularly arranged smooth muscle. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "Arterioles are the smallest artery branches, regulating flow into capillaries — a distinct, smaller class from the medium muscular artery.",
      },
    },
    {
      key: "regarding-the-wall-of-blood-vessels-internal-elastic-lamina-41190697",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify medium-sized (muscular) arteries as the vessel type where the internal elastic lamina is most prominently developed.",
      explanations: {
        A: "Metarterioles are too small and structurally simple — a discontinuous smooth-muscle cuff over an endothelial tube — to carry a distinct internal elastic lamina.",
        B: "Blood capillaries are a single endothelial layer with no distinct tunica layers at all, so they carry no elastic lamina of any kind.",
        C: "The internal elastic lamina is most prominently and consistently developed in medium-sized (muscular) arteries, forming a clear, wavy boundary sheet between intima and media that helps identify this vessel type under the microscope. A common trap: using the presence of an internal elastic lamina alone to separate the classes, rather than how prominent it is.",
        D: "The inferior vena cava, like veins generally, lacks a well-developed internal elastic lamina, consistent with its low-pressure, capacitance role.",
      },
    },
    {
      key: "which-one-of-the-following-statements-about-the-medium-sized-9923d5d5",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Confirm that smooth muscle fibres in the tunica media, not an absent internal elastic lamina or a thick adventitia, are the true feature of a medium-sized artery.",
      explanations: {
        A: "Vasa vasorum, where present in a vessel wall, sit in the tunica adventitia, not the tunica intima.",
        B: "True, and the answer. A medium-sized (muscular) artery's tunica media is dominated by smooth muscle fibres, with elastic fibres only interspersed between them, allowing active regulation of vascular tone. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "A medium-sized artery has a well-developed, clearly visible internal elastic lamina — one of its most distinguishing features, not an absent one.",
        D: "It is the tunica media, not the adventitia, that is the thicker, dominant layer in an artery; a thicker adventitia relative to media is instead a feature of a vein.",
      },
    },
  ],
}
