import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Histology Cardiovascular System — Artery Classification",
  modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
  articleId: "ART-104-HIS-ARTERIES-AND-VEINS",

  concepts: [
    {
      key: "artery-classification.elastic-muscular-and-arteriolar-types",
      label: "Arteries are classed as large elastic, medium muscular or small arterioles, distinguished chiefly by their tunica media",
      definition: "Arteries fall into three histological classes. Large elastic (conducting) arteries — the aorta and its large branches — carry blood from the heart; they have very wide lumina and thick walls, an intima with a thin, inconspicuous internal elastic lamina, and a thick media of 40 to 70 circularly arranged fenestrated elastic membranes (increasing with age) with some smooth muscle, collagen and proteoglycan. Medium-sized muscular (distributing) arteries, the most common type, deliver blood to organs; their intima carries a prominent internal elastic lamina that distinguishes them from elastic arteries, and their thick media is almost entirely circular smooth muscle with elastic fibres between the cells, often with a recognisable external elastic lamina. Small arteries (arterioles), the smallest branches of muscular arteries, regulate flow to the capillaries; their wall thins gradually with diameter — a thin subendothelium and a disappearing internal elastic lamina, only one or two smooth-muscle layers in the media, and a very thin, ill-defined adventitia.",
      objective: "Name the three histological classes of artery, give one example of each, and say what distinguishes their tunica intima and media.",
      pitfall: "Using the presence of an internal elastic lamina alone to separate the classes. All three have some form of it; what separates elastic from muscular arteries is that the muscular artery's IEL is prominent and distinct from the media, where the elastic artery's is not — its media is already made of the same elastic membranes.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "classification",
      aliases: ["Elastic artery", "Muscular artery", "Arteriole classification", "Types of arteries"],
    },
    {
      key: "elastic-artery.aortic-tunica-media-structure",
      label: "The aorta's tunica media is packed with 40-70 fenestrated elastic membranes with smooth muscle between them, so its internal elastic lamina cannot be told apart from these same membranes",
      definition: "The aorta, the archetypal large elastic artery, has a tunica media formed of 40 to 70 concentric, fenestrated elastic membranes (laminae), increasing in number with age, with smooth muscle fibres, collagen and proteoglycan filling the spaces between them. This dense elastic media lets the wall stretch during systole and recoil during diastole, smoothing the heart's pulsatile output into steadier downstream flow. Because the media itself is already built from ring upon ring of elastic tissue, the internal elastic lamina — the specific boundary sheet that so clearly separates intima from media in a muscular artery — cannot be told apart as a separate structure from the many other elastic laminae surrounding it: it is present, not absent, thin or unstainable, but indistinguishable by contrast.",
      objective: "State that the aorta's tunica media is dominated by 40-70 fenestrated elastic membranes with smooth muscle between them, and explain why its internal elastic lamina is not a clearly visible boundary the way it is in a muscular artery.",
      pitfall: "Assuming an unclear internal elastic lamina means it is absent, thin, or fails to stain. In the aorta it is present and does take elastic stains — it simply cannot be distinguished from the many other elastic laminae of the same media that surround it.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "structural_description",
      aliases: ["Aorta histology", "Elastic artery tunica media", "Aortic internal elastic lamina"],
    },
    {
      key: "basilar-artery.muscular-type-despite-cranial-location",
      label: "The basilar artery is histologically a muscular artery, identified by its unusually prominent, thick internal elastic lamina rather than by concentric elastic membranes",
      definition: "The basilar artery, formed by the union of the two vertebral arteries in the posterior cerebral circulation, is classified histologically as a muscular (medium-sized) artery rather than an elastic one, despite supplying a major cranial territory. Its signature identifying feature on a microscope slide is an unusually prominent, thick internal elastic lamina — a wavy, corrugated boundary sheet standing out clearly against a media built mainly of circular smooth muscle, not against 40-70 concentric elastic membranes as an elastic artery's media would be.",
      objective: "Classify the basilar artery as a muscular, not elastic, artery, identified by its prominent internal elastic lamina.",
      pitfall: "Assuming a named artery's size or clinical importance dictates its histological class. The basilar artery is classed by what its tunica media is built of — smooth muscle with a prominent internal elastic lamina — not by how large a territory it supplies.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "structural_description",
      aliases: ["Basilar artery histology"],
      gaps: ["The covering article teaches the general elastic-vs-muscular classification rule (internal elastic lamina prominence marks a muscular artery) but does not name the basilar artery specifically as a worked example; this question applies the general rule to a named vessel the article does not itself mention."],
    },
    {
      key: "arterioles.resistance-function-and-regulation",
      label: "Arterioles are the principal resistance vessels of the systemic circulation, and Poiseuille's law — resistance and flow varying with the fourth power of radius — explains why their smooth-muscle tone has such a powerful effect on local blood flow and total peripheral resistance",
      definition: "Arterioles, the smallest artery branches, are the body's chief resistance vessels: their combination of a small lumen and a well-developed smooth-muscle media lets them change vascular resistance far more than any other vessel type, so sympathetic constriction of arterioles produces the largest rise in total peripheral resistance of any vessel class, and arterioles carry out the last point of active flow control before the capillary bed. This control ends at the metarteriole, the arteriole's own terminal segment draining directly into the capillary bed, whose smooth muscle thickens into a precapillary sphincter that opens and closes the entrance to that bed. The physical basis is Poiseuille's law: flow is proportional to the pressure gradient and to the radius raised to the fourth power, so a vessel doubling its radius increases flow sixteen-fold from that change alone — which is why small changes in arteriolar diameter dominate local blood flow and resistance far more than comparable changes in driving pressure, and why a blood vessel that displays pressure autoregulation responds to a fall in perfusion pressure with a fall in its own vascular resistance (arteriolar dilation) to defend flow. Arterioles are also more compliant than an elastic artery wall but far less compliant than a vein, whose thin wall and large capacitance make it, not the arteriole, the most compliant vessel type; an arteriole's own constriction instead raises both arterial and capillary pressure downstream.",
      objective: "Identify arterioles as the principal resistance vessels, explain their role via Poiseuille's fourth-power radius relationship, and distinguish their function (active resistance and flow control) from a vein's (passive capacitance).",
      pitfall: "Calling arterioles the most compliant vessel type. Veins, not arterioles, are the body's capacitance vessels with the greatest compliance; an arteriole's own smooth muscle instead makes it the vessel best able to actively raise or lower resistance.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "mechanism",
      aliases: ["Arteriole resistance vessels", "Metarteriole", "Precapillary sphincter", "Poiseuille's law", "Pressure autoregulation"],
    },
  ],

  questions: [
    {
      key: "all-characters-of-basilar-arteries-except-a2a3bf98",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Recognise a muscular (medium-sized) artery's tunica intima and adventitia by its prominent internal elastic lamina and its only recognisable, not sharply clear, external elastic lamina.",
      explanations: {
        A: "True of a muscular artery, so not the exception. The internal elastic lamina is prominent in medium-sized muscular arteries — it is what distinguishes them from elastic arteries, whose IEL is thin and inconspicuous.",
        B: "True of a muscular artery's media, so not the exception — a thin tunica media is incorrect; muscular arteries have a thick media of almost entirely circular smooth muscle.",
        C: "The exception, and the answer. A muscular artery's external elastic lamina is merely 'recognisable' in many muscular arteries, not a sharply defined, 'clear' layer — this option's stronger description overstates the actual anatomy. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "True of a muscular artery's adventitia, so not the exception — it is a thin, loose connective-tissue coat, in contrast to the thick media that dominates the wall.",
      },
    },
    {
      key: "all-characters-of-medium-arteries-except-724680ef",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that medium (muscular) arteries carry more smooth muscle and less elastic tissue in their media than elastic arteries, not the reverse.",
      explanations: {
        A: "True, so not the exception. Muscular arteries supply most muscular and organ arteries, which is where this type is found.",
        B: "The exception, and the answer. Medium arteries have more smooth muscle fibres and less elastic fibres in the tunica media than elastic arteries — this option reverses that relationship. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "True, so not the exception. A prominent internal elastic lamina and a recognisable external elastic lamina are exactly what identifies a muscular artery.",
        D: "True, so not the exception. The tunica media, almost entirely circular smooth muscle, is the thickest layer of a medium artery's wall.",
      },
    },
    {
      key: "all-characters-of-medium-sized-artery-except-a1d1c716",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a medium artery does not collapse and holds no blood after death, unlike a medium vein.",
      explanations: {
        A: "True of a medium artery, so not the exception — a thick wall around a narrow, rounded lumen is exactly how a medium artery compares against a vein's wide, thin-walled lumen.",
        B: "The exception, and the answer. Collapsing and holding blood after death are characteristics of a vein; the medium artery's are the opposite — it does not collapse and has no blood in it after death. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "True, so not the exception. A clear internal elastic lamina and the absence of valves are both artery, not vein, features.",
        D: "True, so not the exception. The artery's tunica intima is thick and rich in elastic fibres, in contrast with the vein's thin, elastic-poor intima.",
      },
    },
    {
      key: "is-the-commonest-type-of-arteries-00813a7c",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name medium-sized (muscular) arteries as the commonest type of artery.",
      explanations: {
        A: "Large elastic arteries are limited to the aorta and its large branches — these are not the commonest type.",
        B: "Medium-sized muscular arteries are the most common type of artery, delivering blood to organs. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Small arteries (arterioles) are the smallest branches of muscular arteries, regulating flow into capillaries — not the commonest type.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "the-thickest-layer-in-large-elastic-arteries-is-49c219c7",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the tunica media, with its 40-70 fenestrated elastic membranes, as the thickest layer of a large elastic artery's wall.",
      explanations: {
        A: "Tunica intima is described as the thinnest layer of a large elastic artery such as the aorta, not the thickest.",
        B: "The tunica media of a large elastic artery is the thickest layer, formed of 40 to 70 circularly arranged fenestrated elastic membranes. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Tunica adventitia is a thin, loose connective-tissue coat in a large elastic artery — not the thickest layer.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "all-characters-of-t-media-except-6df57b9b",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the aorta's tunica media, not its intima, is where the 40-70 fenestrated elastic membranes lie.",
      explanations: {
        A: "True of the aorta's tunica media, so not the exception — numerous fenestrated elastic membranes are its main component.",
        B: "True, so not the exception. These membranes number 40 to 70 circularly arranged layers in adults, and increase with age.",
        C: "True, so not the exception. The fenestrae in these elastic layers are important to facilitate substance diffusion.",
        D: "The exception, and the answer. This describes the tunica intima, not the tunica media — the intima is loose connective tissue and, in the aorta specifically, its internal elastic lamina is not prominent, the opposite of the media's own thick, elastic-membrane-dominated structure. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
      },
    },
    {
      key: "medium-sized-artery-is-characterized-by-60b39a97",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Identify medium-sized muscular arteries as the most numerous, widely distributed artery type, found all over the body supplying individual organs and regions.",
      explanations: {
        A: "It is the tunica media, not the adventitia, that is the thick, defining layer of a medium artery's wall — its adventitia is comparatively thin.",
        B: "The 40-70 elastic membrane feature belongs to large elastic arteries such as the aorta, not medium muscular arteries, whose media is dominated by smooth muscle instead.",
        C: "A continuous, non-fenestrated endothelium is shared by essentially every artery, so it does not specifically identify the medium type.",
        D: "Medium-sized muscular arteries are the most common, widely distributed artery type, forming the many named arteries supplying individual organs and regions — in contrast to the few large elastic arteries and the much smaller arterioles. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
      },
    },
    {
      key: "in-medium-sized-arteries-internal-elastic-lamina-is-f147fcea",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina is very clear (prominent) in medium-sized muscular arteries, unlike its indistinct appearance in elastic arteries.",
      explanations: {
        A: "The internal elastic lamina in a muscular artery is not thin — it is a thick, well-defined sheet, which is exactly what makes it prominent against the media.",
        B: "In medium-sized muscular arteries the internal elastic lamina is very clear — a thick, wavy, sharply defined boundary sheet separating intima from media. A common trap: using the presence of an internal elastic lamina alone to separate the classes, rather than how prominent and distinct it is from the media.",
        C: "An unclear internal elastic lamina describes the elastic artery, whose lamina cannot be told apart from the media's own many elastic membranes — the opposite of the muscular artery this question asks about.",
        D: "The internal elastic lamina does take up elastic stains readily in a muscular artery; staining failure is not why it might ever appear unclear.",
      },
    },
    {
      key: "tunica-media-of-medium-sized-arteries-is-mainly-formed-of-749f7ae1",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that smooth muscle fibres, not elastic fibres, dominate the tunica media of a medium-sized (muscular) artery.",
      explanations: {
        A: "Elastic fibres dominate the tunica media of large elastic arteries, not medium muscular arteries — the naming itself distinguishes the two types by which tissue dominates the media.",
        B: "The tunica media of a medium-sized (muscular) artery is mainly formed of circularly arranged smooth muscle fibres, with elastic fibres present only between the muscle cells. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "Collagen fibres are a minor component of the media, chiefly associated with the tunica adventitia's own longitudinal bundles, not the dominant tissue of a muscular artery's media.",
        D: "Ground substance is the amorphous matrix between cells and fibres, not the tissue that defines or dominates the muscular artery's media.",
      },
    },
    {
      key: "muscular-arteries-are-characterized-by-all-the-following-exc-fe4d102c",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a muscular artery's tunica media, not its adventitia, is the thicker, dominant layer of the wall.",
      explanations: {
        A: "True of a muscular artery, so not the exception — a continuous endothelial lining is the norm for arteries generally.",
        B: "True, so not the exception. The endothelium rests on a thin, continuous basement membrane, as in arteries generally.",
        C: "The exception, and the answer. It is the tunica media, not the adventitia, that is the thicker, dominant layer of a muscular artery's wall — a thin adventitia relative to a thick, muscular media is exactly what marks this type out, the reverse pattern from a vein. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "True, so not the exception. A prominent internal elastic lamina and a recognisable external elastic lamina both belong to the muscular artery.",
      },
    },
    {
      key: "muscular-arteries-are-related-to-e5dd3ce8",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Equate the term 'muscular artery' with the medium-sized artery class, as distinct from large elastic arteries and arterioles.",
      explanations: {
        A: "Large arteries are the elastic (conducting) type — the aorta and its major branches — defined by concentric elastic laminae, not by a muscle-dominated media.",
        B: "'Small sized arteries' describes arterioles, the smallest branches, not the medium muscular type this question asks about.",
        C: "'Muscular artery' is the alternative name for the medium-sized artery class, whose media is dominated by circularly arranged smooth muscle. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        D: "Arterioles are the smallest artery branches, regulating flow into capillaries — a distinct, smaller class from the medium muscular artery.",
      },
    },
    {
      key: "regarding-the-wall-of-blood-vessels-internal-elastic-lamina-41190697",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify medium-sized (muscular) arteries as the vessel type where the internal elastic lamina is most prominently developed.",
      explanations: {
        A: "Metarterioles are too small and structurally simple — a discontinuous smooth-muscle cuff over an endothelial tube — to carry a distinct internal elastic lamina.",
        B: "Blood capillaries are a single endothelial layer with no distinct tunica layers at all, so they carry no elastic lamina of any kind.",
        C: "The internal elastic lamina is most prominently and consistently developed in medium-sized (muscular) arteries, forming a clear, wavy boundary sheet between intima and media that helps identify this vessel type under the microscope. A common trap: using the presence of an internal elastic lamina alone to separate the classes, rather than how prominent it is.",
        D: "The inferior vena cava, like veins generally, lacks a well-developed internal elastic lamina, consistent with its low-pressure, capacitance role.",
      },
    },
    {
      key: "which-one-of-the-following-statements-about-the-medium-sized-9923d5d5",
      conceptKey: "artery-classification.elastic-muscular-and-arteriolar-types",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Confirm that smooth muscle fibres in the tunica media, not an absent internal elastic lamina or a thick adventitia, are the true feature of a medium-sized artery.",
      explanations: {
        A: "Vasa vasorum, where present in a vessel wall, sit in the tunica adventitia, not the tunica intima.",
        B: "True, and the answer. A medium-sized (muscular) artery's tunica media is dominated by smooth muscle fibres, with elastic fibres only interspersed between them, allowing active regulation of vascular tone. A common trap: using the presence of an internal elastic lamina alone to separate the classes.",
        C: "A medium-sized artery has a well-developed, clearly visible internal elastic lamina — one of its most distinguishing features, not an absent one.",
        D: "It is the tunica media, not the adventitia, that is the thicker, dominant layer in an artery; a thicker adventitia relative to media is instead a feature of a vein.",
      },
    },
    {
      key: "tunica-media-of-aorta-is-characterized-by-the-following-f277cc08",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the aorta's tunica media, though dominated by elastic membranes, still contains smooth muscle fibres between them.",
      explanations: {
        A: "The aorta's tunica media contains smooth muscle fibres in the spaces between its 40-70 fenestrated elastic membranes, alongside collagen and proteoglycan — the media is not elastic tissue alone.",
        B: "The collagen of the aortic media is not specifically type II — type II collagen is characteristic of cartilage, not the elastic artery wall.",
        C: "Ground substance (proteoglycan) is present between the elastic membranes and smooth-muscle cells of the aortic media, not absent from it.",
        D: "The tunica media is by far the dominant layer of the aortic wall, far exceeding 30% of its thickness — the media, not the thin intima or adventitia, is what makes the aorta's wall so thick.",
      },
    },
    {
      key: "in-aorta-internal-elastic-lamina-is-unclear-because-cf5d90ae",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Explain that the aorta's internal elastic lamina is unclear because it cannot be told apart from the media's own many elastic membranes, not because it is absent, thin or unstainable.",
      explanations: {
        A: "The internal elastic lamina is present in the aorta's wall — it is simply indistinguishable as a separate structure from the surrounding elastic laminae, not absent altogether.",
        B: "The lamina does take up elastic stains in the aorta, the same as its neighbouring elastic membranes; a staining failure is not why it appears unclear.",
        C: "In the aorta the tunica media itself is packed with 40 to 70 concentric elastic laminae, so the single internal elastic lamina cannot be distinguished from the many other, equally prominent elastic membranes filling the media around it. A common trap: assuming an unclear internal elastic lamina must mean it is absent, thin, or fails to stain.",
        D: "Thinness is not the issue — the lamina is obscured by contrast with the surrounding elastic membranes, not by being unusually thin itself.",
      },
    },
    {
      key: "inaorta-internal-elastic-lamina-is-unclear-because-4955103f",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Explain that the aorta's internal elastic lamina is unclear because it cannot be told apart from the media's own many elastic membranes, not because it is absent, thin or unstainable.",
      explanations: {
        A: "The internal elastic lamina is present in the aorta's wall — it is simply indistinguishable as a separate structure from the surrounding elastic laminae, not absent altogether.",
        B: "Thinness is not the issue — the lamina is obscured by contrast with the surrounding elastic membranes, not by being unusually thin itself.",
        C: "In the aorta the tunica media itself is packed with 40 to 70 concentric elastic laminae, so the single internal elastic lamina cannot be distinguished from the many other, equally prominent elastic membranes filling the media around it. A common trap: assuming an unclear internal elastic lamina must mean it is absent, thin, or fails to stain.",
        D: "The lamina does take up elastic stains in the aorta, the same as its neighbouring elastic membranes; a staining failure is not why it appears unclear.",
      },
    },
    {
      key: "large-elastic-arteries-are-characterized-by-6fa6edbe",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Fix 40-70 concentric fenestrated elastic membranes in the tunica media as the defining histological feature of large elastic arteries.",
      explanations: {
        A: "Longitudinal smooth muscle in the tunica adventitia is a real but secondary feature of large elastic arteries, not the defining one.",
        B: "Valves belong to veins, particularly medium-sized limb veins — arteries of any class carry no valves.",
        C: "Large elastic arteries like the aorta are defined by a tunica media of 40 to 70 concentric, fenestrated elastic membranes, letting the wall stretch in systole and recoil in diastole to smooth pulsatile flow. A common trap: assuming an unclear internal elastic lamina must mean it is absent, thin, or fails to stain — in an elastic artery it is present but indistinguishable from these same membranes.",
        D: "A single, clearly identifiable external elastic lamina is a feature of muscular arteries; in an elastic artery the media's many elastic laminae make any one lamina hard to distinguish separately.",
      },
    },
    {
      key: "the-wall-of-aorta-shows-ea35f5ef",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Fix 40-70 elastic membranes in the tunica media as the aorta's headline histological feature.",
      explanations: {
        A: "Longitudinal smooth muscle bundles are a real but secondary feature of the aorta's tunica adventitia, not its single defining feature.",
        B: "Smooth muscle is a tunica media feature; the tunica intima consists only of endothelium and a thin subendothelium, never smooth muscle.",
        C: "Vasa vasorum do extend into the outer part of the aortic media from the adventitia, but their defining location is the adventitia, not the media itself.",
        D: "The aorta's tunica media is packed with 40 to 70 concentric, fenestrated elastic membranes — its single most defining, most frequently tested histological feature. A common trap: assuming an unclear internal elastic lamina must mean it is absent, thin, or fails to stain.",
      },
    },
    {
      key: "which-of-the-following-is-not-true-regarding-the-aorta-0be21235",
      conceptKey: "elastic-artery.aortic-tunica-media-structure",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The extraction merges two option pairs into two surviving keys — option A carries both 'Thick tunica intima' and a bled-over 'B- well prominent internal elastic lamina', and option C carries both 'Thick tunica media' and a bled-over 'D- Fenestrated elastic lamina in tunica media' — leaving only 2 distinguishable choices for what should be a 4-option item, well below the platform's 4-to-5-option import contract. No seed-level field exists to split merged option text back into separate letters.",
    },
    {
      key: "the-main-feature-of-basilar-artery-is-c2068f7e",
      conceptKey: "basilar-artery.muscular-type-despite-cranial-location",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Name a prominent internal elastic lamina as the basilar artery's specific identifying histological feature.",
      explanations: {
        A: "A prominent external elastic lamina is not the feature this exam bank associates with the basilar artery.",
        B: "The basilar artery is noted for an unusually prominent, thick internal elastic lamina — a feature used to help identify this named vessel on a microscope slide, and a sign it is classified as a muscular, not elastic, artery. A common trap: assuming a named artery's size or clinical importance, rather than its tunica media, sets its histological class.",
        C: "Prominent collagen fibres are not the basilar artery's distinguishing histological feature.",
        D: "Prominent vasa vasorum is a feature associated with large vessels generally needing their own wall nutrition, not a specific hallmark of the basilar artery.",
      },
    },
    {
      key: "the-main-feature-of-basilar-artery-is-prominent-3b70a70a",
      conceptKey: "basilar-artery.muscular-type-despite-cranial-location",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Name a prominent internal elastic lamina as the basilar artery's specific identifying histological feature.",
      explanations: {
        A: "A prominent external elastic lamina is not the feature this exam bank associates with the basilar artery.",
        B: "The basilar artery is noted for an unusually prominent, thick internal elastic lamina — a feature used to help identify this named vessel on a microscope slide, and a sign it is classified as a muscular, not elastic, artery. A common trap: assuming a named artery's size or clinical importance, rather than its tunica media, sets its histological class.",
        C: "Prominent collagen fibres are not the basilar artery's distinguishing histological feature.",
        D: "Prominent vasa vasorum is a feature associated with large vessels generally needing their own wall nutrition, not a specific hallmark of the basilar artery.",
      },
    },
    {
      key: "regarding-metarteriole-6ebae641",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the metarteriole is the arteriole's own terminal segment, controlling blood flow into the capillary bed via its precapillary sphincter.",
      explanations: {
        A: "A metarteriole connects an arteriole to a capillary bed, not directly to a venule — it drains into capillaries, which in turn drain into venules.",
        B: "The precapillary sphincter — smooth muscle thickened at the metarteriole's origin — is composed of smooth muscle, not a sphincter of elastic fibres.",
        C: "The metarteriole is the arteriole's own terminal segment, not a lateral branch of the capillary — capillaries branch from the metarteriole, not the reverse.",
        D: "The metarteriole's precapillary sphincter is the last point of active control before the capillary bed, opening and closing to control blood flow into it. A common trap: treating the metarteriole as a separate vessel class rather than the arteriole's own terminal segment.",
      },
    },
    {
      key: "all-about-arterioles-is-true-except-6a81e1f5",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that veins, not arterioles, are the most compliant vessel type, despite arterioles being the principal resistance vessels.",
      explanations: {
        A: "True of arterioles, so not the exception — their walls carry one or two layers of smooth muscle even at their smallest calibre.",
        B: "The exception, and the answer. Veins, not arterioles, are the body's most compliant vessel type — their thin walls and large capacitance let them hold a disproportionate share of blood volume with little rise in pressure. An arteriole's own smooth muscle instead makes it the vessel best suited to actively raising or lowering resistance, the opposite property from high compliance.",
        C: "True of arterioles, so not the exception — as the principal resistance vessels, they are central to local blood-flow control.",
        D: "True of arterioles, so not the exception — arteriolar constriction raises resistance upstream of the capillaries, raising both arterial and capillary pressure.",
        E: "Since B alone is the exception, 'both b and d' is incorrect — d describes a genuine arteriole property, not a false one.",
      },
    },
    {
      key: "hypertension-develops-when-the-77d3bbd0",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Identify a rise in arteriolar smooth-muscle tone, raising total peripheral resistance, as the direct mechanism of hypertension.",
      explanations: {
        A: "Increased collagen in the arteriolar media is a chronic structural consequence of long-standing hypertension (vascular remodelling), not the direct, primary trigger of the pressure rise itself.",
        B: "A decrease in elastic fibres reduces arteriolar compliance over time, a slower structural change, not the immediate mechanism that raises peripheral resistance.",
        C: "Since arterial pressure equals cardiac output multiplied by total peripheral resistance, a sustained rise in arteriolar smooth-muscle tone directly raises resistance and so raises pressure — the standard direct mechanism of hypertension. A common trap: assuming arterioles are the most compliant vessels; their smooth muscle instead makes them the vessel best suited to actively raising resistance.",
        D: "An increase in adventitial thickness is a structural remodelling change, not the direct, acute mechanism by which resistance and pressure rise.",
      },
    },
    {
      key: "hypertension-develops-when-the-a-amount-of-collagen-fibers-i-9f819538",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Identify a rise in arteriolar smooth-muscle tone, raising total peripheral resistance, as the direct mechanism of hypertension.",
      explanations: {
        A: "Increased collagen in the arteriolar media is a chronic structural consequence of long-standing hypertension (vascular remodelling), not the direct, primary trigger of the pressure rise itself.",
        B: "A decrease in elastic fibres reduces arteriolar compliance over time, a slower structural change, not the immediate mechanism that raises peripheral resistance.",
        C: "Since arterial pressure equals cardiac output multiplied by total peripheral resistance, a sustained rise in arteriolar smooth-muscle tone directly raises resistance and so raises pressure — the standard direct mechanism of hypertension. A common trap: assuming arterioles are the most compliant vessels; their smooth muscle instead makes them the vessel best suited to actively raising resistance.",
        D: "An increase in adventitial thickness is a structural remodelling change, not the direct, acute mechanism by which resistance and pressure rise.",
      },
    },
    {
      key: "in-a-blood-vessel-that-displays-pressure-autoregulation-a-de-b93e41bd",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State that a fall in perfusion pressure, in a vessel displaying pressure autoregulation, is met with a fall in vascular resistance (arteriolar dilation) to defend flow.",
      explanations: {
        A: "Constriction would compound a fall in flow, not defend it — autoregulation responds to a pressure fall with dilation, the opposite of constriction.",
        B: "Pressure autoregulation defends flow against a change in perfusion pressure by adjusting arteriolar resistance in the opposite direction — a fall in pressure is met with a fall in resistance (arteriolar dilation), keeping flow relatively constant. A common trap: assuming resistance and pressure must move the same direction, when autoregulation exists precisely to oppose that.",
        C: "Nitric oxide release from endothelium is one contributor to vasodilator tone generally, but the defining feature of pressure autoregulation as tested here is the resistance change itself, not this single mediator.",
        D: "Since B alone correctly describes the autoregulatory response, 'both b and c' overstates what the question is testing.",
      },
    },
    {
      key: "sympathetic-stimulation-of-which-vessels-cause-the-greatest-30d5bfc3",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Identify arterioles as the vessel type whose sympathetic constriction produces the greatest rise in total peripheral resistance.",
      explanations: {
        A: "Large arteries have low resistance and act mainly as conduits, not as the primary site of resistance regulation.",
        B: "Arterioles are the principal resistance vessels: their small radius combined with a well-developed smooth-muscle coat gives them the greatest capacity to change resistance under sympathetic stimulation, since resistance varies with the fourth power of radius. A common trap: assuming arterioles are the most compliant vessels; that property belongs to veins, not arterioles.",
        C: "Capillaries carry no smooth muscle in their walls and cannot actively constrict or dilate under sympathetic stimulation.",
        D: "Venules do respond to sympathetic stimulation, but chiefly by altering venous capacitance and return, not by producing the greatest rise in total peripheral resistance.",
      },
    },
    {
      key: "the-main-site-of-r-sistance-in-the-systemic-circulation-is-a-63db5055",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option A's text ('Aorta') bled into the stem itself rather than surviving as a selectable option, leaving only options B, C and D — 3 options, below the platform's 4-to-5-option import contract. The same fact (arterioles as the principal site of systemic vascular resistance) is already established cleanly by this leaf's own sympathetic-stimulation-of-which-vessels-cause-the-greatest question on the same concept.",
    },
    {
      key: "what-would-be-the-change-in-blood-flow-to-a-tissue-if-radius-98cfcd7f",
      conceptKey: "arterioles.resistance-function-and-regulation",
      difficulty: "Hard",
      questionType: "Calculation",
      learningObjective: "Apply Poiseuille's law (flow proportional to radius to the fourth power) to calculate the net change in flow when arteriolar radius doubles and perfusion pressure halves.",
      explanations: {
        A: "By Poiseuille's law, flow is proportional to pressure and to radius to the fourth power. Doubling the radius alone raises flow 2⁴ = 16-fold; halving the pressure alone would halve it; combined, flow rises 16 × ½ = 8-fold. A common trap: forgetting to combine both changes, or misapplying the fourth-power relationship to radius.",
        B: "A 16-fold rise would follow from doubling the radius with pressure held constant — it ignores that halving the pressure cuts this effect in half.",
        C: "A 4-fold rise does not correctly apply the radius-to-the-fourth-power relationship of Poiseuille's law to a doubled radius.",
        D: "Flow rises rather than falls overall: the 16-fold gain from doubling the radius outweighs the 2-fold loss from halving the pressure.",
      },
    },
  ],
}
