import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Histology Cardiovascular System — General Vessel Wall Plan",
  modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
  articleId: "ART-104-HIS-HEART-AND-VESSEL-WALL",

  concepts: [
    {
      key: "blood-vessel-wall.general-three-tunic-plan",
      label: "Most blood vessel walls are three tunics: intima, media and adventitia, each adapted to the vessel's function",
      definition: "Wall of most blood vessels is formed of three layers from inside outwards. Tunica intima is innermost and in direct contact with blood: an endothelium of simple squamous epithelium on its basal lamina, providing a smooth surface for flow and a thin barrier for exchange; a subendothelium of loose areolar connective tissue supporting it; and, in arteries only, an internal elastic lamina of condensed, fenestrated elastic fibres that prevents complete occlusion. Tunica media is the middle layer, variable amounts of circularly arranged smooth muscle (which regulates flow by contracting and also manufactures the media's own extracellular components), elastic fibres that allow distension, and reticular fibres and proteoglycans between the muscle cells. Tunica adventitia is the outermost loose connective tissue connecting the vessel to its surroundings: longitudinal collagen fibres that resist overdistension, a few circular elastic fibres, vasa vasorum (small vessels, chiefly in large veins, nourishing the vessel wall itself) and nervi vasorum (autonomic nerves controlling the smooth muscle). An external elastic lamina may lie between media and adventitia, fenestrated like the internal one, and the fenestrae in both allow nutrients to diffuse into the wall.",
      objective: "Name the three tunics of a blood vessel wall in order and state what each layer contributes to the vessel's function.",
      pitfall: "Damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
      subject: "cvs",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-CVS-T01-S01"],
      modulePath: "104 CPS > Histology > Cardiovascular System > Arteries",
      type: "structural_description",
      aliases: ["Tunica intima, media and adventitia", "General plan of the blood vessel wall"],
    },
  ],

  questions: [
    {
      key: "allow-distension-of-arteries-540e87f4",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute the tunica media's elastic fibres to arterial distension, as distinct from the smooth muscle that regulates flow.",
      explanations: {
        A: "Plainly that the elastic fibres of the tunica media allow distension of the arteries. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        B: "Smooth muscle regulates blood flow by contracting, and builds the media's own extracellular components — distension is the elastic fibre's job, not the muscle's.",
        C: "Reticular fibres lie between the smooth muscle cells as a supportive scaffold; they are credited with support, not with allowing distension.",
        D: "Collagen fibres sit in the tunica adventitia and, being longitudinally arranged, resist overdistension rather than permit it — the opposite function.",
      },
    },
    {
      key: "is-innermost-layer-in-contact-with-blood-8f8e6d95",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the tunica intima as the vessel wall's innermost layer, in direct contact with blood.",
      explanations: {
        A: "Tunica media is the middle layer, separated from the blood by the intima — it is not in direct contact with it.",
        B: "Plainly that the tunica intima is the innermost layer, in direct contact with the blood. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Tunica adventitia is the outermost coat, connecting the vessel to the surrounding tissue, furthest from the blood.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "prevent-vessel-over-distension-8f85ff7b",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute the tunica adventitia's longitudinal collagen fibres to preventing vessel overdistension.",
      explanations: {
        A: "Elastic fibres, in the tunica media, allow distension — the opposite function to the one the stem describes.",
        B: "Smooth muscle fibres regulate flow by contracting and build the media's own extracellular components; preventing overdistension is not their stated role.",
        C: "Reticular fibres support the smooth muscle cells structurally within the media; they are not credited with resisting overdistension.",
        D: "The longitudinally arranged collagen fibres of the tunica adventitia prevent vessel overdistension. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
      },
    },
    {
      key: "provide-smooth-surface-for-easily-blood-flow-e2ac2ee7",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute a smooth surface for blood flow to the tunica intima's endothelium.",
      explanations: {
        A: "Tunica media regulates flow by smooth-muscle contraction; the smooth surface for flow itself is the intima's endothelium, not the media.",
        B: "The tunica intima's endothelium provides a smooth surface for easy blood flow, and forms a thin layer letting fluids, gases and metabolites pass. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Tunica adventitia is the outer connective-tissue coat, with no contact with the flowing blood at all.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "regulate-blood-flow-produce-extracell-component-of-t-media-f26f7959",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute both flow regulation and the tunica media's own extracellular components to its smooth muscle fibres.",
      explanations: {
        A: "Elastic fibres allow distension of the media, but they are not credited with regulating flow or manufacturing the media's other extracellular components.",
        B: "The tunica media's smooth muscle fibres regulate blood flow by their contraction, and also produce all the extracellular components of the tunica media. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        C: "Reticular fibres lie between the smooth muscle cells as a structural scaffold — they are a product, not the producing cell, and play no role in flow regulation.",
        D: "Collagen fibres sit chiefly in the adventitia, resisting overdistension — they neither regulate flow nor manufacture the media's own components.",
      },
    },
    {
      key: "t-media-is-formed-of-all-the-following-except-0ad4222c",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that nervi vasorum belong to the tunica adventitia, not the tunica media's own composition.",
      explanations: {
        A: "True of the tunica media, so not the exception — circularly arranged smooth muscle fibres are its main component.",
        B: "True, so not the exception. Elastic fibres in the media allow distension of the vessel.",
        C: "The exception, and the answer. Nervi vasorum are the autonomic nerves of the tunica adventitia, controlling smooth-muscle contraction from outside the media — they belong to the adventitia, not as a component of the media itself. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a mechanism stated explicitly, one examiners like to test as a short reasoning chain, not a fact to recite in isolation.",
        D: "True, so not the exception. Reticular fibres and proteoglycans lie between the smooth muscle cells of the media.",
      },
    },
    {
      key: "the-function-of-the-internal-elastic-lamina-is-to-f18912da",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina's function is to prevent complete occlusion of the vessel lumen.",
      explanations: {
        A: "Regulating blood flow by contraction is the tunica media's smooth muscle, not the internal elastic lamina, which is a passive elastic sheet.",
        B: "Nourishing the vessel wall is the role of vasa vasorum in the adventitia, not the internal elastic lamina.",
        C: "The internal elastic lamina's condensed, fenestrated elastic tissue keeps the lumen from fully collapsing, preventing complete occlusion of the vessel. A common trap: damage to the endothelium exposes the subendothelial connective tissue, which induces platelet aggregation, thrombus formation and obstruction of flow — a related but separate mechanism.",
        D: "The internal elastic lamina differentiates tunica intima from tunica media, not media from adventitia — that boundary, where present, is the external elastic lamina's role.",
      },
    },
    {
      key: "thrombus-formation-and-obstruction-of-blood-flow-occurs-when-4934a455",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that endothelial damage, exposing the subendothelial connective tissue, is what triggers thrombus formation and vessel obstruction.",
      explanations: {
        A: "Disrupted elastic fibres reduce a vessel's ability to distend and recoil, but this is not the trigger for platelet aggregation and thrombus formation.",
        B: "Damage to the endothelium exposes the subendothelial connective tissue beneath it, which induces platelet aggregation, then thrombus formation, then obstruction of flow — the vessel wall's normal protective plan read as a mechanism of disease.",
        C: "A rise in collagen within the media of arterioles is a chronic structural change (vascular remodelling), not the acute trigger for thrombus formation.",
        D: "A fall in elastic fibres within the media of arterioles reduces compliance over time; it is not what triggers acute thrombus formation.",
      },
    },
    {
      key: "endothelium-of-tunica-intima-is-2046124d",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the endothelium of the tunica intima as simple squamous epithelium.",
      explanations: {
        A: "Simple cuboidal epithelium lines glandular ducts and tubules, not the vessel lumen.",
        B: "The endothelium lining every blood vessel's tunica intima is simple squamous epithelium — a single layer of flattened cells giving a smooth, low-friction surface for flow and a thin barrier for exchange.",
        C: "Stratified cuboidal epithelium lines structures such as sweat gland ducts, not the vascular lumen.",
        D: "Stratified squamous epithelium lines surfaces built for abrasion resistance, such as the epidermis or oesophagus, not the thin exchange surface a vessel lumen needs.",
      },
    },
    {
      key: "fenestrated-elastic-membrane-in-t-media-or-t-adventitia-6e131dc9",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the external elastic lamina as the fenestrated elastic membrane that may sit between the tunica media and tunica adventitia.",
      explanations: {
        A: "Nervi vasorum are the autonomic nerves of the tunica adventitia driving smooth-muscle tone, not an elastic membrane.",
        B: "An external elastic lamina may sit between the tunica media and tunica adventitia, fenestrated like the internal elastic lamina, letting nutrients reach the wall by diffusion through its gaps.",
        C: "Vasa vasorum are small nourishing blood vessels of the adventitia, not an elastic membrane.",
        D: "The subendothelium is loose connective tissue supporting the endothelium in the tunica intima, not a fenestrated elastic membrane at the media-adventitia boundary.",
      },
    },
    {
      key: "internal-elastic-lamina-is-developed-in-the-tunica-intima-of-11ac0429",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina, found in the tunica intima, is a feature of arteries rather than veins, capillaries or lymphatics.",
      explanations: {
        A: "The internal elastic lamina is a condensed, fenestrated sheet of elastic tissue that develops in the tunica intima of arteries only, keeping the lumen from fully collapsing. A common trap: damage to the endothelium, not the lamina itself, is what exposes the subendothelium and triggers thrombosis.",
        B: "Veins characteristically lack a well-developed internal elastic lamina, unlike arteries.",
        C: "Capillaries are a single endothelial layer with no distinct tunica intima, media or adventitia, and so no internal elastic lamina.",
        D: "Lymphatic vessels, like capillaries, are simple-walled and carry no distinct internal elastic lamina.",
      },
    },
    {
      key: "only-in-arteries-forming-fenestrated-like-layer-1a5838b5",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the internal elastic lamina as the fenestrated layer found only in arteries.",
      explanations: {
        A: "Endothelium lines every vessel type, arteries and veins alike, so it is not the layer found only in arteries.",
        B: "Subendothelium supports the endothelium in the tunica intima of vessels generally, not a layer confined to arteries.",
        C: "Vasa vasorum nourish the walls of large vessels, both arteries and veins, so they are not confined to arteries.",
        D: "The internal elastic lamina — a condensed, fenestrated elastic sheet — develops in the tunica intima of arteries only, not in veins, capillaries or lymphatics. A common trap: damage to the endothelium, not the lamina, is what exposes the subendothelium and triggers thrombosis.",
      },
    },
    {
      key: "prevent-complete-occlusion-of-arteries-during-contraction-d1029fb3",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the internal elastic lamina prevents complete occlusion of an artery's lumen when its tunica media contracts.",
      explanations: {
        A: "Endothelium provides a smooth flow surface and exchange barrier; it does not keep the lumen from collapsing during medial contraction.",
        B: "Subendothelium is loose connective tissue supporting the endothelium; it plays no role in resisting occlusion during contraction.",
        C: "Vasa vasorum nourish the outer vessel wall from the adventitia; they have no mechanical role in preventing luminal occlusion.",
        D: "The internal elastic lamina's condensed, fenestrated elastic tissue keeps the lumen from fully collapsing even when the tunica media's smooth muscle contracts, preventing complete occlusion. A common trap: damage to the endothelium, not the lamina, is what exposes the subendothelium and triggers thrombosis.",
      },
    },
    {
      key: "the-endothelial-cells-of-the-blood-vessels-are-present-in-bc33152e",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Locate endothelial cells within the tunica intima, the innermost layer of a blood vessel wall.",
      explanations: {
        A: "Endothelial cells sit in the tunica intima, the innermost layer in direct contact with blood, resting on a basal lamina.",
        B: "There is no distinct layer between tunica intima and tunica media that houses endothelium; the internal elastic lamina occupies that boundary in arteries, not endothelial cells.",
        C: "Tunica adventitia is the outermost connective-tissue coat, with no contact with the blood and no endothelium.",
        D: "Tunica media is smooth muscle, elastic and reticular fibres — the middle, contractile layer — not the endothelial layer.",
      },
    },
    {
      key: "thick-rich-in-elastic-collagen-fiber-81d11216",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the subendothelium, in a large vessel, as a layer that can be relatively thick and rich in elastic and collagen fibres.",
      explanations: {
        A: "Endothelium is a single layer of flattened cells, not a thick, fibre-rich layer.",
        B: "In large vessels the subendothelium, though loose connective tissue, can be relatively substantial and carries both elastic and collagen fibres supporting the endothelium above it.",
        C: "The internal elastic lamina is a condensed elastic sheet, not a layer characteristically described as collagen-rich.",
        D: "The external elastic lamina, like the internal, is elastic tissue proper, not a mixed elastic-and-collagen-rich layer.",
      },
    },
    {
      key: "tunica-media-of-blood-vessels-continuous-the-following-1b8c608a",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that elastic fibres, alongside smooth muscle, are a component of the tunica media.",
      explanations: {
        A: "Elastic fibres run through the tunica media between the smooth-muscle cells, allowing the vessel to distend under pressure.",
        B: "Endothelium belongs to the tunica intima, not the media.",
        C: "Vasa vasorum belong to the tunica adventitia (extending only partly into the outer media in large vessels), not the media generally.",
        D: "The internal elastic lamina marks the intima-media boundary; it is not itself a component distributed through the media.",
      },
    },
    {
      key: "internal-elastic-lamina-is-well-developed-in-the-tunica-inti-5c46764e",
      conceptKey: "blood-vessel-wall.general-three-tunic-plan",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option C's text merges two distinct choices ('Capillaries' and a bled-over 'c. Lymphatic') into a single surviving key, and no fourth option (Lymphatic, on its own letter) survives extraction — leaving only 3 distinguishable options (A, B, merged-C), below the platform's 4-to-5-option import contract. The same fact, with all 4 options intact, is already established by this leaf's own internal-elastic-lamina-is-developed-in-the-tunica-intima-of-11ac0429 question.",
    },
  ],
}
