import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Cytogenetics — Aneuploidy Mechanisms and General Causes",
  modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
  articleId: "ART-104-HIS-CELL-RENEWAL-AND-ANEUPLOIDY",

  concepts: [
    {
      key: "aneuploidy.causes",
      label: "Aneuploidy arises from non-disjunction, from failure of duplication, or from simple loss of a chromosome",
      definition: "Aneuploidy is a chromosome number that is not an exact multiple of the haploid number, the karyotype having gained or lost a single chromosome. It arises from non-disjunction, primary when two homologous chromosomes fail to separate at the first meiotic division, giving four abnormal daughter cells, and secondary when two chromatids fail to separate at the centromere at the second meiotic division or in mitosis, giving two normal and two abnormal daughter cells in meiosis and two abnormal cells in mitosis; from failure of duplication, one chromatid failing to duplicate in S phase; and from simple loss, a chromosome failing to align at metaphase or lagging in anaphase. Secondary non-disjunction occurring in mitosis after many normal divisions produces a mosaic, whose body cells carry more than one karyotype.",
      objective: "Give the causes of aneuploidy, distinguishing primary from secondary non-disjunction by the daughter cells each produces.",
      pitfall: "Treating aneuploidy as always meiotic. Mitotic non-disjunction after fertilisation gives mosaicism, which is why a karyotype from one tissue can read normal in an affected patient.",
      subject: "dev",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
      type: "mechanism",
      aliases: ["Non-disjunction", "Causes of aneuploidy"],
    },
    {
      key: "chromosomal-aberration.general-causes",
      label: "Radiation, viral infection, advanced maternal age, cytotoxic drugs and autoimmune disease all predispose to chromosomal aberration, each by a different route",
      definition: "Before splitting into numerical and structural types, there are five general causes of chromosomal aberration. Radiation causes chromosomal damage and non-disjunction. Viral infections, such as German measles (rubella), cause fragmentation of the chromosome. Pregnancy at an advanced maternal age increases the risk of non-disjunction, through a very long prophase. Drugs, such as the cytotoxic drug colchicine, inhibit formation of the mitotic spindle — which is why colchicine is used experimentally to arrest cells in metaphase, since without a spindle the chromatids cannot be pulled apart into anaphase. Autoimmune diseases are usually associated with non-disjunction as well.",
      objective: "List the five general causes of chromosomal aberration — radiation, viral infection, advanced maternal age, cytotoxic drugs, autoimmune disease — and state which mechanism each acts through.",
      pitfall: "Confusing this general list of predisposing causes with the mechanism of aneuploidy itself (non-disjunction, failure of duplication, simple loss). Radiation and advanced maternal age are named here as things that increase the risk of non-disjunction happening; they are not alternative mechanisms to it.",
      subject: "dev",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
      type: "mechanism",
      aliases: ["Causes of chromosomal aberration", "Colchicine and mitotic spindle inhibition"],
    },
  ],

  questions: [
    {
      key: "cause-fragmentation-of-chromosome-3c6fbfde",
      conceptKey: "chromosomal-aberration.general-causes",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Name viral infection (German measles) as the cause of chromosome fragmentation.",
      explanations: {
        A: "Advanced maternal age is the stated risk factor for non-disjunction, not fragmentation.",
        B: "Autoimmune disease is associated with non-disjunction in the list, not fragmentation.",
        C: "Viral infections, such as German measles, are the cause of chromosome fragmentation. A common trap: confusing this general list of predisposing causes with the mechanism of aneuploidy itself (non-disjunction, failure of duplication, simple loss).",
        D: "Colchicine is the example drug that inhibits mitotic spindle formation, not a cause of fragmentation.",
      },
    },
    {
      key: "when-2-homologous-chromosome-fail-to-separate-result-in-4-ab-7fcb5904",
      conceptKey: "aneuploidy.causes",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Name primary non-disjunction, at the first meiotic division, as the event producing four abnormal daughter cells.",
      explanations: {
        A: "Primary non-disjunction is the failure of two homologous (bivalent) chromosomes to separate at the first meiotic division, resulting in four abnormal daughter cells. A common trap: treating aneuploidy as always meiotic.",
        B: "Secondary non-disjunction is a failure of chromatids (not homologous chromosomes) to separate, at the second meiotic division or in mitosis, giving a different mix of normal and abnormal daughter cells.",
        C: "A mosaic results from secondary non-disjunction occurring in mitosis after many normal divisions, a different pattern from this stem's single failed separation.",
        D: "Simple loss is a chromosome failing to align or lagging in movement, not two homologous chromosomes failing to separate together.",
      },
    },
    {
      key: "colchicine-is-a-chemical-that-stops-chromatids-from-separati-1ee2d739",
      conceptKey: "chromosomal-aberration.general-causes",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State that colchicine, by inhibiting mitotic spindle formation, arrests dividing cells at metaphase.",
      explanations: {
        A: "Prophase precedes spindle formation; colchicine's spindle-inhibiting action is what stops the cell from proceeding past the point the spindle is needed, later than prophase.",
        B: "Anaphase requires spindle microtubules to pull chromatids apart — colchicine prevents the cell from ever reaching this stage, since the spindle it needs never forms.",
        C: "Colchicine inhibits formation of the mitotic spindle; without a spindle, chromatids cannot be pulled apart into anaphase, so the cell arrests at metaphase — the basis of using colchicine to capture metaphase spreads for karyotyping. A common trap: confusing this general list of predisposing causes with the mechanism of aneuploidy itself (non-disjunction, failure of duplication, simple loss).",
        D: "Telophase is well past the point a spindle-inhibited cell can reach, since it never completes chromatid separation.",
      },
    },
    {
      key: "failure-of-chromosome-to-align-during-metaphase-10e2bfdc",
      conceptKey: "aneuploidy.causes",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Name simple loss as the aneuploidy mechanism from a chromosome failing to align at metaphase or lagging in anaphase.",
      explanations: {
        A: "Primary non-disjunction is two homologous chromosomes failing to separate at the first meiotic division, not a single chromosome failing to align.",
        B: "Secondary non-disjunction is two chromatids failing to separate at the centromere, not a single chromosome's alignment failure.",
        C: "A mosaic results from secondary non-disjunction in mitosis after many normal divisions, a different pattern from a single alignment failure.",
        D: "Simple loss occurs due to failure of a chromosome to align during metaphase, or its lagging to move in anaphase. A common trap: treating aneuploidy as always meiotic.",
      },
    },
    {
      key: "inhibit-formation-of-mitotic-spindle-1da00505",
      conceptKey: "chromosomal-aberration.general-causes",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Name colchicine as the drug that inhibits mitotic-spindle formation.",
      explanations: {
        A: "Advanced maternal age is the stated risk factor for non-disjunction, not a drug inhibiting the spindle.",
        B: "Autoimmune disease is a general association with non-disjunction in the list, not a spindle-inhibiting drug.",
        C: "German measles causes chromosome fragmentation, not spindle inhibition.",
        D: "Colchicine, a cytotoxic drug, is inhibiting the formation of the mitotic spindle. A common trap: confusing this general list of predisposing causes with the mechanism of aneuploidy itself (non-disjunction, failure of duplication, simple loss).",
      },
    },
    {
      key: "occurs-in-2-meiotic-division-or-mitosis-f8462f4c",
      conceptKey: "aneuploidy.causes",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Name secondary non-disjunction as the failure of chromatids to separate at the second meiotic division or in mitosis.",
      explanations: {
        A: "Primary non-disjunction is a failure of homologous chromosomes at the first meiotic division, not chromatids at the second division or in mitosis.",
        B: "Secondary non-disjunction is the failure of two chromatids to separate at the centromere, either during the second meiotic division or during mitosis. A common trap: treating aneuploidy as always meiotic.",
        C: "A mosaic is the pattern that results from secondary non-disjunction happening in mitosis after many normal divisions, not the non-disjunction event itself.",
        D: "Simple loss is a chromosome failing to align or lagging in movement, a different mechanism from chromatids failing to separate.",
      },
    },
    {
      key: "occurs-in-mitosis-after-many-normal-division-f411ee8c",
      conceptKey: "aneuploidy.causes",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Name a mosaic as the pattern from secondary non-disjunction occurring in mitosis after many normal divisions.",
      explanations: {
        A: "Primary non-disjunction happens at the first meiotic division, not repeatedly during mitosis after normal divisions.",
        B: "Secondary non-disjunction is the underlying event; the stem asks for what results when it happens in mitosis after many normal divisions, which specifically is a mosaic.",
        C: "Secondary non-disjunction occurring in mitosis after many normal divisions produces a mosaic, whose body cells carry more than one karyotype. A common trap: treating aneuploidy as always meiotic.",
        D: "Simple loss is a chromosome failing to align or lagging, a different mechanism from the repeated-division pattern this stem describes.",
      },
    },
    {
      key: "result-in-2-normal-2-abnormal-daughter-cell-bebb01a5",
      conceptKey: "aneuploidy.causes",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Name secondary non-disjunction in meiosis as the event producing two normal and two abnormal daughter cells.",
      explanations: {
        A: "Primary non-disjunction produces four abnormal daughter cells, not a 2-normal/2-abnormal split.",
        B: "Secondary non-disjunction (chromatids failing to separate at the centromere) in meiosis produces two normal and two abnormal daughter cells — in mitosis, by contrast, both resulting cells are abnormal. A common trap: treating aneuploidy as always meiotic.",
        C: "A mosaic is the pattern from repeated mitotic secondary non-disjunction, not the immediate 2-normal/2-abnormal meiotic outcome this stem describes.",
        D: "Simple loss is a chromosome failing to align or lagging, a different mechanism from a chromatid-separation failure producing this specific daughter-cell split.",
      },
    },
    {
      key: "cause-non-disjunction-cacb3a17",
      conceptKey: "chromosomal-aberration.general-causes",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Genuine two-correct-answer ambiguity, not an extraction corruption: the bank's own editorial answer is B (autoimmune disease), but this leaf's own pinned concept (chromosomal-aberration.general-causes, sourced from the same department book) states BOTH 'pregnancy at an advanced maternal age increases the risk of non-disjunction' AND 'autoimmune diseases are usually associated with non-disjunction' as true causes — so option A is exactly as defensible as the credited option B on this leaf's own source material, and the stem gives no way to prefer one over the other (no 'except', no 'best answer' framing, no distinguishing detail). Per the law of priority (register ambiguity as an exclude with a reason, never author around it), left unauthored rather than picking a single answer the source itself does not privilege. The two remaining distractors are genuinely wrong and already well understood: German measles (rubella) causes chromosome fragmentation, a distinct mechanism from non-disjunction, and colchicine inhibits mitotic spindle formation, arresting cells in metaphase rather than causing non-disjunction itself.",
    },
  ],
}
