import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Cytogenetics — Cell Cycle Phases and Stem Cells",
  modulePath: "104 CPS > Histology > Cytogenetics > The Cell Cycle",
  articleId: "ART-104-HIS-CELL-CYCLE-RENEWAL-DEATH",

  concepts: [
    {
      key: "cell-cycle.phases-g1-s-g2-m-and-g0",
      label: "The cell cycle is mitosis plus a three-phase interphase, with a G0 stable phase for cells that have left the cycle",
      definition: "The cell cycle is a series of events within the cell that prepare it for division into two daughter cells, recognised in two phases. Mitosis is the period of division itself, changes visible by microscope, lasting about one hour. Interphase is the period between two successive divisions, changes not detectable by microscope, lasting about 20 hours in rapidly dividing cells, and subdivided into three phases. Gap 1 (G1), about 8 hours: the daughter cell's nucleus holds 46 single chromosomes (s-chromosomes, or chromatids); the cell grows and acquires energy as ATP; RNA and protein synthesis needed for DNA duplication occurs; and the cell becomes a specialised working cell — the more specialised, the longer G1 and the lower the rate of division. Synthesis (S), about 8 hours: DNA duplicates, so each cell now holds 46 double (d-) chromosomes, and the centrioles duplicate. Gap 2 (G2), about 4 hours: RNA and proteins essential for division are synthesised, energy for mitosis is stored, tubulin is made to build the mitotic microtubules, and any DNA replication error is corrected. Cells that have left the cycle are said to be in the stable, or G0, phase — a resting stage outside the cycle in which most specialised working cells spend a prolonged G1.",
      objective: "Name the cell cycle's phases in order, state the chromosome number and type at G1 versus S, and define G0.",
      pitfall: "Confusing the s-chromosome (single-stranded chromatid, present through G1) with the d-chromosome (double-stranded, present from S phase onward) — the '46 chromosomes' fact is true in both G1 and after S, but what a chromosome is made of has changed.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > The Cell Cycle",
      type: "mechanism",
      aliases: ["Interphase", "G0 phase", "G1, S and G2 phases"],
    },
    {
      key: "stem-cells.pluripotential-and-unipotential-types",
      label: "Stem cells self-renew and are pluripotential, giving rise to more than one specialised cell type, or unipotential, giving rise to only one",
      definition: "Stem cells are undifferentiated cells capable of self-renewal, of two types. Pluripotential (multipotential) stem cells have the potential to give rise to more than one type of specialised cell — for example, blood cells, and the cells lining the gastrointestinal tract. Unipotential stem cells are able to produce only one type of specialised cell — for example, male germ cells.",
      objective: "Define a stem cell and distinguish a pluripotential from a unipotential stem cell, with the book's own example of each.",
      pitfall: "Assuming 'pluripotential' means unlimited potential. The book's own bar is comparative — more than one specialised type — not a claim that a pluripotential stem cell can become anything; a unipotential stem cell such as the male germ cell is still a true stem cell, simply restricted to one fate.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > The Cell Cycle",
      type: "classification",
      aliases: ["Pluripotential stem cells", "Multipotential stem cells", "Unipotential stem cells"],
    },
  ],

  questions: [
    {
      key: "blood-cell-cells-lining-git-are-example-for-048adc09",
      conceptKey: "stem-cells.pluripotential-and-unipotential-types",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Recall blood cells and the cells lining the gastrointestinal tract as the book's own example of pluripotential, not unipotential, stem cells.",
      explanations: {
        A: "Correct. The book gives blood cells and the cells lining the gastrointestinal tract as its example of pluripotential (multipotential) stem cells — cells with the potential to give rise to more than one type of specialised cell. A common trap: assuming 'pluripotential' means unlimited potential.",
        B: "Unipotential stem cells are able to produce only one type of specialised cell, and the book's example of that category is the male germ cell, not blood cells or gut lining.",
        C: "A non-renewing cell cannot be replaced once lost; blood cells and GIT lining cells are, by contrast, continually replaced from stem cells, which is why they are the stem-cell example rather than the non-renewing one.",
        D: "A potentially renewing cell (like the hepatocyte) leaves the cycle but can return to it; that is a different category from a stem cell that continuously gives rise to other cell types.",
      },
      answerOverride: "A",
      answerOverrideReason: "The printed key contradicts the book's own sentence. Histology department book p40 states, verbatim, under pluripotential (multipotential) stem cells: 'e.g. blood cells and cells lining the gastro-intestinal tract' — the exact phrase in the question stem. The book gives no such example under unipotential stem cells (its example there is the male germ cell), so option B cannot be correct.",
    },
    {
      key: "cell-become-specialized-working-cell-in-phase-fc169e08",
      conceptKey: "cell-cycle.phases-g1-s-g2-m-and-g0",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Place the acquisition of a specialised working identity in G1, alongside RNA/protein synthesis for DNA duplication and cell growth.",
      explanations: {
        A: "S phase is when DNA duplicates, giving each cell 46 d-chromosomes, and centrioles duplicate — a different set of events from the stem's description.",
        B: "Correct. The book lists 'the cells become specialised working cells' among G1's own characteristics, alongside cell growth, ATP acquisition and the RNA/protein synthesis needed to duplicate DNA. A common trap: confusing the s-chromosome (single-stranded chromatid, present through G1) with the d-chromosome (double-stranded, present from S phase onward) — the '46 chromosomes' fact is true in both G1 and after S, but what a chromosome is made of has changed.",
        C: "G2 is when RNA and proteins essential to division are synthesised, energy for mitosis is stored, tubulin for microtubules is formed, and DNA-replication errors are corrected — not when the cell becomes specialised.",
        D: "G0 is the stable, resting phase a cell has left the cycle for entirely — it is not where a cell becomes a specialised working cell; that happens during active G1.",
      },
    },
    {
      key: "phase-in-which-an-error-in-dna-replication-is-corrected-53e4bccb",
      conceptKey: "cell-cycle.phases-g1-s-g2-m-and-g0",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Place error correction in DNA replication within G2, alongside RNA/protein synthesis and tubulin formation.",
      explanations: {
        A: "G1 is when the daughter cell grows, acquires energy and synthesises the RNA/protein needed to duplicate DNA — the correction of a replication error is a G2 event, once DNA has already been duplicated.",
        B: "Correct. The book lists correcting any error in DNA replication among G2's own characteristics, alongside synthesising RNA and proteins for division, storing energy for mitosis, and forming tubulin. A common trap: confusing the s-chromosome (single-stranded chromatid, present through G1) with the d-chromosome (double-stranded, present from S phase onward) — the '46 chromosomes' fact is true in both G1 and after S, but what a chromosome is made of has changed.",
        C: "S phase is when DNA duplication itself, and centriole duplication, happen — the error correction the book describes comes after, in G2.",
        D: "G0 is the resting phase a cell has left the cycle for; no DNA replication, and so no error correction, occurs there.",
      },
    },
    {
      key: "phase-in-which-cell-left-cycle-to-be-in-resting-state-bbbcec8a",
      conceptKey: "cell-cycle.phases-g1-s-g2-m-and-g0",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Name G0 as the stable, resting phase a cell enters on leaving the active cell cycle.",
      explanations: {
        A: "G1 is an active phase within the cycle — growth, ATP acquisition, and RNA/protein synthesis — not the resting state a cell leaves the cycle for.",
        B: "G2 is likewise an active phase, preparing the cell for mitosis, not a resting state outside the cycle.",
        C: "Synthesis (S) phase actively duplicates DNA — the opposite of a resting state.",
        D: "Correct. The book names G0, the stable phase, as the resting stage a cell enters on leaving the active cell cycle. A common trap: confusing the s-chromosome (single-stranded chromatid, present through G1) with the d-chromosome (double-stranded, present from S phase onward) — the '46 chromosomes' fact is true in both G1 and after S, but what a chromosome is made of has changed.",
      },
    },
    {
      key: "phase-last-about-4-hours-a0777052",
      conceptKey: "cell-cycle.phases-g1-s-g2-m-and-g0",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Recall the book's stated duration for each interphase sub-phase, and identify G2 as the roughly four-hour one.",
      explanations: {
        A: "The book gives G1 a duration of about 8 hours, not 4.",
        B: "Correct. The book states G2 lasts about 4 hours. A common trap: confusing the s-chromosome (single-stranded chromatid, present through G1) with the d-chromosome (double-stranded, present from S phase onward) — the '46 chromosomes' fact is true in both G1 and after S, but what a chromosome is made of has changed.",
        C: "The book gives synthesis (S) phase a duration of about 8 hours, not 4.",
        D: "G0 is not assigned a fixed duration by the book at all — it is a resting state a cell can remain in indefinitely, not a timed phase.",
      },
    },
  ],
}
