import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Cytogenetics — Mitosis Stages, Meiosis and Their Comparison",
  modulePath: "104 CPS > Histology > Cytogenetics > Cell Division",
  articleId: "ART-104-HIS-MITOSIS-AND-MEIOSIS",

  concepts: [
    {
      key: "mitosis.four-stages-prophase-to-telophase",
      label: "Mitosis is prophase, metaphase, anaphase and telophase, producing two genetically identical daughter cells",
      definition: "Mitosis divides the nucleus to produce two daughter cells genetically identical to the parent, in four stages. Prophase: the 46 d-chromosomes shorten, thicken and stain more darkly, becoming visible as fine threads; the nucleoli and nuclear envelope disappear; centrioles move to opposite poles as cytoplasmic microtubules radiate from the microtubule-organising centre around them; and these microtubules organise into a spindle. Metaphase: chromosomes migrate to the equatorial metaphase plate, and a dense plaque, the kinetochore, develops at each chromosome's centromere as the attachment site for chromosomal microtubules. The mitotic spindle's microtubules are of three kinds: cytoplasmic microtubules, which elongate the cell; chromosomal microtubules, attached to kinetochores, which arrange the chromosomes at the equator; and astral microtubules, star-like around the centrioles, which establish the spindle's axis. Anaphase: each d-chromosome splits longitudinally at the centromere, its two sister chromatids pulled to opposite poles by the chromosomal microtubules as the cytoplasmic microtubules elongate. Telophase: a cleavage furrow forms at the equator by contraction of actin filaments, dividing the cytoplasm in two; the 46 chromatids (s-chromosomes) of each new cell lengthen, uncoil and lose visibility; nuclear envelopes re-form; and nucleoli reappear.",
      objective: "Name mitosis's four stages in order and state, for each, what happens to the chromosomes, the nuclear envelope/nucleoli and the spindle.",
      pitfall: "Describing the kinetochore as the centromere itself. The kinetochore is a protein plaque that develops at the centromere in metaphase specifically to serve as the microtubule attachment site — the centromere is the chromosomal constriction it sits on.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Cell Division",
      type: "mechanism",
      aliases: ["Prophase, metaphase, anaphase, telophase", "Mitotic spindle", "Kinetochore"],
    },
    {
      key: "meiosis.two-successive-divisions-and-crossing-over",
      label: "Meiosis is two successive divisions without an intervening S-phase, producing four haploid germ cells with crossing over",
      definition: "Meiosis is a special cell division in which a diploid cell undergoes two successive divisions without an S-phase between them, occurring in the testis and ovary and producing haploid germ cells — sperm or ova. The first meiotic division (reduction division) has a prophase I that is long — 22 days in spermatogenesis, 12 to 45 years in oogenesis — passing through stages in which the 46 d-chromosomes appear as long threads, then pair as 23 bivalents of one maternal and one paternal homologue each, then condense into tetrads of four chromatids in which crossing over exchanges segments between non-sister chromatids at the chiasmata (with the help of recombinase), before the nucleolus and nuclear envelope disappear; metaphase I aligns the 23 bivalent d-chromosomes on the spindle; anaphase I separates the bivalents, one homologous d-chromosome to each pole; and telophase I yields two daughter cells, each with 23 d-chromosomes. The second meiotic division (equatorial division) is mitosis-like, follows rapidly with a very short interphase and no S-phase: prophase II shortens the chromosomes and forms a new spindle; metaphase II aligns the 23 d-chromosomes at the equator; anaphase II splits each d-chromosome at its centromere into two chromatids (s-chromosomes) moving to opposite poles; and telophase II separates the two daughter cells, each now with 23 s-chromosomes — the haploid number.",
      objective: "State why meiosis has no S-phase between its two divisions, name where crossing over occurs, and give the chromosome number and type at the end of each division.",
      pitfall: "Treating prophase I's duration as a minor detail. It varies enormously — 22 days in the male, 12 to 45 years in the female — and that decades-long arrest in oogenesis is exactly why maternal age is linked to non-disjunction: the bivalent sits arrested in prophase I for as long as the oocyte does.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Cell Division",
      type: "mechanism",
      aliases: ["First meiotic division", "Second meiotic division", "Crossing over", "Chiasmata", "Bivalent chromosomes"],
    },
    {
      key: "mitosis-vs-meiosis.comparison",
      label: "Mitosis is one division producing two identical diploid daughter cells; meiosis is two divisions with crossing over, producing four genetically varied haploid ones",
      definition: "Mitosis and meiosis contrast across five features. Site: mitosis occurs in somatic cells; meiosis occurs in the germ cells of testis and ovary. Number of divisions: mitosis is a single division; meiosis is two successive divisions without an intervening S-phase. Crossing over: absent in mitosis, with no exchange of genes; present in meiosis, where pairing allows crossing over and gene exchange. Separation: in mitosis each chromosome divides longitudinally at the centromere into two chromatids; in meiosis, in the first division, each chromosome of a bivalent moves toward one pole instead. Daughter cells: mitosis gives two somatic daughter cells with the diploid chromosome number, genetically identical to each other; meiosis gives four germ cells with the haploid number, genetically varied.",
      objective: "Set mitosis against meiosis by site, number of divisions, crossing over, chromosome separation, and the number and genetic identity of the daughter cells.",
      pitfall: "Reducing the comparison to 'mitosis makes two cells, meiosis makes four.' The comparison table roots that difference in mechanism — one division versus two, and whether the bivalent's homologues separate as whole chromosomes or split at the centromere — which is what a mechanism question actually tests.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Cell Division",
      type: "comparison",
      aliases: ["Mitosis versus meiosis table"],
    },
  ],

  questions: [
    {
      key: "in-clearage-furrow-all-are-free-except-2f073dce",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that at telophase's cleavage furrow, chromosomes are already lengthening and uncoiling, not still visible as fine threads.",
      explanations: {
        A: "True of telophase, so not the exception. A constriction (cleavage furrow) does develop at the equatorial plane by contraction of actin filaments, dividing the cytoplasm into two halves.",
        B: "True, so not the exception. Each new cell at telophase has 46 chromatids (s-chromosomes).",
        C: "The exception, and the answer. Chromosomes becoming visible as fine threads is a prophase event, as chromosomes first condense — at telophase they are doing the opposite, lengthening and uncoiling out of visibility. A common trap: describing the kinetochore as the centromere itself.",
        D: "True of telophase, so not the exception. The chromatids lengthen and uncoil, losing their visibility, at this stage.",
      },
    },
    {
      key: "mitosis-is-characterized-by-the-following-0e055cd3",
      conceptKey: "mitosis-vs-meiosis.comparison",
      difficulty: "Easy",
      questionType: "Comparison",
      learningObjective: "State that mitosis has no crossing over and no gene exchange, unlike meiosis.",
      explanations: {
        A: "Exchange of genes is what crossing over in meiosis achieves; mitosis has no exchange of genes.",
        B: "The comparison table states mitosis has 'No crossing over, No exchange of genes' — the opposite of meiosis, where pairing allows crossing over. A common trap: reducing the comparison to 'mitosis makes two cells, meiosis makes four.' The comparison table roots that difference in mechanism — one division versus two, and whether the bivalent's homologues separate as whole chromosomes or split at the centromere — which is what a mechanism question actually tests.",
        C: "Mitosis's daughter cells keep the diploid number, not the haploid (n) number that meiosis produces.",
        D: "Mitosis's daughter cells are genetically identical to the parent cell — not different from it.",
      },
    },
    {
      key: "all-characters-of-meiosis-except-a0fb9d0f",
      conceptKey: "mitosis-vs-meiosis.comparison",
      difficulty: "Moderate",
      questionType: "Comparison",
      learningObjective: "State that meiosis produces four, not two, haploid germ cells.",
      explanations: {
        A: "True of meiosis, so not the exception. It occurs in the germ cells of the testes and ovaries.",
        B: "The exception, and the answer. Meiosis produces four germ cells with the haploid number of chromosomes, not two. A common trap: reducing the comparison to 'mitosis makes two cells, meiosis makes four.' The comparison table roots that difference in mechanism — one division versus two, and whether the bivalent's homologues separate as whole chromosomes or split at the centromere — which is what a mechanism question actually tests.",
        C: "True, so not the exception. Meiosis's daughter cells show genetic variation.",
        D: "True, so not the exception. Crossing over during meiosis leads to gene exchange, per the comparison table.",
      },
    },
    {
      key: "all-characters-of-prophase-i-except-d22eb82e",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "State that chromosomes aligning at the equatorial plate is a metaphase I event, not prophase I's.",
      explanations: {
        A: "True of prophase I, so not the exception. The 46 d-chromosomes first appear as long thin threads.",
        B: "True, so not the exception. The bivalents become shorter and thicker as prophase I proceeds.",
        C: "The exception, and the answer. The 23 bivalent d-chromosomes aligning at the equatorial plane is the description of metaphase I, the stage that follows prophase I, not a prophase I event. A common trap: treating prophase I's duration as a minor detail.",
        D: "True, so not the exception. Crossing over between non-sister chromatids of homologous chromosomes happens during prophase I, at the chiasmata.",
        E: "True, so not the exception. The nucleolus and nuclear envelope disappear during prophase I, freeing the chromosomes into the cytoplasm.",
      },
    },
    {
      key: "at-metaphase-ii-3a5d8206",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that at metaphase II the 23 d-chromosomes are aligned at the equatorial plate.",
      explanations: {
        A: "At metaphase II, the 23 d-chromosomes are aligned at the equatorial plate. A common trap: treating prophase I's duration as a minor detail.",
        B: "46 d-chromosomes is the somatic (diploid) count, not the haploid count each meiotic daughter cell carries by metaphase II.",
        C: "23 s-chromosomes is the count after anaphase II, once each d-chromosome has already split into its two chromatids — not yet true at metaphase II.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "at-second-meiotic-division-all-are-nature-except-86ec88c5",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "State that the second meiotic division has a very short interphase without an S-phase — not a longer one.",
      explanations: {
        A: "True of the second meiotic division, so not the exception. It is described as a mitosis-like division.",
        B: "The exception, and the answer. The second meiotic division has a very short interphase, without an S-phase at all — not a longer S-phase. A common trap: treating prophase I's duration as a minor detail.",
        C: "True, so not the exception. Each daughter cell of the second division has 23 d-chromosomes to begin with.",
        D: "True, so not the exception. The second meiotic division is called the equatorial division.",
      },
    },
    {
      key: "at-telophase-ii-23b7eba7",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that at telophase II the two daughter cells separate, each with 23 s-chromosomes — the haploid number.",
      explanations: {
        A: "23 d-chromosomes describes the state entering metaphase II, before the chromatids split apart at anaphase II.",
        B: "46 d-chromosomes is the somatic, diploid-cell count, not what a haploid meiotic daughter cell carries.",
        C: "At telophase II, the two daughter cells separate, each with 23 s-chromosomes — the haploid number. A common trap: treating prophase I's duration as a minor detail.",
        D: "Not applicable — a correct answer is listed among the options.",
      },
    },
    {
      key: "centriole-move-towards-opposite-pole-of-cell-become-surround-c1a94bd3",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Place centriole migration to opposite poles, driven by microtubules from the MTOC, in prophase.",
      explanations: {
        A: "Metaphase is when chromosomes are already aligned at the equator, after the centrioles have finished moving apart in prophase.",
        B: "During prophase, centrioles move to opposite cell poles by cytoplasmic microtubules radiating out from the microtubule-organising centre (MTOC) around them. A common trap: describing the kinetochore as the centromere itself.",
        C: "Telophase reforms the nuclear envelope and nucleoli, well after the centrioles have already reached the poles.",
        D: "Anaphase is when chromatids are pulled apart, after the spindle (built from the centriole-organised microtubules) is already established.",
      },
    },
    {
      key: "chromosome-appear-shorten-darker-fine-thread-in-6cd6517c",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Place chromosomes becoming shorter, thicker, darker-staining fine threads in prophase.",
      explanations: {
        A: "Metaphase is when the already-condensed chromosomes align at the equator, past this initial condensing step.",
        B: "During prophase, chromosomes gradually become shorter, thicker, darker in staining, and visible as fine threads. A common trap: describing the kinetochore as the centromere itself.",
        C: "Telophase is when chromatids lengthen and uncoil, losing visibility — the opposite of this description.",
        D: "Anaphase is when the already-split chromatids migrate to the poles, past this early condensation stage.",
      },
    },
    {
      key: "chromosome-migrate-to-equatorial-plane-of-cell-in-2258147d",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Place chromosome migration to the equatorial (metaphase) plate in metaphase.",
      explanations: {
        A: "Chromosomes migrate to the equatorial plane of the cell — the metaphase plate — during metaphase. A common trap: describing the kinetochore as the centromere itself.",
        B: "Prophase is when chromosomes are still condensing, before they migrate to the equator.",
        C: "Telophase is well after the chromosomes have already separated and migrated to the poles.",
        D: "Anaphase is when the already-aligned chromosomes' chromatids separate and move toward the poles, after the metaphase alignment this stem describes.",
      },
    },
    {
      key: "crossing-over-occurs-by-help-of-e363efe6",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Name recombinase as the enzyme that helps crossing over at the chiasmata.",
      explanations: {
        A: "Sulfatase is not the enzyme for crossing over.",
        B: "Nuclease (endonuclease) is the enzyme credited with fragmenting chromatin in karyorrhexis, not with crossing over.",
        C: "Spectrin is a cytoskeletal protein, not an enzyme involved in crossing over.",
        D: "Crossing over occurs at the chiasmata with the help of the recombinase enzyme, exchanging segments between non-sister chromatids of homologous chromosomes. A common trap: treating prophase I's duration as a minor detail.",
      },
    },
    {
      key: "elongation-of-cytoplasmic-microtubules-in-873a6986",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Hard",
      questionType: "Structure and function",
      learningObjective: "Place the elongation of cytoplasmic microtubules, driving chromatid migration to the poles, in anaphase.",
      explanations: {
        A: "Metaphase is when chromosomes are aligned at the equator, before the cytoplasmic microtubules elongate to pull the separated chromatids apart.",
        B: "Prophase is when the spindle first organises, before its cytoplasmic microtubules elongate to move chromatids in anaphase.",
        C: "Telophase is when the spindle's work is already done and the nuclear envelope is reforming, after the elongation that carried the chromatids to the poles.",
        D: "In anaphase, migration of the separated chromatids to opposite poles of the cell happens by elongation of the cytoplasmic microtubules. A common trap: describing the kinetochore as the centromere itself.",
      },
      answerOverride: "D",
      answerOverrideReason: "The printed key (A, metaphase) contradicts the book. Histology department book p41 (printed p40-41) states under Anaphase: 'Migration to opposite poles of cell by elongation of cytoplasmic microtubules' — an anaphase event, not a metaphase one.",
    },
    {
      key: "mts-are-organized-to-form-spindle-in-01c77303",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Place the organisation of microtubules into the mitotic spindle in prophase.",
      explanations: {
        A: "Metaphase uses the already-organised spindle to align the chromosomes, after prophase has built it.",
        B: "During prophase, microtubules are organised to form a spindle, after centrioles have moved to opposite poles. A common trap: describing the kinetochore as the centromere itself.",
        C: "Telophase is when the spindle's work is finished and the nuclear envelope reforms.",
        D: "Anaphase uses the already-formed spindle to pull chromatids apart, after prophase organised it.",
      },
    },
    {
      key: "nuclear-envelope-nucleoli-reappear-in-0e3b3a36",
      conceptKey: "mitosis.four-stages-prophase-to-telophase",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Place the reappearance of the nuclear envelope and nucleoli in telophase.",
      explanations: {
        A: "Metaphase is mid-division, well before the nuclear envelope and nucleoli reform.",
        B: "Prophase is when the nuclear envelope and nucleoli disappear, the opposite of this stem.",
        C: "In telophase, nuclear envelopes develop and nucleoli reappear, as the two daughter cells separate. A common trap: describing the kinetochore as the centromere itself.",
        D: "Anaphase is when chromatids are still migrating to the poles, before the nuclear envelope and nucleoli reform in telophase.",
      },
    },
    {
      key: "prophase-in-male-last-for-9ef9f35f",
      conceptKey: "meiosis.two-successive-divisions-and-crossing-over",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "State that prophase I of spermatogenesis lasts about 22 days.",
      explanations: {
        A: "28 days is not the duration for male prophase I.",
        B: "Prophase I lasts 22 days in spermatogenesis (male), against 12 to 45 years in oogenesis (female). A common trap: treating prophase I's duration as a minor detail.",
        C: "12-45 years is the duration for female prophase I (oogenesis), not the male's.",
        D: "22 years is not the stated duration; 22 is the correct number, but the unit is days, not years, for the male.",
      },
    },
  ],
}
