import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Cytogenetics — Numerical Aberrations, Down Syndrome, Sex-Chromosome Aberrations",
  modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
  articleId: "ART-104-HIS-NUMERICAL-ABERRATIONS",

  concepts: [
    {
      key: "numerical-chromosomal-aberration.euploidy-and-aneuploidy-types",
      label: "A numerical chromosomal aberration is euploidy — an exact multiple of the haploid number beyond diploid — or aneuploidy — an addition or loss of one chromosome",
      definition: "Numerical aberrations are anomalies of chromosome number, occurring in germ or somatic cells, and are of two kinds. Euploidy is a karyotype that is an exact multiple of the haploid number and exceeds the diploid number — triploid (3n, 69 chromosomes), tetraploid (4n, 92 chromosomes), or polyploidy (5n, 6n or more, meaning one or both gametes were not haploid). Aneuploidy is not an exact multiple of the haploid number: the karyotype shows the addition or loss of one chromosome. Trisomy adds an extra chromosome, giving a karyotype of 2n+1 — three copies of one chromosome instead of two, as in Down syndrome (trisomy 21). Monosomy loses one chromosome, giving 2n−1 — one copy instead of two, as in Turner syndrome (45 chromosomes). Aneuploidy can also be mosaic: secondary non-disjunction occurring in mitosis after many normal divisions leaves the body with more than one karyotype (for example 46, 47, 45 cells coexisting).",
      objective: "Distinguish euploidy from aneuploidy, and trisomy from monosomy, each with an example.",
      pitfall: "Treating 'aneuploid' and 'not diploid' as synonyms. A triploid or tetraploid cell is also not diploid, but it is euploid, because 3n and 4n are still exact multiples of the haploid number — aneuploidy specifically means the count is off by one chromosome, not a whole haploid set.",
      subject: "dev",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
      type: "classification",
      aliases: ["Euploidy", "Aneuploidy", "Trisomy", "Monosomy", "Mosaicism"],
    },
    {
      key: "down-syndrome.causes-and-features",
      label: "Down syndrome is trisomy 21, from non-disjunction or a 14;21 translocation, with mental retardation and characteristic dysmorphic features",
      definition: "Down syndrome (mongolism) results from either non-disjunction of chromosome 21, giving trisomy 21, or a translocation between chromosomes 21 and 14, which accounts for 3 to 4% of cases. The mongol child's cells contain 47 chromosomes, the extra one similar to chromosome 21. Characteristic features are mental retardation, small genital organs, cardiac abnormalities, a lateral upward slope of the eyes, small ears, and a short, broad nose and neck.",
      objective: "State Down syndrome's two chromosomal causes and the proportion due to translocation, and list its characteristic features.",
      pitfall: "Treating Down syndrome as caused by non-disjunction alone. A second route explicitly — centric-fusion translocation between chromosomes 21 and 14 — accounting for 3 to 4% of cases, and that minority route is exactly what an exam question on 'other causes of Down syndrome' is testing.",
      subject: "dev",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
      type: "genetic_basis",
      aliases: ["Mongolism", "Trisomy 21"],
    },
    {
      key: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      label: "Klinefelter (47,XXY), triple X (47,XXX) and Turner (45,XO) syndromes are sex-chromosome aneuploidies from non-disjunction in oogenesis",
      definition: "Numerical aberrations of the sex chromosomes are caused by non-disjunction in the first meiotic division of the primary oocyte, which can produce an ovum with two X chromosomes or none. Klinefelter's syndrome (47, XXY), a trisomy of the sex chromosomes, arises when a two-X ovum is fertilised by a Y-bearing sperm; the affected male has a positive Barr body, and is characteristically mentally retarded, tall, with small testes and large breasts with widely separated nipples. Multiple X syndrome (47, XXX), also a trisomy, arises by the same non-disjunction but with fertilisation by an X-bearing sperm; the affected female carries two Barr bodies, and characteristically shows delayed language development, motor coordination problems and auditory disorders. Turner's syndrome (45, XO), a monosomy of the sex chromosomes, arises when an ovum with no X is fertilised by an X-bearing sperm; the affected female has no Barr body, from the missing X, and is characteristically short, mentally retarded, with limb oedema, underdeveloped ovaries and external genitalia, and primary amenorrhoea.",
      objective: "For Klinefelter, triple X and Turner syndrome, state the karyotype, the fertilising sperm that produces it, the Barr-body count, and two characteristic features.",
      pitfall: "Assuming the karyotype alone predicts the Barr-body count without tracking which parent's gamete carried the error. All three syndromes trace to the same event — non-disjunction in the first meiotic division of the oocyte — and the karyotype, not the mechanism, is what differs; get the karyotype right and the Barr-body count (one fewer than the X count) follows directly.",
      subject: "dev",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Chromosomal Aberrations (Abnormalities)",
      type: "genetic_basis",
      aliases: ["Klinefelter syndrome", "Turner syndrome", "Triple X syndrome", "47 XXY", "45 XO"],
    },
  ],

  questions: [
    {
      key: "a-female-patient-presented-with-mental-retardation-edema-of-7fdcb2d0",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise mental retardation, limb oedema, short stature and primary amenorrhoea as Turner syndrome, karyotype 45,XO — a monosomy, not a trisomy.",
      explanations: {
        A: "Not a real karyotype notation — 47 chromosomes is not paired with the XO label used for Turner syndrome, which is 45, not 47.",
        B: "Turner syndrome has only one X chromosome, not two — two X chromosomes describes a normal female or triple-X syndrome, not this vignette.",
        C: "The opposite of the true mechanism. Turner syndrome is a monosomy of the sex chromosome, not a trisomy — the karyotype has one fewer sex chromosome than normal, not one more.",
        D: "The Turner syndrome description matches this vignette word for word: '45, XO... short female with mental retardation, edema of limbs... primary amenorrhoea' — a monosomy, karyotype 45,XO.",
      },
      answerOverride: "D",
      answerOverrideReason: "The printed key (C, 'trisomy of sex chromosome') directly contradicts the book. Histology department book p49-50 states explicitly: 'Turner's Syndrome (45, XO): i.e. monosomy of sex chromosome... short female with mental retardation, edema of limbs, underdeveloped ovaries & external genitalia with primary amenorrhea' — the exact clinical picture in the stem, and explicitly a monosomy, not a trisomy. D is the only option consistent with the vignette.",
    },
    {
      key: "a-child-with-mental-retardation-hypotonia-and-mongol-like-fe-4f41efac",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise that a Down-syndrome child with 46 (not 47) chromosomes has the disease from a chromosome 21/14 translocation, not a Philadelphia chromosome.",
      explanations: {
        A: "Down syndrome may be caused by 'Translocation (21 and 14)' — a Robertsonian/centric-fusion translocation — which keeps the total chromosome count at 46 (unlike trisomy 21's 47), matching this child's karyotype. A common trap: treating Down syndrome as caused by non-disjunction alone.",
        B: "The Philadelphia chromosome is the marker for chronic myeloid leukaemia, from a 9;22 translocation — an entirely different, acquired somatic change with no connection to Down syndrome's mongol-like features.",
        C: "A duplication of chromosome 14 alone is not a named cause of Down syndrome; the translocation cause fuses 21 with 14, not duplicates 14.",
        D: "A deletion of chromosome 21 would remove genetic material, not add the extra copy of chromosome-21 material that produces Down syndrome's features.",
      },
      answerOverride: "A",
      answerOverrideReason: "The printed key (B, Philadelphia chromosome) contradicts the book, which reserves the Philadelphia chromosome for chronic myeloid leukaemia (a 9;22 translocation, p46/51) — unconnected to Down syndrome. The explanation for a 46-chromosome, mongol-featured child is the 21;14 translocation form of Down syndrome (p48, 'Translocation (21 and 14)'), which is option A.",
    },
    {
      key: "all-characters-of-klinefilter-syndrome-except-22e1320a",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a Klinefelter male has one Barr body (a positive result), not two.",
      explanations: {
        A: "True of Klinefelter syndrome, so not the exception — 47 chromosomes with an XXY complement is the karyotype for it.",
        B: "The exception, and the answer. A Klinefelter male has a positive Barr body — one, from the single extra X — not two; two Barr bodies is the sign of triple-X syndrome instead. A common trap: assuming the karyotype alone predicts the Barr-body count without tracking which parent's gamete carried the error.",
        C: "True, so not the exception. A Klinefelter male does have an additional X chromosome.",
        D: "True, so not the exception. Mental retardation, tall stature, small testis, and large breast with widely separated nipples are the stated features.",
      },
    },
    {
      key: "cells-of-a-person-with-klinefilter-syndrome-contain-d78ce216",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "State that Klinefelter syndrome's 47 chromosomes break down as 44 autosomes plus an XXY sex-chromosome complement.",
      explanations: {
        A: "46 autosomes overstates the autosome count — humans have 44 autosomes (22 homologous pairs), not 46, regardless of the sex-chromosome complement.",
        B: "The karyotype for Klinefelter syndrome is 47, XXY: the 44 autosomes (22 pairs) that every karyotype has, plus the extra sex chromosome giving XXY instead of the normal XY. A common trap: assuming the karyotype alone predicts the Barr-body count without tracking which parent's gamete carried the error.",
        C: "An XXX sex-chromosome complement is the karyotype for triple-X syndrome (in a genetic female), not Klinefelter syndrome, which is XXY.",
        D: "45 autosomes is not a valid autosome count, and a plain XY complement describes a normal male, not Klinefelter syndrome.",
      },
    },
    {
      key: "mentally-retarded-female-patient-with-short-stature-primary-918c2d20",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise short stature, mental retardation, primary amenorrhoea and underdeveloped secondary sex organs in a female as Turner syndrome, karyotype 45,XO.",
      explanations: {
        A: "47, XXY is the karyotype for Klinefelter syndrome, which affects males, not this female patient.",
        B: "The Turner syndrome description matches exactly: '45, XO... short female with mental retardation... underdeveloped ovaries & external genitalia with primary amenorrhea.'",
        C: "47, XY trisomy 21 is not a real combination — trisomy 21 (Down syndrome) does not carry a Y chromosome notation this way, and this stem is a female patient.",
        D: "47, XXX is the karyotype for triple-X syndrome, whose features are delayed language and motor/auditory problems, not the short stature and primary amenorrhoea this vignette describes.",
      },
    },
    {
      key: "main-cause-of-numerical-abberation-in-sex-chromosome-ffdd9878",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "State non-disjunction of the sex chromosomes, in the first meiotic division of the oocyte, as the stated cause of sex-chromosome numerical aberrations.",
      explanations: {
        A: "Viral infection causes chromosome fragmentation in the general list, not specifically the sex-chromosome numerical aberrations this stem asks about.",
        B: "These aberrations are due to non-disjunction of the sex chromosomes during the first meiotic division of the primary oocyte. A common trap: assuming the karyotype alone predicts the Barr-body count without tracking which parent's gamete carried the error.",
        C: "Advanced maternal age is a general listed risk factor for non-disjunction, not itself the mechanism the stem asks for.",
        D: "Autoimmune disease is a general association with non-disjunction in the list, not the specific mechanism named for sex-chromosome aberrations.",
      },
    },
    {
      key: "a-male-child-at-puberty-is-presented-with-mental-retardation-4a86cd63",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise mental retardation, tall stature, small testis and widely separated nipples as Klinefelter syndrome, caused by non-disjunction of the X chromosomes.",
      explanations: {
        A: "Trisomy of chromosome 21 is Down syndrome, whose features (small genital organs, cardiac abnormality, characteristic facies) do not match this tall, small-testis, gynaecomastia picture.",
        B: "Loss of an autosome during mitosis is not the stated cause of Klinefelter syndrome, whose vignette this stem is.",
        C: "The stated event is a gain, not a loss — an extra X chromosome from non-disjunction, not a lost Y.",
        D: "Klinefelter syndrome — mentally retarded tall males, small testis, large breast, widely separated nipples — is due to non-disjunction of the X chromosomes during the first meiotic division of the oocyte. A common trap: assuming the karyotype alone predicts the Barr-body count without tracking which parent's gamete carried the error.",
      },
      answerOverride: "D",
      answerOverrideReason: "The printed key (C, 'loss of Y chromosome during meiosis') contradicts the book. Histology department book p49 states Klinefelter syndrome is 'Due to non disjunction of X chromosomes during 1st meiotic division of oocyte. Ovum with 2 X chromosomes is fertilized with sperm containing Y chromosome' — a gain of an X, not a loss of a Y.",
    },
    {
      key: "a-child-presented-with-mental-retardation-muscular-hypotonia-91b259cf",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise mental retardation, small genital organs and cardiac abnormality as Down syndrome's own stated features, not Klinefelter's.",
      explanations: {
        A: "Klinefelter syndrome's stated features are tall stature, small testis, large breast and separated nipples — none of which are in this stem, which instead names small genital organs and cardiac abnormality, Down syndrome's own wording.",
        B: "'Mental retardation, small genital organs, cardiac abnormalities' is close to verbatim the Down syndrome feature list, alongside the facial and limb features it also names. A common trap: treating Down syndrome as caused by non-disjunction alone.",
        C: "A monosomy of chromosome 21 is not a real, described entity — Down syndrome is a trisomy (or translocation-driven gain) of chromosome 21, not a monosomy.",
        D: "Turner syndrome's stated features are short stature, oedema of the limbs and primary amenorrhoea in a female — features not present in this stem.",
      },
      answerOverride: "B",
      answerOverrideReason: "The printed key (A, Klinefelter syndrome) contradicts the book. Histology department book p48 states Down syndrome's features as 'Mental retardation, small genital organs, cardiac abnormalities' — matching the stem almost word for word — while Klinefelter's own stated features (p49: tall stature, small testis, large breast, separated nipples) do not appear in the stem at all.",
    },
    {
      key: "all-characters-of-down-syndrome-except-c421f58c",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that Down syndrome's translocation cause is between chromosomes 21 and 14, not 9 and 22.",
      explanations: {
        A: "True of Down syndrome, so not the exception — non-disjunction of chromosome 21 (trisomy 21) is one of the two stated causes.",
        B: "The exception, and the answer. A translocation between chromosomes 9 and 22 is the Philadelphia chromosome, causing chronic myeloid leukaemia — Down syndrome's translocation cause is between 21 and 14. A common trap: treating Down syndrome as caused by non-disjunction alone.",
        C: "True, so not the exception. Advanced maternal age is a risk factor for non-disjunction, which underlies the trisomy-21 form of Down syndrome.",
        D: "True, so not the exception. The mongol child's cells contain 47 chromosomes.",
        E: "True, so not the exception. Mental retardation and small genital organs are among the stated features.",
      },
    },
    {
      key: "centric-fusion-occurs-in-cases-of-down-syndrome-40018781",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "State that centric fusion accounts for 3-4% of Down syndrome cases.",
      explanations: {
        A: "30-40% overstates the figure by an order of magnitude.",
        B: "10-15% is not the figure for the translocation form of Down syndrome.",
        C: "Centric fusion between chromosomes 21 and 14 occurs in 3-4% of cases of Down syndrome. A common trap: treating Down syndrome as caused by non-disjunction alone.",
        D: "20-30% is not the stated figure.",
      },
    },
    {
      key: "down-syndrome-68763198",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Comparison",
      learningObjective: "State that centric fusion between chromosomes 21 and 14 is one of the two causes of Down syndrome.",
      explanations: {
        A: "Down syndrome may be caused by centric fusion (translocation) between chromosomes 21 and 14, alongside non-disjunction (trisomy 21). A common trap: treating Down syndrome as caused by non-disjunction alone.",
        B: "Multiple X syndrome (triple X, 47 XXX) is a separate sex-chromosome aberration in females, with its own distinct features — not a cause of Down syndrome.",
        C: "Monosomy of chromosome 21 is not a described cause of Down syndrome — Down syndrome is caused by a gain of chromosome-21 material, not a loss.",
        D: "47 chromosomes with an XXY complement is the karyotype for Klinefelter syndrome, an unrelated sex-chromosome aberration, not Down syndrome.",
      },
    },
    {
      key: "if-a-parent-is-a-carrier-of-a-chromosome-21-translocation-he-c24c4e48",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "State that a parent carrying a chromosome-21 translocation risks having a child with Down syndrome, not chronic myeloid leukaemia.",
      explanations: {
        A: "Turner syndrome arises from non-disjunction of the sex chromosomes in the oocyte, unrelated to an inherited chromosome-21 translocation.",
        B: "Translocation between chromosomes 21 and 14 is one of its two stated causes of Down syndrome — an inherited translocation carrier's child is at risk of this outcome. A common trap: treating Down syndrome as caused by non-disjunction alone.",
        C: "Klinefelter syndrome arises from non-disjunction of the sex chromosomes, unrelated to a chromosome-21 translocation.",
        D: "Chronic myeloid leukaemia's Philadelphia chromosome is an acquired somatic translocation between chromosomes 9 and 22, arising in leukaemic cells — it is not inherited from a chromosome-21-translocation-carrier parent.",
      },
      answerOverride: "B",
      answerOverrideReason: "The printed key (D, chronic myeloid leukaemia) contradicts the book. Histology department book p48 states a chromosome-21 translocation (with 14) is a cause of Down syndrome; the Philadelphia chromosome that causes chronic myeloid leukaemia (p51-52) is a separate, acquired 9;22 translocation, not something a parent 'carries' and passes to a child.",
    },
    {
      key: "a-child-with-mental-retardation-hypotonia-and-mongol-like-fe-92c527a1",
      conceptKey: "down-syndrome.causes-and-features",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise that a Down-syndrome child with 46 chromosomes has the translocation form, a Robertsonian fusion of 21 and 14, not the Philadelphia chromosome, a duplication or a deletion.",
      explanations: {
        A: "A 46-chromosome karyotype with the Down syndrome phenotype (mental retardation, hypotonia, mongoloid facial features) points to translocation Down syndrome, most commonly a Robertsonian translocation fusing chromosome 21 onto chromosome 14 — the extra chromosome-21 material rides along on chromosome 14 rather than existing as a free 47th chromosome, keeping the total count at 46 while still producing three functional copies of chromosome-21 material.",
        B: "The Philadelphia chromosome is the marker for chronic myeloid leukaemia, from an acquired 9;22 translocation — unconnected to the Down syndrome phenotype.",
        C: "A duplication of chromosome 14 alone is not a described cause of Down syndrome; the translocation cause fuses 21 onto 14, it does not duplicate 14.",
        D: "A deletion of chromosome 21 would remove genetic material, the opposite of the extra chromosome-21 material that produces Down syndrome's features.",
      },
    },
    {
      key: "a-m-ntaliy-retarded-female-patient-with-short-stature-primar-2601c06b",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Recognise short stature, primary amenorrhoea and underdeveloped secondary sex organs in a female as Turner syndrome, karyotype 45,XO, against three karyotypes for other conditions.",
      explanations: {
        A: "47,XXY is the karyotype for Klinefelter syndrome, which affects males (tall stature, small testes, gynecomastia) — not this female patient's short stature and amenorrhoea.",
        B: "The Turner syndrome karyotype, 45,XO, matches this vignette's short stature, primary amenorrhoea and underdeveloped secondary sex organs — the classic triad from ovarian dysgenesis in a single-X female.",
        C: "'47, XY trisomy 21' names a genetically male karyotype notation, inconsistent both with the stated female sex and with Down syndrome's own distinct phenotype (present from birth, not this pubertal presentation).",
        D: "47,XXX is triple X syndrome, whose features are delayed language development and motor/auditory problems — not the short stature and primary amenorrhoea this vignette specifically describes.",
      },
    },
    {
      key: "all-characters-of-multiple-x-chromosome-except-fe676c7f",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "State that multiple-X (triple X) syndrome is a trisomy, not the monosomy with an XO karyotype, and identify that as the false statement.",
      explanations: {
        A: "The exception, and the answer. 'Monosomy sex chromosome with XO' describes Turner syndrome, not multiple X syndrome — triple X syndrome (47,XXX) is a trisomy, an addition of a sex chromosome, the opposite numerical change from Turner's monosomy.",
        B: "True of multiple X syndrome, so not the exception. It is a female with an additional X chromosome beyond the normal two.",
        C: "True, so not the exception. Two Barr bodies are present in triple X syndrome, one fewer than the three X chromosomes present.",
        D: "True, so not the exception. Triple X syndrome arises when an ovum carrying two X chromosomes (from non-disjunction) is fertilised by a normal X-bearing sperm.",
      },
    },
    {
      key: "all-characters-of-turner-syndrome-except-d442923d",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "State that Turner syndrome affects females with a single X chromosome, not males, and identify that as the false statement.",
      explanations: {
        A: "True of Turner syndrome, so not the exception. Its karyotype is 45 chromosomes with an XO (single X) sex-chromosome complement.",
        B: "True, so not the exception. With only one X chromosome, a Turner syndrome patient has no sex chromatin (no Barr body) at all.",
        C: "The exception, and the answer. Turner syndrome affects FEMALES with a single X chromosome, not males — describing it as a male condition reverses the sex the syndrome actually affects.",
        D: "True, so not the exception. Turner syndrome arises when an ovum with no X chromosome (from non-disjunction) is fertilised by a normal X-bearing sperm.",
      },
    },
    {
      key: "amale-child-at-puberty-is-presented-with-mental-retardation-d31b09e6",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Attribute the Klinefelter phenotype at puberty to non-disjunction of the X chromosomes, against three unrelated mechanisms.",
      explanations: {
        A: "Trisomy of chromosome 21 causes Down syndrome, a distinct phenotype present from birth, not this pubertal, hypogonadal presentation.",
        B: "Loss of an autosome during mitosis is generally lethal to the affected cell line or produces a very different, non-viable outcome, not this specific pubertal phenotype.",
        C: "Loss of the Y chromosome during meiosis would tend toward a Turner-like (45,X) karyotype, not the extra-X Klinefelter phenotype this vignette describes.",
        D: "Mental retardation, tall stature, small testes and widely separated nipples (gynecomastia) at puberty is the Klinefelter phenotype (47,XXY), which arises from non-disjunction of the X chromosomes during meiosis, producing a gamete carrying an extra X chromosome.",
      },
    },
    {
      key: "euploidy-include-all-the-following-except-7a26317a",
      conceptKey: "numerical-chromosomal-aberration.euploidy-and-aneuploidy-types",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "State that a single-chromosome loss is aneuploidy, not euploidy, and identify that as the false statement among euploidy's true characters.",
      explanations: {
        A: "True of euploidy, so not the exception. A euploid karyotype is an exact multiple of the haploid number, exceeding the diploid number.",
        B: "The exception, and the answer. 'Additional loss of one chromosome' describes aneuploidy (specifically monosomy), not euploidy — euploidy is always a whole extra haploid set, never an off-by-one count.",
        C: "True, so not the exception. Triploidy (3n) totals 69 chromosomes, an exact multiple of the 23-chromosome haploid set.",
        D: "True, so not the exception. Tetraploidy (4n) totals 92 chromosomes, likewise an exact multiple of the haploid set.",
      },
    },
    {
      key: "one-of-the-following-is-a-numerical-aberration-in-sex-chromo-db39b774",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name Turner's syndrome as the numerical (not structural) sex-chromosome aberration among the four options.",
      explanations: {
        A: "Down's syndrome is a numerical aberration, but of an autosome (chromosome 21), not a sex chromosome.",
        B: "Turner's syndrome (45,XO) is a numerical aberration of the sex chromosomes — a monosomy from loss of one X — matching exactly what this stem asks for.",
        C: "An isochromosome is a structural aberration (from transverse rather than longitudinal centromere division), not a numerical one.",
        D: "A translocation is a structural aberration (movement of a segment between chromosomes), not a numerical one.",
      },
    },
    {
      key: "a-female-patient-presented-with-mental-retardation-edema-of-45ad91b4",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Clinical vignette",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (B, C, D — option A is missing entirely, its text apparently absorbed into the stem itself as the trailing, internally-inconsistent fragment '...Her karyotype is 47 XO'), below the platform's 4-to-5-option import contract. The same Turner-syndrome vignette (short female, limb oedema, primary amenorrhoea, karyotype 45,XO) is already tested cleanly by this leaf's own a-female-patient-presented-with-mental-retardation-edema-of-7fdcb2d0 and mentally-retarded-female-patient-with-short-stature-primary-918c2d20 questions.",
    },
    {
      key: "klinefelter-s-syndrome-is-82256d5f",
      conceptKey: "sex-chromosome-aberration.klinefelter-turner-and-triple-x-syndromes",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, B, C — option D is missing entirely), below the platform's 4-to-5-option import contract. The Barr-body-positive fact this row's editorial key rests on is already tested cleanly by this leaf's own all-characters-of-klinefilter-syndrome-except-22e1320a question.",
    },
  ],
}
