import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Cytogenetics — Chromosome Structure, Karyotyping, Classification, Sex Chromatin",
  modulePath: "104 CPS > Histology > Cytogenetics > Human Chromosome",
  articleId: "ART-104-HIS-CHROMOSOME-STRUCTURE-KARYOTYPE",

  concepts: [
    {
      key: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      label: "A chromosome is DNA coiled on histones, its two chromatids joined at a centromere bearing kinetochores, capped by telomeres",
      definition: "Chromosomes are chromatin fibres that become so condensed and tightly coiled during mitosis and meiosis that they are visible with the light microscope. At the G1 stage of interphase the chromosome is a single thread of DNA, the s-chromosome or chromatid; at the S stage it becomes double-threaded, the d-chromosome. During late prophase and metaphase each chromosome is formed of two chromatids connected at the centromere, which divides the d-chromosome into a short arm (p) and a long arm (q). Kinetochores are two discs of protein at the centromere to which the spindle fibres attach during cell division. Each chromatid is a DNA molecule coiled around histone and non-histone proteins. A gene is a segment of DNA coding for a specific protein, with a precise position, its locus, on the chromosome. Telomeres are repeated-sequence regions at the chromosomal ends, protecting the end from destruction and preventing end-to-end fusion of chromosomes.",
      objective: "Name a chromosome's parts — chromatid, centromere, kinetochore, p and q arms, gene locus and telomere — and state when a chromosome is single- versus double-stranded.",
      pitfall: "Confusing 'chromosome' with a single, fixed structure rather than a state that changes across the cycle — the same 46 chromosomes are single-stranded s-chromosomes through G1 and double-stranded d-chromosomes from S phase through metaphase, before splitting back into single chromatids at anaphase.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Human Chromosome",
      type: "structural_description",
      aliases: ["Centromere", "Kinetochore", "Telomere", "p and q arms", "s-chromosome and d-chromosome"],
    },
    {
      key: "karyotyping.definition-technique-and-banding",
      label: "Karyotyping studies chromosome number and type from a metaphase spread of leucocytes, refined by banding to stain individual genes",
      definition: "Karyotyping is the study of the number and type of chromosomes according to their length and the position of the centromere. Technique: leucocytes are the best cells to study; cells are allowed to divide by mitosis and then stopped at metaphase; the metaphase spread is photographed, matched into pairs and arranged in descending order of length; and chromosomes are studied with specialised computer software. Banding technique differentiates chromosomes further by staining different segments (genes) in different colours.",
      objective: "State what karyotyping studies, which cell type is used, at which stage of division the cells are stopped, and what banding adds.",
      pitfall: "Assuming karyotyping needs a dividing tissue like bone marrow. Leucocytes — ordinary blood cells stimulated to divide in culture — are the cell of choice, which is what makes the test practical from a simple blood draw.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Human Chromosome",
      type: "definition",
      aliases: ["Karyotype", "Chromosome banding"],
    },
    {
      key: "chromosome-classification.by-gene-content-centromere-position-and-length",
      label: "Chromosomes are classed by gene content into autosomes and sex chromosomes, by centromere position into four shapes, and by length into seven groups",
      definition: "Chromosomes are classified three ways. By gene content: 22 homologous autosome pairs control somatic characters, and one pair of sex chromosomes controls sex — homologous (XX) in females, heterologous (XY) in males. By centromere position: metacentric, centromere central so the arms are equal; submetacentric, centromere midway between centre and end so the short arm is shorter than the long; acrocentric, centromere close to the upper end so the short arm is very short, and — except on the Y — some acrocentric chromosomes carry satellites, small chromatin masses on the short arm attached by a narrow secondary constriction containing rRNA genes; and telocentric, centromere terminal with no short arm, a type not present in humans. By length: the 22 homologous pairs are numbered 1 to 22 in descending order of length and grouped into seven groups, A through G; the sex chromosomes are placed either alone or with X in group C and Y in group G.",
      objective: "Name the three ways chromosomes are classified, and state the four centromere-position categories with which one does not occur in humans.",
      pitfall: "Forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Human Chromosome",
      type: "classification",
      aliases: ["Metacentric", "Submetacentric", "Acrocentric", "Telocentric", "Autosomes and sex chromosomes"],
    },
    {
      key: "sex-chromatin.barr-body-structure-and-clinical-significance",
      label: "The Barr body is the inactive, coiled X chromosome, present in normal females and X-excess males but absent in normal males and Turner syndrome",
      definition: "Sex chromatin, the Barr body, first described by Murray Barr, is a darkly stained mass of chromatin representing the inactive, coiled, dark-staining X chromosome in the nucleus of a female cell, while the other X chromosome stays active, extended and inapparent. It is seen on the inner aspect of the nuclear envelope in about 60% of female buccal epithelial cell nuclei, and as a drumstick-like mass attached to the nucleus in 3 to 5% of female blood neutrophils. Every somatic cell must keep at least one active X chromosome, which carries genes other than the sex-determining ones. A Barr body appears in normal female cells and in male cells with an extra X chromosome (47, XXY, Klinefelter syndrome); it is not apparent in normal male cells, nor in female cells with only one X chromosome (45, XO, Turner syndrome). Chromosomal examination, including Barr body assessment, has clinical importance: diagnosing genetic sex in doubtful hermaphroditism; identifying fetal sex from amniotic-fluid cells; diagnosing sex-chromosome abnormalities such as Turner and Klinefelter syndromes; diagnosing structural abnormalities such as the deletion behind some mental retardation or the translocation behind chronic myeloid leukaemia; diagnosing numerical abnormalities such as mongolism; and forensic, medico-legal use.",
      objective: "State what the Barr body represents, where it is seen in the female buccal cell and neutrophil, and predict its presence in Klinefelter and Turner syndrome.",
      pitfall: "Predicting Barr-body number from X-chromosome number by simple subtraction without the rule behind it — the number of Barr bodies is always one fewer than the number of X chromosomes present, because exactly one X per cell stays active and every other X is inactivated as a Barr body.",
      subject: "fnd",
      primary: "DIS-HIS-T01",
      secondary: [],
      modulePath: "104 CPS > Histology > Cytogenetics > Human Chromosome",
      type: "definition",
      aliases: ["Barr body", "Sex chromatin", "X-inactivation"],
    },
  ],

  questions: [
    {
      key: "barr-body-in-3-5-in-8cfa0a59",
      conceptKey: "sex-chromatin.barr-body-structure-and-clinical-significance",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "State that the drumstick-like Barr body appears in 3-5% of female blood neutrophils.",
      explanations: {
        A: "The drumstick-shaped Barr body appears in 3-5% of female blood neutrophils, alongside the nuclear-envelope form in about 60% of buccal epithelial cells. A common trap: predicting Barr-body number from X-chromosome number by simple subtraction without the rule behind it — the number of Barr bodies is always one fewer than the number of X chromosomes present, because exactly one X per cell stays active and every other X is inactivated as a Barr body.",
        B: "Eosinophils are not the cell for this 3-5% figure.",
        C: "Lymphocytes are not the cell for the drumstick-shaped Barr body.",
        D: "Monocytes are not the cell for the drumstick-shaped Barr body.",
      },
    },
    {
      key: "best-cell-to-study-chromosome-2d59d311",
      conceptKey: "karyotyping.definition-technique-and-banding",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Name leucocytes as the stated best cell for chromosome study by karyotyping.",
      explanations: {
        A: "Platelets have no nucleus, so they carry no chromosomes to study.",
        B: "Red blood cells are anucleate in their mature form and carry no chromosomes either.",
        C: "Leucocytes are the best cells to study chromosomes — they are allowed to divide by mitosis and stopped at metaphase for the spread. A common trap: assuming karyotyping needs a dividing tissue like bone marrow.",
        D: "Not applicable — a correct single answer is listed among the options.",
      },
    },
    {
      key: "central-fusion-occurs-in-chromosome-9da50345",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify acrocentric chromosomes (like 21 and 14) as the type centric fusion occurs between.",
      explanations: {
        A: "Metacentric chromosomes have a central centromere with equal arms — not the type the centric-fusion example (21 and 14) belongs to.",
        B: "Submetacentric chromosomes are not the type centric fusion is described between.",
        C: "Telocentric chromosomes have no short arm at all and do not occur in humans.",
        D: "Chromosomes 21 and 14, the centric-fusion example in Down syndrome, are acrocentric — centromere very close to one end. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
      },
    },
    {
      key: "centromere-between-center-upper-end-7cdb942b",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name submetacentric as the class whose centromere sits midway between the centre and the upper end.",
      explanations: {
        A: "Metacentric describes a centromere at the exact centre, with equal arms.",
        B: "The submetacentric centromere sits midway between the centre and the upper end, giving a short and a long arm. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
        C: "Acrocentric describes a centromere very close to the upper end, not midway.",
        D: "Telocentric describes a terminal centromere with no short arm, not a midway one.",
      },
    },
    {
      key: "centromere-is-very-close-to-upper-end-p-is-very-short-fb711fe0",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name acrocentric as the class whose centromere sits very close to one end, leaving a very short p arm.",
      explanations: {
        A: "Metacentric has a centromere at the centre, not close to one end.",
        B: "Submetacentric has the centromere midway between centre and end, closer to the middle than acrocentric's is.",
        C: "Acrocentric chromosomes have a centromere very close to the upper end, so the p arm is very short. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
        D: "Telocentric would have no p arm at all, and this type does not occur in humans.",
      },
    },
    {
      key: "isochromosome-occurs-in-chromosome-55b81623",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State that isochromosome formation occurs mostly in submetacentric chromosomes.",
      explanations: {
        A: "Metacentric chromosomes are not where this anomaly occurs.",
        B: "Isochromosomes occur mostly in submetacentric chromosomes, which divide transversely rather than longitudinally at the centromere during anaphase. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
        C: "Acrocentric chromosomes are not where isochromosome formation occurs.",
        D: "Telocentric chromosomes do not occur in humans.",
      },
    },
    {
      key: "kinetochore-is-0d17451f",
      conceptKey: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Define the kinetochore as the pair of protein discs at the centromere where spindle fibres attach.",
      explanations: {
        A: "Two chromatids joined at the centromere describes the d-chromosome itself, not the kinetochore.",
        B: "A gene, not a kinetochore, is the DNA segment coding for a protein.",
        C: "Kinetochores are two discs of protein located at the centromere, to which the spindle fibres attach during cell division. A common trap: confusing 'chromosome' with a single, fixed structure rather than a state that changes across the cycle — the same 46 chromosomes are single-stranded s-chromosomes through G1 and double-stranded d-chromosomes from S phase through metaphase, before splitting back into single chromatids at anaphase.",
        D: "A telomere, not a kinetochore, is the repeated-sequence region protecting the chromosome's end.",
      },
    },
    {
      key: "mass-of-chromatin-attached-to-short-arm-in-all-the-following-a17e69ee",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that satellites attach to the short arm of acrocentric chromosomes generally, but not the Y.",
      explanations: {
        A: "Chromosome 21 is acrocentric and does carry a satellite, so this is not the exception.",
        B: "The X chromosome is not an acrocentric chromosome and is not part of the satellite-bearing group at all, but the stated exception is Y, named directly — not X.",
        C: "Chromosome 14 is acrocentric and does carry a satellite, so this is not the exception.",
        D: "Among the acrocentric chromosomes, all except the Y carry a satellite mass of chromatin on the short arm — the Y is the named exception. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
      },
    },
    {
      key: "small-mass-of-chromatin-attached-to-short-arm-by-narrow-stal-1e230d75",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute the satellite (attached by a narrow stalk to the short arm) to acrocentric chromosomes.",
      explanations: {
        A: "Metacentric chromosomes are not known for carrying satellites.",
        B: "Submetacentric chromosomes are not known for carrying satellites.",
        C: "Some acrocentric chromosomes (except the Y) carry a small satellite mass of chromatin attached to the short arm by a narrow stalk, containing rRNA genes. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
        D: "Telocentric chromosomes do not occur in humans.",
      },
    },
    {
      key: "telomere-is-a73ab400",
      conceptKey: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Define the telomere as the repeated-sequence region protecting a chromosome's end.",
      explanations: {
        A: "Two chromatids connected at the centromere describes the d-chromosome, not the telomere.",
        B: "A gene, not a telomere, is the DNA segment coding for a protein.",
        C: "Two protein discs at the centromere describes the kinetochore, not the telomere.",
        D: "Telomeres are regions of repeated sequence at the chromosomal ends, protecting the end from destruction and preventing end-to-end fusion. A common trap: confusing 'chromosome' with a single, fixed structure rather than a state that changes across the cycle — the same 46 chromosomes are single-stranded s-chromosomes through G1 and double-stranded d-chromosomes from S phase through metaphase, before splitting back into single chromatids at anaphase.",
      },
    },
    {
      key: "when-two-arm-are-equal-41aa9daf",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Easy",
      questionType: "Classification",
      learningObjective: "Name metacentric as the class whose centromere is central, giving equal arms.",
      explanations: {
        A: "Metacentric describes a centromere at the centre of the chromosome, so the two arms (p and q) are equal. A common trap: forgetting that satellites occur on acrocentric chromosomes 'except the Y' — this exception is stated explicitly, and it is the kind of single-word qualifier a classification question is built to test.",
        B: "Submetacentric gives a short and a long arm, not equal ones.",
        C: "Acrocentric gives a very short p arm against a long q arm, not equal ones.",
        D: "Telocentric would have no short arm at all, and does not occur in humans.",
      },
    },
    {
      key: "in-karyotyping-the-chromosomes-are-obtained-in-d6c78142",
      conceptKey: "karyotyping.definition-technique-and-banding",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "State that karyotyping stops dividing cells at metaphase to obtain the chromosome spread.",
      explanations: {
        A: "Prophase chromosomes are still condensing and not yet aligned — the technique stops cells later, at metaphase.",
        B: "Anaphase chromosomes are already separating toward opposite poles, past the point karyotyping captures them.",
        C: "The karyotyping technique allows cells to divide by mitosis and stops them at metaphase, when the spread is photographed. A common trap: assuming karyotyping needs a dividing tissue like bone marrow.",
        D: "Interphase chromosomes are uncondensed chromatin, not visible as the discrete metaphase spread karyotyping needs.",
      },
    },
    {
      key: "at-karyotyping-cell-is-stopped-division-at-24c1dd45",
      conceptKey: "karyotyping.definition-technique-and-banding",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "State that karyotyping stops the dividing cell at metaphase.",
      explanations: {
        A: "Prophase precedes the point the technique stops cells at.",
        B: "The karyotyping technique stops the dividing cell at metaphase for the spread to be photographed. A common trap: assuming karyotyping needs a dividing tissue like bone marrow.",
        C: "Telophase is well past the metaphase point the technique actually captures.",
        D: "Anaphase is past metaphase, the stage the technique actually stops the cell at.",
      },
    },
    {
      key: "in-which-a-chromatid-connected-at-centromere-that-divide-d-c-0ccdeacd",
      conceptKey: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that a d-chromosome's two chromatids, joined at the centromere into a short and long arm, are seen from late prophase through metaphase.",
      explanations: {
        A: "Anaphase is when the chromatids have already split apart at the centromere, past the stage of being joined as described here.",
        B: "During late prophase and metaphase, each chromosome is formed of two chromatids connected at the centromere, dividing the d-chromosome into a short (p) and long (q) arm. A common trap: confusing 'chromosome' with a single, fixed structure rather than a state that changes across the cycle — the same 46 chromosomes are single-stranded s-chromosomes through G1 and double-stranded d-chromosomes from S phase through metaphase, before splitting back into single chromatids at anaphase.",
        C: "Telophase is after the chromatids have already separated, not while they are still joined at the centromere as one d-chromosome.",
        D: "Anaphase, again, is after separation — this description of a still-joined d-chromosome belongs to late prophase and metaphase, not anaphase.",
      },
    },
    {
      key: "segments-of-dna-molecules-that-code-for-formation-of-specifi-d5b539e9",
      conceptKey: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Define a gene as the DNA segment coding for a specific protein, against three other chromosome-structure terms.",
      explanations: {
        A: "Kinetochores are the two protein discs at the centromere to which spindle fibres attach — a structural, not coding, feature of the chromosome.",
        B: "A gene is a segment of DNA coding for a specific protein, with a precise position (its locus) on the chromosome — exactly the definition this stem describes.",
        C: "The centromere is the constriction joining a d-chromosome's two chromatids and dividing it into its p and q arms — a structural landmark, not a protein-coding segment.",
        D: "Chiasmata are the points where crossing over exchanges segments between non-sister chromatids during meiosis — a meiotic event, not the general term for a protein-coding DNA segment.",
      },
    },
    {
      key: "two-discs-of-protein-located-at-centromere-for-spindle-fiber-e8770502",
      conceptKey: "chromosome-structure.chromatid-centromere-kinetochore-and-telomere",
      difficulty: "Easy",
      questionType: "Definition",
      learningObjective: "Name kinetochores as the two protein discs at the centromere where spindle fibres attach.",
      explanations: {
        A: "Kinetochores are two discs of protein at the centromere to which the spindle fibres attach during cell division — one on each sister chromatid, so each spindle pole can pull its own chromatid apart at anaphase.",
        B: "Telomeres are the repeated-sequence regions capping the chromosome's ends, protecting them from degradation and fusion — unrelated to spindle-fibre attachment at the centromere.",
        C: "A gene is a segment of DNA coding for a specific protein — a coding unit, not the protein discs the stem describes.",
        D: "Chiasmata are the visible crossover points between homologous chromosomes in meiotic prophase I, not protein structures for spindle attachment.",
      },
    },
    {
      key: "using-specific-chemical-chromatids-are-stopped-from-separati-796779b2",
      conceptKey: "karyotyping.definition-technique-and-banding",
      difficulty: "Moderate",
      questionType: "Definition",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, C, D — option B is missing entirely) and option A's own text is itself an OCR/page-bleed merge of two choices ('Prophase. ‏.م‎ Anaphase'), below the platform's 4-to-5-option import contract and too corrupted to present cleanly. Excluded rather than guessing the true A/B split; the underlying fact (a spindle-poison chemical such as colchicine arrests dividing cells at metaphase, the basis of karyotyping) is already tested cleanly by this leaf's own at-karyotyping-cell-is-stopped-division-at-24c1dd45 question.",
    },
    {
      key: "when-the-chromosome-divides-transversely-during-anaphase-0536de99",
      conceptKey: "chromosome-classification.by-gene-content-centromere-position-and-length",
      difficulty: "Hard",
      questionType: "Mechanism",
      learningObjective: "State that transverse, rather than the normal longitudinal, centromere division at anaphase produces an isochromosome.",
      explanations: {
        A: "Normally a chromosome's centromere splits longitudinally at anaphase, giving each daughter one copy of each arm; when it instead splits transversely, each resulting chromosome carries two copies of the same arm (two short or two long arms) rather than one of each — this is exactly how an isochromosome forms, most often in submetacentric chromosomes.",
        B: "The Philadelphia chromosome arises from a reciprocal translocation between chromosomes 9 and 22, an entirely different mechanism from a transverse centromere division.",
        C: "A ring chromosome forms when a chromosome breaks at both ends and the broken ends fuse together — a different mechanism from transverse centromere splitting.",
        D: "Terminal deletion results from loss of a chromosome's end segment after a single break, not from an abnormal transverse centromere division.",
      },
    },
  ],
}
