import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Lymphatic and Macrophage System — Lymph Node",
  modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
  articleId: "ART-104-HIS-LYMPHOID-ORGANS",

  concepts: [
    {
      key: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      label: "The lymph node's cortex holds B-cell-dominant follicles and macrophage-lined sinuses around a T-cell-only paracortex, and its medulla holds B-lymphocyte cords and macrophage-lined medullary sinuses",
      definition: "The lymph node is organised into a cortex and a medulla. The cortex's outer part carries lymphatic nodules (follicles) — primary follicles of mainly B-lymphocytes with a few T-lymphocytes, and, once antigen has driven some B-lymphocytes to enlarge and aggregate, secondary follicles with a peripheral dark region of small lymphocytes around a pale germinal centre of large activated B-lymphocytes, plasma cells and a few macrophages and T-lymphocytes. Cortical (subcapsular and trabecular) lymph sinuses separate the follicles from the capsule and trabeculae and are lined by endothelial cells and macrophages, carrying B-lymphocytes, plasma cells, macrophages and a few T-cells. Between the cortex and the medulla lies the paracortex, the thymus-dependent zone: unlike the follicles and sinuses around it, it holds only T-lymphocytes, which have migrated in from the thymus through post-capillary venules lined with simple cubical epithelium (carrying receptors for T-lymphocyte homing). The medulla is medullary cords — irregular branching cords of B-lymphocytes, plasma cells and macrophages, sometimes continuous with the cortical follicles — separated by medullary sinuses, which are lined by endothelium and macrophages and filter the lymph arriving from the cortical sinuses before it leaves at the hilum.",
      objective: "Place B-lymphocytes, T-lymphocytes, plasma cells and macrophages correctly among the lymph node's cortical follicles, cortical sinuses, paracortex and medullary cords/sinuses, and identify the paracortex as the one zone that is T-lymphocytes only.",
      pitfall: "Assuming every named cortical or medullary compartment is B-lymphocyte territory. The paracortex is the one exception explicitly — it is the thymus-dependent zone, populated only by T-lymphocytes that have migrated from the thymus, with no follicle and no germinal centre of its own.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
      type: "structural_description",
      aliases: ["Lymph node cortex and medulla", "Lymphoid follicle", "Paracortex", "Thymus-dependent zone"],
    },
    {
      key: "lymph-node.capsule-trabeculae-and-stroma",
      label: "The bean- or kidney-shaped, encapsulated lymph node has a thin capsule with smooth muscle at the hilum and adipose covering, pierced by afferent lymphatics at its convex surface, with trabeculae dividing the cortex regularly and the medulla irregularly",
      definition: "The lymph node is a bean- or kidney-shaped encapsulated lymphatic organ, ranging from the size of a small bean up to an almond, found in groups along lymphatic vessels (axilla, groin, neck, thorax). It has a convex surface, which receives afferent lymphatics, and a concave surface (the hilum), where arteries enter and veins and efferent lymphatics leave. Its stroma has three components: the capsule, formed of dense irregular fibrous connective tissue and elastic fibres — thin, containing smooth muscle at the thickened hilum, covered with adipose tissue, and pierced by afferent lymphatic vessels at its convex surface; connective-tissue septa (trabeculae), extending from the capsule's deep surface, dividing the cortex into regular compartments and, on branching further into the medulla, dividing it into irregular compartments; and a reticular connective-tissue network of reticular cells and fibres forming the organ's background, more condensed where cell density is higher, staining brown with silver stain.",
      objective: "Describe the lymph node's shape and surfaces, list the three components of its stroma, and state which structure pierces the capsule where, and which part of the parenchyma the trabeculae divide regularly versus irregularly.",
      pitfall: "Assuming the trabeculae divide both cortex and medulla the same way. They divide the cortex into regular compartments but branch further into the medulla to divide it into irregular compartments — reversing which part gets the regular division is a common trap.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
      type: "structural_description",
      aliases: ["Lymph node capsule", "Lymph node shape", "Lymph node trabeculae", "Lymph node stroma"],
    },
    {
      key: "lymph-node.functions-filtration-lymphocytopoiesis-and-immunity",
      label: "The lymph node filters lymph, forms lymphocytes, and carries out both humoral immunity (B-lymphocytes to plasma cells to antibodies) and cell-mediated immunity (activated T-lymphocytes) — RBC destruction and blood-cell storage are spleen functions, not lymph node ones",
      definition: "The lymph node's functions are filtration of lymph from microorganisms and foreign bodies; formation of lymphocytes; and immunological function in two forms — humoral immunity, the activation of B-lymphocytes into plasmablasts and then plasma cells that secrete immunoglobulins (antibodies), and cell-mediated immunity, in which activated T-lymphocytes directly destroy antigen. Destruction of old red blood cells and storage of blood cells and platelets are, by contrast, functions of the spleen, not the lymph node — the department book's own comparison table lists lymph node function as 'filter lymph, humoral and cell mediated immunity' against spleen function as 'filter blood, storage of blood and immunological functions'.",
      objective: "List the lymph node's three functions (filtration of lymph, lymphocyte formation, humoral and cell-mediated immunity) and distinguish them from the spleen's functions (filtration of blood, storage, destruction of old RBCs).",
      pitfall: "Assigning a spleen function — destruction of old red blood cells, or storage of blood cells — to the lymph node. The lymph node filters lymph and mounts immune responses; it is the spleen that filters blood and destroys/stores blood cells.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
      type: "mechanism",
      aliases: ["Lymph node functions", "Lymphadenitis", "Humoral immunity", "Cell-mediated immunity"],
    },
    {
      key: "lymph-node.clinical-enlargement-lymphadenitis-and-metastasis",
      label: "Regional lymph node enlargement follows infection of the area a node drains (lymphadenitis) or malignant spread through lymphatic vessels from that area — not a blood-borne route, and not the leukaemias, which the department book does not describe as regional-enlargement causes",
      definition: "Infection in any part of the body can lead to enlarged and inflamed lymph nodes draining that area, called lymphadenitis. Malignant cells can also spread from their primary site through lymphatic vessels, causing enlargement of the regional lymph nodes; examining lymph nodes gives valuable information about the spread of the cancer. Both causes act through the local drainage relationship between a body region and its regional nodes, which is what makes the enlargement regional rather than generalised.",
      objective: "State the two causes of regional lymph node enlargement the department book names (local infection and lymphatic — not haematogenous — spread of malignancy) and why both are regional rather than generalised.",
      pitfall: "Attributing regional node enlargement to spread of cancer via the blood stream, or to leukaemia. The department book specifies spread through lymphatic vessels, not the blood stream, as the malignant route to regional nodes, and does not discuss the leukaemias as a cause of regional (as opposed to generalised) lymphadenopathy at all.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
      type: "clinical_correlation",
      aliases: ["Lymphadenitis", "Regional lymph node enlargement", "Metastasis to lymph nodes"],
    },
    {
      key: "lymphatic-organs.primary-vs-secondary-classification",
      label: "Thymus and bone marrow are the primary (central) lymphatic organs, where lymphocytes are produced — the thymus specifically producing CD4+ and CD8+ T-lymphocytes — while lymph nodes, spleen and tonsils are secondary (peripheral) organs, where mature lymphocytes mount immune responses",
      definition: "Lymphatic tissue is organised into primary (central) and secondary (peripheral) lymphatic organs. The primary organs are the thymus and bone marrow, the sites where lymphocytes are produced: the thymus is a primary lymphoid organ with an endocrine function, of double origin (mesodermal, giving lymphocytes; endodermal, giving epithelial reticular cells), whose cortex and medulla complete T-lymphocyte production and maturation, including the CD4+ and CD8+ T-lymphocyte populations, before they seed the peripheral organs. The secondary organs are the lymph nodes, spleen and tonsils, where those already-produced lymphocytes encounter antigen and mount the immune response — lymph nodes filtering lymph and carrying out humoral and cell-mediated immunity, the spleen filtering blood, and the tonsils protecting the digestive and respiratory systems' entry points.",
      objective: "Classify thymus and bone marrow as primary (central) lymphatic organs and lymph node, spleen and tonsil as secondary (peripheral) ones, and state that CD4+/CD8+ T-lymphocyte production is a primary-organ (thymic) function, not a secondary-organ one.",
      pitfall: "Placing the spleen, lymph node or tonsil among the primary lymphatic organs, or attributing a primary-organ function (production of new lymphocytes, including CD4+/CD8+ T-cells) to a secondary organ. Secondary organs act on lymphocytes already produced elsewhere; they do not produce them.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Lymph node",
      type: "classification",
      aliases: ["Primary lymphatic organs", "Secondary lymphatic organs", "Central vs peripheral lymphoid organs"],
    },
    // Pinned outside mintConceptId in docs/Kasr-Source-Imports/concept/104-CPS-mcq-concepts.md
    // (CON-HEM-594B1725902DAD) — declared here with the identical canonical_key
    // so resolveConceptId reuses that id and emits a sparse update row. Content
    // below is a summary for a seed reader's sake; the emitted label/definition
    // come from the pinned record.
    {
      key: "spleen.red-pulp-billroth-cords-and-stave-cell-sinusoids",
      label: "Splenic red pulp is Billroth cords (blood- and lymphoid-cell-infiltrated cords between the white pulps and sinusoids) and blood sinusoids lined by fenestrated stave cells",
      definition: "The spleen's red pulp is formed of splenic (Billroth) cords, present between the white pulps and blood sinusoids and infiltrated with blood cells and lymphoid cells (RBCs, granulocytes, lymphocytes, monocytes, platelets, plasma cells and macrophages), and blood sinusoids — barrel-shaped, irregular, wide blood channels lined by fenestrated elongated endothelium (stave cells) with large intercellular spaces and a noncontinuous basal lamina, an arrangement that facilitates the passage of blood from the cords into the sinusoids. Littoral cells (macrophages) sit in and around the sinusoid walls.",
      objective: "Distinguish Billroth cords (blood/lymphoid-cell-filled cords) from blood sinusoids (stave-cell-lined channels) within splenic red pulp, and state that Billroth cords belong to the spleen, not the lymph node.",
      pitfall: "Placing Billroth cords in the lymph node, or describing them as spaces between follicles rather than cell-infiltrated cords. Billroth cords are a splenic red-pulp structure with no lymph node counterpart.",
      subject: "haem",
      primary: "DIS-HIS-T02",
      secondary: [],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Spleen",
      type: "structural_description",
      aliases: ["Billroth cords", "Splenic cords", "Stave cells", "Red pulp"],
    },
    // Pinned outside mintConceptId in docs/Kasr-Source-Imports/concept/104-CPS-mcq-concepts.md
    // (CON-HEM-D1628423BE0844) — same reuse mechanism as above.
    {
      key: "mononuclear-phagocyte-system.definition-origin-and-distribution",
      label: "Every cell of the mononuclear phagocyte system differentiates from a blood monocyte, takes up a vital stain, and shares a histological signature of irregular pseudopodial surfaces, prominent Golgi/rER and an eccentric kidney-shaped nucleus",
      definition: "The macrophage system, or mononuclear phagocytic system, is distributed by site under separate names: monocytes in blood; macrophages (histiocytes) in loose connective tissue and in the reticular stroma of bone marrow, spleen and lymph node; littoral cells in the walls of blood sinusoids of spleen and bone marrow; von Kupffer cells in the liver's blood sinusoids; Langerhans cells in the skin; microglia in the CNS; dust cells and heart-failure cells in lung alveoli; and osteoclasts in bone's Howship's lacunae. All differentiate from blood monocytes and share a histological signature: irregular pseudopodial surfaces, a well-developed Golgi complex, many lysosomes, prominent rough endoplasmic reticulum, and an eccentric oval or kidney-shaped nucleus.",
      objective: "Name the mononuclear phagocyte system's site-specific cell name at each of its eight listed locations, and identify littoral cells as the name used specifically in spleen and bone marrow sinusoids.",
      pitfall: "Treating the eight named cell types as eight separate lineages rather than one monocyte-derived lineage under site-specific names, or assigning 'littoral cell' to a site other than spleen/bone marrow sinusoids.",
      subject: "haem",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-HEM"],
      modulePath: "104 CPS > Histology > Lymphatic and Macrophage System > Macrophage System",
      type: "structural_description",
      aliases: ["Mononuclear phagocyte system", "Macrophage system", "Littoral cells"],
    },
    // Pinned outside mintConceptId in docs/Kasr-Source-Imports/concept/104-CPS-mcq-concepts.md
    // (CON-RES-7C79F2D68F1003) — same reuse mechanism as above.
    {
      key: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      label: "Intrapulmonary bronchi keep bronchial epithelium but move their cartilage plates, mucoserous glands and lymphatic nodules into the adventitia, between the cartilage plates, unlike extrapulmonary bronchi (submucosal glands/nodules) or bronchioles (none of the three)",
      definition: "Extrapulmonary bronchi are structurally identical to the trachea: pseudostratified ciliated epithelium rich in goblet cells, an elastic membrane separating mucosa from submucosa, a true submucosa carrying mucoserous glands and lymphatic nodules, and incomplete C-shaped hyaline cartilage rings. Intrapulmonary (secondary) bronchi keep the same epithelium with fewer goblet cells, lose the elastic membrane and submucosa as distinct layers, replace the cartilage rings with multiple plates of hyaline cartilage in the adventitia, and carry their mucoserous glands and lymphatic nodules in the adventitia, between those cartilage plates. Bronchioles carry none of these: no cartilage plate, no mucoserous gland, no lymphatic nodule, with simple columnar/cuboidal ciliated epithelium and Clara cells instead.",
      objective: "State where an intrapulmonary bronchus's mucoserous glands and lymphatic nodules sit (the adventitia, between cartilage plates), against the submucosal location in an extrapulmonary bronchus and their complete absence in a bronchiole.",
      pitfall: "Assuming an intrapulmonary bronchus keeps a submucosa the way the trachea and extrapulmonary bronchus do. It does not — the submucosa and elastic membrane are lost as distinct layers, and the glands/nodules that submucosa once held move into the adventitia instead.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: [],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structural_description",
      aliases: ["Intrapulmonary bronchus", "Extrapulmonary bronchus", "Bronchiole", "Clara cells"],
    },
  ],

  questions: [
    {
      key: "all-contain-b-lymph-except-with-t-lymphocyte-cafe31f9",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the paracortex as the lymph node's one zone that carries only T-lymphocytes, against the B-lymphocyte-carrying follicles, sinuses and medullary cords around it.",
      explanations: {
        A: "Contains B-lymphocytes, so not the exception. A primary follicle is formed mainly of B-lymphocytes with a few T-lymphocytes.",
        B: "Contains B-lymphocytes, so not the exception. A secondary follicle's germinal centre carries large activated B-lymphocytes and plasma cells, alongside macrophages and a few T-lymphocytes.",
        C: "Contains B-lymphocytes, so not the exception. The medullary cords are B-lymphocytes, plasma cells and macrophages — no zone of the medulla is T-cell only.",
        D: "The exception, and the true answer. The paracortex is the thymus-dependent zone: unlike the follicles, sinuses and cords around it, it carries only T-lymphocytes, which have migrated in from the thymus through post-capillary venules. A common trap: assuming every named cortical or medullary compartment is B-lymphocyte territory.",
      },
      answerOverride: "D",
      answerOverrideReason: "The extracted key (C, medullary cords) contradicts the book. Histology department book p16-17: medullary cords are explicitly 'B-lymphocytes, plasma cells and macrophages' — a B-lymphocyte-carrying compartment, not the T-only exception the stem asks for. The paracortex (p16) is the T-lymphocyte-only zone ('the thymus dependant zone... it contains T-lymphocytes which have migrated from thymus'), which is the structure the stem is actually describing.",
    },
    {
      key: "have-peripheral-dark-small-lymph-with-germinal-center-that-h-cd96123a",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Recognise the secondary follicle by its peripheral dark small-lymphocyte region around a germinal centre of large B-lymphocytes, with few T-lymphocytes.",
      explanations: {
        A: "A primary follicle has no germinal centre at all — it is formed of aggregated cells, mainly B-lymphocytes, before antigen exposure produces the germinal centre the stem describes.",
        B: "The secondary follicle exactly this way: peripheral dark regions of small lymphocytes around a pale germinal centre containing large activated B-lymphocytes and plasma cells, with macrophages and a few T-lymphocytes. A common trap: assuming every named cortical or medullary compartment is B-lymphocyte territory.",
        C: "A cortical sinus is a lymph-filled space lined by endothelium and macrophages, not a lymphocyte aggregation with a germinal centre.",
        D: "The paracortex has no germinal centre and no B-lymphocytes at all — it is the thymus-dependent zone of T-lymphocytes only, the opposite of the structure the stem describes.",
      },
      answerOverride: "B",
      answerOverrideReason: "The printed key (D, paracortex) contradicts the book. Histology department book p16 gives this exact description — peripheral dark small lymphocytes around a germinal centre of large activated B-lymphocytes, with few T-lymphocytes — as the secondary lymphatic nodule (follicle). The paracortex (also p16) is described as containing only T-lymphocytes with no germinal centre and no B-lymphocyte population at all, so it cannot be what the stem is describing.",
    },
    {
      key: "is-lined-by-endothelium-macrophage-d15029d8",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Recognise that both the lymph node's cortical (subcapsular and trabecular) sinuses and its medullary sinuses share an endothelium-and-macrophage lining.",
      explanations: {
        A: "True of the trabecular sinus, so not a wrong option on its own — but it is only one of the sinus types this lining, not the single correct answer to a question with 'all the above' available.",
        B: "True of the medullary sinus too, for the same reason — correct as far as it goes, but not the most complete answer available.",
        C: "True of the subcapsular sinus as well — again correct but partial, since this same lining to more than one sinus type.",
        D: "The cortical lymph sinuses — both subcapsular and trabecular — are lined with endothelial cells and macrophages, and separately the medullary sinuses are lined with endothelium and macrophages. All three named sinus types share this lining, so 'all the above' is the actual answer.",
      },
      answerOverride: "D",
      answerOverrideReason: "The printed key (C, subcapsular sinus alone) understates what the book says. Histology department book p16 states the cortical lymph sinuses (which it explicitly defines as both subcapsular and trabecular) are 'lined with endothelial cells and macrophages,' and p17 states the medullary sinuses are 'lined with endothelium and macrophages' in the same words. Since all three named sinuses (trabecular, medullary, subcapsular) get the identical lining, without singling one out, 'all the above' is the answer consistent with the source, not one sinus alone.",
    },

    // --- kasr-104-author-run38: Lymph node cluster (17 remaining keys) ---

    {
      key: "all-characters-of-lymph-node-capsule-except-95568569",
      conceptKey: "lymph-node.capsule-trabeculae-and-stroma",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the capsule's trabeculae divide the cortex regularly and the medulla irregularly, not the reverse.",
      explanations: {
        A: "True, so not the exception. The capsule contains smooth muscle at the thickened hilum.",
        B: "True, so not the exception. The capsule is covered with adipose tissue.",
        C: "True, so not the exception. Afferent lymphatic vessels pierce the capsule's convex surface.",
        D: "The exception, and the answer. Trabeculae divide the cortex into regular compartments and, branching further into the medulla, divide it into irregular compartments — the reverse of what this option states (irregular cortex, regular medulla). The regularly-arranged cortical follicles sit inside those regular compartments, while the medullary cords wind irregularly through theirs.",
      },
      answerOverride: "D",
      answerOverrideReason: "The printed key (B) contradicts the book, which states the capsule is 'covered with adipose tissue' as a plain fact, not an exception. Histology department book p15-16 states trabeculae 'divide the cortex into regular compartments' and, branching in the medulla, 'divide it into irregular compartments' — option D reverses this (irregular cortex, regular medulla), making it the one statement that does not match the source.",
    },
    {
      key: "all-functions-of-lymph-node-except-4faf6247",
      conceptKey: "lymph-node.functions-filtration-lymphocytopoiesis-and-immunity",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Distinguish the lymph node's own functions from the spleen's function of destroying old red blood cells and forming blood elements.",
      explanations: {
        A: "True, so not the exception. Filtration of lymph from microorganisms and bacteria is a stated lymph node function.",
        B: "True, so not the exception. Formation of lymphocytes, including in the germinal centre where B-lymphocytes proliferate on antigen exposure, is a stated lymph node function.",
        C: "The exception, and the answer. Destruction of old red blood cells and formation of blood elements are spleen functions in this book, not lymph node ones — the lymph node's own list is filtration, lymphocyte formation, and humoral/cell-mediated immunity. The comparison table contrasts the two organs on exactly this point: the lymph node filters lymph and mounts immunity, while the spleen filters blood and handles blood-cell turnover.",
        D: "True, so not the exception. Humoral immunity (B-lymphocytes to plasma cells to antibodies) and cell-mediated immunity (activated T-lymphocytes) are both stated lymph node functions.",
      },
      answerOverride: "C",
      answerOverrideReason: "The printed key (B) contradicts the book, which states germinal-centre lymphocyte formation as a plain lymph node function, not an exception. Histology department book p17-18 lists the lymph node's functions as filtration, lymphocyte formation, and humoral/cell-mediated immunity, while p20's comparison table assigns 'destruction of old RBCs' and blood-cell storage/formation to the spleen specifically — making option C the one function this book does not credit to the lymph node.",
    },
    {
      key: "choose-the-correct-statement-about-billroth-cords-aa93a7fb",
      conceptKey: "spleen.red-pulp-billroth-cords-and-stave-cell-sinusoids",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that Billroth cords are infiltrated with blood cells, against distractors describing lymph node stroma or white pulp features.",
      explanations: {
        A: "Billroth cords are a splenic red-pulp structure, found between the white pulps and blood sinusoids of the spleen — not in the stroma of lymph nodes, which have no Billroth cords at all.",
        B: "Correct. Billroth cords are infiltrated with blood cells and lymphoid cells — RBCs, granulocytes, lymphocytes, monocytes, platelets, plasma cells and macrophages. That mixed cellular filling is what lets red-pulp cords act as a checkpoint where the spleen inspects and, when needed, removes ageing or abnormal blood cells.",
        C: "The spaces between secondary lymphatic follicles are not Billroth cords; Billroth cords are themselves cell-infiltrated cords, not empty spaces, and they sit between white pulp and blood sinusoids, not between follicles.",
        D: "The central arteriole is a white-pulp feature (running through the Malpighian corpuscle), not a feature of Billroth cords, which belong to the red pulp.",
      },
    },
    {
      key: "choose-the-correct-statement-about-lymph-node-functions-79a10886",
      conceptKey: "lymph-node.functions-filtration-lymphocytopoiesis-and-immunity",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify lymphocyte formation and recirculation as a lymph node function, against blood-filtration/storage functions that belong to the spleen.",
      explanations: {
        A: "Correct. The lymph node forms lymphocytes and, through the paracortex's post-capillary venules, participates in T-lymphocyte recirculation from the thymus. This recirculation is what lets already-produced T-lymphocytes patrol repeatedly through the peripheral lymphoid tissue rather than passing through only once.",
        B: "Filtration of blood is a spleen function; the lymph node filters lymph, not blood.",
        C: "Formation of blood platelets is not a lymph node function in this book.",
        D: "Storage of blood cells is a spleen function (the spleen is a blood reservoir), not a lymph node one.",
      },
    },
    {
      key: "choose-the-correct-statement-about-the-lymph-node-8ca055b5",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that afferent lymphatic vessels enter the lymph node at the convex surface, against distractors describing reversed lymph flow, spleen terminology or an incorrect sinus lining.",
      explanations: {
        A: "Lymph circulates the opposite way: from the cortical (subcapsular and trabecular) sinuses to the medullary sinuses, not from medullary to cortical.",
        B: "Littoral cells are the macrophage-system name used specifically in spleen and bone marrow sinusoid walls; the lymph node's sinuses are lined by endothelial cells and macrophages, not cells named littoral cells in this book.",
        C: "Correct. Afferent lymph vessels pierce and enter the lymph node through its convex surface; efferent vessels and blood vessels use the concave hilum instead. This one-way traffic pattern — lymph entering broadly across the convex surface and leaving concentrated at the hilum — is what lets the node filter every drop of lymph passing through it.",
        D: "White and red pulp are spleen terminology; the lymph node's parenchyma is organised into cortex and medulla instead.",
      },
    },
    {
      key: "choose-the-correct-statement-about-the-lymph-node-a-lymph-ci-76fd16cb",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the paracortex as the deep cortical zone containing only T-lymphocytes.",
      explanations: {
        A: "As printed, this option is an uninterpretable extraction fragment ('T-suppressor and an antibody') rather than a coherent statement about the lymph node, and so cannot be the correct answer regardless of how it is read.",
        B: "Littoral cells line spleen and bone marrow sinusoids in this book's naming, not lymph node lymphatic sinuses, which are lined by endothelial cells and macrophages instead.",
        C: "Efferent lymphatic vessels drain the lymph node through the concave surface (the hilum), not the convex surface — the convex surface is where afferent vessels enter.",
        D: "Correct. The paracortex lies between the cortex's outer follicles and the medulla — deep to the outer cortex — and, unlike every surrounding zone, contains only T-lymphocytes, which have migrated in from the thymus. No germinal centre or B-lymphocyte population forms here, which is what makes it the one exception among the lymph node's named compartments.",
      },
    },
    {
      key: "concerning-the-billroth-cords-the-following-is-true-775e83c5",
      conceptKey: "spleen.red-pulp-billroth-cords-and-stave-cell-sinusoids",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that Billroth cords contain WBCs and RBCs, against distractors describing lymph node location or follicle types.",
      explanations: {
        A: "Billroth cords are present in the spleen's red pulp, not in the lymph node, which has no Billroth cords at all.",
        B: "A primary lymph follicle is a B-lymphocyte-dominant lymphatic nodule, not a Billroth cord — cords and follicles are different structures within different pulps of the spleen.",
        C: "A secondary lymph follicle is likewise a lymphatic nodule with a germinal centre, not a Billroth cord.",
        D: "Correct. Billroth cords are infiltrated with blood cells — RBCs, granulocytes, monocytes, platelets — alongside lymphoid cells such as lymphocytes, plasma cells and macrophages. This mixed filling is what distinguishes the red pulp's cords from the white pulp's purely lymphoid follicles.",
      },
    },
    {
      key: "concerning-the-paracortex-of-lymph-node-choose-the-correct-s-b9c8b9f2",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the paracortex's post-capillary venules are lined with simple cubical epithelium.",
      explanations: {
        A: "White pulp and Billroth cords are spleen terms, not lymph node ones; the paracortex is a lymph node zone lying between the cortex's follicles and the medulla, with no white-pulp or Billroth-cord neighbour to speak of.",
        B: "The paracortex is the one zone that contains only T-lymphocytes, not B-lymphocytes — B-lymphocytes belong to the surrounding follicles instead.",
        C: "Correct. The paracortex's post-capillary venules — through which T-lymphocytes migrate in from the thymus — are lined with simple cubical epithelium, which carries receptors for T-lymphocyte homing. This is a departure from the flatter endothelium lining most small vessels, and it is exactly what lets circulating T-lymphocytes recognise and cross into the paracortex.",
        D: "The paracortex is not 'lined' by anything; that phrasing fits a sinus, and the paracortex is a lymphocyte-populated zone, not a lined space.",
      },
    },
    {
      key: "identify-the-following-organ-choose-the-correct-statement-bd5813e3",
      conceptKey: "lymphatic-organs.primary-vs-secondary-classification",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify CD4+/CD8+ T-lymphocyte production as a primary lymphoid organ (thymic) function, against statements describing secondary-organ functions.",
      explanations: {
        A: "Antibody production is carried out in secondary lymphoid organs such as the lymph node (via humoral immunity), not in a primary organ producing lymphocytes.",
        B: "Red blood cell degradation and bilirubin recycling is a spleen (secondary organ) function, not a function of an organ that produces lymphocytes.",
        C: "Having both afferent and efferent lymphatic vessels describes the lymph node specifically; a primary lymphoid organ such as the thymus has no afferent lymphatics at all.",
        D: "Correct. Production of CD4+ and CD8+ T-lymphocytes is a primary lymphoid organ's role — the thymus completes T-lymphocyte production and maturation before these cells seed the secondary (peripheral) organs. None of the secondary organs (lymph node, spleen, tonsil) make new lymphocytes; they only act on the ones the thymus and bone marrow have already supplied.",
      },
    },
    {
      key: "in-intrapulmonary-bronchi-muco-serous-lymphatic-nodule-prese-63a9f274",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that an intrapulmonary bronchus's mucoserous glands and lymphatic nodules sit in the adventitia, between the cartilage plates.",
      explanations: {
        A: "The mucosa is the epithelial lining and its immediate lamina propria; it is the extrapulmonary bronchus (and trachea) whose elastic membrane sits just deep to the mucosa, not the site of the intrapulmonary bronchus's glands and nodules.",
        B: "The submucosa, present in the extrapulmonary bronchus, is lost as a distinct layer in the intrapulmonary bronchus — its glands and nodules move to the adventitia instead, not the (absent) submucosa.",
        C: "The musculosa (smooth muscle layer) is spirally arranged in the intrapulmonary bronchus but does not carry the mucoserous glands or lymphatic nodules.",
        D: "Correct. In the intrapulmonary bronchus, mucoserous glands and lymphatic nodules sit in the adventitia, between the cartilage plates — unlike the extrapulmonary bronchus, where they sit in the submucosa. This relocation tracks the loss of the submucosa and elastic membrane as distinct layers once the bronchus enters the lung.",
      },
    },
    {
      key: "is-bean-or-kidney-shaped-with-capsule-a9e2e5ba",
      conceptKey: "lymph-node.capsule-trabeculae-and-stroma",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "State that the lymph node, not the spleen, is described as bean- or kidney-shaped.",
      explanations: {
        A: "Correct. The lymph node is described as bean- or kidney-shaped, an encapsulated lymphatic organ found along lymphatic vessels. Its size ranges from a small bean up to an almond, and it presents a convex surface for afferent lymphatics and a concave hilum for its vessels.",
        B: "The spleen is described as the large single intra-abdominal hemolymphatic organ, not by a bean or kidney shape — that description is reserved for the lymph node in this book.",
        C: "The tonsil is an incompletely encapsulated aggregation of lymphatic tissue, not a fully encapsulated, bean-shaped organ.",
        D: "The liver is not a lymphatic organ and is not described this way in this chapter.",
      },
      answerOverride: "A",
      answerOverrideReason: "The printed key (B, spleen) contradicts the book. Histology department book p15 states of the lymph node specifically: 'Shape: bean or kidney shaped encapsulated lymphatic organs along lymphatic vessels.' The spleen's own structure section (p18) describes it only as 'the large single intra-abdominal hemolymphatic organ' — no bean/kidney description appears anywhere in the spleen's entry, so the printed key does not match the source and A is used instead.",
    },
    {
      key: "regarding-lymph-node-which-answer-is-correct-821e3545",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that differentiated T-lymphocytes reach the lymph node through post-capillary venules, against distractors naming an epithelial covering, RBC storage or an all-B paracortex.",
      explanations: {
        A: "The lymph node is not covered by an epithelium; its outer boundary is the connective-tissue capsule, not simple columnar epithelium.",
        B: "Storage of RBCs is a spleen function, not a lymph node one — the lymph node filters lymph and mounts immune responses rather than storing blood cells.",
        C: "Correct. Differentiated (thymus-matured) T-lymphocytes reach the lymph node's paracortex by migrating through post-capillary venules, which are lined with simple cubical epithelium carrying homing receptors for them. This route is what continually restocks the paracortex with T-lymphocytes as they recirculate around the body's lymphoid tissue.",
        D: "The paracortex contains only T-lymphocytes, not only B-lymphocytes — B-lymphocytes belong to the surrounding cortical follicles instead.",
      },
    },
    {
      key: "regarding-the-germinal-center-in-lymph-node-2a8628a2",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the germinal centre contains large activated lymphocytes, against distractors placing it in the wrong compartment or misdescribing its cell population.",
      explanations: {
        A: "The germinal centre is found in the secondary lymphatic nodule (follicle) itself, not in the cortical lymph sinus, which is a separate, endothelium-and-macrophage-lined space.",
        B: "The germinal centre carries large activated B-lymphocytes, plasma cells and only a few T-lymphocytes — not only T-lymphocytes, which is the paracortex's population instead.",
        C: "The germinal centre does contain plasma cells (with pale nuclei), alongside large activated B-lymphocytes and a few macrophages and T-lymphocytes.",
        D: "Correct. The germinal centre is a pale central region containing large activated B-lymphocytes, along with plasma cells, macrophages and a few T-lymphocytes. It is this large-cell population that gives the germinal centre its pale appearance against the darker, small-lymphocyte rim surrounding it.",
      },
    },
    {
      key: "regional-enlargement-of-lymph-nodes-may-be-due-to-68fe188c",
      conceptKey: "lymph-node.clinical-enlargement-lymphadenitis-and-metastasis",
      difficulty: "Moderate",
      questionType: "Clinical correlation",
      learningObjective: "State that regional lymph node enlargement follows local infection (lymphadenitis) or lymphatic (not haematogenous) spread of malignancy, distinguishing both from the leukaemias.",
      explanations: {
        A: "Correct. Infection in any part of the body can lead to enlarged and inflamed lymph nodes draining that area — lymphadenitis — matching the book's own statement of this cause almost verbatim. This local drainage relationship is exactly why the enlargement is regional rather than affecting nodes throughout the body.",
        B: "The book specifies that malignant cells spread to regional nodes through lymphatic vessels, not through the blood stream; a blood-borne route would tend to produce distant metastases rather than enlargement specifically of the nodes draining the primary site.",
        C: "Acute leukaemia is not discussed in this book as a cause of regional (as opposed to generalised) lymph node enlargement; leukaemic lymphadenopathy is typically generalised, arising from disease in the blood and bone marrow rather than from a single drained region.",
        D: "Chronic leukaemia, like acute leukaemia, is not discussed in this book as a cause of regional lymph node enlargement, and leukaemic lymphadenopathy is characteristically generalised rather than confined to one drainage area.",
      },
      answerOverride: "A",
      answerOverrideReason: "The printed key (C, acute leukaemia) is not supported by the book. Histology department book p18's read-only topic names exactly two causes of regional lymph node enlargement — local infection ('Infection in any part of body, can lead to enlarged and inflammed lymph nodes draining that area, which is called Lymphadenitis') and malignant spread specifically 'through lymphatic vessels' — and does not mention the leukaemias at all. Option A restates the book's own infection cause almost verbatim; option B misstates the malignant route as haematogenous rather than lymphatic; C and D (the leukaemias) have no support in this source, so A is used instead of the printed C.",
    },
    {
      key: "the-germinal-center-of-secondary-lymphatic-nodules-contain-m-7128bcbf",
      conceptKey: "lymph-node.cortex-medulla-zones-and-cell-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the germinal centre of a secondary lymphatic nodule contains large activated B-lymphocytes.",
      explanations: {
        A: "Small B-lymphocytes populate the peripheral dark region of the secondary nodule surrounding the germinal centre, not the germinal centre's own pale central area.",
        B: "The germinal centre carries only a few T-lymphocytes, not numerous ones — T-lymphocytes are the dominant population of the paracortex instead.",
        C: "Correct. The germinal centre of a secondary lymphatic nodule contains many large activated B-lymphocytes (plus plasma cells, macrophages and a few T-lymphocytes). Their presence is what marks the transformation of a primary nodule into a secondary one following antigen exposure.",
        D: "Erythrocytes are not a described population of the lymph node's germinal centre; RBC-related content belongs to the spleen's red pulp instead.",
      },
    },
    {
      key: "the-primary-lymphatic-organs-include-1a970a71",
      conceptKey: "lymphatic-organs.primary-vs-secondary-classification",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "Name bone marrow (with the thymus) as a primary lymphatic organ, against the secondary organs spleen, lymph node and tonsil.",
      explanations: {
        A: "Correct. Bone marrow is, with the thymus, one of the two primary (central) lymphatic organs. Lymphocytes produced there seed the secondary organs — lymph node, spleen and tonsil — where they later mount immune responses.",
        B: "The spleen is a secondary (peripheral) lymphatic organ, not a primary one.",
        C: "The lymph node is a secondary (peripheral) lymphatic organ, not a primary one.",
        D: "The tonsil is a secondary (peripheral) lymphatic organ, not a primary one.",
      },
    },
    {
      key: "which-cell-considered-as-a-part-of-the-phagocytic-system-325b83f1",
      conceptKey: "mononuclear-phagocyte-system.definition-origin-and-distribution",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify littoral cells as the mononuclear phagocyte system's name for macrophages in spleen and bone marrow sinusoid walls.",
      explanations: {
        A: "Reticular epithelial cells are the thymus's endoderm-derived stromal cells, not part of the monocyte-derived mononuclear phagocyte system.",
        B: "Activated B-lymphocytes are antibody-producing cells of the adaptive immune system, not phagocytic cells of the monocyte-derived lineage.",
        C: "Correct. Littoral cells are the mononuclear phagocyte system's macrophages in the walls of blood sinusoids of the spleen and bone marrow. Like every member of this system, they differentiate from blood monocytes and share the family's phagocytic, pseudopodia-bearing appearance.",
        D: "Merkel's cells are epidermal mechanoreceptor cells, not part of the monocyte-derived mononuclear phagocyte system's list of site-specific names.",
      },
    },
  ],
}
