import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Physiology Respiratory System — Non-Chemical Control of Respiration",
  modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
  articleId: "ART-104-PHY-RESPIRATORY-CENTERS-AND-CHEMORECEPTORS",

  concepts: [
    {
      key: "non-chemical-nervous-regulation-of-respiration.afferent-sources",
      label: "Non-chemical (nervous) regulation of respiration works through reflex afferents from higher centres, the upper airway, the lungs, the chest wall, proprioceptors and the cardiovascular system, distinct from the chemical (PCO2/pH/PO2) drive",
      definition: "Alongside the chemical control of breathing by PCO2, pH and PO2, the respiratory centre is regulated by nervous reflexes that are independent of blood gases. Afferents from higher centres carry voluntary control from the cerebral cortex (talking, singing, voluntary apnoea/breath-holding, ended by the 'break point' when rising PCO2 and falling PO2 become overwhelming), pain and emotion from the limbic system, and temperature from the hypothalamus. Afferents from upper airway receptors give the coughing reflex (irritant receptors in trachea/larynx/bronchi, vagal afferents, forced expiration against a closed then suddenly opened glottis) and the sneezing reflex (irritant receptors in nasal mucosa, trigeminal afferents, glottis stays open). Afferents from lung receptors give the Hering-Breuer stretch reflex and the lung irritant reflex (coughing, bronchospasm). Afferents from chest wall muscle spindles set tidal volume; afferents from proprioceptors drive the ventilation rise of exercise. Afferents from the cardiovascular system carry the arterial baroreceptor reflex (a rise in arterial pressure inhibits the respiratory centre) and the atrial stretch-receptor reflex (a rise in venous return stimulates it, Harrison's reflex). Visceral reflexes give swallowing apnoea and hiccup.",
      objective: "List the non-chemical (nervous) sources of respiratory drive by their afferent pathway — higher centres, upper airway, lung, chest wall, proprioceptors, cardiovascular system, visceral reflexes — and distinguish each from the chemical (PCO2/pH/PO2) control of breathing.",
      pitfall: "Treating hypercapnia (a rise in arterial PCO2) as one item on the non-chemical list. PCO2 is the major controller of respiration through central and peripheral chemoreceptors — the chemical route — and it sits in a separate section from 'Non-Chemical (Nervous) Regulation of Respiratory Activity'. Coughing, swallowing and pain, by contrast, are genuinely nervous reflexes filed under the non-chemical heading.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
      type: "mechanism",
      aliases: ["Nervous regulation of respiration", "Non-chemical control of breathing"],
    },
    // The next three concepts already exist as hand-authored, pinned records in
    // `docs/Kasr-Source-Imports/concept/104-CPS-physiology-concepts.md` (not
    // `GENERATED_BY`, so `existingConceptIds()` in build-batches.ts does see
    // them): CON-RES-A54FECB95CBEBC, CON-RES-C6F65BAAC06FAA and
    // CON-RES-B68E39C6B4178F, all already `article_ids`/`related_concepts`-
    // linked to this leaf's own ART-104-PHY-RESPIRATORY-CENTERS-AND-
    // CHEMORECEPTORS. Declaring them here with the identical canonical_key
    // makes `resolveConceptId` resolve to the pinned id and emit a sparse
    // reuse row (label restated verbatim from the pinned record, only
    // exam_signal + article_ids added) — never a duplicate full mint. Content
    // below matches the pinned records for a seed reader's sake; the actual
    // emitted label/definition/etc. always come from the pinned file.
    {
      key: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      label: "The dorsal respiratory group drives normal quiet breathing alone, the ventral respiratory group activates only for forced breathing, and the pontine apneustic and pneumotaxic centres tune the medullary rhythm rather than generating it",
      definition: "The respiratory centre is a bilateral collection of inspiratory and expiratory neurons in the pons and medulla, reciprocally inhibiting each other, with basic rhythm generated by pacemaker neurons in the medullary pre-Botzinger complex. The dorsal respiratory group (DRG, in and around the nucleus of the tractus solitarius) is the primary inspiratory centre: it fires continuous rhythmic signals to the inspiratory muscles during normal quiet breathing and has its own slow, irregular inherent rhythmicity, finely tuned by the pontine centres. The ventral respiratory group (VRG, around the nucleus ambiguus) carries both inspiratory and expiratory neurons but is totally inactive during quiet breathing, activating only during forced breathing. Two pontine centres regulate the medulla: the apneustic centre (lower pons) sends tonic excitatory drive to the DRG and, if it loses its own inhibitory input, produces apneusis (prolonged inspiratory gasps); the pneumotaxic centre (upper pons) sends inhibitory signals to the DRG and apneustic centre, switching off inspiration and starting expiration, thereby setting the rate and depth of breathing.",
      objective: "Name the four groups of the respiratory centre (DRG, VRG, apneustic centre, pneumotaxic centre), state their correct medullary/pontine locations and which is active during quiet versus forced breathing, and explain what apneustic breathing reveals about the apneustic centre's role.",
      pitfall: "Reversing the two pontine centres' locations or roles — the apneustic centre (lower pons) excites the DRG and, unopposed, prolongs inspiration; the pneumotaxic centre (upper pons) inhibits the DRG and apneustic centre and limits inspiration. Swapping either the location or the excitatory/inhibitory direction is the commonest way this topic is mis-answered.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
      type: "mechanism",
      aliases: ["DRG and VRG", "Brainstem respiratory centres", "Apneustic and pneumotaxic centres", "Dorsal and ventral respiratory groups"],
    },
    {
      key: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      label: "Central chemoreceptors provide 75-80% of resting respiratory drive, responding to CSF H+ generated when CO2 (not H+ itself) crosses the blood-brain barrier, while peripheral chemoreceptors provide the remaining 20-25%, monitoring arterial PO2 directly and switching on sharply only once PO2 falls below about 60 mmHg",
      definition: "Central (medullary) chemoreceptors, just beneath the ventral medullary surface and protected by the blood-brain barrier, provide about 75-80% of resting respiratory drive; their direct stimulus is H+ in the CSF, which plasma H+ cannot reach, so CO2 stimulates them only indirectly, by crossing the barrier freely and lowering CSF pH. Peripheral chemoreceptors (carotid bodies via the glossopharyngeal nerve, aortic bodies via the vagus) provide the remaining 20-25% of drive; their very high blood flow lets them sense dissolved PO2 directly rather than O2 content, so they are unaffected by anaemia or carbon monoxide poisoning, and they are almost insensitive to a PO2 fall from 100 to 60 mmHg before responding steeply as PO2 falls further. CO2 is overall the most potent respiratory stimulus: a 3% rise in arterial PCO2 can double ventilation, mostly through the central route, while a marked rise above about 70 mmHg instead depresses the respiratory centre (CO2 narcosis).",
      objective: "State the approximate drive contribution of central versus peripheral chemoreceptors, explain why central chemoreceptors respond to CSF H+ but are driven mainly by CO2 rather than plasma H+, describe the peripheral chemoreceptors' anatomical location and afferent pathway, and state the threshold and mechanism of CO2 narcosis.",
      pitfall: "Assuming central chemoreceptors respond to plasma H+ or O2 directly, or assuming O2 lack is the everyday respiratory stimulus the way CO2 is. Central chemoreceptors respond only to H+ generated locally in the CSF — the blood-brain barrier excludes plasma H+ and O2 changes — and peripheral chemoreceptors only become the dominant drive once PO2 falls well below its resting value.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
      type: "mechanism",
      aliases: ["Central chemoreceptors (respiratory)", "Peripheral chemoreceptors (respiratory)", "CO2 narcosis", "Carotid and aortic bodies"],
    },
    {
      key: "hering-breuer-reflex.pulmonary-stretch-receptors",
      label: "The Hering-Breuer reflex — lung stretch receptors signalling through the vagus to inhibit the DRG and apneustic centre and switch off inspiration — matters little in resting adult breathing but engages once tidal volume triples, as in exercise",
      definition: "The Hering-Breuer reflex is triggered by lung inflation acting on stretch receptors in the walls of the bronchi and bronchioles, which send inhibitory afferent signals through the vagus nerve to the DRG and apneustic centre, stopping inspiration and starting expiration. In newborn infants it adjusts the normal rate and depth of every breath; in human adults it is important only at high rates and depths of breathing, when tidal volume rises to more than three times normal, as in exercise, functioning as a protective brake against over-expanding the lungs.",
      objective: "State the stimulus, receptor, afferent pathway and response of the Hering-Breuer reflex, and explain why it matters in the newborn but not at rest in the adult.",
      pitfall: "Assuming the Hering-Breuer reflex is a major regulator of every resting adult breath. In adults it is essentially silent at normal tidal volumes and only engages once tidal volume rises well above normal, unlike in the newborn where it shapes ordinary quiet breathing.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
      type: "mechanism",
      aliases: ["Hering-Breuer inflation reflex", "Pulmonary stretch reflex"],
    },
    // run44 — this leaf's own 10-row "what's left" recompute
    // (docs/Kasr-Source-Imports/coverage/104-CPS-LEDGER.md). find-
    // existing.mjs "brainstem transection breathing levels" — 0 hits,
    // fresh mint. This article's own evidence_gaps previously said
    // brainstem-transection evidence "was not reached", but it sits on
    // p.142 of the department book, squarely inside the article's already-
    // cited 136-147 page range — re-checked directly and read cleanly (see
    // the article's own updated evidence_basis note).
    {
      key: "brainstem-transection.effect-on-breathing-by-level",
      label: "Transecting the brainstem at four successively lower levels shows breathing is unaffected until the pontine centres are progressively removed (irregular by level 3), and stops completely only when level 4 disconnects the medulla from the spinal respiratory motor neurons entirely",
      definition: "Level 1 (upper border of the pons, above both pontine centres): respiration is unaffected, since every respiratory centre below the cut is intact; adding bilateral vagotomy at this level makes breathing slower and deeper, showing vagal (Hering-Breuer) afferents normally help set tidal volume and rate. Level 2 (mid-pons, between the pneumotaxic and apneustic centres): breathing becomes slightly slower and deeper, confirming the pneumotaxic centre's role in adjusting rate and depth; adding bilateral vagotomy at this level removes the apneustic centre's only remaining source of inhibition, and breathing stops in full inspiration — apneusis. Level 3 (between pons and medulla, removing both pontine centres): respiration continues, but irregularly, on the DRG's own crude intrinsic rhythm alone. Level 4 (between medulla and the upper border of the spinal cord): respiration stops completely, leading to death, because the DRG/VRG are entirely disconnected from the phrenic and intercostal motor neurons that actually drive breathing — clinically equivalent to a high cervical cord or brainstem injury above the phrenic outflow (C3-C5), unlike a lower injury (e.g. below C7) which spares diaphragmatic breathing.",
      objective: "State what each of the four brainstem transection levels does to breathing, with and without added vagotomy, and identify level 4 as the only one that stops breathing completely.",
      pitfall: "Assuming any brainstem transection stops breathing, or that vagotomy or a mid-pontine cut alone (rather than both together) produces apneusis. Only level 4 (medulla-to-spinal-cord) stops breathing outright; apneusis at level 2 needs BOTH the pneumotaxic-centre cut AND vagotomy, since either one alone still leaves an inhibitory input reaching the apneustic centre.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Control of Respiration",
      type: "mechanism",
      aliases: ["Brainstem transection levels", "Apneusis experiment", "Level 4 transection", "Spinal cord transection and breathing"],
    },
  ],

  questions: [
    {
      key: "non-chemical-influence-on-respiration-includes-all-of-the-fo-3dfb369c",
      conceptKey: "non-chemical-nervous-regulation-of-respiration.afferent-sources",
      difficulty: "Moderate",
      questionType: "Classification",
      learningObjective: "Separate the chemical (PCO2) drive to breathe from the nervous, non-chemical afferents that also regulate the respiratory centre.",
      explanations: {
        A: "A genuine non-chemical influence. The 'Afferents from Higher Centers' pathway carries pain and emotional stimuli by the limbic system and temperature by the hypothalamus into the respiratory centre — both nervous routes, not chemical ones.",
        B: "A genuine non-chemical influence. Swallowing is one of the visceral reflexes: mechanoreceptors in the pharynx send a glossopharyngeal afferent that inhibits respiration (swallowing apnoea) to keep food out of the airway.",
        C: "A genuine non-chemical influence, not the exception. Coughing is the first example under 'Afferents from Upper Airway Receptors' — irritant receptors in the trachea, larynx and bronchi, carried by the vagus, producing deep inspiration then forced expiration against a glottis that opens suddenly.",
        D: "The exception, and the answer. A rise in arterial PCO2 (hypercapnia) belongs under chemical control of respiration, not under 'Non-Chemical (Nervous) Regulation' — PCO2 is stated as the major controller of ventilation acting through central and peripheral chemoreceptors, the one route on this list that is not a nervous reflex. A common trap: treating hypercapnia (a rise in arterial PCO2) as one item on the non-chemical list.",
      },
      answerOverride: "D",
      answerOverrideReason: "The chapter structure contradicts the printed key. 'Non-Chemical (Nervous) Regulation of Respiratory Activity' (physiology department book p149-153) explicitly lists pain/limbic afferents, coughing and swallowing as nervous reflex sources of respiratory drive. Hypercapnia (raised PCO2) sits in a separate, earlier section, 'Ventilatory Response to Changes in CO2' (p148-149), stated as the major controller of respiration through chemoreceptors — the chemical route the non-chemical section is being contrasted against. It is therefore the one option that is not a non-chemical influence, not option C.",
    },

    // --- Chemoreceptors (central and peripheral drive) ---

    {
      key: "co-narcosis-means-466cf640",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State what CO2 narcosis is, the approximate PCO2 threshold above which it occurs, and why it represents depression rather than stimulation of the respiratory centre.",
      explanations: {
        A: "This describes hypocapnia, not hypercapnia: a marked fall in PCO2 reduces, rather than stimulates, the drive to breathe, since a rise in CO2 — not a fall — is the principal everyday stimulus to ventilation.",
        B: "A rise of only 10 mmHg is a mild, physiological stimulus that increases ventilation through the central chemoreceptors; it is nowhere near the markedly elevated level needed to depress rather than drive respiration.",
        C: "Correct. Carbon dioxide narcosis is the paradoxical depression of respiratory centre activity and consciousness produced by a marked rise in arterial PCO2, conventionally placed above about 70 mmHg. Moderate hypercapnia stimulates the central chemoreceptors and drives ventilation up, but once PCO2 climbs into this markedly elevated range, CO2 itself becomes directly narcotic to the central nervous system, blunting rather than boosting respiratory drive. This is why patients who chronically retain CO2 — advanced COPD being the classic example — are given supplemental oxygen cautiously: removing their hypoxic (peripheral chemoreceptor) drive without correcting the underlying hypoventilation lets PCO2 climb unchecked into the narcotic range.",
        D: "A decrease in PCO2 cannot itself cause CO2 narcosis, which by definition requires a marked increase above roughly 70 mmHg; pairing a fall in PCO2 with that same threshold value is an internal contradiction, and a falling PCO2 would in any case reduce, not stimulate, respiratory drive.",
      },
    },
    {
      key: "the-most-potent-stimulator-of-the-respiratory-center-is-df5317fa",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Identify a rise in arterial PCO2 as the most potent everyday stimulus to the respiratory centre, acting chiefly through the central chemoreceptors.",
      explanations: {
        A: "A fall in blood oxygen tension does drive ventilation, but only through the peripheral chemoreceptors, and only once PO2 falls substantially below about 60 mmHg — a much weaker and later stimulus than a rise in CO2.",
        B: "A decrease, rather than an increase, in hydrogen ion concentration means more alkaline blood, which would reduce rather than stimulate chemoreceptor drive — the opposite of what the most potent stimulator requires.",
        C: "A decrease in CSF CO2 tension lowers CSF H+ and would reduce, not increase, central chemoreceptor firing — again the opposite direction from what stimulates the respiratory centre most potently.",
        D: "Correct. A rise in arterial PCO2 is the single most potent everyday stimulus to the respiratory centre: a rise of only about 3% in arterial PCO2 can double ventilation, an effect exerted mainly through the central chemoreceptors, which respond to the resulting fall in CSF pH once CO2 diffuses across the blood-brain barrier. A smaller share of the CO2 response runs through the peripheral chemoreceptors in the carotid and aortic bodies. This dominance of CO2 over oxygen is why arterial PO2 can fall a long way before ventilation rises appreciably, while even a small rise in PCO2 produces an immediate, large ventilatory response.",
      },
    },
    {
      key: "the-peripheral-chemoreceptors-7aa47469",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Locate the peripheral chemoreceptors, explain why they sense PO2 directly rather than oxygen content, and state their afferent pathway.",
      explanations: {
        A: "Correct. The peripheral chemoreceptors are the glomus cells of the carotid bodies, at the bifurcation of the common carotid arteries, and the aortic bodies in the aortic arch. Their exceptionally high blood flow per gram of tissue lets them sense dissolved arterial PO2 directly rather than total oxygen content, which is why they remain responsive in anaemia and carbon monoxide poisoning even though those conditions reduce oxygen content without changing PO2. They provide only a minority share of resting respiratory drive, becoming the dominant stimulus only once PO2 falls substantially, which is why fixing their location and identity firmly matters.",
        B: "The reverse is true: the peripheral chemoreceptors are far more sensitive to a fall in PO2 than to a rise in PCO2 — CO2 drives ventilation predominantly through the central chemoreceptors, and the peripheral route contributes only a minor share of the CO2 response.",
        C: "Peripheral chemoreceptor input is not essential for normal resting breathing, which continues after their denervation; they become physiologically important mainly once PO2 falls well below its normal resting value, as in significant hypoxaemia.",
        D: "Peripheral chemoreceptor afferents travel to the respiratory centre via the glossopharyngeal nerve (carotid bodies) and the vagus nerve (aortic bodies), not along sympathetic fibres.",
      },
    },

    // --- Brainstem respiratory centre anatomy and interactions ---

    {
      key: "regarding-the-nervous-control-of-respiration-3842aa0d",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Locate the inspiratory centre in the medulla and distinguish its role from the excitatory apneustic and inhibitory pneumotaxic pontine centres, and from cortical voluntary control.",
      explanations: {
        A: "The apneustic centre sends tonic excitatory, not inhibitory, drive to the inspiratory centre — when that excitatory input is left unopposed by the pneumotaxic centre, the result is prolonged inspiratory gasps (apneusis), the opposite of an inhibited inspiratory drive.",
        B: "Correct. The inspiratory centre — the dorsal respiratory group — sits in the medulla, in and around the nucleus of the tractus solitarius, and is the neuron population that generates the basic rhythmic drive to the inspiratory muscles during quiet breathing. It fires on its own slow, irregular intrinsic rhythm rather than needing a signal from higher up, which is why an isolated medulla can still produce a crude breathing rhythm. The two pontine centres — apneustic and pneumotaxic — only tune this medullary rhythm; they do not replace it, which is the point this question tests.",
        C: "The cerebral cortex does influence respiration — voluntary breath-holding, hyperventilation before speech, and singing all route through cortical pathways onto the respiratory centre, ending only at the 'break point' when rising PCO2 and falling PO2 override voluntary control.",
        D: "The pneumotaxic centre inhibits, rather than stimulates, inspiration: it switches off the inspiratory ramp signal from the medulla, which is what sets the rate and depth of breathing rather than prolonging each breath.",
      },
    },
    {
      key: "the-basic-rhythm-of-respiration-is-generated-by-neurons-loca-dbed56b4",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Identify the pneumotaxic centre as the structure that limits the duration of inspiration, and distinguish its off-switch role from the apneustic centre, dorsal respiratory group and nucleus ambiguus.",
      explanations: {
        A: "The apneustic centre does the opposite: unopposed, it prolongs inspiration rather than limiting its duration, producing apneustic breathing.",
        B: "The dorsal respiratory group generates the basic inspiratory rhythm itself in the medulla; it is the rhythm being limited, not the structure that limits it.",
        C: "Correct. The pneumotaxic centre, in the upper pons, limits the duration of inspiration by switching off the inspiratory ramp signal generated in the medulla, allowing expiration to begin at an appropriate point. This 'off-switch' action is what sets the rate and depth of breathing from breath to breath, and it is the functional opposite of the apneustic centre, which prolongs inspiration rather than limiting it. Losing pneumotaxic input experimentally produces apneusis — abnormally long inspiratory gasps — the clearest evidence that this centre's normal job is to end inspiration on time.",
        D: "The nucleus ambiguus contributes motor fibres to the pharynx and larynx via cranial nerves IX and X and plays no role in setting the duration of inspiration.",
      },
    },
    {
      key: "the-pneumotaxic-center-d24fa5ca",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State that the pneumotaxic centre inhibits both the dorsal respiratory group and the apneustic centre, and locate it correctly in the upper pons.",
      explanations: {
        A: "Rhythmic respiration is initiated by pacemaker neurons in the medullary pre-Botzinger complex driving the dorsal respiratory group, not by the pneumotaxic centre, which only tunes an already-generated rhythm.",
        B: "The pneumotaxic centre sends inhibitory, not excitatory, signals to the inspiratory centre — it is the apneustic centre that provides excitatory drive.",
        C: "Correct. The pneumotaxic centre, in the upper pons, inhibits both the dorsal respiratory group and the apneustic centre, switching off the inspiratory ramp signal and so setting the rate and depth of breathing. Because it inhibits the apneustic centre's tonic excitatory drive to the medulla, removing the pneumotaxic centre experimentally unmasks the apneustic centre's unopposed excitation and produces apneustic breathing — long inspiratory gasps with only brief expiration. This inhibitory relationship between the two pontine centres is the mechanism behind normal breath-to-breath rate and depth control.",
        D: "The pneumotaxic centre lies in the upper pons, not the medulla; placing it in the medulla confuses it with the dorsal and ventral respiratory groups.",
      },
    },
    {
      key: "the-respiratory-center-includes-8fbc9f3b",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State that the respiratory centre's inspiratory neurons lie in the medulla, and correctly locate the apneustic centre (lower pons) and pneumotaxic centre (upper pons).",
      explanations: {
        A: "Correct. The respiratory centre's inspiratory neurons — the dorsal respiratory group — sit in the medulla, around the nucleus of the tractus solitarius, and generate the basic rhythmic drive to the inspiratory muscles during quiet breathing. The pons contributes two separate tuning centres rather than a second set of inspiratory neurons: the apneustic centre and the pneumotaxic centre, each with an opposite effect on the medullary rhythm. Holding the medulla as the site of rhythm generation, with the pons only modulating it, is the anchor fact this whole topic builds on.",
        B: "The pons does not contain a separate population of inspiratory neurons alongside the medulla's; instead it holds the apneustic and pneumotaxic centres, which tune the medullary inspiratory rhythm rather than generating their own.",
        C: "The apneustic centre sits in the lower third of the pons, not the upper third — this option reverses the correct locations of the two pontine centres.",
        D: "The pneumotaxic centre sits in the upper third of the pons, not the lower third — again a reversal of the two pontine centres' correct locations.",
      },
    },
    {
      key: "the-respiratory-center-includes-a-inspiratory-neurons-that-a-782073f6",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Easy",
      questionType: "Mechanism",
      learningObjective: "Restate that inspiratory neurons generating the basic breathing rhythm lie in the medulla, and correctly assign the apneustic centre to the lower pons and the pneumotaxic centre to the upper pons.",
      explanations: {
        A: "Correct. Quiet breathing is driven by inspiratory neurons of the dorsal respiratory group, located in the medulla rather than the pons. The two structures in the pons — the apneustic centre and the pneumotaxic centre — modulate this medullary rhythm from opposite directions instead of generating a second, independent inspiratory rhythm of their own. This exact option set recurring across different question books is itself a clue that examiners treat the medulla-versus-pons location as the single fact most worth testing here.",
        B: "There is no separate set of inspiratory neurons native to the pons; the pons instead houses the apneustic and pneumotaxic centres, each of which acts on the medulla's own inspiratory rhythm rather than generating an independent one.",
        C: "This reverses the apneustic centre's true location: it lies in the lower third of the pons, not the upper third.",
        D: "This reverses the pneumotaxic centre's true location: it lies in the upper third of the pons, not the lower third.",
      },
    },

    // --- Hering-Breuer reflex ---

    {
      key: "which-of-the-following-can-stop-normal-inspiration-and-start-9d7e98d1",
      conceptKey: "hering-breuer-reflex.pulmonary-stretch-receptors",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "State the stimulus, afferent pathway and effect of the Hering-Breuer reflex, and distinguish it from the apneustic centre and dorsal respiratory group.",
      explanations: {
        A: "The apneustic centre does the opposite of stopping inspiration: left unopposed, it prolongs inspiration rather than ending it.",
        B: "The dorsal respiratory group generates the basic inspiratory drive itself; it is the rhythm being switched off, not the mechanism that switches it off.",
        C: "Correct. The Hering-Breuer (inflation) reflex is triggered when lung inflation stretches receptors in the walls of the bronchi and bronchioles; the resulting afferent signal travels through the vagus nerve to inhibit the dorsal respiratory group and the apneustic centre, stopping inspiration and allowing expiration to begin. It acts as an 'off-switch' for inspiration, alongside the pneumotaxic centre's own off-switch role. In adults at rest it stays largely silent and only engages once tidal volume rises to more than about three times normal, as in exercise, though it shapes every breath in the newborn.",
        D: "The Cushing reflex is a cardiovascular pressor response to rising intracranial pressure and cerebral ischaemia — a rise in systemic blood pressure with reflex bradycardia — and plays no part in the normal inspiration-to-expiration transition.",
      },
    },

    // --- run44: brainstem transection levels (p.142) ---

    {
      key: "transection-between-medulla-oblongata-and-upper-border-of-sp-d728ec2a",
      conceptKey: "brainstem-transection.effect-on-breathing-by-level",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that transection between the medulla and the upper border of the spinal cord (level 4) causes complete stoppage of breathing and death.",
      explanations: {
        A: "This is the correct answer. The department book's own level 4 transection — between the medulla and the upper border of the spinal cord — completely disconnects the DRG/VRG from the phrenic and intercostal motor neurons that actually drive breathing, so respiration stops entirely, leading to death, unlike levels 1-3, which all leave some form of breathing going.",
        B: "Irregular respiration is what level 3 (between pons and medulla) produces, not level 4 — at level 4 breathing stops completely rather than merely becoming irregular.",
        C: "Slower and deeper respiration is what level 1 (top of the pons) plus vagotomy produces; level 4 stops breathing entirely rather than slowing and deepening it.",
        D: "Rapid shallow respiration is not a pattern any of the four classic transection levels produces; level 4 specifically abolishes breathing rather than making it rapid and shallow.",
      },
    },
    {
      key: "immediate-stoppage-of-respiration-can-be-caused-by-transecti-82f47191",
      conceptKey: "brainstem-transection.effect-on-breathing-by-level",
      difficulty: "Moderate",
      questionType: "Applied recall",
      learningObjective: "Identify a transection above the second cervical vertebra as equivalent to level 4 brainstem transection, disconnecting the respiratory centres from the phrenic outflow entirely.",
      explanations: {
        A: "A transection between pons and medulla (level 3) leaves respiration continuing, only irregularly, on the DRG's own intrinsic rhythm — not an immediate stoppage.",
        B: "Cutting both vagi alone does not stop breathing; it only removes the Hering-Breuer reflex's contribution to tidal volume and rate, leaving the DRG's own rhythm intact.",
        C: "A transection below the 7th cervical vertebra sits below the phrenic nerve's spinal origin (C3-C5), so diaphragmatic breathing driven by the phrenic nerve continues even though thoracic outflow below the cut is lost.",
        D: "This is the correct answer. A transection above the 2nd cervical vertebra severs every descending pathway from the medullary respiratory centres to the phrenic (C3-C5) and intercostal motor neurons — functionally the same disconnection as the department book's own level 4 (medulla-to-spinal-cord) transection — so breathing stops immediately.",
      },
    },
    {
      key: "spontaneous-respiration-ceases-after-7ab1a72f",
      conceptKey: "brainstem-transection.effect-on-breathing-by-level",
      difficulty: "Hard",
      questionType: "Applied mechanism",
      learningObjective: "State that combining bilateral vagotomy with a pontine transection that removes pneumotaxic input abolishes normal rhythmic breathing and replaces it with apneusis.",
      explanations: {
        A: "Bilateral vagotomy alone does not abolish normal rhythmic breathing — the department book's own level 1 experiment shows vagotomy alone only makes breathing slower and deeper, since the pneumotaxic centre still supplies its own independent inhibitory input to the apneustic centre and DRG.",
        B: "This is the correct answer. The department book's own level 2 transection (removing pneumotaxic input to the apneustic centre and DRG) combined with bilateral vagotomy removes the apneustic centre's only two sources of inhibition at once, so it fires unopposed — normal rhythmic breathing ceases and is replaced by apneusis, breathing held in full inspiration.",
        C: "Transection of the spinal cord at the first thoracic segment leaves the phrenic nerve (C3-C5) and its brainstem connections intact, so normal rhythmic diaphragmatic breathing continues; it does not by itself abolish spontaneous respiration.",
        D: "'Trachea' names an airway structure, not a transection level or manoeuvre that could abolish the brainstem's own respiratory rhythm.",
      },
    },

    // --- run44: existing-concept reuses (non-chemical afferents,
    // chemoreceptor drive, DRG spontaneous rhythmicity) ---

    {
      key: "medullary-inspiratory-neurons-are-stimulated-by-370da678",
      conceptKey: "non-chemical-nervous-regulation-of-respiration.afferent-sources",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "Identify proprioceptive afferents as a genuine stimulatory input to the medullary inspiratory neurons, unlike vagal stretch afferents, arterial H+ or baroreceptor afferents, which do not directly stimulate them.",
      explanations: {
        A: "This is the correct answer. Afferent impulses from proprioceptors are one of this leaf's own non-chemical afferent sources, driving the ventilation rise of exercise by stimulating the medullary inspiratory neurons.",
        B: "Vagal afferents from lung stretch receptors are inhibitory, not stimulatory, to the medullary inspiratory neurons — this is the Hering-Breuer reflex, which switches inspiration off, the opposite direction from stimulation.",
        C: "Arterial (plasma) H+ does not directly stimulate the medullary inspiratory neurons — the central chemoreceptors respond to CSF H+, which plasma H+ cannot reach because of the blood-brain barrier.",
        D: "Afferent impulses from arterial baroreceptors inhibit, not stimulate, the respiratory centre — a rise in arterial pressure raising baroreceptor discharge reflexly inhibits respiration.",
      },
    },
    {
      key: "in-normal-individual-respiration-is-regulated-by-all-except-7e8ddaae",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "True/false-except",
      learningObjective: "Identify that central chemoreceptors respond to CSF H+/PCO2, not directly to PO2, which the peripheral chemoreceptors alone sense.",
      explanations: {
        A: "The exception, and the answer. Central chemoreceptors do not respond to changes in PO2 at all — they are protected from arterial blood by the blood-brain barrier and respond only to CSF H+, generated indirectly when CO2 crosses that barrier. Sensing PO2 directly is a peripheral, not central, chemoreceptor function.",
        B: "True, so not the exception. Peripheral chemoreceptors do respond to changes in PCO2, contributing roughly 20-30% of the overall CO2 ventilatory response alongside the dominant central route.",
        C: "True, so not the exception. Peripheral chemoreceptors are the ones that sense PO2 directly, thanks to their exceptionally high blood flow per gram of tissue.",
        D: "True, so not the exception. Central chemoreceptors respond to changes in PCO2, indirectly, via the CSF acidification CO2 produces once it crosses the blood-brain barrier.",
      },
    },
    {
      key: "the-carotid-and-aortic-bodies-increase-their-rate-of-dischar-32d0556f",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "State that the carotid and aortic bodies (peripheral chemoreceptors) increase their discharge in response to a decreased partial pressure of blood oxygen, not decreased H+, O2 content, or CSF dissolved oxygen.",
      explanations: {
        A: "A decrease in blood H+ concentration means more alkaline blood, which would reduce, not increase, chemoreceptor discharge — the opposite direction.",
        B: "The peripheral chemoreceptors' very high blood flow per gram of tissue lets them sense dissolved PO2 directly rather than total O2 content, so a fall in O2 content alone (as in anaemia, with normal PO2) does not markedly raise their discharge.",
        C: "This is the correct answer. The carotid and aortic bodies sense dissolved arterial PO2 directly, and increase their rate of discharge as PO2 falls, becoming markedly more active once PO2 drops below about 60 mmHg.",
        D: "The peripheral chemoreceptors are stimulated by arterial blood, not CSF, and their location (carotid bifurcation, aortic arch) and blood supply have nothing to do with dissolved oxygen in CSF, which is instead what the (unaffected-by-O2) central chemoreceptors are bathed in.",
      },
    },
    {
      key: "which-of-the-following-discharge-spontaneously-during-quiet-b30226e7",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "Identify the dorsal respiratory group, not stretch receptors, respiratory motor neurons, or the ventral respiratory group, as the structure that discharges spontaneously during quiet breathing.",
      explanations: {
        A: "Stretch receptors in the lung do not discharge spontaneously — they fire in response to lung inflation, driving the Hering-Breuer reflex, not generating rhythm on their own.",
        B: "Motor neurons of the respiratory muscles fire in response to the DRG's own descending drive; they do not spontaneously generate the rhythm themselves.",
        C: "This is the correct answer. The dorsal respiratory group has its own slow, irregular inherent rhythmicity and fires spontaneously during quiet breathing, generating the basic inspiratory drive that the pontine centres only tune.",
        D: "The ventral respiratory group is totally inactive during quiet breathing, activating only for forced breathing — the opposite of discharging spontaneously at rest.",
      },
    },
    {
      key: "which-of-the-following-discharge-spontaneously-during-quist-89974900",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "Identify the dorsal respiratory group, not stretch receptors, respiratory motor neurons, or the ventral respiratory group, as the structure that discharges spontaneously during quiet breathing.",
      explanations: {
        A: "Stretch receptors in the lung fire in response to lung inflation (the Hering-Breuer reflex); they do not spontaneously generate rhythm on their own.",
        B: "Motor neurons of the respiratory muscles fire in response to the DRG's own descending drive rather than generating the rhythm themselves.",
        C: "This is the correct answer. The dorsal respiratory group has its own slow, irregular inherent rhythmicity and fires spontaneously during quiet breathing.",
        D: "The ventral respiratory group is totally inactive during quiet breathing, activating only for forced breathing.",
      },
    },
    {
      key: "which-of-the-following-discharges-spontaneously-during-quiet-20ea9248",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "Identify the dorsal respiratory group, not stretch receptors, respiratory motor neurons, or the ventral respiratory group, as the structure that discharges spontaneously during quiet breathing.",
      explanations: {
        A: "Stretch receptors in the lung fire in response to lung inflation (the Hering-Breuer reflex); they do not spontaneously generate rhythm on their own.",
        B: "Motor neurons of the respiratory muscles fire in response to the DRG's own descending drive rather than generating the rhythm themselves.",
        C: "This is the correct answer. The dorsal respiratory group has its own slow, irregular inherent rhythmicity and fires spontaneously during quiet breathing.",
        D: "The ventral respiratory group is totally inactive during quiet breathing, activating only for forced breathing.",
      },
    },
    {
      key: "which-of-the-following-conditions-causes-hypoventilation-6ee07624",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "Identify COPD, not strenuous exercise, high-altitude ascent, anaemia or diabetic ketoacidosis, as a cause of hypoventilation, via the chronic CO2-retention drive-shift mechanism.",
      explanations: {
        A: "Strenuous exercise raises ventilation to match the sharp rise in CO2 production and O2 consumption — hyperventilation relative to rest, not hypoventilation.",
        B: "Ascent to high altitude lowers arterial PO2, stimulating the peripheral chemoreceptors and driving hyperventilation, not hypoventilation.",
        C: "Anaemia lowers O2 content but leaves PO2 normal, so it does not stimulate or depress the chemoreceptor drive to ventilation; it is not a cause of hypoventilation.",
        D: "Diabetic ketoacidosis produces a metabolic acidosis that drives compensatory hyperventilation (Kussmaul breathing) via the peripheral and central chemoreceptors, not hypoventilation.",
        E: "This is the correct answer. In chronic lung disease such as COPD, longstanding CO2 retention lets the central chemoreceptors tolerate higher CO2 levels than normal, shifting these patients onto hypoxic (peripheral chemoreceptor) drive as their main stimulus to breathe — the underlying mechanism is chronic hypoventilation relative to CO2 production, with the central chemoreceptor response blunted.",
      },
    },

    // --- Excluded: corrupted or unrecoverable beyond what this pipeline can fix ---

    {
      key: "all-about-peripheral-chemoreceptors-is-true-except-332ae5b1",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option C's text is corrupted at the OCR/extraction stage: a literal Arabic letter (waw, U+0648) stands in for the 'P' of 'PO2', wrapped in RTL/LRM direction marks ('...changes in ‏و20‎ than the central chemoreceptors'), confirmed by inspecting the raw codepoints. A clean variant of this exact option ('...changes in PO2 than the central chemoreceptors') exists from a sibling exam-book occurrence, but the bank keeps this occurrence's corrupted text as the canonical option, and the McqAuthored contract has no field to override option text — only the answer letter can be overridden (answerOverride). Same class of unfixable defect as the leading-'+' hazard: left unauthored rather than showing a student a garbled option.",
    },
    {
      key: "concerning-the-interaction-of-respiratory-centers-in-the-bra-61d1bcea",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "All four options are truncated OCR fragments (option A ends mid-sentence 'near the inferior colliculus of the...'; option B ends '...whose rhythmicity is abolished when the...'), recovered only by fuzzy-OCR match (meanOptionRatio 0.749, the weakest match in this cluster) against a single sibling book. The bank's own answer, option C ('Transection above the apneustic center results in prolonged expiration and very short inspiration'), also contradicts standard brainstem-transection physiology: isolating the apneustic centre from pneumotaxic inhibition is what produces apneusis — prolonged INSPIRATION with brief expiration, the reverse of this option's wording — which casts further doubt on the OCR recovery rather than confirming it. Independently, this leaf's own article (ART-104-PHY-RESPIRATORY-CENTERS-AND-CHEMORECEPTORS) states in its own evidence_gaps that brainstem-transection experimental evidence was not reached in the reading pass and is not covered — so even a clean version of this question would need a new evidence pass before it could gate. Left unauthored.",
    },
    {
      key: "in-metabolic-acidosis-compensatory-hyperventilation-occurs-i-4b08cc0a",
      conceptKey: "chemoreceptors-respiratory.central-and-peripheral-drive-contributions",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Option B's text ('3920 ml/minute; 3920 ml/minute') is garbage carried over from an unrelated ventilation-calculation question elsewhere in the same source PDF — a column-alignment OCR failure, not a genuine distractor for this metabolic-acidosis question. Options A, C and D are clean and the bank's answer (D — peripheral chemoreceptors respond to H+ that cannot cross the blood-brain barrier) is physiologically sound, but with B unusable this is effectively a 3-option item, below the 4-5 option contract, and there is no seed-level field to substitute real text for a corrupted option. Left unauthored rather than showing a student a nonsensical distractor.",
    },
    {
      key: "the-basic-rhythm-of-respiration-is-generated-by-neurons-loca-4d2b32e9",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Already flagged unkeyed/uncorrectable by the bank's own extraction (editorialExcluded): the correct answer (pneumotaxic centre) survives only as unlettered text inside a corrupted, merged stem, and the two lettered options that do survive (nucleus ambiguus; 'breathing is mostly involuntary') are both wrong, leaving no valid letter for the answer.",
    },
    {
      key: "the-respiratory-center-includes-inspiratory-neurons-that-are-373857a5",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "The stem is a corrupted OCR merge of two separate questions (a 'respiratory center includes...' item and a following 'which of the following discharges spontaneously during quiet breathing' item), and only two of what was originally four lettered options survive (A: stretch receptors in lung; B: motor neurons of respiratory muscles). The option set cannot be reconstructed to the 4-5 option contract, and it is not possible to confirm with confidence which of the two merged questions the surviving handwritten mark (A) actually answers. Left unauthored.",
    },
    {
      key: "which-of-the-following-discharges-s-8-1-receptort-fa-ling-be-5358ae60",
      conceptKey: "respiratory-center.drg-vrg-pontine-groups-and-rhythm-generation",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Already flagged unkeyed by the bank's own extraction (editorialExcluded): the correct answer (dorsal respiratory group, established repeatedly elsewhere in this cluster as the medulla's spontaneously-discharging rhythm generator) is missing from the surviving lettered options (apneustic center; motor neurons of respiratory muscles; ventral respiratory group of neurons), none of which is correct.",
    },
  ],
}
