/**
 * `104 CPS > Physiology > Respiratory System > Pulmonary Compliance` —
 * surfactant's effect on compliance, and which diseases raise versus lower
 * pulmonary compliance.
 *
 * `articleId` is the already-live `ART-104-PHY-LUNG-RECOIL-AND-SURFACTANT`
 * (`104-CPS-articles.md`), which covers elastic recoil, surfactant
 * composition/function, Laplace's law and surfactant-deficiency causes in
 * depth — exactly this file's teaching ground — but explicitly excludes lung
 * volumes/spirometry and the obstructive/restrictive PFT pattern (see
 * `physiology-lung-volumes-and-capacities.ts` for those).
 *
 * The `surfactant.*` concept below overlaps with the live, already-Kasr/
 * Year-1-tagged concept `CON-RES-4D4CBF3BB8AF1E` (canonical_key
 * `pulmonary-surfactant.functions-and-causes-of-deficiency`), minted by the
 * written-paper pipeline into the generated `104-CPS-concepts.md`. It is not
 * reused here: that file carries `Generated by scripts/kasr/build-batches.ts`,
 * so `existingConceptIds()` treats it as this pipeline's own prior output and
 * skips it — reusing the same canonical_key would not produce a safe sparse
 * update, it would emit a **full** `mcqConceptBlock` that "Update matching
 * items" then applies over the live record, silently replacing its
 * `blueprint_weight`, `exam_signal`, `secondary_node_ids` and every other
 * field this pipeline does not itself populate (a documented failure mode —
 * see the comment on `reuseNote` in `build-batches.ts`). A fresh, distinct
 * key avoids that risk; the overlap is flagged in `conflicts` below and in
 * PROGRESS.md for a chief-of-staff ruling on cross-pipeline consolidation,
 * not resolved by guessing here.
 */
import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Pulmonary Compliance",
  modulePath: "104 CPS > Physiology > Respiratory System > Pulmonary Compliance",
  articleId: "ART-104-PHY-LUNG-RECOIL-AND-SURFACTANT",

  concepts: [
    {
      key: "surfactant.reduces-surface-tension-and-increases-compliance",
      label: "Pulmonary surfactant, secreted by type II pneumocytes, lowers alveolar surface tension and thereby increases pulmonary compliance; its deficiency increases surface tension and decreases compliance",
      definition: "Pulmonary surfactant is a phospholipid-rich secretion of the type II alveolar cells that spreads over the air-fluid interface lining the alveoli and markedly lowers its surface tension. Because surface tension is the larger of the two forces resisting lung expansion (the smaller being the elastic recoil of collagen and elastin), lowering it makes the lung easier to inflate for a given pressure change — surfactant increases pulmonary compliance, rather than the alveolar surface tension itself, which it reduces. A surfactant deficiency reverses this: alveolar surface tension rises, the lung becomes stiffer, and pulmonary compliance falls. This is exactly what happens in a preterm infant born before adequate surfactant production (respiratory distress syndrome of prematurity): increased surface tension collapses alveoli at the end of each expiration, and decreased compliance means far greater inspiratory pressure is needed to reinflate them, together driving progressive respiratory failure.",
      objective: "State that surfactant lowers alveolar surface tension and thereby increases pulmonary compliance, and predict the opposite pair of changes (increased surface tension, decreased compliance) in a surfactant-deficient lung such as in respiratory distress syndrome of prematurity.",
      pitfall: "Saying that surfactant's major function is to increase surface tension. It is the reverse: surfactant lowers surface tension, and it is that reduction which increases compliance, prevents end-expiratory alveolar collapse, and eases the work of breathing.",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Pulmonary Compliance",
      type: "mechanism",
      aliases: ["Pulmonary surfactant function", "Surfactant and pulmonary compliance", "Respiratory distress syndrome of prematurity", "Type II pneumocyte secretion"],
      conflicts: [
        "Overlaps with the live concept CON-RES-4D4CBF3BB8AF1E (canonical_key `pulmonary-surfactant.functions-and-causes-of-deficiency`), authored by the written-paper pipeline into the generated `104-CPS-concepts.md`. Not merged: that file carries the pipeline's own GENERATED_BY marker, so `existingConceptIds()` cannot see it as pinned, and re-minting the same key here would silently full-overwrite an already-scored, under-review live record rather than issue a safe sparse update. Minted as a distinct concept instead; flagged for a chief-of-staff ruling on cross-pipeline concept consolidation for 104 CPS.",
      ],
    },
    {
      key: "pulmonary-compliance.rises-in-emphysema-falls-in-fibrosis-oedema-and-surfactant-deficiency",
      label: "Pulmonary compliance rises when the lung's elastic recoil is lost, as in emphysema, and falls whenever the lung is stiffened by fibrosis, pulmonary oedema or a surfactant deficiency",
      definition: "Pulmonary compliance is the change in lung volume produced per unit change in distending pressure — a measure of how easy the lung is to stretch. It rises whenever the lung's elastic recoil is reduced: in emphysema, destruction of the alveolar walls and their elastin and collagen fibres leaves the lung with less tissue resisting expansion, producing the classic abnormally compliant, 'floppy' lung of that disease. Compliance falls, by contrast, whenever something stiffens the lung: pulmonary fibrosis lays down excess fibrous tissue; acute pulmonary oedema fills the interstitium and alveoli with fluid; and a surfactant deficiency leaves alveolar surface tension abnormally high. All three of these opposite-direction conditions raise, rather than lower, the elastic resistance the respiratory muscles must overcome, and so make the lung harder — not easier — to inflate.",
      objective: "State that pulmonary compliance is increased in emphysema (lost elastic recoil) and decreased in pulmonary fibrosis, acute pulmonary oedema and surfactant deficiency (all of which stiffen the lung), and explain the mechanism behind each direction of change.",
      pitfall: "Assuming any lung disease affects compliance the same way. Emphysema is the one common condition that increases compliance, by destroying elastic tissue; fibrosis, oedema and surfactant deficiency all decrease it, by stiffening the lung through three different mechanisms (excess fibrous tissue, fluid-filled airspaces, and raised surface tension respectively).",
      subject: "resp",
      primary: "DIS-PHY-T03",
      secondary: [],
      modulePath: "104 CPS > Physiology > Respiratory System > Pulmonary Compliance",
      type: "mechanism",
      aliases: ["Lung compliance in emphysema", "Compliance in restrictive lung disease", "Floppy lung of emphysema"],
    },
  ],

  questions: [
    {
      key: "57-10-4-8-function-10-n-msfp-cardiac-output-af-ae-ae-output-72c4f14b",
      conceptKey: "surfactant.reduces-surface-tension-and-increases-compliance",
      difficulty: "Moderate",
      questionType: "Not sittable as extracted.",
      learningObjective: "Not sittable as extracted.",
      explanations: {},
      exclude: true,
      excludeReason: "Not a coherent single MCQ: the extracted 'stem' and 'options' are an OCR dump of an entire lecture-slide deck spanning venous-return curves, ABP regulation, arteriolar autoregulation and vasoconstrictor hormones, run together with a separate set of numbered 'Idea' notes on inspiration, surfactant and the respiratory centre. No single question, stem or option set can be recovered from this text; it is unusable regardless of which leaf's bank tag it carries.",
    },
    {
      key: "a-major-function-of-surfactant-is-to-increase-7cf67456",
      conceptKey: "surfactant.reduces-surface-tension-and-increases-compliance",
      difficulty: "Easy",
      questionType: "Recall",
      learningObjective: "State that surfactant's major effect is to increase pulmonary compliance, not surface tension.",
      explanations: {
        A: "Surfactant lowers alveolar surface tension; it does not increase it. Raising surface tension is what happens in its absence, not what it does.",
        B: "Correct. Surfactant's whole mechanism is to lower alveolar surface tension, and because surface tension is the larger source of the lung's elastic resistance, lowering it makes the lung easier to inflate — surfactant increases pulmonary compliance.",
        C: "Surfactant acts on the mechanics of lung inflation, not on gas exchange or haemoglobin's affinity for oxygen; it has no role in releasing O2 from haemoglobin in the capillaries.",
        D: "Surfactant reduces the work of breathing, by increasing compliance, rather than increasing it — the opposite of this option's claim.",
      },
    },
    {
      key: "a-preterm-infant-has-a-surfactant-deficiency-without-surfact-87f66d17",
      conceptKey: "surfactant.reduces-surface-tension-and-increases-compliance",
      difficulty: "Moderate",
      questionType: "Comparison",
      learningObjective: "Predict increased alveolar surface tension and decreased pulmonary compliance in a surfactant-deficient preterm infant.",
      explanations: {
        A: "Surface tension is increased, not decreased, without surfactant — surfactant's whole function is to lower surface tension, so its absence raises it.",
        B: "Surface tension is increased (not decreased) without surfactant, and compliance also falls as a direct consequence — it does not stay unchanged.",
        C: "Surface tension is correctly identified as increased here, but compliance also falls as a direct result of the raised surface tension; it does not remain unchanged.",
        D: "Correct. Without surfactant, alveolar surface tension is markedly increased — surfactant's whole role is to lower it — and that increased surface tension directly stiffens the lung, decreasing pulmonary compliance. Together these explain why a surfactant-deficient preterm infant needs much greater inspiratory pressure to expand the lungs and why alveoli progressively collapse at the end of each expiration.",
      },
    },
    {
      key: "lung-compliance-is-increased-in-1ce011e2",
      conceptKey: "pulmonary-compliance.rises-in-emphysema-falls-in-fibrosis-oedema-and-surfactant-deficiency",
      difficulty: "Moderate",
      questionType: "Recall",
      learningObjective: "Identify emphysema as the condition among these four that increases, rather than decreases, pulmonary compliance.",
      explanations: {
        A: "Correct. Emphysema destroys alveolar walls and the elastin and collagen fibres within them, reducing the lung's elastic recoil and making it abnormally easy to inflate — the classic 'floppy lung' of increased compliance.",
        B: "Pulmonary fibrosis stiffens the lung with excess fibrous tissue, decreasing — not increasing — compliance.",
        C: "Surfactant deficiency raises alveolar surface tension, stiffening the lung and decreasing — not increasing — compliance.",
        D: "Acute pulmonary oedema fills the interstitium and alveoli with fluid, stiffening the lung and decreasing — not increasing — compliance.",
      },
    },
  ],
}
