import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Physiology Cardiovascular System — Cardiac Function',
  modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
  articleId: 'ART-104-PHY-CARDIAC-CYCLE-AND-HEART-SOUNDS',

  concepts: [
    {
      key: 'cardiac-cycle.seven-phase-sequence-and-duration',
      label: 'The cardiac cycle runs through a fixed order of seven phases starting with atrial systole, and a rising heart rate shortens the cycle mainly by shortening diastole, not systole',
      definition: 'The cardiac cycle is triggered by the P wave of the ECG, so one cycle is the period between two successive P waves. It runs through seven phases in a fixed order: atrial systole, isovolumetric contraction, rapid ejection, reduced ejection, isovolumetric relaxation, rapid filling, and reduced filling. As heart rate rises the whole cycle shortens, but not evenly: at 75/min the cycle is 0.8 sec (0.3 sec systole, 0.5 sec diastole); at 200/min it falls to 0.3 sec, and systole and diastole become almost equal (0.15 sec each), because the shortening is taken disproportionately out of diastole.',
      objective: 'State the seven phases of the cardiac cycle in their normal order beginning with atrial systole, name the ECG event that initiates the cycle, and explain why a rising heart rate shortens the cycle mainly at the expense of diastole rather than systole.',
      pitfall: "Assuming heart rate shortens systole and diastole by the same proportion. The book's own numbers show diastole absorbing almost all of the shortening: between 75/min and 200/min, ventricular systole only halves (0.3 to 0.15 sec) while ventricular diastole falls to less than a third (0.5 to 0.15 sec).",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Seven phases of the cardiac cycle', 'Effect of tachycardia on diastole'],
    },
    {
      key: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      label: 'Every cardiac valve is briefly closed twice a cycle — during isovolumetric contraction (making the first heart sound) and isovolumetric relaxation (making the second) — while the AV valves stay open through atrial systole and both filling phases',
      definition: "Valve state tracks ventricular pressure against atrial and aortic/pulmonary pressure through the seven phases. In atrial systole the AV valves are already open (blood is being pushed from atria into ventricles) and the semilunar valves stay closed. Isovolumetric (isometric) ventricular contraction begins the instant rising ventricular pressure exceeds atrial pressure and slams the AV valves shut; the semilunar valves are not yet open because ventricular pressure has not yet exceeded aortic/pulmonary pressure, so for this one phase every valve is closed at once, and the AV valve closure produces the first heart sound. Once ventricular pressure exceeds the great-vessel pressure, the semilunar valves open and rapid then reduced ejection follow, with the AV valves held shut throughout. Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure and slams the semilunar valves shut, producing the second heart sound; the AV valves are not yet open because ventricular pressure is still above atrial pressure, so every valve is closed a second time in the cycle. Once ventricular pressure falls below atrial pressure, the AV valves open again and rapid then reduced ventricular filling follow, with the semilunar valves held shut throughout — so, across the whole cycle, the AV valves are open during atrial systole, rapid filling and reduced filling, and closed only during the two ejection phases and the two isovolumetric phases together with the semilunar valves.",
      objective: 'State which two phases of the cardiac cycle have every cardiac valve closed at once, name the valve closure that produces each heart sound, and list the three phases during which the AV valves are open.',
      pitfall: "Assuming a valve's opening or closing defines only one phase rather than the boundary between two. AV valve closure ends atrial systole and begins isovolumetric contraction (first heart sound); semilunar valve closure ends reduced ejection and begins isovolumetric relaxation (second heart sound) — each sound marks a phase transition, not a phase's whole duration.",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['First heart sound', 'Second heart sound', 'AV valve timing', 'Semilunar valve timing', 'All valves closed phases'],
    },
    {
      key: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      label: 'The aortic pressure curve rises on the ejection-driven anacrotic limb and falls on the catacrotic limb, whose dicrotic notch and dicrotic wave mark aortic valve closure',
      definition: 'The aortic pressure curve traces aortic pressure across one cardiac cycle. Its ascending, "anacrotic", limb coincides with the maximal ejection phase and carries pressure up to about 120 mmHg (systolic arterial blood pressure) — so aortic pressure is highest during rapid (maximal) ventricular ejection, not during any other phase. Its descending, "catacrotic", limb runs through the rest of the cycle down to about 80 mmHg (diastolic arterial blood pressure). On the catacrotic limb, the dicrotic notch is a sharp drop of pressure that ends with closure of the aortic valve at the end of systole; the dicrotic wave that follows it is a small rise of pressure caused by backwardly moving blood bouncing against the now-closed elastic aortic valve during isovolumetric relaxation.',
      objective: 'Name the ascending and descending limbs of the aortic pressure curve, state which pressure value each limb produces, identify rapid ejection as the phase of highest aortic pressure, and explain what causes the dicrotic notch and the dicrotic wave that follows it.',
      pitfall: 'Treating the dicrotic notch and the dicrotic wave as the same event. The notch is the sharp pressure drop at the moment the aortic valve shuts; the wave is the small rebound afterwards, caused by blood bouncing back against the now-closed valve during isovolumetric relaxation.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Anacrotic and catacrotic limbs', 'Dicrotic notch and dicrotic wave', 'Highest aortic pressure phase'],
    },
    {
      key: 'atrial-pressure-curve.a-c-v-waves',
      label: 'The atrial pressure curve rises to an a wave during atrial systole, a smaller c wave when the closed AV valve bulges back into the atrium at the start of isovolumetric ventricular contraction, and a v wave as venous blood fills the atrium against still-closed AV valves — so the a wave, not the c wave, precedes the first heart sound',
      definition: "The atrial pressure curve traces right (or left) atrial pressure across one cardiac cycle and shows three positive waves. The a wave is the largest, produced directly by atrial systole itself; it peaks and is already falling by the time the AV valves slam shut to produce the first heart sound, so the a wave precedes S1, not the reverse. The c wave is a small secondary rise that follows shortly after: it is caused by the closed AV valve bulging backward into the atrium as ventricular pressure rises sharply at the start of isovolumetric ventricular contraction — so it falls just after, not during, atrial systole. The v wave is a third, later rise built up passively as venous blood returns and pools in the atrium while the AV valves are still shut during ventricular systole (isovolumetric contraction through ejection); it peaks around the time the AV valves reopen for filling.",
      objective: 'Name the a, c and v waves of the atrial pressure curve in order, state what produces each one, and identify the a wave — not the c wave — as the wave that precedes the first heart sound.',
      pitfall: "Assuming the c wave is simply part of atrial systole because it comes right after the a wave. The c wave is a ventricular event — AV valve closure bulging into the atrium — that happens once atrial systole has already ended and isovolumetric ventricular contraction has begun.",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['a wave c wave v wave', 'Atrial pressure curve waves', 'Jugular venous pulse waves'],
    },
    {
      key: 'heart-murmurs.turbulent-flow-and-valve-disease',
      label: 'A heart murmur is the audible sound of turbulent blood flow, most often produced by a stenotic or incompetent (regurgitant) cardiac valve',
      definition: "Normal blood flow through the heart is laminar (smooth, silent). A murmur is heard when flow becomes turbulent, which happens when blood is forced through an abnormally narrowed opening (a stenotic valve) or leaks backward through a valve that fails to seal (an incompetent or regurgitant valve). Mild degrees of common physiological states — mild anemia, normal sleep, or a modestly reduced cardiac output on their own — do not generate turbulence of this kind and do not produce a murmur; a murmur points specifically to a mechanical disturbance of flow at a valve (or, less commonly, a large septal defect or vessel narrowing).",
      objective: 'State that a heart murmur is produced by turbulent flow through a diseased (stenotic or regurgitant) valve, and distinguish this from states — mild anemia, sleep, a modest fall in cardiac output — that do not by themselves cause turbulence.',
      pitfall: 'Assuming any change in flow volume or rate is enough to cause a murmur. It is the disturbance of smooth (laminar) flow, typically by a narrowed or leaking valve, that generates the turbulence murmurs are made of — not the mere fact that flow has increased, decreased, or slowed.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Mechanism of heart murmurs', 'Turbulent flow and murmurs'],
    },
    {
      key: 'second-heart-sound.inspiratory-splitting-mechanism',
      label: 'Physiological splitting of the second heart sound widens during inspiration because the negative intrathoracic pressure of inspiration increases venous return to the right heart, delaying pulmonary valve closure relative to aortic valve closure',
      definition: "The second heart sound is normally made of two closely spaced components: aortic valve closure (A2) followed very shortly by pulmonary valve closure (P2). During inspiration, the fall in intrathoracic pressure increases venous return into the right side of the heart, which increases right ventricular stroke volume and prolongs right ventricular ejection; this delays pulmonary valve closure and widens the gap between A2 and P2, producing audible physiological splitting. During expiration the two components move back together and the split narrows or disappears. The delay is on the pulmonary side (P2), not because aortic valve closure is brought forward or because left ventricular stroke volume changes.",
      objective: 'Explain why physiological splitting of the second heart sound widens during inspiration, naming the delayed pulmonary valve closure (P2) as the mechanism, driven by increased right-heart venous return.',
      pitfall: 'Attributing inspiratory splitting to a change on the aortic (left-sided) side of the second heart sound. The delay is on the pulmonary side: inspiration selectively increases right ventricular filling and ejection time, delaying P2, while A2 timing changes comparatively little.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Physiological splitting of S2', 'Inspiratory splitting of second heart sound'],
    },
    {
      key: 'av-node.conduction-delay-function',
      label: "The atrioventricular (AV) node's relatively slow conduction delays the impulse just long enough for atrial systole to finish topping up ventricular filling before ventricular contraction begins",
      definition: "Conduction through the AV node is far slower than through atrial or ventricular muscle or the specialized conducting fibers, producing an AV nodal delay of roughly 0.1 second between atrial and ventricular excitation. This delay is physiologically purposeful: it holds back ventricular depolarisation just long enough for atrial systole — the final active phase of ventricular filling — to be completed and for that extra blood to be added to ventricular volume before the ventricles contract. Without this delay, the ventricles would begin contracting while the atria were still actively emptying into them, and the atrial contribution to filling would be lost rather than captured.",
      objective: 'State that the physiologic function of the AV node’s slow conduction is to delay ventricular excitation long enough for atrial systole to complete ventricular filling before contraction begins.',
      pitfall: 'Treating the AV nodal delay as a mere transmission inefficiency rather than a timed, functional pause. Its slowness is exactly what synchronises the end of active ventricular filling (atrial systole) with the start of ventricular contraction.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['AV nodal delay function', 'Purpose of AV node conduction delay'],
    },
    {
      key: 'fourth-heart-sound.atrial-systole-origin',
      label: 'The fourth heart sound is produced by atrial systole and is not normally heard in a healthy heart',
      definition: "The fourth heart sound (S4), when present, is a low-pitched sound produced by atrial systole — specifically, blood being forced by atrial contraction into a ventricle whose wall is stiffer or less compliant than normal. It is not a normal finding: a healthy, compliant ventricle accepts the atrial contribution to filling without generating an audible sound, so S4 is not normally clearly audible and its presence usually points to reduced ventricular compliance (for example from ventricular hypertrophy).",
      objective: 'State that the fourth heart sound is produced by atrial systole and explain why it is not normally audible in a healthy heart.',
      pitfall: 'Confusing the fourth heart sound with the first heart sound because both relate to events around atrial systole and AV valve behaviour. S1 is produced by AV valve closure at the start of isovolumetric ventricular contraction; S4, when audible, is produced earlier, by atrial systole itself pushing blood into a stiff ventricle.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Fourth heart sound S4', 'Origin of S4'],
    },
    // Same concept as `atria.functions-beyond-pumping` in
    // `physiology-circulatory-control-hemorrhagic-shock.ts` (Basic
    // Mechanisms of Circulatory Control leaf) -- declared identically here
    // so this file's own atrial-filling-percentage row can share it, per
    // build-batches.ts's cross-leaf concept merge (first leaf's definition
    // wins). This is a reuse of an *existing* concept for a Cardiac
    // Function-tagged bank row, not new authoring of that other, deliberately
    // unclaimed cluster; keep the two copies in sync if either is edited.
    {
      key: "atria.functions-beyond-pumping",
      label: "Beyond pumping blood into the ventricles, the atria act as venous reservoirs during ventricular systole, contribute roughly 30% of ventricular filling through atrial systole, and carry stretch receptors that trigger cardiac reflexes",
      definition: "The atria have three functions beyond acting as a simple entry chamber. First, while the AV valves are shut throughout ventricular systole, venous blood returning from the body has nowhere to go but the atria, which act as a reservoir that accumulates it until the AV valves reopen. Second, atrial systole is an active top-up of ventricular filling, normally contributing roughly the last 30% of end-diastolic volume on top of the passive filling that came before it. Third, the atria — especially the right atrium — carry stretch (low-pressure) receptors that trigger cardiac reflexes, including reflex tachycardia when atrial filling rises (the Bainbridge reflex) and secretion of atrial natriuretic peptide when atrial stretch is sustained.",
      objective: "State the three functions of the atria beyond receiving venous blood: acting as a reservoir during ventricular systole, contributing roughly 30% of ventricular filling via atrial systole, and carrying stretch receptors for cardiac reflexes.",
      pitfall: "Treating the atria as passive holding chambers with no active role. Atrial systole is an active contraction contributing a real fraction of ventricular filling, and atrial stretch receptors actively drive reflexes rather than merely sensing pressure for no functional purpose.",
      subject: "cvs",
      primary: "DIS-PHY-T02",
      secondary: [],
      modulePath: "104 CPS > Physiology > Cardiovascular System > Basic Mechanisms of Circulatory Control",
      type: "mechanism",
      aliases: ["Functions of the atria", "Atrial reservoir function", "Atrial stretch receptors"],
    },
  ],

  questions: [
    {
      key: 'which-phase-of-the-cardiac-cycle-is-absent-if-there-is-no-p-656477fd',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that atrial systole depends on the P wave and is absent without it.',
      explanations: {
        A: 'The cardiac cycle is initiated by the P wave, which represents atrial depolarisation; without a P wave there is no atrial contraction, so atrial systole is the phase that is absent.',
        B: 'Isovolumetric ventricular contraction is triggered by the QRS complex (ventricular depolarisation), not the P wave, so it can still occur without a P wave.',
        C: 'Reduced ventricular ejection follows ventricular contraction and does not depend on atrial depolarisation.',
        D: 'Rapid ventricular filling is a passive, pressure-driven phase and does not require atrial contraction to occur.',
      },
    },
    {
      key: 'first-heart-sound-occurs-in-c084db9e',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced by AV valve closure at the start of isovolumetric contraction.',
      explanations: {
        A: 'The first heart sound is produced by closure of the AV valves, which happens at the instant rising ventricular pressure exceeds atrial pressure — the event that begins isovolumetric (isometric) contraction.',
        B: 'AV valves are open during atrial systole, not closing; the closure that makes the first heart sound has not yet happened.',
        C: 'Isometric relaxation begins with semilunar, not AV, valve closure — that event produces the second heart sound, not the first.',
        D: 'Maximum (rapid) filling begins with AV valve opening, the opposite event to the valve closure that produces a heart sound.',
      },
    },
    {
      key: 'second-heart-sound-is-due-to-a990b4ad',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that the second heart sound is produced by semilunar valve closure.',
      explanations: {
        A: 'AV valve closure produces the first heart sound, not the second.',
        B: 'The second heart sound is produced by closure of the semilunar (aortic and pulmonary) valves, at the instant falling ventricular pressure drops below aortic/pulmonary pressure — the event that begins isovolumetric relaxation.',
        C: 'Not a named cardiac valve or valve group — a corrupted option with no anatomical referent.',
        D: 'AV valve opening is a silent event that begins ventricular filling, not a valve closure and not the source of a heart sound.',
      },
    },
    {
      key: 'at-the-beginning-of-which-phase-of-the-cardiac-cycle-does-th-6b54a811',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Place the second heart sound at the start of isovolumetric ventricular relaxation.',
      explanations: {
        A: 'Isovolumetric contraction begins with AV, not semilunar, valve closure, producing the first heart sound, not the second.',
        B: 'Reduced ventricular ejection is already underway with the semilunar valves open; no valve closes at its start.',
        C: 'Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure, closing the semilunar valves and producing the second heart sound.',
        D: 'Rapid ventricular filling begins with AV valve opening, an opening rather than the closing event a heart sound requires.',
      },
    },
    {
      key: 'av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the AV valves are open during atrial systole (and both filling phases).',
      explanations: {
        A: 'Isometric contraction begins exactly because the AV valves have just closed; they stay shut throughout this phase.',
        B: 'The AV valves are open throughout atrial systole, allowing atrial contraction to push blood into the ventricles — they only close at its end, marking the start of isovolumetric contraction.',
        C: 'The protodiastolic interval falls within reduced ejection, with the semilunar valves open and the AV valves still closed.',
        D: 'Maximum ejection has the semilunar valves open and the AV valves closed, the opposite valve state to atrial systole.',
      },
    },
    {
      key: 'all-cardiac-valves-are-closed-in-a22d5c2c',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 3 options survived extraction (A isometric relaxation, B atrial systole, C protodiastole) — below the platform\'s 4-to-5-option import contract. The correct fact (every valve is closed during isometric relaxation, and equally during isometric contraction) is already tested cleanly by this leaf\'s own first-heart-sound-occurs-in-c084db9e and av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce questions.',
    },
    {
      key: 'all-are-involved-in-ventricular-isometric-contraction-phase-3e2ad1bc',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Recall of a false statement',
      learningObjective: 'Identify that ventricular volume stays constant, not decreases, during isovolumetric contraction, as the false statement among its other true characters.',
      explanations: {
        A: 'True of isovolumetric contraction, so not the exception. With both AV and semilunar valves shut and the ventricle contracting against a closed system, pressure inside it rises very rapidly.',
        B: "The exception, and the answer. Isovolumetric ('isovolumic') contraction is defined by an unchanged ventricular volume — both valve sets are shut, so no blood can enter or leave — not a decreasing one; volume only starts falling once the semilunar valves open for ejection.",
        C: 'True, so not the exception. The first heart sound, produced by AV valve closure, occurs at the very start of this phase.',
        D: 'True, so not the exception. The QRS complex (ventricular depolarisation) precedes and triggers ventricular contraction, starting a short interval (about 0.02 sec) before isovolumetric contraction itself begins.',
      },
    },
    {
      key: 'during-isovolumetric-ventricular-contraction-0eb895ff',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced during isovolumetric ventricular contraction.',
      explanations: {
        A: 'Rapid filling is a diastolic phase that follows AV valve opening, well after isovolumetric contraction has ended.',
        B: 'The first heart sound, produced by AV valve closure, is generated at the start of isovolumetric ventricular contraction.',
        C: 'Maximal ejection of blood happens once the semilunar valves open, which is the phase that follows isovolumetric contraction, not this phase itself — by definition no blood is ejected while the ventricle is sealed shut.',
        D: 'The opposite is true: tension (pressure) rises rapidly while volume stays constant during isovolumetric contraction, not the reverse.',
      },
    },
    {
      key: 'during-isovolumetric-ventricular-contraction-a-rapid-filling-ae3cfd14',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced during isovolumetric ventricular contraction.',
      explanations: {
        A: 'Rapid filling is a diastolic phase that follows AV valve opening, well after isovolumetric contraction has ended.',
        B: 'The first heart sound, produced by AV valve closure, is generated at the start of isovolumetric ventricular contraction.',
        C: 'Maximal ejection of blood happens once the semilunar valves open, which is the phase that follows isovolumetric contraction, not this phase itself — by definition no blood is ejected while the ventricle is sealed shut.',
        D: 'The opposite is true: tension (pressure) rises rapidly while volume stays constant during isovolumetric contraction, not the reverse.',
      },
    },
    {
      key: 'during-the-isometric-contraction-pnase-of-cardiac-cycle-what-f8195c12',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that ventricular volume remains unchanged during isometric (isovolumetric) contraction.',
      explanations: {
        A: 'Volume does not decrease here — both AV and semilunar valves are shut, so no blood can leave the ventricle yet; volume only starts decreasing once ejection (semilunar valve opening) begins.',
        B: 'Volume cannot increase either, since the AV valves are already shut and no blood can enter.',
        C: "Ventricular volume remains unchanged (isovolumetric/isometric) throughout this phase, because both valve sets are closed while the ventricle's rising pressure has not yet reached the level needed to open the semilunar valves.",
        D: 'Volume does not decrease during this phase at all — rising intraventricular pressure is exactly what defines it, but with volume held constant, not falling, until ejection begins.',
      },
    },
    {
      key: 'regarding-the-isovolumetric-contraction-phase-of-cardiac-cyc-325b52a8',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Hard',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that ventricular volume remains unchanged throughout isovolumetric contraction.',
      explanations: {
        A: 'Isovolumetric contraction starts with sudden closure of the AV valves, not the semilunar valves — AV valve closure is what produces the first heart sound at this phase\'s start.',
        B: 'By the end of this phase, left ventricular pressure has risen to about aortic diastolic pressure (roughly 80 mmHg) — the level it must reach to force the semilunar valves open — not 10 mmHg, which is far too low.',
        C: "Ventricular volume remains unchanged throughout isovolumetric contraction — this is exactly what 'isovolumetric' means, since both valve sets are shut and no blood can enter or leave.",
        D: 'Atrial pressure does not fall to its minimum here; the small "c wave" rise (from the closed AV valve bulging back into the atrium) occurs around this phase, and atrial pressure reaches its true minimum later, during rapid ejection (the "x descent").',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-is-aortic-pressure-h-39d3d842',
      conceptKey: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that aortic pressure peaks during rapid (maximal) ventricular ejection.',
      explanations: {
        A: 'Aortic pressure is still at its diastolic low during isovolumetric contraction — the semilunar valves have not opened yet, so no blood has entered the aorta to raise it.',
        B: 'Aortic pressure rises on the ejection-driven anacrotic limb, which coincides with rapid (maximal) ventricular ejection, reaching its peak (about 120 mmHg, systolic pressure) here.',
        C: 'Reduced ejection falls on the descending catacrotic limb, after the pressure peak of rapid ejection has already passed.',
        D: 'Aortic pressure is already declining toward its diastolic minimum during rapid ventricular filling, long after the ejection-phase peak.',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-is-ventricular-volum-e85c1847',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that ventricular volume is at its lowest, held constant, throughout isovolumetric relaxation.',
      explanations: {
        A: 'Ventricular volume is at its highest, not lowest, at the start of isovolumetric contraction — filling has just finished and ejection has not yet begun.',
        B: 'Ventricular volume is still falling throughout rapid ejection as blood leaves the ventricle; it has not yet reached its lowest point.',
        C: 'Ventricular volume continues to fall through reduced ejection, reaching its true minimum only at this phase\'s very end.',
        D: 'Ventricular volume reaches its minimum (the end-systolic volume) at the end of ejection and then stays fixed at that lowest value throughout isovolumetric relaxation, since both valve sets are shut and no blood can enter until the AV valves open for filling.',
      },
    },
    {
      key: 'all-are-involved-in-ventricular-filling-except-4c80661d',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Recall of a false statement',
      learningObjective: 'Identify maximal ejection as not a filling phase, against atrial systole, rapid filling and reduced filling, which are.',
      explanations: {
        A: 'Atrial systole is involved in ventricular filling, so not the exception — it is the final, active top-up of ventricular volume before the AV valves close.',
        B: 'The exception, and the answer. Maximum (rapid) ejection is when blood leaves the ventricle through the open semilunar valves, the opposite process to filling.',
        C: 'Maximum (rapid) filling is involved in ventricular filling by definition, so not the exception — it is the phase of fastest AV-valve-driven inflow.',
        D: 'Reduced filling (diastasis) is involved in ventricular filling, so not the exception — it is the slower continuation of filling before the next atrial systole.',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-does-the-mitral-valv-839de1d0',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, B, C) — option C's text is itself a garbled OCR merge of two option texts ('Rapid ventricular ejection' bled together with 'Rapid ventricular filling'), so only 3 distinct answer choices remain, below the platform's 4-to-5-option import contract. The mitral (AV) valve opening at the start of rapid ventricular filling is already established by this leaf's own av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce question and concept.",
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-docs-ventricular-pre-169c9804',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, B, C) — option C's text is itself a garbled OCR merge of two option texts ('Rapid ventricular ejection' bled together with 'Isovolumetric ventricular relaxation'), so only 3 distinct answer choices remain, below the platform's 4-to-5-option import contract. The fact that ventricular pressure rises while volume stays constant during isovolumetric ventricular contraction is already established by this leaf's own during-isovolumetric-ventricular-contraction-0eb895ff and during-the-isometric-contraction-pnase-of-cardiac-cycle-what-f8195c12 questions.",
    },
    {
      key: 'ay-valves-are-opened-in-77911318',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that the AV valves are open during atrial systole.',
      explanations: {
        A: 'The AV valves are already open before isometric (isovolumetric) contraction begins — that phase starts precisely when rising ventricular pressure slams them shut.',
        B: 'The AV valves are open during atrial systole, since atrial contraction is actively pushing blood through them into the ventricles.',
        C: 'By the protodiastolic phase the AV valves are still closed — they only reopen once ventricular pressure has fallen below atrial pressure at the end of isovolumetric relaxation.',
        D: 'The AV valves are shut throughout maximum (rapid) ejection, since ventricular pressure is well above atrial pressure while blood is being ejected through the open semilunar valves.',
      },
    },
    {
      key: 'concerning-the-atrial-pressure-curve-a-c-wave-occurs-during-8e579abd',
      conceptKey: 'atrial-pressure-curve.a-c-v-waves',
      difficulty: 'Hard',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that the a wave of the atrial pressure curve, produced by atrial systole, precedes the first heart sound.',
      explanations: {
        A: 'The c wave is not produced by atrial systole itself — it follows shortly after, caused by the closed AV valve bulging back into the atrium as isovolumetric ventricular contraction begins.',
        B: 'The v wave is built up passively during ventricular systole (isovolumetric contraction through ejection), not specifically during isovolumetric contraction alone, and it peaks later, near AV valve reopening.',
        C: 'The a wave, produced directly by atrial systole, peaks and is already falling by the time the AV valves shut to produce the first heart sound — so it precedes S1, making this the true statement.',
        D: 'The v wave occurs as the atrium fills passively while the AV valves stay shut during ventricular systole, not during the ventricular filling phases themselves — filling only begins once the AV valves reopen at the v wave\'s peak.',
      },
    },
    {
      key: 'concerning-the-cardiac-cycle-232c610b',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that a rising heart rate shortens the diastolic phase of the cardiac cycle disproportionately more than the systolic phase.',
      explanations: {
        A: 'The opposite is true at normal resting heart rates: diastole is longer than systole (about 0.5 sec versus 0.3 sec at 75/min).',
        B: 'Systole and diastole are not equal in duration at rest; they only approach near-equality at very high heart rates, once tachycardia has disproportionately shortened diastole.',
        C: 'True, and the answer: as heart rate rises the whole cycle shortens, but diastole absorbs almost all of the shortening — for example, between 75/min and 200/min, systole only halves while diastole falls to less than a third.',
        D: 'Atria and ventricles do not spend a shared 0.4 sec relaxed together; total diastole at rest is closer to 0.5 sec, and the specific figure of 0.4 sec for combined relaxation is not the established value.',
      },
    },
    {
      key: 'murmur-appears-in-the-following-condition-ab3d9e41',
      conceptKey: 'heart-murmurs.turbulent-flow-and-valve-disease',
      difficulty: 'Easy',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that a stenotic or incompetent cardiac valve, by producing turbulent flow, is the classic cause of a heart murmur.',
      explanations: {
        A: 'Mild anemia does not reduce blood viscosity or raise flow velocity enough to generate turbulence; only more severe anemia can produce a flow murmur, so mild anemia alone is not a cause.',
        B: 'Stenosis of a cardiac valve narrows the opening blood must cross, disturbing smooth laminar flow into turbulence — the classic mechanism of a heart murmur, making this the answer.',
        C: 'Sleep does not by itself disturb the smoothness of blood flow through the heart, so it is not a cause of murmurs.',
        D: 'A decrease in cardiac output changes flow volume, not the smoothness of flow through a normal valve, so it does not by itself generate the turbulence a murmur requires.',
      },
    },
    {
      key: 'normal-splitting-of-the-second-heart-sound-into-two-componen-cdc464c1',
      conceptKey: 'second-heart-sound.inspiratory-splitting-mechanism',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Explain that inspiration widens physiological splitting of the second heart sound by delaying pulmonary valve closure.',
      explanations: {
        A: 'Aortic valve closure (A2) is not delayed by inspiration; the widening of the split during inspiration comes from a delay on the pulmonary side, not the aortic side.',
        B: 'Mitral valve opening is an event of early diastole unrelated to the timing of the second heart sound\'s two components, which are both valve-closure (not valve-opening) events.',
        C: 'Correct: inspiration increases venous return to the right heart, prolonging right ventricular ejection and delaying pulmonary valve closure (P2) relative to aortic valve closure (A2), which widens the split.',
        D: 'It is right ventricular, not left ventricular, filling and ejection that inspiration increases; left ventricular stroke volume is not what drives the wider splitting heard on inspiration.',
      },
    },
    {
      key: 'the-incisura-or-diacrotic-notch-in-the-aortic-pressure-curve-3707d6fa',
      conceptKey: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      difficulty: 'Moderate',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that the dicrotic notch of the aortic pressure curve coincides with aortic valve closure and the second heart sound.',
      explanations: {
        A: 'Its mechanism is well established, not unknown: the notch is the sharp pressure drop that ends with closure of the aortic valve at the end of systole.',
        B: 'The dicrotic notch is a normal feature of every aortic pressure curve, not a marker of cardiovascular disease.',
        C: 'Correct: the dicrotic notch marks aortic valve closure at the end of systole, the same event that produces the second heart sound, so the two coincide.',
        D: 'The dicrotic notch is not selectively absent in arteriosclerosis; a stiffened arterial wall alters the pressure waveform but does not remove the notch produced by valve closure.',
      },
    },
    {
      key: 'the-physiologic-function-of-the-relatively-slow-conduction-t-463f8c70',
      conceptKey: 'av-node.conduction-delay-function',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the AV node\'s slow conduction delays ventricular excitation to allow ventricular filling (via atrial systole) to complete before contraction.',
      explanations: {
        A: 'Runoff of blood from the aorta to the arteries happens throughout diastole via elastic recoil of the aortic wall, and has nothing to do with the timing purpose of AV nodal delay.',
        B: 'Venous return to the atria is continuous and is not what the AV nodal delay is timed to protect; the delay concerns handing atrial contraction\'s contribution on to the ventricles, not filling the atria themselves.',
        C: 'Correct: the AV nodal delay holds back ventricular excitation just long enough for atrial systole to finish topping up ventricular filling before ventricular contraction begins.',
        D: 'Ventricular contraction is the event that follows the AV nodal delay, not something the delay itself allows time for — the delay is about what happens before contraction, namely completing filling.',
      },
    },
    {
      key: 'the-shortest-phase-in-cardiac-cycle-is-85caf56e',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Recall of a true statement',
      learningObjective: 'Identify the protodiastolic phase as the shortest phase of the cardiac cycle.',
      explanations: {
        A: 'Maximum (rapid) ejection occupies a substantial share of systole and is not the shortest phase.',
        B: 'Reduced ejection, the second part of the ejection period, likewise takes up more time than the brief protodiastolic phase.',
        C: 'Maximum (rapid) filling is a comparatively brief but still longer phase than the protodiastolic phase.',
        D: 'The protodiastolic phase — the brief interval right at the end of ejection, just before the semilunar valves shut — is the shortest phase of the cardiac cycle, making this the answer.',
      },
    },
    {
      key: 'which-of-the-following-is-the-normal-order-arrangement-of-ca-ae2b57bd',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Hard',
      questionType: 'Recall of a true statement',
      learningObjective: 'Arrange rapid filling, reduced filling, atrial systole and isovolumetric contraction in their correct cyclic order.',
      explanations: {
        A: 'This order misplaces isovolumetric relaxation (a phase that precedes rapid filling, not one that follows atrial systole) into the sequence, breaking the true cyclic order.',
        B: 'Correct: starting from rapid filling and continuing forward through the cycle, the true order is rapid filling, then reduced filling, then atrial systole, then isovolumetric contraction — exactly matching the seven-phase sequence.',
        C: 'This order places isovolumetric relaxation and rapid ejection out of sequence relative to atrial systole and rapid filling, which does not match the true cyclic order.',
        D: 'This order repeats an ejection phase out of place and omits reduced filling from its correct position, which does not match the true cyclic order.',
      },
    },
    {
      key: 'ventricular-pressure-is-higher-than-the-atrial-pressure-in-a-087f234e',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Recall of a false statement',
      learningObjective: 'Identify atrial systole as the one phase where ventricular pressure is not higher than atrial pressure.',
      explanations: {
        A: 'During isometric (isovolumetric) contraction, ventricular pressure has already risen above atrial pressure — that rise is exactly what slams the AV valves shut to begin the phase.',
        B: 'The exception, and the answer: during atrial systole, atrial pressure is briefly higher than ventricular pressure, since atrial contraction is actively pushing blood forward through the still-open AV valves.',
        C: 'During maximum ejection, ventricular pressure is at its highest and is above both atrial and aortic pressure, driving blood forward through the open semilunar valves.',
        D: 'During reduced ejection, ventricular pressure is still above atrial pressure, even as it has begun to fall from its peak.',
      },
    },
    {
      key: 'which-of-the-following-happens-during-atrial-systole-of-the-2beef02f',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that the aortic (semilunar) valve remains closed throughout atrial systole.',
      explanations: {
        A: 'The first heart sound is produced later, by AV valve closure at the start of isovolumetric ventricular contraction, not during atrial systole itself.',
        B: 'Atrial systole contributes roughly the last 15-30% of ventricular filling, not over 70% — most filling happens passively during rapid filling, before atrial systole.',
        C: 'The AV valves are open, not closed, during atrial systole, since atrial contraction is actively pushing blood through them into the ventricles.',
        D: 'Correct: the aortic (and pulmonary) valve stays closed throughout atrial systole, since ventricular pressure has not yet exceeded aortic/pulmonary pressure.',
      },
    },
    {
      key: 'which-of-the-following-is-responsible-for-the-fourth-heart-s-4009c200',
      conceptKey: 'fourth-heart-sound.atrial-systole-origin',
      difficulty: 'Moderate',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that atrial systole produces the fourth heart sound.',
      explanations: {
        A: 'Opening of the mitral valve is a silent event in the normal heart and is not the origin of the fourth heart sound.',
        B: 'Correct: the fourth heart sound is produced by atrial systole, when blood is forced by atrial contraction into a ventricle whose wall is stiffer or less compliant than normal.',
        C: 'Opening of a semilunar valve is likewise a normally silent event and does not produce the fourth heart sound.',
        D: 'Rapid ventricular filling is a passive, normally silent phase; it is atrial systole, the active phase that follows it, that produces the fourth heart sound when audible.',
      },
    },
    {
      key: 'the-diastolic-blood-pressure-will-increase-e2037aa1',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Hard',
      questionType: 'Mechanism',
      learningObjective: 'Explain that tachycardia raises diastolic blood pressure by shortening diastole and leaving less time for aortic runoff before the next beat.',
      explanations: {
        A: 'A markedly increased stroke volume raises systolic pressure, by ejecting more blood per beat, rather than specifically raising diastolic pressure.',
        B: 'Anemia lowers blood viscosity and increases cardiac output, tending to widen pulse pressure rather than specifically raise diastolic pressure.',
        C: 'An increase in arteriolar diameter lowers peripheral resistance, which lowers diastolic pressure by letting blood run off faster, not raises it.',
        D: 'Correct: tachycardia disproportionately shortens diastole (the cardiac cycle\'s shortening falls mainly on diastole), leaving less time for blood to run off from the arteries before the next beat, so diastolic pressure rises.',
      },
    },
    {
      key: 'a-mild-hemorrhage-will-cause-stroke-volume-to-shift-from-poi-29f14a8f',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The question refers to a ventricular-function/Frank-Starling graph with labelled points X, and options are the bare letters of other points on that figure — no figure was captured by extraction, so the question is not answerable as text, and there is no extracted answer either.',
    },
    {
      key: 'on-the-following-graph-showing-left-ventricular-volume-and-p-a53a02d1',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The question depends on a pressure-volume loop figure with labelled points; no figure was captured by extraction, so the correspondence being asked about cannot be reconstructed from text, and there is no extracted answer either.',
    },
    {
      key: 'the-following-figure-shows-the-jugular-venous-pulse-which-of-f6b115da',
      conceptKey: 'atrial-pressure-curve.a-c-v-waves',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'The question depends on a labelled jugular venous pulse figure that was not captured by extraction, and only 2 of 4 options (B, D) survived transcription — well below the platform\'s 4-to-5-option import contract even before the missing figure is considered.',
    },
    {
      key: 'the-fourth-heart-sound-is-normally-clearly-audible-14328cd4',
      conceptKey: 'fourth-heart-sound.atrial-systole-origin',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option A ("Is normally clearly audible") was bled into the stem field by OCR rather than captured as a selectable option, leaving only 3 selectable choices (B, C, D) — below the platform\'s 4-to-5-option import contract. The fact that atrial systole produces the fourth heart sound is already established by this leaf\'s own which-of-the-following-is-responsible-for-the-fourth-heart-s-4009c200 question.',
    },
    {
      key: 'the-longest-phase-in-cardiac-cycle-is-78f81536',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 3 options survived extraction (A, B, C) — the fourth (protodiastolic-phase-adjacent) distractor is missing entirely, below the platform\'s 4-to-5-option import contract.',
    },
    {
      key: 'which-of-the-following-happens-during-atrial-systole-of-the-cd69f5c8',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Option A ("The first heart sound occurs") was bled into the stem field by OCR rather than captured as a selectable option, leaving only 3 selectable choices (B, C, D) — below the platform\'s 4-to-5-option import contract. The fact that the aortic valve stays closed throughout atrial systole is already established by this leaf\'s own cleanly-extracted which-of-the-following-happens-during-atrial-systole-of-the-2beef02f question.',
    },
    {
      key: 'which-of-the-following-happens-during-rapid-ejection-phase-o-239e492b',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 2 of 4 options (B, D) survived transcription and no answer was extracted or independently recoverable — well below the platform\'s 4-to-5-option import contract.',
    },
    {
      key: 'ventricular-pressure-is-higher-than-the-atrial-pressure-in-a-f2fda77c',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 3 options survived extraction (A, B, C) — the fourth (maximum-ejection) distractor is missing entirely, below the platform\'s 4-to-5-option import contract. The same fact, with all 4 options intact, is already established by this leaf\'s own ventricular-pressure-is-higher-than-the-atrial-pressure-in-a-087f234e question.',
    },
    {
      key: 'which-of-the-following-is-the-normal-order-arrangement-of-ca-0be202e8',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 2 of 4 options (B, D) survived transcription, both further garbled by OCR ("sovolumetric" for "isovolumetric"), well below the platform\'s 4-to-5-option import contract. The same fact, with all 4 options intact, is already established by this leaf\'s own which-of-the-following-is-the-normal-order-arrangement-of-ca-ae2b57bd question.',
    },
    {
      // Bank-tagged leaf: "Pulmonary Compliance" (mistagged; a dicrotic-wave
      // question is Cardiac Function content, not respiratory). Re-routed
      // here rather than authored under the Pulmonary Compliance leaf files,
      // per PROGRESS.md.
      key: 'diacrotic-wave-is-caused-by-1d91da8b',
      conceptKey: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      difficulty: 'Moderate',
      questionType: 'Recall',
      learningObjective: 'State that the dicrotic wave is caused by elastic recoil of the aorta against the newly closed aortic valve.',
      explanations: {
        A: 'Blood continuing to run off into the periphery is what produces the gradual fall of the catacrotic limb overall, not the small secondary rise that specifically follows the dicrotic notch.',
        B: 'Correct. The dicrotic wave is the small rise in aortic pressure that follows the sharper dicrotic notch: once the aortic valve shuts, blood already moving toward it rebounds off the now-closed valve, and the aorta\'s own elastic recoil produces this brief secondary rise in pressure.',
        C: 'Aortic regurgitation is a pathological backflow of blood through an incompetent aortic valve; it is not the mechanism of the normal dicrotic wave, which occurs even with a perfectly competent valve.',
        D: 'The dicrotic wave reflects a brief further stretch from rebounding blood, not a sustained increase in aortic distension as such; describing it as increased distension does not capture that the wave comes specifically from elastic recoil against the closed valve.',
      },
    },

    // --- run43: 3 of the Cardiac Function cluster's 12 remaining ---
    {
      key: 'diacrotic-notch-is-due-to-e9c90ebf',
      conceptKey: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      difficulty: 'Easy',
      questionType: 'Recall',
      learningObjective: 'State that the dicrotic notch is caused by sudden closure of the aortic valve.',
      explanations: {
        A: 'Closure of the AV valves produces the first heart sound at the start of ventricular systole, an entirely different event from the dicrotic notch, which sits on the aortic pressure curve at the end of systole.',
        B: 'Correct. The dicrotic notch is the sharp drop on the descending (catacrotic) limb of the aortic pressure curve caused by the sudden closure of the aortic valve at the end of ejection, once ventricular pressure has fallen below aortic pressure.',
        C: 'A decrease in aortic pressure is what is observed around the notch, but the direct mechanical cause of the notch itself is the aortic valve slamming shut, not the pressure fall in isolation.',
        D: 'A marked decrease in ventricular pressure is a related, concurrent event on the other side of the now-closed aortic valve, but the dicrotic notch is specifically a feature of the aortic pressure trace, directly caused by aortic valve closure.',
      },
    },
    {
      key: 'during-the-reduced-ejection-phase-which-one-of-the-following-a7159cd9',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Recall',
      learningObjective: 'State that the AV valves stay closed throughout the reduced ejection phase, along with the rest of ventricular systole.',
      explanations: {
        A: 'Left atrial pressure is rising, not falling, during reduced ejection: the AV valves are shut, so venous blood returning to the atrium accumulates there with nowhere else to go, building the v wave of the atrial pressure curve.',
        B: 'Aortic pressure has not yet fallen below left ventricular pressure during reduced ejection — the two remain close, with a small forward pressure gradient still driving the tail of ejection; aortic pressure only clearly overtakes ventricular pressure at the transition into isovolumetric relaxation, ending ejection.',
        C: 'Correct. The AV valves are held shut throughout both ejection phases (rapid and reduced), since ventricular pressure remains above atrial pressure the whole time — they only reopen once ventricular pressure falls below atrial pressure during rapid filling.',
        D: 'Left ventricular pressure is not constant during reduced ejection; it has already passed its peak (reached during rapid ejection) and is beginning to fall as the rate of ejection slows.',
      },
    },
    {
      key: 'the-atrial-component-of-ventricular-filling-is-46a00baf',
      conceptKey: 'atria.functions-beyond-pumping',
      difficulty: 'Moderate',
      questionType: 'Recall',
      learningObjective: 'State that atrial systole normally contributes roughly 30% of ventricular filling.',
      explanations: {
        A: '10% understates the atrial contribution; atrial systole normally tops up roughly 30% of end-diastolic volume, not a tenth of it.',
        B: 'Correct. Atrial systole is an active top-up of ventricular filling that normally contributes roughly the last 30% of end-diastolic volume, on top of the passive filling (rapid and reduced filling phases) that fills the rest.',
        C: '50% overstates the atrial contribution; the larger share of ventricular filling happens passively, before atrial systole ever begins, chiefly during the rapid filling phase.',
        D: '80% overstates the atrial contribution even further; passive filling, not atrial systole, is responsible for most of ventricular filling.',
      },
    },
  ],
}
