import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Physiology Cardiovascular System — Cardiac Function',
  modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
  articleId: 'ART-104-PHY-CARDIAC-CYCLE-AND-HEART-SOUNDS',

  concepts: [
    {
      key: 'cardiac-cycle.seven-phase-sequence-and-duration',
      label: 'The cardiac cycle runs through a fixed order of seven phases starting with atrial systole, and a rising heart rate shortens the cycle mainly by shortening diastole, not systole',
      definition: 'The cardiac cycle is triggered by the P wave of the ECG, so one cycle is the period between two successive P waves. It runs through seven phases in a fixed order: atrial systole, isovolumetric contraction, rapid ejection, reduced ejection, isovolumetric relaxation, rapid filling, and reduced filling. As heart rate rises the whole cycle shortens, but not evenly: at 75/min the cycle is 0.8 sec (0.3 sec systole, 0.5 sec diastole); at 200/min it falls to 0.3 sec, and systole and diastole become almost equal (0.15 sec each), because the shortening is taken disproportionately out of diastole.',
      objective: 'State the seven phases of the cardiac cycle in their normal order beginning with atrial systole, name the ECG event that initiates the cycle, and explain why a rising heart rate shortens the cycle mainly at the expense of diastole rather than systole.',
      pitfall: "Assuming heart rate shortens systole and diastole by the same proportion. The book's own numbers show diastole absorbing almost all of the shortening: between 75/min and 200/min, ventricular systole only halves (0.3 to 0.15 sec) while ventricular diastole falls to less than a third (0.5 to 0.15 sec).",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Seven phases of the cardiac cycle', 'Effect of tachycardia on diastole'],
    },
    {
      key: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      label: 'Every cardiac valve is briefly closed twice a cycle — during isovolumetric contraction (making the first heart sound) and isovolumetric relaxation (making the second) — while the AV valves stay open through atrial systole and both filling phases',
      definition: "Valve state tracks ventricular pressure against atrial and aortic/pulmonary pressure through the seven phases. In atrial systole the AV valves are already open (blood is being pushed from atria into ventricles) and the semilunar valves stay closed. Isovolumetric (isometric) ventricular contraction begins the instant rising ventricular pressure exceeds atrial pressure and slams the AV valves shut; the semilunar valves are not yet open because ventricular pressure has not yet exceeded aortic/pulmonary pressure, so for this one phase every valve is closed at once, and the AV valve closure produces the first heart sound. Once ventricular pressure exceeds the great-vessel pressure, the semilunar valves open and rapid then reduced ejection follow, with the AV valves held shut throughout. Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure and slams the semilunar valves shut, producing the second heart sound; the AV valves are not yet open because ventricular pressure is still above atrial pressure, so every valve is closed a second time in the cycle. Once ventricular pressure falls below atrial pressure, the AV valves open again and rapid then reduced ventricular filling follow, with the semilunar valves held shut throughout — so, across the whole cycle, the AV valves are open during atrial systole, rapid filling and reduced filling, and closed only during the two ejection phases and the two isovolumetric phases together with the semilunar valves.",
      objective: 'State which two phases of the cardiac cycle have every cardiac valve closed at once, name the valve closure that produces each heart sound, and list the three phases during which the AV valves are open.',
      pitfall: "Assuming a valve's opening or closing defines only one phase rather than the boundary between two. AV valve closure ends atrial systole and begins isovolumetric contraction (first heart sound); semilunar valve closure ends reduced ejection and begins isovolumetric relaxation (second heart sound) — each sound marks a phase transition, not a phase's whole duration.",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['First heart sound', 'Second heart sound', 'AV valve timing', 'Semilunar valve timing', 'All valves closed phases'],
    },
  ],

  questions: [
    {
      key: 'which-phase-of-the-cardiac-cycle-is-absent-if-there-is-no-p-656477fd',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that atrial systole depends on the P wave and is absent without it.',
      explanations: {
        A: 'The cardiac cycle is initiated by the P wave, which represents atrial depolarisation; without a P wave there is no atrial contraction, so atrial systole is the phase that is absent.',
        B: 'Isovolumetric ventricular contraction is triggered by the QRS complex (ventricular depolarisation), not the P wave, so it can still occur without a P wave.',
        C: 'Reduced ventricular ejection follows ventricular contraction and does not depend on atrial depolarisation.',
        D: 'Rapid ventricular filling is a passive, pressure-driven phase and does not require atrial contraction to occur.',
      },
    },
    {
      key: 'first-heart-sound-occurs-in-c084db9e',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced by AV valve closure at the start of isovolumetric contraction.',
      explanations: {
        A: 'The first heart sound is produced by closure of the AV valves, which happens at the instant rising ventricular pressure exceeds atrial pressure — the event that begins isovolumetric (isometric) contraction.',
        B: 'AV valves are open during atrial systole, not closing; the closure that makes the first heart sound has not yet happened.',
        C: 'Isometric relaxation begins with semilunar, not AV, valve closure — that event produces the second heart sound, not the first.',
        D: 'Maximum (rapid) filling begins with AV valve opening, the opposite event to the valve closure that produces a heart sound.',
      },
    },
    {
      key: 'second-heart-sound-is-due-to-a990b4ad',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that the second heart sound is produced by semilunar valve closure.',
      explanations: {
        A: 'AV valve closure produces the first heart sound, not the second.',
        B: 'The second heart sound is produced by closure of the semilunar (aortic and pulmonary) valves, at the instant falling ventricular pressure drops below aortic/pulmonary pressure — the event that begins isovolumetric relaxation.',
        C: 'Not a named cardiac valve or valve group — a corrupted option with no anatomical referent.',
        D: 'AV valve opening is a silent event that begins ventricular filling, not a valve closure and not the source of a heart sound.',
      },
    },
    {
      key: 'at-the-beginning-of-which-phase-of-the-cardiac-cycle-does-th-6b54a811',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Place the second heart sound at the start of isovolumetric ventricular relaxation.',
      explanations: {
        A: 'Isovolumetric contraction begins with AV, not semilunar, valve closure, producing the first heart sound, not the second.',
        B: 'Reduced ventricular ejection is already underway with the semilunar valves open; no valve closes at its start.',
        C: 'Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure, closing the semilunar valves and producing the second heart sound.',
        D: 'Rapid ventricular filling begins with AV valve opening, an opening rather than the closing event a heart sound requires.',
      },
    },
    {
      key: 'av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the AV valves are open during atrial systole (and both filling phases).',
      explanations: {
        A: 'Isometric contraction begins exactly because the AV valves have just closed; they stay shut throughout this phase.',
        B: 'The AV valves are open throughout atrial systole, allowing atrial contraction to push blood into the ventricles — they only close at its end, marking the start of isovolumetric contraction.',
        C: 'The protodiastolic interval falls within reduced ejection, with the semilunar valves open and the AV valves still closed.',
        D: 'Maximum ejection has the semilunar valves open and the AV valves closed, the opposite valve state to atrial systole.',
      },
    },
    {
      key: 'all-cardiac-valves-are-closed-in-a22d5c2c',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 3 options survived extraction (A isometric relaxation, B atrial systole, C protodiastole) — below the platform\'s 4-to-5-option import contract. The correct fact (every valve is closed during isometric relaxation, and equally during isometric contraction) is already tested cleanly by this leaf\'s own first-heart-sound-occurs-in-c084db9e and av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce questions.',
    },
  ],
}
