import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Physiology Cardiovascular System — Cardiac Output Formula',
  modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
  articleId: 'ART-104-PHY-CARDIAC-OUTPUT-AND-EXERCISE',

  concepts: [
    {
      key: 'cardiac-output.definition-formula-and-index',
      label: 'Cardiac output is the volume each ventricle pumps per minute, equals heart rate times stroke volume, and is corrected for body size as the cardiac index',
      definition: 'Cardiac output (CO) is the volume of blood pumped by each ventricle per minute, normally about 5 litres/minute in adults. Because CO depends on body size (it is higher in people with a larger body size), it is corrected for size as the cardiac index, calculated by dividing CO in L/min by body surface area in m2; the normal cardiac index is about 3.2 L/min/m2. CO is determined by heart rate (beats per minute) and stroke volume, the volume of blood ejected by each ventricle per beat, so that CO = stroke volume x heart rate.',
      objective: 'State the definition and normal value of cardiac output, write the formula CO = SV x HR, and define cardiac index and its normal value.',
      pitfall: 'Forgetting that cardiac index divides cardiac output by body surface area, not by body weight, and treating "5 L/min" as a fixed constant rather than a value that itself scales with body size.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'definition',
      aliases: ['CO = SV x HR', 'Cardiac index'],
    },
    {
      key: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      label: 'Ejection fraction is the fraction of end-diastolic volume ejected per beat, normally about 55-60% at rest, and is characteristically reduced (around 40% or less) in heart failure',
      definition: 'Ejection fraction (EF) is the stroke volume expressed as a fraction (percentage) of the end-diastolic volume: EF = stroke volume / end-diastolic volume x 100. In a resting healthy adult it is normally about 55-60% — a healthy ventricle ejects roughly three-fifths of the blood it holds at the end of filling, not all of it, leaving an end-systolic volume behind as a reserve. In systolic heart failure, when the ventricle\'s contractile performance falls, ejection fraction falls with it, characteristically to around 40% or less, and is used clinically as the chief marker of that reduced pumping performance.',
      objective: 'State the ejection fraction formula (SV / EDV), its normal resting value (~55-60%), and that it falls characteristically to ~40% or below in heart failure.',
      pitfall: 'Confusing ejection fraction (the fraction of the filled ventricle that is ejected, ~55-60% normally) with stroke volume itself (an absolute volume, ~70 ml) — a normal heart never approaches 100% ejection fraction, because some blood always remains as the end-systolic volume.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'definition',
      aliases: ['Ejection fraction', 'EF in heart failure', 'EF = SV/EDV'],
    },
  ],

  questions: [
    {
      key: 'cardiac-output-is-equal-to-4aebbffc',
      conceptKey: 'cardiac-output.definition-formula-and-index',
      difficulty: 'Easy',
      questionType: 'Definition',
      learningObjective: 'State the formula CO = heart rate x stroke volume.',
      explanations: {
        A: 'This is the formula for mean arterial pressure, not cardiac output — MAP approximates diastolic pressure plus one-third of the pulse pressure.',
        B: 'Cardiac output equals heart rate multiplied by stroke volume, the volume of blood pumped by each ventricle per minute.',
        C: 'This difference is stroke volume itself (end diastolic volume minus end systolic volume), not cardiac output — stroke volume must still be multiplied by heart rate to reach output per minute.',
        D: 'This combination does not correspond to any standard cardiovascular quantity; end diastolic volume minus stroke volume gives end systolic volume, and multiplying that by heart rate is not cardiac output.',
      },
    },
    {
      key: 'cardiac-output-is-equal-to-which-of-the-following-31600b33',
      conceptKey: 'cardiac-output.definition-formula-and-index',
      difficulty: 'Easy',
      questionType: 'Definition',
      learningObjective: 'State the formula CO = heart rate x stroke volume.',
      explanations: {
        A: 'This is the formula for mean arterial pressure, not cardiac output — MAP approximates diastolic pressure plus one-third of the pulse pressure.',
        B: 'Cardiac output equals heart rate multiplied by stroke volume, the volume of blood pumped by each ventricle per minute.',
        C: 'This difference is stroke volume itself (end diastolic volume minus end systolic volume), not cardiac output — stroke volume must still be multiplied by heart rate to reach output per minute.',
        D: 'This combination does not correspond to any standard cardiovascular quantity; end diastolic volume minus stroke volume gives end systolic volume, and multiplying that by heart rate is not cardiac output.',
      },
    },
    {
      key: 'cardiac-output-is-equal-to-which-of-the-following-diastolic-09022e39',
      conceptKey: 'cardiac-output.definition-formula-and-index',
      difficulty: 'Easy',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (B, C, D) — option A's text ('Diastolic BP + 1/3 (Systolic BP - diastolic BP)') was absorbed into the stem itself, mixed with unreadable OCR debris, below the platform's 4-to-5-option import contract. The same fact is already tested cleanly by this leaf's own cardiac-output-is-equal-to-4aebbffc and cardiac-output-is-equal-to-which-of-the-following-31600b33 questions, which preserve all 4 options.",
    },
    {
      key: 'the-following-data-are-obtained-from-a-patient-the-end-diast-40b0894f',
      conceptKey: 'cardiac-output.definition-formula-and-index',
      difficulty: 'Moderate',
      questionType: 'Calculation',
      learningObjective: 'Calculate heart rate from cardiac output and stroke volume (end-diastolic minus end-systolic volume).',
      explanations: {
        A: 'Stroke volume here is 130 - 70 = 60 ml; dividing cardiac output (4800 ml/min) by 60 ml gives 80 beats/minute, not 70.',
        B: 'Stroke volume is end-diastolic minus end-systolic volume: 130 - 70 = 60 ml. Heart rate = cardiac output / stroke volume = 4800 / 60 = 80 beats/minute.',
        C: 'Using the correct stroke volume of 60 ml, cardiac output / stroke volume gives 80, not 90, beats/minute.',
        D: '4800 / 60 = 80, not 100; 100 beats/minute would require a smaller stroke volume than the 60 ml these figures give.',
      },
    },
    {
      key: 'the-following-data-are-obtained-from-a-patient-the-end-diast-70439a00',
      conceptKey: 'cardiac-output.definition-formula-and-index',
      difficulty: 'Moderate',
      questionType: 'Calculation',
      learningObjective: 'Calculate heart rate from cardiac output and stroke volume (end-diastolic minus end-systolic volume).',
      explanations: {
        A: 'Stroke volume here is 120 - 70 = 50 ml; dividing cardiac output (4500 ml/min) by 50 ml gives 90 beats/minute, not 70.',
        B: 'Using the correct stroke volume of 50 ml, cardiac output / stroke volume gives 90, not 80, beats/minute.',
        C: 'Stroke volume is end-diastolic minus end-systolic volume: 120 - 70 = 50 ml. Heart rate = cardiac output / stroke volume = 4500 / 50 = 90 beats/minute.',
        D: '4500 / 50 = 90, not 100; 100 beats/minute would require a smaller stroke volume than the 50 ml these figures give.',
      },
    },
    {
      key: 'a-patient-with-heart-failure-the-ejection-fraction-is-535bf7d6',
      conceptKey: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      difficulty: 'Moderate',
      questionType: 'Clinical application',
      learningObjective: 'State that ejection fraction falls to around 40% in heart failure.',
      explanations: {
        A: 'Ejection fraction characteristically falls to around 40% or less in heart failure, well below the normal resting value of about 55-60%, reflecting the ventricle\'s reduced pumping performance.',
        B: '60% is within the normal resting range, not the reduced value expected in heart failure.',
        C: '70% is above even the normal resting range and is the opposite direction of change from what heart failure produces.',
        D: '80% would be an implausibly high ejection fraction even for a healthy heart, and is the opposite direction of change from heart failure.',
      },
    },
    {
      key: 'a-patient-with-heart-failure-the-ejection-fraction-is-feprat-a02135d6',
      conceptKey: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "The bank's keyed answer is A, but option A's text ('fePrat a 40%') was absorbed into the stem itself during extraction and does not survive as a selectable option — only B, C and D remain, so the answer letter the key names is not among the filled options. The same fact (heart failure EF ~40%) is already tested cleanly by this leaf's own a-patient-with-heart-failure-the-ejection-fraction-is-535bf7d6 question, which preserves all 4 options including A.",
    },
    {
      key: 'in-a-resting-adult-the-ventricular-ejection-fraction-is-1d96e27f',
      conceptKey: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      difficulty: 'Easy',
      questionType: 'Definition',
      learningObjective: 'State the normal resting ventricular ejection fraction (~55-60%).',
      explanations: {
        A: '20% is far below normal — a value this low signals severely reduced ventricular performance, not a resting healthy adult.',
        B: '30% is still well below the normal resting range and would itself indicate significantly impaired ejection.',
        C: '40% is the value characteristic of heart failure, not the normal resting value in a healthy adult.',
        D: 'The normal ventricular ejection fraction at rest in a healthy adult is about 60% — the ventricle ejects roughly three-fifths of its end-diastolic volume each beat.',
      },
    },
    {
      key: 'in-a-resting-adult-what-s-the-normal-ventricular-ejection-fr-12088240',
      conceptKey: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      difficulty: 'Easy',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (B, C, D) — option A's text ('a= 20%') was absorbed into the stem itself, below the platform's 4-to-5-option import contract. The same fact is already tested cleanly by this leaf's own in-a-resting-adult-the-ventricular-ejection-fraction-is-1d96e27f and in-a-resting-adult-what-s-the-normal-ventricular-ejection-fr-dbe6d127 questions, both of which preserve all 4 options.",
    },
    {
      key: 'in-a-resting-adult-what-s-the-normal-ventricular-ejection-fr-dbe6d127',
      conceptKey: 'ventricular-ejection-fraction.normal-value-and-reduction-in-heart-failure',
      difficulty: 'Easy',
      questionType: 'Definition',
      learningObjective: 'State the normal resting ventricular ejection fraction (~55-60%).',
      explanations: {
        A: '20% is far below normal — a value this low signals severely reduced ventricular performance, not a resting healthy adult.',
        B: '30% is still well below the normal resting range and would itself indicate significantly impaired ejection.',
        C: '40% is the value characteristic of heart failure, not the normal resting value in a healthy adult.',
        D: 'The normal ventricular ejection fraction at rest in a healthy adult is about 55%, at the lower end of the commonly quoted 55-60% resting range — the ventricle ejects roughly half to three-fifths of its end-diastolic volume each beat.',
      },
    },
  ],
}
