import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Physiology Cardiovascular System — Cardiac Function',
  modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
  articleId: 'ART-104-PHY-CARDIAC-CYCLE-AND-HEART-SOUNDS',

  concepts: [
    {
      key: 'cardiac-cycle.seven-phase-sequence-and-duration',
      label: 'The cardiac cycle runs through a fixed order of seven phases starting with atrial systole, and a rising heart rate shortens the cycle mainly by shortening diastole, not systole',
      definition: 'The cardiac cycle is triggered by the P wave of the ECG, so one cycle is the period between two successive P waves. It runs through seven phases in a fixed order: atrial systole, isovolumetric contraction, rapid ejection, reduced ejection, isovolumetric relaxation, rapid filling, and reduced filling. As heart rate rises the whole cycle shortens, but not evenly: at 75/min the cycle is 0.8 sec (0.3 sec systole, 0.5 sec diastole); at 200/min it falls to 0.3 sec, and systole and diastole become almost equal (0.15 sec each), because the shortening is taken disproportionately out of diastole.',
      objective: 'State the seven phases of the cardiac cycle in their normal order beginning with atrial systole, name the ECG event that initiates the cycle, and explain why a rising heart rate shortens the cycle mainly at the expense of diastole rather than systole.',
      pitfall: "Assuming heart rate shortens systole and diastole by the same proportion. The book's own numbers show diastole absorbing almost all of the shortening: between 75/min and 200/min, ventricular systole only halves (0.3 to 0.15 sec) while ventricular diastole falls to less than a third (0.5 to 0.15 sec).",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Seven phases of the cardiac cycle', 'Effect of tachycardia on diastole'],
    },
    {
      key: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      label: 'Every cardiac valve is briefly closed twice a cycle — during isovolumetric contraction (making the first heart sound) and isovolumetric relaxation (making the second) — while the AV valves stay open through atrial systole and both filling phases',
      definition: "Valve state tracks ventricular pressure against atrial and aortic/pulmonary pressure through the seven phases. In atrial systole the AV valves are already open (blood is being pushed from atria into ventricles) and the semilunar valves stay closed. Isovolumetric (isometric) ventricular contraction begins the instant rising ventricular pressure exceeds atrial pressure and slams the AV valves shut; the semilunar valves are not yet open because ventricular pressure has not yet exceeded aortic/pulmonary pressure, so for this one phase every valve is closed at once, and the AV valve closure produces the first heart sound. Once ventricular pressure exceeds the great-vessel pressure, the semilunar valves open and rapid then reduced ejection follow, with the AV valves held shut throughout. Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure and slams the semilunar valves shut, producing the second heart sound; the AV valves are not yet open because ventricular pressure is still above atrial pressure, so every valve is closed a second time in the cycle. Once ventricular pressure falls below atrial pressure, the AV valves open again and rapid then reduced ventricular filling follow, with the semilunar valves held shut throughout — so, across the whole cycle, the AV valves are open during atrial systole, rapid filling and reduced filling, and closed only during the two ejection phases and the two isovolumetric phases together with the semilunar valves.",
      objective: 'State which two phases of the cardiac cycle have every cardiac valve closed at once, name the valve closure that produces each heart sound, and list the three phases during which the AV valves are open.',
      pitfall: "Assuming a valve's opening or closing defines only one phase rather than the boundary between two. AV valve closure ends atrial systole and begins isovolumetric contraction (first heart sound); semilunar valve closure ends reduced ejection and begins isovolumetric relaxation (second heart sound) — each sound marks a phase transition, not a phase's whole duration.",
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['First heart sound', 'Second heart sound', 'AV valve timing', 'Semilunar valve timing', 'All valves closed phases'],
    },
    {
      key: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      label: 'The aortic pressure curve rises on the ejection-driven anacrotic limb and falls on the catacrotic limb, whose dicrotic notch and dicrotic wave mark aortic valve closure',
      definition: 'The aortic pressure curve traces aortic pressure across one cardiac cycle. Its ascending, "anacrotic", limb coincides with the maximal ejection phase and carries pressure up to about 120 mmHg (systolic arterial blood pressure) — so aortic pressure is highest during rapid (maximal) ventricular ejection, not during any other phase. Its descending, "catacrotic", limb runs through the rest of the cycle down to about 80 mmHg (diastolic arterial blood pressure). On the catacrotic limb, the dicrotic notch is a sharp drop of pressure that ends with closure of the aortic valve at the end of systole; the dicrotic wave that follows it is a small rise of pressure caused by backwardly moving blood bouncing against the now-closed elastic aortic valve during isovolumetric relaxation.',
      objective: 'Name the ascending and descending limbs of the aortic pressure curve, state which pressure value each limb produces, identify rapid ejection as the phase of highest aortic pressure, and explain what causes the dicrotic notch and the dicrotic wave that follows it.',
      pitfall: 'Treating the dicrotic notch and the dicrotic wave as the same event. The notch is the sharp pressure drop at the moment the aortic valve shuts; the wave is the small rebound afterwards, caused by blood bouncing back against the now-closed valve during isovolumetric relaxation.',
      subject: 'cvs',
      primary: 'DIS-PHY-T02',
      secondary: ['SYS-CVS-T01-S01'],
      modulePath: '104 CPS > Physiology > Cardiovascular System > Cardiac Function',
      type: 'mechanism',
      aliases: ['Anacrotic and catacrotic limbs', 'Dicrotic notch and dicrotic wave', 'Highest aortic pressure phase'],
    },
  ],

  questions: [
    {
      key: 'which-phase-of-the-cardiac-cycle-is-absent-if-there-is-no-p-656477fd',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that atrial systole depends on the P wave and is absent without it.',
      explanations: {
        A: 'The cardiac cycle is initiated by the P wave, which represents atrial depolarisation; without a P wave there is no atrial contraction, so atrial systole is the phase that is absent.',
        B: 'Isovolumetric ventricular contraction is triggered by the QRS complex (ventricular depolarisation), not the P wave, so it can still occur without a P wave.',
        C: 'Reduced ventricular ejection follows ventricular contraction and does not depend on atrial depolarisation.',
        D: 'Rapid ventricular filling is a passive, pressure-driven phase and does not require atrial contraction to occur.',
      },
    },
    {
      key: 'first-heart-sound-occurs-in-c084db9e',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced by AV valve closure at the start of isovolumetric contraction.',
      explanations: {
        A: 'The first heart sound is produced by closure of the AV valves, which happens at the instant rising ventricular pressure exceeds atrial pressure — the event that begins isovolumetric (isometric) contraction.',
        B: 'AV valves are open during atrial systole, not closing; the closure that makes the first heart sound has not yet happened.',
        C: 'Isometric relaxation begins with semilunar, not AV, valve closure — that event produces the second heart sound, not the first.',
        D: 'Maximum (rapid) filling begins with AV valve opening, the opposite event to the valve closure that produces a heart sound.',
      },
    },
    {
      key: 'second-heart-sound-is-due-to-a990b4ad',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that the second heart sound is produced by semilunar valve closure.',
      explanations: {
        A: 'AV valve closure produces the first heart sound, not the second.',
        B: 'The second heart sound is produced by closure of the semilunar (aortic and pulmonary) valves, at the instant falling ventricular pressure drops below aortic/pulmonary pressure — the event that begins isovolumetric relaxation.',
        C: 'Not a named cardiac valve or valve group — a corrupted option with no anatomical referent.',
        D: 'AV valve opening is a silent event that begins ventricular filling, not a valve closure and not the source of a heart sound.',
      },
    },
    {
      key: 'at-the-beginning-of-which-phase-of-the-cardiac-cycle-does-th-6b54a811',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Place the second heart sound at the start of isovolumetric ventricular relaxation.',
      explanations: {
        A: 'Isovolumetric contraction begins with AV, not semilunar, valve closure, producing the first heart sound, not the second.',
        B: 'Reduced ventricular ejection is already underway with the semilunar valves open; no valve closes at its start.',
        C: 'Isovolumetric (isometric) ventricular relaxation begins the instant falling ventricular pressure drops below aortic/pulmonary pressure, closing the semilunar valves and producing the second heart sound.',
        D: 'Rapid ventricular filling begins with AV valve opening, an opening rather than the closing event a heart sound requires.',
      },
    },
    {
      key: 'av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the AV valves are open during atrial systole (and both filling phases).',
      explanations: {
        A: 'Isometric contraction begins exactly because the AV valves have just closed; they stay shut throughout this phase.',
        B: 'The AV valves are open throughout atrial systole, allowing atrial contraction to push blood into the ventricles — they only close at its end, marking the start of isovolumetric contraction.',
        C: 'The protodiastolic interval falls within reduced ejection, with the semilunar valves open and the AV valves still closed.',
        D: 'Maximum ejection has the semilunar valves open and the AV valves closed, the opposite valve state to atrial systole.',
      },
    },
    {
      key: 'all-cardiac-valves-are-closed-in-a22d5c2c',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: 'Only 3 options survived extraction (A isometric relaxation, B atrial systole, C protodiastole) — below the platform\'s 4-to-5-option import contract. The correct fact (every valve is closed during isometric relaxation, and equally during isometric contraction) is already tested cleanly by this leaf\'s own first-heart-sound-occurs-in-c084db9e and av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce questions.',
    },
    {
      key: 'all-are-involved-in-ventricular-isometric-contraction-phase-3e2ad1bc',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Recall of a false statement',
      learningObjective: 'Identify that ventricular volume stays constant, not decreases, during isovolumetric contraction, as the false statement among its other true characters.',
      explanations: {
        A: 'True of isovolumetric contraction, so not the exception. With both AV and semilunar valves shut and the ventricle contracting against a closed system, pressure inside it rises very rapidly.',
        B: "The exception, and the answer. Isovolumetric ('isovolumic') contraction is defined by an unchanged ventricular volume — both valve sets are shut, so no blood can enter or leave — not a decreasing one; volume only starts falling once the semilunar valves open for ejection.",
        C: 'True, so not the exception. The first heart sound, produced by AV valve closure, occurs at the very start of this phase.',
        D: 'True, so not the exception. The QRS complex (ventricular depolarisation) precedes and triggers ventricular contraction, starting a short interval (about 0.02 sec) before isovolumetric contraction itself begins.',
      },
    },
    {
      key: 'during-isovolumetric-ventricular-contraction-0eb895ff',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced during isovolumetric ventricular contraction.',
      explanations: {
        A: 'Rapid filling is a diastolic phase that follows AV valve opening, well after isovolumetric contraction has ended.',
        B: 'The first heart sound, produced by AV valve closure, is generated at the start of isovolumetric ventricular contraction.',
        C: 'Maximal ejection of blood happens once the semilunar valves open, which is the phase that follows isovolumetric contraction, not this phase itself — by definition no blood is ejected while the ventricle is sealed shut.',
        D: 'The opposite is true: tension (pressure) rises rapidly while volume stays constant during isovolumetric contraction, not the reverse.',
      },
    },
    {
      key: 'during-isovolumetric-ventricular-contraction-a-rapid-filling-ae3cfd14',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the first heart sound is produced during isovolumetric ventricular contraction.',
      explanations: {
        A: 'Rapid filling is a diastolic phase that follows AV valve opening, well after isovolumetric contraction has ended.',
        B: 'The first heart sound, produced by AV valve closure, is generated at the start of isovolumetric ventricular contraction.',
        C: 'Maximal ejection of blood happens once the semilunar valves open, which is the phase that follows isovolumetric contraction, not this phase itself — by definition no blood is ejected while the ventricle is sealed shut.',
        D: 'The opposite is true: tension (pressure) rises rapidly while volume stays constant during isovolumetric contraction, not the reverse.',
      },
    },
    {
      key: 'during-the-isometric-contraction-pnase-of-cardiac-cycle-what-f8195c12',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that ventricular volume remains unchanged during isometric (isovolumetric) contraction.',
      explanations: {
        A: 'Volume does not decrease here — both AV and semilunar valves are shut, so no blood can leave the ventricle yet; volume only starts decreasing once ejection (semilunar valve opening) begins.',
        B: 'Volume cannot increase either, since the AV valves are already shut and no blood can enter.',
        C: "Ventricular volume remains unchanged (isovolumetric/isometric) throughout this phase, because both valve sets are closed while the ventricle's rising pressure has not yet reached the level needed to open the semilunar valves.",
        D: 'Volume does not decrease during this phase at all — rising intraventricular pressure is exactly what defines it, but with volume held constant, not falling, until ejection begins.',
      },
    },
    {
      key: 'regarding-the-isovolumetric-contraction-phase-of-cardiac-cyc-325b52a8',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Hard',
      questionType: 'Recall of a true statement',
      learningObjective: 'State that ventricular volume remains unchanged throughout isovolumetric contraction.',
      explanations: {
        A: 'Isovolumetric contraction starts with sudden closure of the AV valves, not the semilunar valves — AV valve closure is what produces the first heart sound at this phase\'s start.',
        B: 'By the end of this phase, left ventricular pressure has risen to about aortic diastolic pressure (roughly 80 mmHg) — the level it must reach to force the semilunar valves open — not 10 mmHg, which is far too low.',
        C: "Ventricular volume remains unchanged throughout isovolumetric contraction — this is exactly what 'isovolumetric' means, since both valve sets are shut and no blood can enter or leave.",
        D: 'Atrial pressure does not fall to its minimum here; the small "c wave" rise (from the closed AV valve bulging back into the atrium) occurs around this phase, and atrial pressure reaches its true minimum later, during rapid ejection (the "x descent").',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-is-aortic-pressure-h-39d3d842',
      conceptKey: 'aortic-pressure-curve.limbs-and-dicrotic-notch',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that aortic pressure peaks during rapid (maximal) ventricular ejection.',
      explanations: {
        A: 'Aortic pressure is still at its diastolic low during isovolumetric contraction — the semilunar valves have not opened yet, so no blood has entered the aorta to raise it.',
        B: 'Aortic pressure rises on the ejection-driven anacrotic limb, which coincides with rapid (maximal) ventricular ejection, reaching its peak (about 120 mmHg, systolic pressure) here.',
        C: 'Reduced ejection falls on the descending catacrotic limb, after the pressure peak of rapid ejection has already passed.',
        D: 'Aortic pressure is already declining toward its diastolic minimum during rapid ventricular filling, long after the ejection-phase peak.',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-is-ventricular-volum-e85c1847',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that ventricular volume is at its lowest, held constant, throughout isovolumetric relaxation.',
      explanations: {
        A: 'Ventricular volume is at its highest, not lowest, at the start of isovolumetric contraction — filling has just finished and ejection has not yet begun.',
        B: 'Ventricular volume is still falling throughout rapid ejection as blood leaves the ventricle; it has not yet reached its lowest point.',
        C: 'Ventricular volume continues to fall through reduced ejection, reaching its true minimum only at this phase\'s very end.',
        D: 'Ventricular volume reaches its minimum (the end-systolic volume) at the end of ejection and then stays fixed at that lowest value throughout isovolumetric relaxation, since both valve sets are shut and no blood can enter until the AV valves open for filling.',
      },
    },
    {
      key: 'all-are-involved-in-ventricular-filling-except-4c80661d',
      conceptKey: 'cardiac-cycle.seven-phase-sequence-and-duration',
      difficulty: 'Moderate',
      questionType: 'Recall of a false statement',
      learningObjective: 'Identify maximal ejection as not a filling phase, against atrial systole, rapid filling and reduced filling, which are.',
      explanations: {
        A: 'Atrial systole is involved in ventricular filling, so not the exception — it is the final, active top-up of ventricular volume before the AV valves close.',
        B: 'The exception, and the answer. Maximum (rapid) ejection is when blood leaves the ventricle through the open semilunar valves, the opposite process to filling.',
        C: 'Maximum (rapid) filling is involved in ventricular filling by definition, so not the exception — it is the phase of fastest AV-valve-driven inflow.',
        D: 'Reduced filling (diastasis) is involved in ventricular filling, so not the exception — it is the slower continuation of filling before the next atrial systole.',
      },
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-does-the-mitral-valv-839de1d0',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, B, C) — option C's text is itself a garbled OCR merge of two option texts ('Rapid ventricular ejection' bled together with 'Rapid ventricular filling'), so only 3 distinct answer choices remain, below the platform's 4-to-5-option import contract. The mitral (AV) valve opening at the start of rapid ventricular filling is already established by this leaf's own av-valves-are-open-during-which-of-the-following-phases-of-c-b3cd86ce question and concept.",
    },
    {
      key: 'during-which-phase-of-the-cardiac-cycle-docs-ventricular-pre-169c9804',
      conceptKey: 'cardiac-cycle.valve-states-and-heart-sounds-by-phase',
      difficulty: 'Moderate',
      questionType: 'Not sittable as extracted.',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason: "Only 3 options survived extraction (A, B, C) — option C's text is itself a garbled OCR merge of two option texts ('Rapid ventricular ejection' bled together with 'Isovolumetric ventricular relaxation'), so only 3 distinct answer choices remain, below the platform's 4-to-5-option import contract. The fact that ventricular pressure rises while volume stays constant during isovolumetric ventricular contraction is already established by this leaf's own during-isovolumetric-ventricular-contraction-0eb895ff and during-the-isometric-contraction-pnase-of-cardiac-cycle-what-f8195c12 questions.",
    },
  ],
}
