import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Respiratory System — Conducting Portion Epithelium and Olfactory Mucosa",
  modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
  articleId: "ART-104-HIS-NASAL-MUCOSA",

  concepts: [
    {
      key: "conducting-portion-epithelium.five-cell-types",
      label: "The conducting portion's epithelium has five cell types: ciliated, goblet, brush, basal and small granule cells",
      definition: "The epithelium lining most of the conducting portion is pseudostratified columnar ciliated with goblet cells, and five cell types are recognised within it. Ciliated columnar cells are the most abundant, each carrying about 300 motile cilia, their apical cytoplasm packed with the cilia's basal bodies and with mitochondria supplying energy for ciliary beating; they push mucus, with its trapped bacteria and dust, outward in one direction. Mucous goblet cells are next most numerous, their apical portions filled with mucin granules, secreting the mucus that covers the epithelium and traps particles. Brush cells are columnar cells with abundant apical microvilli and basal afferent nerve endings, acting as sensory receptors. Basal cells are small, rounded cells sitting on the basal lamina without reaching the lumen — the stem cells that replace the other types. Small granule cells are neuroendocrine cells of the APUD group, with numerous basal dense granules, secreting hormones such as serotonin and catecholamines that control airway and blood-vessel diameter and regulate mucous and serous secretion.",
      objective: "Name the conducting portion's five epithelial cell types and state the distinguishing feature and function of each.",
      pitfall: "In smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-RES-T01-S01-M01"],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structural_description",
      aliases: ["Respiratory epithelium cell types", "Ciliated, goblet, brush, basal and small granule cells", "Pseudostratified ciliated columnar epithelium"],
    },
    {
      key: "nasal-cavity.vestibule-and-fossae-regions",
      label: "The nasal cavity is a keratinized, hair-lined vestibule opening into two conchae-bearing fossae that condition inspired air",
      definition: "The nasal cavity is the external vestibule and the internal nasal fossae. The vestibule is the anterior dilated portion, lined with hairy keratinized stratified squamous epithelium that changes, deeper in, to non-keratinized stratified squamous epithelium; its epithelium carries thick short hairs, the vibrissae, that filter large particles out of the air. The nasal fossae are two chambers separated by the bony nasal septum, each bearing three bony shelf-like projections from its lateral wall — the superior, middle and inferior conchae. The lamina propria of the conchae is loose connective tissue containing large venous plexuses (swell bodies) and mucous and serous glands, and its function is to improve the conditioning of inspired air by increasing the surface area of the respiratory mucosa.",
      objective: "Describe the vestibule and the nasal fossae as the two regions of the nasal cavity, and state the function of the conchae.",
      pitfall: "Allergic congestion of the swell bodies in the conchae's lamina propria, and epistaxis from the same vascular lamina propria after trauma, are both read-only clinical notes tied directly to this structure — not separate facts to learn apart from it.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-RES-T01-S01-M01"],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structural_description",
      aliases: ["Vestibule of the nose", "Nasal fossae", "Swell bodies"],
    },
    {
      key: "olfactory-mucosa.cell-types-and-lamina-propria",
      label: "Olfactory epithelium has three cell types — olfactory neurons, sustentacular cells and basal cells — over a lamina propria of Bowman's glands",
      definition: "Olfactory mucosa covers the roof and superior conchae of the nasal cavity and is formed of olfactory epithelium with its connective-tissue lamina propria. The epithelium is the neuro-epithelium responsible for smell, much thicker than respiratory epithelium, a modified pseudostratified columnar ciliated epithelium with no goblet cells, built of three cell types. Olfactory neurons are bipolar nerve cells whose dendrites extend to the surface and end in an olfactory vesicle bearing multiple basal bodies, from which arise cilia that are few, very long and non-motile, increasing the surface exposed to odorous substances; their axons pass into the lamina propria as olfactory nerve fibres. Sustentacular (supporting) cells are tall columnar cells with wide apices and narrow bases, apical microvilli in a fluid layer, and apical yellow lipofuscin granules that give olfactory mucosa its yellow colour; junctional complexes bind them to the olfactory cells. Basal cells are small pyramidal cells with basophilic cytoplasm and round nuclei, acting as stem cells for both the sensory and the supporting cells. The lamina propria beneath is dense connective tissue carrying olfactory nerve bundles and Bowman's glands, whose serous secretion reaches the surface through ducts and forms the fluid medium in which odorous substances dissolve around the olfactory cilia.",
      objective: "Name olfactory epithelium's three cell types and state what each contributes, and say what Bowman's glands secrete and why.",
      pitfall: "Olfactory neurons are the only neurons considered capable of substantial regeneration, owing to the high regenerative capacity of the basal stem cells beneath them — a read-only fact worth holding against the cytogenetics chapter's statement that nerve cells are non-renewing.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-RES-T01-S01-M01"],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structural_description",
      aliases: ["Olfactory neurons", "Sustentacular cells", "Bowman's glands", "Olfactory epithelium structure"],
    },
  ],

  questions: [
    {
      key: "bind-supporting-cell-to-olfactory-cell-b5fd3674",
      conceptKey: "olfactory-mucosa.cell-types-and-lamina-propria",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the junctional complex as the structure binding sustentacular (supporting) cells to olfactory neurons.",
      explanations: {
        A: "A gap junction couples cells electrically or metabolically; the word for what binds the supporting cell to the olfactory cell is a junctional complex, not a gap junction.",
        B: "Junctional complexes directly bind the supporting (sustentacular) cells to the olfactory cells. A common trap: olfactory neurons are the only neurons considered capable of substantial regeneration, owing to the high regenerative capacity of the basal stem cells beneath them — a read-only fact worth holding against the cytogenetics chapter's statement that nerve cells are non-renewing.",
        C: "A tight junction is only one component of a junctional complex; it is the complex as a whole, not this one component alone, that performs the binding.",
        D: "An adherens junction is likewise only one component of a junctional complex, not the term used for this specific attachment.",
      },
    },
    {
      key: "cell-act-as-sensory-receptor-contain-afferent-nerve-ending-424f9d70",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the brush cell as the conducting portion's sensory-receptor epithelial cell, by its basal afferent nerve endings.",
      explanations: {
        A: "Ciliated columnar cells beat their cilia to move mucus outward — them no sensory role or afferent nerve ending.",
        B: "Mucous goblet cells secrete mucus; no nerve ending or sensory function for them.",
        C: "Brush cells have basal afferent nerve endings and act as sensory receptors. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        D: "Basal cells are the epithelium's stem cells, replacing the other cell types — them no sensory or nerve-ending role.",
      },
    },
    {
      key: "cell-belong-to-apud-with-numerous-basal-granules-58631828",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name the small granule cell as the conducting portion's APUD (neuroendocrine) epithelial cell.",
      explanations: {
        A: "Brush cells are sensory receptors with apical microvilli and basal afferent nerve endings — them no APUD classification or basal granules.",
        B: "Mucous goblet cells secrete mucus from apical mucin granules; they are not classed as APUD cells.",
        C: "Small granule cells is neuroendocrine cells belonging to APUD, with numerous basal dense granules secreting hormones such as serotonin and catecholamines. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        D: "Basal cells are stem cells for the other epithelial types — them no APUD role or basal secretory granules.",
      },
    },
    {
      key: "cell-is-columnar-with-apical-microvilli-3639368c",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the brush cell by its columnar shape and abundant apical microvilli.",
      explanations: {
        A: "Ciliated columnar cells carry motile cilia on their apex, not the abundant microvilli the stem describes.",
        B: "Mucous goblet cells are filled apically with mucin granules, not microvilli.",
        C: "Brush cells is columnar cells with abundant apical microvilli. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        D: "Basal cells are small and rounded, resting on the basal lamina without reaching the lumen at all, so they carry no apical surface feature such as microvilli.",
      },
    },
    {
      key: "cell-is-most-numerous-cell-with-numerous-mitochondria-fe96c124",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the ciliated columnar cell as the conducting portion's most abundant epithelial cell, mitochondria-rich to power ciliary beating.",
      explanations: {
        A: "Ciliated columnar cells the most abundant cells of the epithelium, with numerous apical mitochondria supplying the energy for ciliary beating. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        B: "Mucous goblet cells are described as the next most numerous, not the most numerous, and their apical cytoplasm is filled with mucin granules rather than being mitochondria-rich.",
        C: "Brush cells are a minority sensory population, not the most numerous cell of the epithelium.",
        D: "Basal cells are the epithelium's stem-cell population, not described as mitochondria-rich or as the most numerous type.",
      },
    },
    {
      key: "cell-is-next-most-numerous-trap-bacteria-dust-45d4166b",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the mucous goblet cell as the epithelium's next most numerous cell, trapping bacteria and dust in the mucus it secretes.",
      explanations: {
        A: "Ciliated columnar cells are the most numerous cell, not the next most numerous, and they move trapped material rather than trapping it themselves.",
        B: "Mucous goblet cells is the next most numerous cell type, secreting mucus that covers the epithelium and traps bacteria and dust particles. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        C: "Brush cells are sensory receptors, not the mucus-secreting, trapping cell the stem describes.",
        D: "Basal cells are stem cells resting on the basal lamina, playing no part in trapping inhaled particles.",
      },
    },
    {
      key: "cell-is-small-rounded-don-t-reach-lumen-act-as-stem-cell-a7b44dd9",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify the basal cell as the small, lumen-absent, epithelium-replacing stem cell of the conducting portion.",
      explanations: {
        A: "Ciliated columnar cells are tall and reach the lumen, carrying cilia at their apex — the opposite of the stem's description.",
        B: "Mucous goblet cells also reach the epithelial surface to release mucus, unlike the cell the stem describes.",
        C: "Brush cells reach the lumen with an apical microvillous surface — they are not the basal, lumen-absent stem cell being asked for.",
        D: "Basal cells is small, rounded cells sitting on the basal lamina without reaching the lumen, which act as the stem cells that replace the other cell types. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
      },
    },
    {
      key: "cell-secrete-serotonin-catecholamine-d2ab6f51",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute serotonin and catecholamine secretion to the small granule (APUD) cell.",
      explanations: {
        A: "Brush cells are sensory receptors with basal nerve endings, not secretory APUD cells.",
        B: "Mucous goblet cells secrete mucus, not serotonin or catecholamines.",
        C: "Small granule cells secrete hormones such as serotonin and catecholamines, to help control airway and blood vessel diameter and regulate glandular secretion. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        D: "Basal cells are the epithelium's stem-cell population, with no secretory role of this kind.",
      },
    },
    {
      key: "in-vestibule-deeper-its-epithelium-change-into-5d9df6bc",
      conceptKey: "nasal-cavity.vestibule-and-fossae-regions",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Trace the vestibule's epithelium from hairy keratinized stratified squamous at its entrance to non-keratinized stratified squamous deeper in.",
      explanations: {
        A: "Stratified columnar epithelium is not a lining anywhere in the nasal vestibule.",
        B: "Keratinized stratified squamous epithelium is the vestibule's own anterior lining, at the nostril itself — the stem is asking what it changes into further in, not what it starts as.",
        C: "The vestibule is lined by hairy keratinized stratified squamous epithelium which, deeper in, changes to non-keratinized stratified squamous epithelium. A common trap: allergic congestion of the swell bodies in the conchae's lamina propria, and epistaxis from the same vascular lamina propria after trauma, are both read-only clinical notes tied directly to this structure — not separate facts to learn apart from it.",
        D: "Pseudostratified columnar ciliated epithelium is the respiratory epithelium of the nasal fossae beyond the vestibule, not the epithelium the vestibule's own deeper part changes into.",
      },
    },
    {
      key: "middle-inferior-conchae-covered-by-231b8c31",
      conceptKey: "nasal-cavity.vestibule-and-fossae-regions",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the middle and inferior conchae carry respiratory (pseudostratified columnar ciliated) epithelium, unlike the superior conchae's olfactory lining.",
      explanations: {
        A: "Stratified columnar epithelium is not a lining found in any part of the nasal fossae.",
        B: "Keratinized stratified squamous epithelium lines the anterior vestibule, not the middle and inferior conchae further inside the nasal fossae.",
        C: "Non-keratinized stratified squamous epithelium is the deeper vestibule's lining, not the conchae's.",
        D: "The middle and inferior conchae are covered with respiratory epithelium — pseudostratified columnar ciliated with goblet cells — while only the superior concha carries olfactory epithelium. A common trap: allergic congestion of the swell bodies in the conchae's lamina propria, and epistaxis from the same vascular lamina propria after trauma, are both read-only clinical notes tied directly to this structure — not separate facts to learn apart from it.",
      },
    },
    {
      key: "olfactory-neuron-is-characterized-by-all-except-4de2c09a",
      conceptKey: "olfactory-mucosa.cell-types-and-lamina-propria",
      difficulty: "Hard",
      questionType: "Structure and function",
      learningObjective: "Separate the olfactory neuron's own features (bipolar, regenerating, dendrite to olfactory vesicle, multiple basal bodies, axon to lamina propria) from the sustentacular cell's wide apex, narrow base and apical microvilli.",
      explanations: {
        A: "True of olfactory neurons, so not the exception. Them is bipolar nerve cells with a high capacity to regenerate.",
        B: "The exception, and the answer. A wide cylindrical apex, narrow base and apical microvilli are the description of the sustentacular (supporting) cell, not the olfactory neuron, whose dendrite ends in an olfactory vesicle rather than a broad microvillous apex. A common trap: olfactory neurons are the only neurons considered capable of substantial regeneration, owing to the high regenerative capacity of the basal stem cells beneath them — a read-only fact worth holding against the cytogenetics chapter's statement that nerve cells are non-renewing.",
        C: "True, so not the exception. The olfactory neuron's dendrite extends toward the surface and ends in the olfactory vesicle.",
        D: "True, so not the exception. Multiple basal bodies in the olfactory vesicle are what the long, non-motile olfactory cilia arise from.",
        E: "True, so not the exception. The olfactory neuron's axon passes into the lamina propria to form the olfactory nerve fibres.",
      },
    },
    {
      key: "secrete-serous-fluid-that-act-as-media-where-odorous-substan-93b9e6ad",
      conceptKey: "olfactory-mucosa.cell-types-and-lamina-propria",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name Bowman's glands as the source of the serous fluid odorous substances dissolve in around the olfactory cilia.",
      explanations: {
        A: "A generic mucous gland is not the specific structure for this fluid — the olfactory mucosa's own glands are Bowman's glands.",
        B: "Bowman's glands secrete a serous fluid that acts as the medium around the olfactory cilia in which odorous substances dissolve. A common trap: olfactory neurons are the only neurons considered capable of substantial regeneration, owing to the high regenerative capacity of the basal stem cells beneath them — a read-only fact worth holding against the cytogenetics chapter's statement that nerve cells are non-renewing.",
        C: "A muco-serous gland is not the specific term for the olfactory lamina propria's glands, which are named specifically as Bowman's glands.",
        D: "The parotid gland is a salivary gland with no role in the olfactory mucosa.",
      },
    },
    {
      key: "small-granule-cell-2a6beb4c",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute airway diameter control (via serotonin and catecholamine secretion) to the small granule cell.",
      explanations: {
        A: "Small granule cells secrete hormones like serotonin and catecholamines that control the diameter of the airway and blood vessels and regulate mucous and serous secretion. A common trap: in smokers, mucus accumulates in the small airways because the normal ratio of ciliated to goblet cells reverses, or because the cilia are paralysed — a read-only clinical note that turns this cell-type list into a mechanism question rather than a naming one.",
        B: "The stem cell that replaces the other epithelial types is the basal cell, not the small granule cell.",
        C: "Acting as a sensory receptor is the brush cell's role, with its basal afferent nerve endings, not the small granule cell's.",
        D: "Pushing mucus with trapped bacteria outward is the ciliated columnar cell's job, driven by ciliary beating, not the small granule cell's secretion.",
      },
    },
    {
      key: "concerning-small-granule-cells-2d4e1325",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Hard",
      questionType: "Structure and function",
      learningObjective: "Not sittable with confidence.",
      explanations: {},
      exclude: true,
      excludeReason: "The editorial-no-printed-key answer (C, 'has basal afferent nerve endings') contradicts this leaf's own department-book-sourced concept text, which attributes basal afferent nerve endings and a sensory-receptor role specifically to the BRUSH cell (see conducting-portion-epithelium.five-cell-types), while crediting the small granule cell with APUD hormone secretion (serotonin, catecholamines) that 'may control the caliber of airways' -- making option D, not C, the statement the department book's own small-granule-cell description actually supports. Per the ANSWER-KEY GAPS ruling a wrong key is worse than a missing one, and this is a case where the editorial guess (reasoning from Kulchitsky-cell chemoreceptor physiology in general) conflicts with the specific attribution this module's own primary source makes; excluded rather than keyed against the source it should agree with.",
    },
    {
      key: "concerning-small-granule-cells-it-i-85641459",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Hard",
      questionType: "Structure and function",
      learningObjective: "Not sittable with confidence.",
      explanations: {},
      exclude: true,
      excludeReason: "Duplicate stem of concerning-small-granule-cells-2d4e1325 (same OCR-garbled options, same editorial C key) -- same conflict with this leaf's own department-book concept text, which places basal afferent nerve endings on the brush cell, not the small granule cell. Excluded for the same reason.",
    },
    {
      key: "function-of-nasal-fossae-is-by-increasing-surface-area-22100d98",
      conceptKey: "nasal-cavity.vestibule-and-fossae-regions",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that the nasal fossae's surface-area increase (via the conchae) serves to condition, not merely conduct, inspired air.",
      explanations: {
        A: "Conduction of air is simply moving it through the passage; increasing the mucosa's surface area is specifically about acting on the air passing over it, which is conditioning, not conduction.",
        B: "Increasing the respiratory mucosa's surface area, by the conchae's shelf-like projections into the airstream, improves the conditioning (warming, humidifying, filtering) of inspired air -- the function this leaf's own concept text names directly for the conchae's lamina propria and its venous plexuses.",
        C: "Gas exchange happens across the thin alveolar-capillary membrane deep in the respiratory portion, not across the thick, vascular nasal mucosa lining the fossae.",
        D: "Only conditioning, not conduction or gas exchange, is the function this increased surface area serves, so 'all the above' overstates it.",
      },
    },
    {
      key: "olfactory-cells-are-b9dcb943",
      conceptKey: "olfactory-mucosa.cell-types-and-lamina-propria",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that olfactory (neuro-sensory) cells are bipolar nerve cells, distinct from the sustentacular cell's microvillous apex and yellow pigment.",
      explanations: {
        A: "Regeneration is a real, notable property of olfactory neurons (via the basal stem cells beneath them), but it is not what the three olfactory-mucosa cell types share -- sustentacular and basal cells are not themselves regenerating neurons, so 'regenerative for all three cell types' overstates a property that belongs to the sensory neuron's renewal pathway, not to all three types equally.",
        B: "Apical microvilli submerged in a fluid layer describes the sustentacular (supporting) cell's apex, not the olfactory neuron itself, whose surface feature is instead long, non-motile cilia arising from its olfactory vesicle.",
        C: "Olfactory cells are bipolar nerve cells, their dendrite reaching the surface to end in an olfactory vesicle and their axon passing into the lamina propria as an olfactory nerve fibre -- the one plainly neuronal cell among the three olfactory-mucosa cell types.",
        D: "Yellow lipofuscin pigment is the sustentacular cell's own distinguishing content (giving the olfactory mucosa its yellow colour), not a feature of the olfactory neuron.",
      },
    },
    {
      key: "smokers-suffer-from-disturbed-ratio-between-oo-3b771e32",
      conceptKey: "conducting-portion-epithelium.five-cell-types",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Name the ciliated-to-goblet-cell ratio as the one smoking disturbs, driving mucus accumulation in the small airways.",
      explanations: {
        A: "Small granule and ciliated cells are not the pairing whose ratio smoking is described as disturbing; the small granule cell's APUD secretory role is unrelated to the mucus-clearance mechanism this question tests.",
        B: "Goblet and brush cells are not the pair implicated; the brush cell's sensory role plays no part in the mucus-accumulation mechanism smoking disturbs.",
        C: "In smokers, mucus accumulates in the small airways because the normal ratio between ciliated cells and goblet cells reverses (relatively more mucus-secreting goblet cells, relatively fewer mucus-clearing ciliated cells) -- the same read-only clinical note already carried on this leaf's conducting-portion-epithelium concept, now the direct answer rather than a pitfall aside.",
        D: "Goblet and small granule cells are not the pairing described; small granule cells are a minority neuroendocrine population uninvolved in the ciliated/goblet mucus-clearance balance.",
      },
    },
  ],
}
