import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: "Respiratory System — Larynx and Airway Wall",
  modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
  articleId: "ART-104-HIS-LARYNX-TRACHEA-BRONCHI",

  concepts: [
    {
      key: "larynx.vocal-cords-and-cartilages",
      label: "The larynx is mostly respiratory epithelium over hyaline and elastic cartilages, except at the true vocal cords",
      definition: "The larynx connects the pharynx with the trachea. It is lined with respiratory epithelium, except over the true vocal cords and the lingual surface of the epiglottis, which are covered by stratified squamous epithelium; its connective-tissue lamina propria contains the laryngeal cartilages. The large cartilages — thyroid, cricoid and most of the arytenoids — are hyaline and may calcify with age; the small cartilages — epiglottis, cuneiform, corniculate and the tip of the arytenoids — are elastic and do not calcify. Two pairs of folds extend into the laryngeal lumen. The upper pair, the false vocal cords (vestibular folds), are lined by respiratory epithelium and prevent food and fluid from entering the larynx. The lower pair, the true vocal cords, are lined by non-keratinized stratified squamous epithelium and produce voice. Overall the larynx produces voice through the true vocal cords, maintains an open airway through its cartilages, and, through the epiglottis and false vocal cords, prevents food and fluid from entering the respiratory passages.",
      objective: "State which parts of the larynx are lined by stratified squamous rather than respiratory epithelium, and contrast the false and true vocal cords by lining and function.",
      pitfall: "Assuming the whole larynx is lined the same way because 'respiratory epithelium' is stated first. The true vocal cords and the lingual epiglottis are the two named exceptions, and it is exactly those two mechanically abraded surfaces that switch to a tougher, non-keratinized stratified squamous lining.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-RES-T01-S01-M01"],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structural_description",
      aliases: ["True and false vocal cords", "Laryngeal cartilages", "Vestibular folds"],
    },
    {
      key: "conducting-portion.airway-wall-components-and-functions",
      label: "The conducting portion's wall pairs cartilage and collagen to prevent airway collapse with elastic fibres and smooth muscle for the airway's flexibility and extensibility",
      definition: "The conducting portion of the respiratory system conducts and conditions inspired air. Conduction relies on two paired components of the airway wall: cartilage and collagen fibres, which prevent the airway from collapsing and so ensure a continuous supply of air; and elastic fibres and smooth muscle, which give the airway the flexibility and extensibility it needs as it conducts that air. Conditioning (cleaning, moistening and warming the inspired air) is carried out separately, by the respiratory epithelium (pseudostratified columnar ciliated with goblet cells) and by the vascular network, mucous glands and serous glands of the connective tissue beneath it.",
      objective: "Pair the conducting portion's structural components with their function: cartilage and collagen against collapse, elastic fibres and smooth muscle for flexibility and extensibility, epithelium and glands for conditioning the air.",
      pitfall: "Swapping the two pairings — crediting cartilage with flexibility or elastic fibre/smooth muscle with preventing collapse. It pairs the other way: the rigid components (cartilage, collagen) resist collapse, and the compliant components (elastic fibre, smooth muscle) supply flexibility and extensibility.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: [],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "structure_function_relationship",
      aliases: ["Conducting portion wall structure", "Airway wall components"],
    },
    {
      key: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      label: "Cartilage, glands and goblet cells fall away from extrapulmonary bronchus to bronchiole, while smooth muscle becomes more developed and Clara cells appear",
      definition: "The trachea divides into two primary (extrapulmonary) bronchi, structurally identical to the trachea; each penetrates a lung's hilum as intrapulmonary (secondary) bronchi, which divide repeatedly into bronchioles. Extrapulmonary bronchi have a wider, less-folded lumen, pseudostratified ciliated epithelium with many goblet cells, an elastic membrane separating mucosa from submucosa, a true submucosa, incomplete C-shaped hyaline cartilage rings, smooth muscle lying posteriorly at the ends of the cartilage, and mucoserous glands and lymphatic nodules in the submucosa. Intrapulmonary bronchi keep the same epithelium but with fewer goblet cells, lose the elastic membrane and submucosa as distinct layers (though the lamina propria is rich in elastic fibres and lymphatic follicles), replace the C-shaped rings with multiple plates of hyaline cartilage in the adventitia, arrange their smooth muscle spirally around the whole lumen, and carry their glands and nodules in the adventitia between the cartilage plates. Bronchioles go further: simple columnar or cuboidal ciliated epithelium with Clara cells and no goblet cells, cilia disappearing as the bronchiole narrows; more developed, circularly arranged smooth muscle whose contraction now controls airflow to the gas-exchange sites rather than merely shortening the airway; and no cartilage plate, mucoserous gland or lymphatic nodule at all. Clara cells — dome-shaped, non-ciliated, rich in basal rough endoplasmic reticulum, apical smooth endoplasmic reticulum, mitochondria, Golgi apparatus and glycoprotein-containing secretory granules — protect the bronchiolar epithelium, degrade inhaled toxins, secrete a surfactant-like material that keeps the bronchiole patent, protect against emphysema by inhibiting macrophage-secreted protease and elastase, and may act as stem cells for the bronchiolar lining.",
      objective: "Trace, from extrapulmonary bronchus to bronchiole, how the epithelium, cartilage, smooth muscle and glands change, and state four functions of the Clara cell.",
      pitfall: "Bronchial asthma is an allergic condition in which spasm of bronchiolar smooth muscle constricts the airway and causes difficulty during expiration — a read-only clinical note the book ties to exactly the circularly arranged, well-developed bronchiolar muscle this progression ends on.",
      subject: "resp",
      primary: "DIS-HIS-T03",
      secondary: ["SYS-RES-T01-S01-M01"],
      modulePath: "104 CPS > Histology > Respiratory System > Conducting Portion",
      type: "comparison",
      aliases: ["Extrapulmonary versus intrapulmonary bronchus", "Bronchus versus bronchiole", "Clara cells"],
    },
  ],

  questions: [
    {
      key: "cartilage-in-epiglottis-cuneiform-corniculate-is-ee6e989d",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Classify the epiglottis, cuneiform and corniculate cartilages, and the tip of the arytenoids, as the larynx's small elastic cartilages, against the large hyaline ones.",
      explanations: {
        A: "Hyaline cartilage describes the larynx's large cartilages — thyroid, cricoid, and most of the arytenoids — not this list of small ones.",
        B: "The epiglottis, cuneiform, corniculate and the tip of the arytenoid cartilages are the larynx's small cartilages, and are elastic cartilage. A common trap: assuming the whole larynx is lined the same way because 'respiratory epithelium' is stated first.",
        C: "White fibrocartilage is not a category that applies to any of the laryngeal cartilages.",
        D: "Not applicable — a correct single answer is listed among the options.",
      },
    },
    {
      key: "for-flexibility-extensibility-during-conduction-of-air-c29fe2d7",
      conceptKey: "conducting-portion.airway-wall-components-and-functions",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Pair elastic fibres and smooth muscle with the conducting airway's flexibility and extensibility, distinct from cartilage's role against collapse.",
      explanations: {
        A: "Cartilage and collagen fibres are credited with preventing collapse, not with flexibility and extensibility.",
        B: "Collagen fibres sit with cartilage in the 'prevent collapse' pairing, and elastic fibre alone is not the full pairing for flexibility.",
        C: "Cartilage again belongs to the collapse-prevention pairing; collagen fibre alone is not the stated pairing for flexibility and extensibility either.",
        D: "Elastic fibres and smooth muscle are paired with the airway's flexibility and extensibility during air conduction, as distinct from cartilage and collagen, which prevent collapse. A common trap: swapping the two pairings — crediting cartilage with flexibility or elastic fibre/smooth muscle with preventing collapse.",
      },
    },
    {
      key: "large-laryngeal-cartilage-is-characterized-by-all-except-0455c101",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the larynx's large cartilages are hyaline and may calcify with age, unlike the small elastic ones, which do not calcify.",
      explanations: {
        A: "True of the large laryngeal cartilages (thyroid, cricoid, most of the arytenoids), so not the exception — they are hyaline cartilage.",
        B: "True, so not the exception. The large laryngeal cartilages may calcify with age.",
        C: "The exception, and the answer. Not undergoing calcification is stated of the larynx's small cartilages (epiglottis, cuneiform, corniculate, arytenoid tips), which are elastic — the opposite is true of the large hyaline ones this question asks about. A common trap: assuming the whole larynx is lined the same way because 'respiratory epithelium' is stated first.",
        D: "Not applicable — the true exception is named among the other options.",
      },
    },
    {
      key: "prevent-collapse-ensure-continuous-supply-of-air-d7f3beea",
      conceptKey: "conducting-portion.airway-wall-components-and-functions",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Pair cartilage and collagen fibres with preventing airway collapse, distinct from elastic fibre and smooth muscle's flexibility role.",
      explanations: {
        A: "Cartilage is correctly half of this pairing, but elastic fibre belongs to the other pairing (flexibility and extensibility), not to preventing collapse.",
        B: "Collagen fibre is correctly one component paired with cartilage for this function, but elastic fibre is not its partner here either.",
        C: "Cartilage and collagen fibres are what prevent airway collapse and ensure a continuous supply of air. A common trap: swapping the two pairings — crediting cartilage with flexibility or elastic fibre/smooth muscle with preventing collapse.",
        D: "Elastic fibre and smooth muscle are the pairing for flexibility and extensibility, a separate function from preventing collapse.",
      },
    },
    {
      key: "the-larynx-contains-df3d2df9",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Identify elastic cartilage as present in the larynx (epiglottis, cuneiform, corniculate, arytenoid tips), against distractors describing tracheal or bronchial cartilage.",
      explanations: {
        A: "Rings of hyaline cartilage describe the trachea's C-shaped cartilage, not the larynx's own mixed cartilage set.",
        B: "Plates of hyaline cartilage describe intrapulmonary bronchi, not the larynx.",
        C: "The larynx has two pairs of folds (false and true vocal cords), not one pair.",
        D: "The larynx contains elastic cartilage — its small cartilages (epiglottis, cuneiform, corniculate, arytenoid tips) — alongside the large hyaline cartilages (thyroid, cricoid, most of the arytenoids).",
      },
    },
    {
      key: "the-ideal-way-to-treat-bronchial-asthma-is-b0b61729",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Tie bronchial asthma's airway obstruction to spasm of the bronchiole's well-developed, circularly arranged smooth muscle, and its relief to relaxing that muscle.",
      explanations: {
        A: "Decreasing mucoserous gland secretion would not relieve the smooth-muscle spasm that actually narrows the airway in asthma, and bronchioles have no such glands to begin with.",
        B: "Stimulating ciliary beating addresses mucus clearance, not the bronchospasm that is asthma's defining mechanism.",
        C: "Bronchial asthma is an allergic condition in which spasm of the bronchiole's well-developed, circularly arranged smooth muscle constricts the airway, causing difficulty on expiration; relaxing that same smooth muscle is the ideal way to relieve the obstruction.",
        D: "Increasing bronchial diameter is the desired outcome, not a treatment mechanism in itself — it is achieved precisely by relaxing the bronchiolar smooth muscle causing the constriction.",
      },
    },
    {
      key: "a-histological-feature-of-the-bronchiole-is-92ed3513",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that well-developed, circularly arranged smooth muscle is a defining histological feature of the bronchiole, unlike its lost cartilage, goblet cells and glands.",
      explanations: {
        A: "Cartilage plates are exactly what the bronchiole has lost in the progression from bronchus to bronchiole — the bronchiole has no cartilage at all.",
        B: "Goblet cells likewise fall away in the bronchiole's lining, which instead carries Clara cells — the opposite of this option's claim.",
        C: "The bronchiole's smooth muscle becomes more developed and circularly arranged as cartilage, glands and goblet cells fall away, now controlling airflow to the gas-exchange sites directly.",
        D: "Mucoserous glands, like cartilage and goblet cells, are absent from the bronchiole's wall — a defining loss, not a retained feature.",
      },
    },
    {
      key: "branchiole-is-characterized-by-729c4827",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that the bronchiole's epithelium is simple columnar ciliated with Clara cells, unlike the bronchus's pseudostratified, goblet-cell-rich lining.",
      explanations: {
        A: "The bronchiole's smooth muscle is circularly, not longitudinally, arranged — this option reverses the actual orientation.",
        B: "The bronchiole's epithelium is simple columnar (or cuboidal) ciliated with Clara cells and no goblet cells, distinguishing it from the pseudostratified, goblet-cell-rich epithelium of the bronchus above it.",
        C: "Pseudostratified columnar epithelium with goblet cells describes the bronchus, not the bronchiole, which has simplified down to a simple ciliated epithelium.",
        D: "Mucoserous glands and lymphatic nodules are indeed absent from the bronchiole, but this option alone does not capture the epithelial change the stem is testing, and the correct option (Clara-cell epithelium) states the defining feature directly.",
        E: "Cilia disappear progressively as the bronchiole narrows distally, not gradually appear — this option reverses the actual direction of the change.",
      },
    },
    {
      key: "clara-cell-degrade-toxins-in-inhaled-air-faede62f",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Attribute Clara cells' detoxification of inhaled toxins to their apical smooth endoplasmic reticulum (SER).",
      explanations: {
        A: "SER together with the Golgi apparatus is the machinery behind Clara cells' surfactant-like secretion, not their toxin-degrading function specifically.",
        B: "rER together with the Golgi apparatus underlies Clara cells' protective, glycoprotein-secreting role for the bronchiolar epithelium, not toxin degradation.",
        C: "Clara cells degrade inhaled toxins using their apical smooth endoplasmic reticulum (SER), rich in detoxifying enzymes — the same organelle basis as hepatocyte detoxification.",
        D: "Macrophages are a separate phagocytic cell entirely; the toxin-degrading enzymatic machinery here belongs to the Clara cell's own SER, not to a macrophage.",
      },
    },
    {
      key: "clara-cell-protect-against-emphysema-by-ffebe733",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Hard",
      questionType: "Mechanism",
      learningObjective: "State that Clara cells protect against emphysema by inhibiting macrophage-secreted protease and elastase, preserving the elastic tissue of the airway wall.",
      explanations: {
        A: "SER with the Golgi apparatus underlies detoxification and secretion, not the anti-protease mechanism specific to emphysema protection.",
        B: "rER with the Golgi apparatus underlies Clara cells' protective glycoprotein secretion generally, not the specific anti-macrophage-protease mechanism this question asks about.",
        C: "SER alone is credited with toxin degradation, not with the anti-elastase mechanism protecting against emphysema.",
        D: "Clara cells protect against emphysema by inhibiting protease and elastase secreted by macrophages — enzymes that would otherwise break down the elastic tissue supporting the airway wall and alveoli, the basis of emphysema.",
      },
    },
    {
      key: "clara-cell-protect-bronchiolar-epithelium-by-cd2894db",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Attribute Clara cells' protection of the bronchiolar epithelium to their rER and Golgi apparatus, which build the protective glycoprotein secretion.",
      explanations: {
        A: "SER with the Golgi apparatus is the machinery behind the surfactant-like secretion, not the protective glycoprotein secretion this question asks about.",
        B: "Clara cells protect the bronchiolar epithelium using their basal rough endoplasmic reticulum (rER) together with the Golgi apparatus, which synthesise and package the glycoprotein-containing secretory granules that coat and protect the lining.",
        C: "SER alone underlies toxin degradation, a different Clara-cell function from epithelial protection by secreted glycoprotein.",
        D: "Macrophages are a separate cell type; the protective secretion here comes from the Clara cell's own rER and Golgi apparatus.",
      },
    },
    {
      key: "clara-cell-secrete-surfactant-like-material-by-71daa52c",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Mechanism",
      learningObjective: "Attribute Clara cells' surfactant-like secretion, which keeps the bronchiole patent, to their apical SER and Golgi apparatus.",
      explanations: {
        A: "Clara cells secrete their surfactant-like material — which keeps the bronchiole patent by lowering surface tension — using their apical smooth endoplasmic reticulum (SER) together with the Golgi apparatus, the lipid-synthesising and packaging combination expected for a lipid-rich secretion.",
        B: "rER with the Golgi apparatus builds the protective glycoprotein secretion for the epithelium, not the lipid-based surfactant-like material.",
        C: "SER alone is credited with toxin degradation, not with synthesising and packaging a secretion, which needs the Golgi apparatus too.",
        D: "Macrophages are a separate phagocytic cell type, not the source of the Clara cell's own surfactant-like secretion.",
      },
    },
    {
      key: "clara-cell-which-of-the-following-is-false-90453836",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Recall of a false statement",
      learningObjective: "Correct 'dome-shaped with many cilia' to 'dome-shaped and non-ciliated' as the accurate description of the Clara cell.",
      explanations: {
        A: "True of Clara cells, so not the exception — protecting the bronchiolar epithelium is one of their named functions.",
        B: "The exception, and the answer. Clara cells are dome-shaped but non-ciliated, with apical microvilli rather than cilia — 'many cilia' reverses their defining feature, since they sit among an epithelium whose cilia are already disappearing distally.",
        C: "True, so not the exception. Clara cells may act as a stem cell for the bronchiolar lining.",
        D: "True, so not the exception. Secretion of a surfactant-like material, keeping the bronchiole patent, is a named Clara-cell function.",
      },
    },
    {
      key: "concerning-the-upper-pair-of-vocal-cords-294613e1",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute a protective role — keeping food and fluid out of the larynx — to the upper (false, vestibular) vocal folds, against the true cords' phonation role.",
      explanations: {
        A: "The true vocal cords are the lower pair of folds; the upper pair are the false (vestibular) folds, a separate structure with a separate role.",
        B: "The well-developed elastic vocal ligament belongs to the lower, true vocal cords — the specialised structure enabling phonation — not to the upper, false vocal folds.",
        C: "Non-keratinized stratified squamous epithelium, built to withstand vibrational friction, covers the true vocal cords; the vestibular folds are instead covered by respiratory-type epithelium.",
        D: "The upper pair of folds, the false (vestibular) vocal folds, protect the larynx by helping prevent food, fluid and other foreign material from entering the airway below.",
      },
    },
    {
      key: "concerning-the-upper-pair-of-vocal-cords-a-they-are-the-true-db8e5351",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute a protective role to the upper (false) vocal folds, distinct from the true cords' phonation, elastic ligament and squamous lining.",
      explanations: {
        A: "The true vocal cords are the lower pair, specialised for phonation, not the upper pair this question asks about.",
        B: "The well-developed elastic vocal ligament is a feature of the lower, true vocal cords, not the upper, vestibular folds.",
        C: "The mechanically durable non-keratinized stratified squamous epithelium, built to withstand vibrational friction, covers the true vocal cords, not the vestibular folds, which carry respiratory-type epithelium instead.",
        D: "The upper pair of laryngeal folds, the vestibular (false vocal) folds, protect the larynx by helping close off the airway and keep foreign material, food and liquid from entering it and the trachea below.",
      },
    },
    {
      key: "concerning-the-upper-pair-of-vocal-cords-they-d0e9e07b",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute a protective role to the upper (false) vocal folds, distinct from the true cords' phonation role.",
      explanations: {
        A: "The lower pair of folds, not the upper pair, are the true vocal cords, specialised for phonation.",
        B: "The elastic vocal ligament belongs to the true (lower) vocal cords, not to the vestibular (upper) folds this question asks about.",
        C: "Non-keratinized stratified squamous epithelium, built for vibrational durability, covers the true (lower) vocal cords; the vestibular folds are typically covered by respiratory-type epithelium instead.",
        D: "The upper pair of laryngeal folds — the vestibular (false vocal) folds — have the protective role of helping prevent food, fluid and other foreign material from entering the larynx and airway below.",
      },
    },
    {
      key: "conducting-portion-include-the-following-except-4deb85f2",
      conceptKey: "conducting-portion.airway-wall-components-and-functions",
      difficulty: "Easy",
      questionType: "Recall of a false statement",
      learningObjective: "Exclude alveoli from the conducting portion, correctly grouping trachea with nasal cavity, larynx, bronchi and bronchioles as conducting-portion structures.",
      explanations: {
        A: "True — the nasal cavity and larynx are both conducting-portion structures, so not the exception.",
        B: "The exception, and the answer. The trachea is a conducting-portion structure, but alveoli are not — alveoli are the respiratory portion's site of gas exchange, so pairing it with the trachea makes this option the one containing a structure that does not belong.",
        C: "True — bronchioles and bronchi are both conducting-portion structures, so not the exception.",
        D: "True — the nasopharynx is part of the conducting portion's upper airway, so not the exception.",
      },
    },
    {
      key: "elastic-cartilage-provides-structural-support-for-the-follow-4693342f",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the larynx as the one airway among trachea, bronchi, bronchioles and larynx that contains elastic cartilage.",
      explanations: {
        A: "The trachea's C-shaped rings are entirely hyaline cartilage, not elastic cartilage.",
        B: "The bronchi's supporting cartilage (rings or plates) is entirely hyaline cartilage, not elastic cartilage.",
        C: "Bronchioles have no cartilage support at all — its complete absence is exactly what defines the transition from bronchus to bronchiole.",
        D: "The larynx contains elastic cartilage in its small cartilages (epiglottis, cuneiform, corniculate, arytenoid tips), making it the one airway among these options with any elastic cartilage support.",
      },
    },
    {
      key: "elastic-cartilage-provides-structural-support-for-the-follow-8a78cb3d",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the larynx as the airway containing elastic cartilage.",
      explanations: {
        A: "Trachea and bronchi are both supported by hyaline, not elastic, cartilage.",
        C: "Bronchioles carry no cartilage of any kind.",
        D: "The larynx's small cartilages (epiglottis, cuneiform, corniculate, arytenoid tips) are elastic cartilage, distinguishing it from the trachea and bronchi's hyaline support and the bronchiole's complete absence of cartilage.",
      },
    },
    {
      key: "elastic-cartilage-provides-structural-support-for-the-respir-0efcaf59",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the larynx as the airway containing elastic cartilage, against trachea, bronchi and bronchioles.",
      explanations: {
        A: "The trachea's supporting C-shaped rings are entirely hyaline cartilage, not elastic.",
        B: "The bronchi's supporting cartilage is entirely hyaline cartilage, not elastic.",
        C: "Bronchioles have no cartilage support at all — the loss of cartilage is precisely what defines the transition from bronchus to bronchiole.",
        D: "Within the respiratory airway, elastic cartilage is found specifically in parts of the larynx — the epiglottis, and the corniculate and cuneiform cartilages — making it the one airway among these four with any elastic cartilage.",
      },
    },
    {
      key: "extra-pulmonary-bronchi-is-lined-by-8658d6d6",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "State that extrapulmonary bronchi keep a pseudostratified ciliated columnar lining rich in goblet cells, like the trachea, unlike the intrapulmonary bronchus's fewer goblet cells.",
      explanations: {
        A: "Non-keratinized stratified squamous epithelium lines mechanically abraded surfaces such as the true vocal cords, not the bronchus.",
        B: "Extrapulmonary bronchi are structurally identical to the trachea, keeping its pseudostratified ciliated columnar epithelium with many goblet cells — richer in goblet cells than the intrapulmonary bronchus further along.",
        D: "Stratified columnar epithelium with only few goblet cells describes neither bronchus level accurately; extrapulmonary bronchi specifically keep many goblet cells, and the epithelium itself is pseudostratified, not truly stratified.",
      },
    },
    {
      key: "in-bronchiole-cell-degrades-the-toxin-in-inhaled-air-is-867e6059",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the Clara cell as the bronchiolar cell that degrades inhaled toxins.",
      explanations: {
        A: "Clara cells, the bronchiole's non-ciliated secretory cells, are rich in smooth endoplasmic reticulum and detoxifying enzymes, giving them the job of metabolising and neutralising inhaled toxins and pollutants reaching the small airways.",
        B: "Basal cells are a progenitor population in the larger airways (trachea, bronchi), not the bronchiole's toxin-degrading cell.",
        D: "Goblet cells trap inhaled particles mechanically in mucus, a physical protective role, not enzymatic toxin detoxification — and goblet cells are in any case absent from the bronchiole.",
      },
    },
    {
      key: "lung-bronchiole-has-76f40d7b",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify Clara cells in the mucosa as a defining, hallmark feature of the bronchiole.",
      explanations: {
        A: "Goblet cells are largely absent from bronchiolar epithelium — a defining loss as airways progress from the goblet-cell-rich bronchus to the bronchiole.",
        B: "Clara cells in the mucosa are a hallmark bronchiolar feature, appearing as non-ciliated, dome-shaped secretory cells once goblet cells have disappeared at this level of the airway.",
        C: "Airway smooth muscle, including in the bronchiole, is smooth muscle, not striated muscle, an entirely different tissue type.",
        D: "Bronchioles characteristically lack cartilage support altogether — a defining feature distinguishing them from bronchi, which do have cartilage plates.",
      },
    },
    {
      key: "most-of-larynx-lined-by-non-keratinized-ccd32993",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "State that most of the larynx is lined by respiratory epithelium, reserving stratified squamous epithelium for the true vocal cords and lingual epiglottis alone.",
      explanations: {
        A: "Olfactory epithelium is specific to the olfactory mucosa of the nasal cavity, with no part in lining the larynx.",
        B: "Stratified squamous epithelium is the exception covering only the true vocal cords and the lingual surface of the epiglottis, not most of the larynx.",
        C: "The larynx is lined with respiratory epithelium (pseudostratified ciliated columnar with goblet cells) everywhere except the true vocal cords and the lingual epiglottis, which switch to a tougher, non-keratinized stratified squamous lining.",
        D: "Stratified columnar epithelium is not a lining found anywhere in the larynx.",
      },
    },
    {
      key: "regarding-clara-cells-9281510c",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Hard",
      questionType: "Structure and function",
      learningObjective: "State that Clara cells carry apical smooth ER and basal rough ER, matching their dual role in detoxification/secretion and protective glycoprotein synthesis.",
      explanations: {
        A: "Clara cells are dome-shaped but non-ciliated, not ciliated — cilia are exactly what they lack among the bronchiole's remaining ciliated cells.",
        B: "Clara cells are found within the epithelium of bronchioles, distal to the intrapulmonary bronchi, not within the intrapulmonary bronchi's own epithelium, which still carries goblet cells and lacks Clara cells.",
        C: "Clara cells act as a stem cell for the bronchiolar lining itself, not specifically for type I pneumocytes, which are instead regenerated from type II pneumocytes in the respiratory portion.",
        D: "Clara cells' cytoplasm contains apical smooth endoplasmic reticulum (detoxification and surfactant-like secretion) and basal rough endoplasmic reticulum (protective glycoprotein synthesis) — the organelle basis for their several distinct functions.",
      },
    },
    {
      key: "the-first-part-of-the-respiratory-tract-containsnon-ciliated-fdc3a214",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Hard",
      questionType: "Mechanism",
      learningObjective: "Place the terminal bronchiole as the first airway segment where non-ciliated Clara cells become a notable component of the epithelium.",
      explanations: {
        A: "Non-ciliated Clara cells first become a notable component of the airway epithelium at the level of the terminal bronchiole, interspersed among the remaining ciliated cells — the most proximal (first) segment where non-ciliated cells become histologically prominent, even as scattered ciliated cells persist alongside them.",
        B: "The respiratory bronchiole shows an even higher proportion of non-ciliated Clara cells than the terminal bronchiole, but it is not the first (most proximal) site where non-ciliated cells appear.",
        C: "The trachea is lined by essentially uniform ciliated pseudostratified columnar epithelium with goblet cells, without a significant non-ciliated cell population.",
        D: "The alveolar duct lies well beyond the terminal bronchiole, so it is not the first site where non-ciliated cells appear.",
        E: "Bronchi, like the trachea, are lined by predominantly ciliated epithelium with goblet cells, without yet a significant non-ciliated Clara-cell population.",
      },
    },
    {
      key: "the-following-cell-is-considered-as-a-stem-cell-1-a2296218",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the Clara cell as the bronchiolar epithelium's recognised progenitor (stem) cell.",
      explanations: {
        A: "Type I pneumocytes are terminally differentiated, thin, non-dividing cells; damaged alveolar epithelium is repaired by proliferation of type II pneumocytes, not by type I cells regenerating themselves.",
        B: "Clara cells function as a recognised progenitor cell population for the bronchiolar epithelium, dividing and differentiating into both new Clara cells and ciliated cells to regenerate the bronchiolar lining after injury.",
        C: "The regenerative role in olfactory epithelium belongs to its own basal cells, not to the sustentacular (supporting) cells named here.",
        D: "Alveolar macrophages are fully differentiated immune cells, not a stem or progenitor cell population.",
      },
    },
    {
      key: "the-following-cell-is-considered-as-a-stem-cell-822eaddf",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Identify the Clara cell as the bronchiolar epithelium's stem cell.",
      explanations: {
        A: "Type I pneumocytes are terminally differentiated and do not regenerate themselves; type II pneumocytes take on that role in the respiratory portion instead.",
        B: "Clara cells may act as stem cells for the bronchiolar lining, dividing to replace both Clara and ciliated cells after injury.",
        C: "Sustentacular cells of the olfactory mucosa are supporting cells; the olfactory epithelium's own stem cells are its basal cells, not the sustentacular cells.",
        D: "Alveolar macrophages are differentiated immune cells, not a progenitor population.",
      },
    },
    {
      key: "the-structural-component-which-is-only-found-in-the-bronchio-04bec76c",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Hard",
      questionType: "Recall",
      learningObjective: "Not sittable with confidence.",
      explanations: {},
      exclude: true,
      excludeReason: "The recovered answer (A, 'Goblet cells') directly contradicts this leaf's own department-book-sourced concept text, which states plainly that bronchioles have no goblet cells at all — the epithelial change specifically credited to the bronchiole is the appearance of Clara cells (option D) alongside the loss of goblet cells, cartilage, glands and nodules. The option-A answer was reconstructed by fuzzy-matching a book whose own lettering apparently differs (optionsBefore shows the original extraction had only options B-D, with option A supplied from the matched book), and the resulting key is the opposite of what the module's own histology text supports. Per the ANSWER-KEY GAPS ruling, excluded rather than keyed against the source it should agree with.",
    },
    {
      key: "the-structural-component-which-is-only-found-in-thebronchiol-8de78d86",
      conceptKey: "bronchi-and-bronchioles.structural-progression-and-clara-cells",
      difficulty: "Hard",
      questionType: "Recall",
      learningObjective: "Not sittable with confidence.",
      explanations: {},
      exclude: true,
      excludeReason: "Duplicate stem of the-structural-component-which-is-only-found-in-the-bronchio-04bec76c (same reconstructed option set, same 'Goblet cells' key) — same conflict with this leaf's own department-book concept text, which states bronchioles have no goblet cells and names Clara cells as the bronchiole's defining addition instead. Excluded for the same reason.",
    },
    {
      key: "true-vocal-cord-lingual-surface-of-epiglottis-lined-by-08413a11",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Name stratified squamous epithelium as the lining of the true vocal cords and the lingual surface of the epiglottis, the larynx's two exceptions to respiratory epithelium.",
      explanations: {
        A: "Olfactory epithelium is specific to the nasal cavity's olfactory mucosa, with no part in the larynx.",
        B: "The true vocal cords and the lingual surface of the epiglottis are covered by (non-keratinized) stratified squamous epithelium, the larynx's two named exceptions to its otherwise respiratory-epithelium lining, built to withstand mechanical stress from vibration and swallowing.",
        C: "Respiratory epithelium lines most of the larynx, but not these two specific, mechanically stressed surfaces.",
        D: "Stratified columnar epithelium is not a lining found anywhere in the larynx.",
      },
    },
    {
      key: "vestibular-folds-for-b2703284",
      conceptKey: "larynx.vocal-cords-and-cartilages",
      difficulty: "Easy",
      questionType: "Structure and function",
      learningObjective: "Attribute preventing food from entering the larynx to the vestibular (false vocal) folds, not voice production or airway patency.",
      explanations: {
        A: "Producing voice is the true vocal cords' role, not the vestibular folds'.",
        B: "Maintaining an open airway is credited to the larynx's cartilages generally, not specifically to the vestibular folds.",
        C: "The vestibular (false vocal) folds' role is protective — preventing food and fluid from entering the larynx — distinct from the true vocal cords' phonation role below them.",
        D: "Only the protective role belongs to the vestibular folds specifically; voice production and airway patency are credited to other laryngeal structures, so 'all the above' overstates it.",
      },
    },
    {
      key: "air-is-cleansed-moistened-by-action-of-845299a8",
      conceptKey: "conducting-portion.airway-wall-components-and-functions",
      difficulty: "Moderate",
      questionType: "Structure and function",
      learningObjective: "Attribute conditioning of inspired air jointly to the respiratory epithelium and the underlying vascular network, against options naming only one or naming connective-tissue fibres instead.",
      explanations: {
        A: "Respiratory epithelium alone conditions the air's cleanliness (via mucus and cilia) but not its warming and humidifying, which needs the vascular network beneath it too.",
        B: "Elastic and collagen fibres give the airway wall its flexibility and resistance to collapse; they play no part in cleansing or moistening the air passing through it.",
        C: "Collagen fibres belong to the structural, collapse-resisting pairing with cartilage, not to the conditioning function this question asks about.",
        D: "Air is cleansed and moistened by the combined action of the respiratory epithelium (mucus trapping particles, cilia clearing them) and the vascular network beneath it (warming and humidifying the air) — conditioning carried out separately from the wall's structural, collapse-resisting components.",
      },
    },
  ],
}
