/**
 * `102 INT > Physiology > Blood > Abnormalities of haemostasis` — the
 * question books' MCQs.
 *
 * Two rows. One tests the intrinsic coagulation cascade (a new concept,
 * declared in full in `platelets-and-haemostasis.ts` where most of its
 * evidence sits, and reused here); the other tests haemophilia, which
 * already has a concept from the hand-authored physiology concept batch.
 */
import type { McqLeafSeed } from '../../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Abnormalities of haemostasis',
  modulePath: '102 INT > Physiology > Blood > Abnormalities of haemostasis',
  articleId: 'ART-102-PHY-ABNORMALITIES-OF-HAEMOSTASIS',

  concepts: [
    {
      key: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      label:
        'The intrinsic pathway starts inside the vessel from exposed collagen, the extrinsic pathway starts outside it from tissue thromboplastin, and both converge on a common pathway that turns prothrombin into thrombin and fibrinogen into fibrin',
      definition:
        'Coagulation runs as two initiating cascades that converge. The intrinsic pathway (occurs both in vivo and in vitro) begins when blood contacts exposed subendothelial collagen or an electronegatively-charged surface such as glass: factor XII is activated to XIIa (catalysed by HMW kininogen and plasma kallikrein), XIIa activates XI, XI activates IX, and IXa forms a complex with VIIIa (itself freed from von Willebrand factor by thrombin) that, together with platelet phospholipid and Ca2+, activates factor X. The extrinsic pathway (in vivo only) begins when tissue trauma releases tissue thromboplastin, which activates factor VII; the VIIa–thromboplastin complex then activates factors IX and X directly. Active factor X, with phospholipid, Ca2+ and factor Va, forms the prothrombin activator that converts prothrombin to thrombin — the common pathway\'s point of convergence. Thrombin then converts fibrinogen to fibrin monomer, and factor XIII (itself activated by thrombin) cross-links the loose fibrin mesh into a stable clot. The extrinsic system is fast (about 15 seconds) and the intrinsic system slow (1–6 minutes), and thrombin generated by the extrinsic route activates factors VIII and V, recruiting the intrinsic system into the same clot.',
      objective:
        'Assign a coagulation event to the intrinsic pathway (collagen or glass contact, factor XII first), the extrinsic pathway (tissue thromboplastin, factor VII first) or the common pathway (factor X onward), and state which factor each named step activates.',
      pitfall:
        'Swapping which pathway is which trigger: the pathway that starts *inside* the vessel (intrinsic) is triggered by contact with something *outside* normal blood flow — exposed collagen or a foreign surface — while the pathway that starts *outside* the vessel (extrinsic, from damaged tissue) needs an outside injury to release thromboplastin. The names describe where the trigger substance normally lives, not where the reaction happens.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
      type: 'mechanism',
      aliases: ['Intrinsic pathway', 'Extrinsic pathway', 'Common pathway', 'Coagulation cascade'],
    },
    {
      key: 'hemophilia-types-a-b-c',
      label: 'Haemophilia is a sex-linked recessive bleeding disorder carried by females and manifested in males, in three types by which factor is missing',
      definition:
        'Haemophilia is a sex-linked recessive disease, carried by females and manifesting almost always in males, characterised by episodes of haemorrhage into joints or internal organs after minor trauma and by prolongation of the whole blood coagulation time. Haemophilia A (classic, 85% of cases) is a deficiency of factor VIII; haemophilia B is absence of factor IX; haemophilia C is absence of factor XI.',
      objective: 'State the inheritance pattern of haemophilia and which factor is missing in each of its three types, and its effect on coagulation time.',
      pitfall: 'Confusing haemophilia\'s prolonged coagulation time (a clotting-factor problem) with a prolonged bleeding time (a platelet-function problem, as in thrombocytopenic purpura) — the two tests measure different stages of haemostasis and haemophilia affects only the former.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Abnormalities of haemostasis',
      type: 'clinical_correlation',
      aliases: ['Classic haemophilia', 'Factor VIII deficiency'],
    },
  ],

  questions: [
    {
      key: 'MCQ-102-2093c80b-p14-q46',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State what activated factor IX does in the intrinsic pathway.',
      explanations: {
        a: 'Factor IX is not a cofactor — it is an enzyme (a serine protease once activated). The cofactor in its activation complex is factor VIIIa, not factor IX itself.',
        b: 'Backwards. Factor IX is activated by factor XIa (upstream of it in the intrinsic pathway), not by factor V, which belongs to the common pathway further downstream.',
        c: 'Backwards. Deficiency of factor IX causes haemophilia B, not haemophilia A — haemophilia A is factor VIII deficiency.',
        d: 'Activated factor IX (IXa), complexed with activated factor VIII (VIIIa), platelet phospholipid and Ca2+, activates factor X — the step at which the intrinsic pathway hands off to the common pathway.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p18-q69',
      conceptKey: 'hemophilia-types-a-b-c',
      difficulty: 'Easy',
      questionType: 'Clinical correlation',
      learningObjective: 'State that haemophilia prolongs the coagulation time, and its inheritance pattern.',
      explanations: {
        a: 'Backwards. A sex-linked recessive disease on the X chromosome is carried by females (who have a second, usually normal, X) and manifests almost always in males (who have only one X) — the opposite of what this option claims.',
        b: 'This describes haemophilia B (factor IX deficiency), but the stem does not name a type, and this option misstates the missing factor as XI when haemophilia B is defined by factor IX — haemophilia C is the one caused by factor XI absence.',
        c: 'Haemophilia is a clotting-factor deficiency, which prolongs the whole blood *coagulation* time, not the *bleeding* time (a platelet-function measure) — the two tests are not interchangeable.',
        d: 'Whichever factor is missing (VIII, IX or XI, according to type), haemophilia slows the intrinsic-pathway cascade and so prolongs the whole blood coagulation time.',
      },
    },
  ],
}
