/**
 * `102 INT > Physiology > Blood > Platelets and haemostasis` — the question
 * books' MCQs.
 *
 * Twenty-two rows — the largest single cluster in this module's Physiology
 * scope, mostly the coagulation cascade (intrinsic/extrinsic/common
 * pathways) and platelet-plug formation, neither of which any existing
 * concept covered despite being the book's densest running-prose section
 * (physical pp134-139). Two new concepts are minted here for that reason;
 * everything else reuses concepts from this leaf's own existing
 * thromboxane/prostacyclin concept or from neighbouring leaves — except the
 * aspirin/bleeding-time content, which mints its own new concept rather than
 * reusing the live `aspirin-cox-inhibition-mi-prevention` (subject `pharm`):
 * the MCQ route's concept mint always attempts a fresh `mintConceptId` for
 * comparison, and `pharm` has no default body-system code with no way to
 * pass a `system` override through `McqConcept`, so reusing that pharm-
 * subject id from this route throws. One OCR key conflict is resolved from
 * the book rather than guessed, and one row is excluded as an intra-book
 * duplicate the extractor's dedup pass did not catch (same source book,
 * same content, two different printed question numbers).
 */
import type { McqLeafSeed } from '../mcq.ts'

export const LEAF: McqLeafSeed = {
  leaf: 'Platelets and haemostasis',
  modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
  articleId: 'ART-102-PHY-PLATELETS-AND-HAEMOSTASIS',

  concepts: [
    {
      key: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      label:
        'The intrinsic pathway starts inside the vessel from exposed collagen, the extrinsic pathway starts outside it from tissue thromboplastin, and both converge on a common pathway that turns prothrombin into thrombin and fibrinogen into fibrin',
      definition:
        'Coagulation runs as two initiating cascades that converge. The intrinsic pathway (occurs both in vivo and in vitro) begins when blood contacts exposed subendothelial collagen or an electronegatively-charged surface such as glass: factor XII is activated to XIIa (catalysed by HMW kininogen and plasma kallikrein), XIIa activates XI, XI activates IX, and IXa forms a complex with VIIIa (freed from von Willebrand factor by thrombin) that, with platelet phospholipid and Ca2+, activates factor X. The extrinsic pathway (in vivo only) begins when tissue trauma releases tissue thromboplastin, which activates factor VII; the VIIa–thromboplastin complex then activates factors IX and X directly. Active factor X, with phospholipid, Ca2+ and factor Va, forms the prothrombin activator that converts prothrombin to thrombin — the common pathway\'s convergence point. Thrombin converts fibrinogen to fibrin monomer, and factor XIII (activated by thrombin) cross-links the loose fibrin mesh into a stable clot. The extrinsic system is fast (about 15 seconds), the intrinsic system slow (1–6 minutes); thrombin generated by the extrinsic route activates factors VIII and V, recruiting the intrinsic system into the same clot.',
      objective: 'Assign a coagulation event to the intrinsic pathway (collagen or glass contact, factor XII first), the extrinsic pathway (tissue thromboplastin, factor VII first) or the common pathway (factor X onward), and state which factor each named step activates.',
      pitfall: 'Swapping which pathway is which trigger: the pathway that starts *inside* the vessel (intrinsic) is triggered by contact with something *outside* normal blood flow — exposed collagen or a foreign surface — while the pathway that starts *outside* the vessel (extrinsic, from damaged tissue) needs an outside injury to release thromboplastin.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
      type: 'mechanism',
      aliases: ['Intrinsic pathway', 'Extrinsic pathway', 'Common pathway', 'Coagulation cascade'],
    },
    {
      key: 'platelet-plug-formation-steps-and-functions',
      label: 'Platelets adhere to exposed collagen and von Willebrand factor, activate, release their granule contents, aggregate through fibrinogen bridges and fuse — five steps that build a temporary haemostatic plug and prepare the surface for coagulation',
      definition:
        'Formation of the temporary haemostatic plug (primary haemostasis) proceeds in steps. (1) Adhesion: platelets, which normally circulate without sticking to endothelium, adhere via glycoprotein receptors to exposed subendothelial collagen and von Willebrand factor when the vessel is damaged. (2) Activation: adhesion triggers an intracellular signalling pathway; platelets swell, change shape, put out pseudopodia and discharge granule contents, enhanced by ADP and thrombin. (3) Release reaction (Ca2+-dependent): dense granules release calcium, ADP (more activation/aggregation/fusion) and serotonin (reinforces vasoconstriction); alpha granules release coagulation factors, platelet-derived growth factor (vessel repair), platelet activating factor and thromboxane A2. (4) Aggregation: released ADP and TXA2 make platelets bind each other through fibrinogen receptor bridges, in a self-propagating cycle. (5) Fusion: irreversible fusion of the aggregated platelets at the injury site, driven by high ADP, thrombin and released enzyme concentrations. Throughout, platelets also act as pro-coagulant catalysts — their exposed membrane phospholipid (PF3) concentrates and activates the coagulation factors — and their released factors promote clotting and reinforce vasoconstriction, arresting bleeding by three separate routes at once.',
      objective: 'Order the five steps of platelet-plug formation (adhesion, activation, release, aggregation, fusion) and name what each step contributes to arresting bleeding.',
      pitfall: 'Placing aggregation before release, or release before activation — the sequence matters because each step\'s products drive the next: activation is what makes the granules dischargeable, the released ADP/TXA2 are what cause aggregation, and only aggregated platelets then fuse irreversibly.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
      type: 'mechanism',
      aliases: ['Primary haemostasis', 'Platelet adhesion', 'Platelet aggregation'],
    },
    {
      key: 'thromboxane-a2-and-prostacyclin-balance',
      label: 'Thromboxane A2 from the platelet and prostacyclin from the endothelium are made by the same enzyme from the same substrate and do the opposite things, and that opposition is what keeps a platelet plug at the site of injury',
      definition:
        'Thromboxane A2, produced from arachidonic acid in the membrane of active platelets by cyclooxygenase, is a vasoconstrictor and a powerful stimulant of platelet release and aggregation. Prostacyclin, produced from arachidonic acid in the vascular endothelium by the same enzyme, is a powerful vasodilator and an inhibitor of platelet release and aggregation. Because their actions are opposite, the balance between the two limits the platelet plug to the site of injury rather than letting it spread.',
      objective: 'State the shared synthetic pathway (cyclooxygenase, arachidonic acid) and opposite actions of thromboxane A2 and prostacyclin, and explain how their balance localises clotting.',
      pitfall: 'Treating thromboxane A2 and prostacyclin as produced by different substrates or different enzymes — they are the same starting material (arachidonic acid) processed by the same enzyme (cyclooxygenase) in two different cell types, which is exactly what aspirin\'s cyclooxygenase inhibition exploits.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
      type: 'mechanism',
      aliases: ['TXA2', 'Prostacyclin', 'PGI2'],
    },
    {
      key: 'aspirin-platelet-aggregation-and-bleeding-time',
      label: 'Aspirin prevents myocardial infarction because it inhibits cyclooxygenase in both cells but only the endothelial cell can make the enzyme again, so a small prolonged dose suppresses thromboxane A2 while prostacyclin recovers',
      definition:
        'Aspirin inhibits cyclooxygenase, reducing both thromboxane A2 and prostacyclin production. Endothelial cells produce new cyclooxygenase within hours, but platelets — lacking a nucleus and the machinery to synthesise new enzyme — cannot. Small prolonged doses of aspirin therefore suppress platelet thromboxane A2 (impairing platelet aggregation and prolonging bleeding time) while endothelial prostacyclin recovers, tilting the balance toward reduced clot formation and away from myocardial infarction.',
      objective: 'Explain why aspirin\'s effect on platelet aggregation outlasts its effect on endothelial prostacyclin, and connect that asymmetry to bleeding-time prolongation and MI prevention.',
      pitfall: 'Assuming aspirin blocks clotting the way heparin or warfarin does (acting on the coagulation cascade) — it acts upstream, on platelet aggregation via thromboxane A2 suppression, which is why it prolongs bleeding time rather than coagulation time.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Platelets and haemostasis',
      type: 'mechanism',
      aliases: ['Aspirin MI prevention', 'Cyclooxygenase inhibition'],
    },
    {
      key: 'vitamin-k-deficiency-bleeding-disorder',
      label: 'Vitamin K deficiency lowers hepatic formation of factors II, VII, IX, X and proteins C and S, prolonging coagulation time',
      definition:
        'Vitamin K, needed by the liver to form factors II, VII, IX, X and proteins C and S, is fat-soluble and depends on bile for its absorption. Bile duct obstruction removes that bile, causing vitamin K deficiency, decreased synthesis of these factors (especially prothrombin), and increased bleeding tendency.',
      objective: 'Trace bile-duct obstruction through fat-soluble-vitamin malabsorption to decreased prothrombin synthesis and bleeding tendency.',
      pitfall: 'Attributing bile-duct-obstruction bleeding to a platelet problem — it is a clotting-factor synthesis problem (vitamin K malabsorption), and would show as a prolonged coagulation time, not a platelet-count or bleeding-time abnormality.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Abnormalities of haemostasis',
      type: 'mechanism',
      aliases: ['Vitamin K malabsorption', 'Cholestatic coagulopathy'],
    },
    {
      key: 'plasma-proteins-formation-and-functions',
      label:
        'The liver makes albumin, fibrinogen, the clotting factors and half the globulins while plasma cells make the gamma globulins, and between them the plasma proteins hold water in the capillary, buffer the blood, defend it, clot it, thicken it, seal the capillary pores, carry small molecules and store amino acids',
      definition:
        'The liver is the main site of plasma protein synthesis — albumin, fibrinogen and all the coagulation factors, plus 50% of globulins. A diseased liver therefore makes fewer clotting factors as well as less albumin, contributing to a bleeding tendency alongside its osmotic and other effects.',
      objective: 'Name the liver as the site where fibrinogen and the coagulation factors are made, and connect liver disease to depressed coagulation.',
      pitfall: 'Attributing liver-disease bleeding only to a vitamin K mechanism — a diseased liver also makes fewer clotting factors directly, independent of whether vitamin K is available, which is a broader defect than the vitamin K deficiency of bile-duct obstruction alone.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Plasma proteins',
      type: 'mechanism',
      aliases: ['Hepatic clotting factor synthesis'],
    },
    {
      key: 'physiological-limitation-of-coagulation',
      label:
        'Coagulation is held in check by general limiting reactions — smooth endothelium, hepatic clearance of activated factors and natural heparin — and by three specific ones: the thromboxane–prostacyclin balance, antithrombin III, and the fibrinolytic system',
      definition:
        'Physiological limits on coagulation include heparin, present in small amounts in the blood, which combines with antithrombin III to inactivate factors IX, X, XI and XII — meaning heparin\'s anticoagulant action works by potentiating (increasing the effective activity of) antithrombin III, not by acting alone. Thrombomodulin, expressed by endothelial cells outside the cerebral microcirculation, binds thrombin to activate protein C, which — with cofactor protein S — inactivates factors V and VIII and frees tissue plasminogen activator to drive fibrinolysis.',
      objective: 'State that heparin\'s anticoagulant mechanism is to increase antithrombin III\'s activity against factors IX, X, XI and XII, not to inhibit clotting factors directly itself.',
      pitfall: 'Treating heparin as though it neutralised clotting factors on its own — its action is entirely dependent on antithrombin III as a cofactor; without antithrombin III present, heparin has nothing to potentiate.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Physiological limitations of blood coagulation',
      type: 'mechanism',
      aliases: ['Antithrombin III', 'Heparin mechanism', 'Protein C pathway'],
    },
    {
      key: 'thrombocytopenic-purpura',
      label: 'Thrombocytopenic purpura follows a platelet count below 50,000/mm3 or defective platelet function, and shows as petechiae and prolonged bleeding time',
      definition:
        'Thrombocytopenic purpura follows either a platelet count decreased below 50,000/mm3 or defective platelet function (thrombasthenia). It is characterised by petechiae (many subcutaneous haemorrhages) and prolongation of bleeding time — the time needed for bleeding to stop without clotting, normally 1–3 minutes, and dependent on platelet count and function.',
      objective: 'Connect a low platelet count (below 50,000/mm3) or defective platelet function to petechiae and a prolonged bleeding time, distinct from a prolonged coagulation time.',
      pitfall: 'Confusing thrombocytopenia\'s prolonged *bleeding* time (a platelet-dependent measure) with a prolonged *coagulation* time (a clotting-factor-dependent measure, as in haemophilia) — the two tests probe different stages of haemostasis.',
      subject: 'haem',
      primary: 'DIS-PHY-T02',
      secondary: [],
      modulePath: '102 INT > Physiology > Blood > Abnormalities of haemostasis',
      type: 'clinical_correlation',
      aliases: ['Petechiae', 'Prolonged bleeding time'],
    },
  ],

  questions: [
    {
      key: 'MCQ-102-2093c80b-p12-q33',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that the extrinsic pathway is initiated by tissue thromboplastin release.',
      explanations: {
        a: 'Backwards. Contact with a negatively charged surface initiates the *intrinsic* pathway (factor XII activation), not the extrinsic one.',
        b: 'Backwards. The intrinsic pathway occurs both in vivo and in vitro — it is the extrinsic pathway that occurs only in vivo, since it needs actual tissue trauma.',
        c: 'Backwards. Tissue damage initiates the *extrinsic* pathway (via thromboplastin release), not the intrinsic one, which is triggered by collagen or foreign-surface contact instead.',
        d: 'Correct. The extrinsic pathway is initiated when tissue trauma releases tissue thromboplastin, which activates factor VII.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p12-q35',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Identify thrombin converting fibrinogen to fibrin as the final step of clot formation.',
      explanations: {
        a: 'Forming the prothrombin activator (active factor X with Ca2+, phospholipid and factor Va) is an earlier common-pathway step, not the final one — it is what makes thrombin, not the last reaction itself.',
        b: 'Correct. Thrombin converting soluble fibrinogen to insoluble fibrin monomer threads is the final reaction that actually produces the clot — everything before it builds toward generating thrombin.',
        c: 'Converting prothrombin to thrombin is the step immediately before the final reaction, not the final reaction itself.',
        d: 'Hageman factor is another name for factor XII, which activates the intrinsic pathway at its very start, not prothrombin at the cascade\'s end.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p12-q36',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that tissue thromboplastin activates factor VII in the extrinsic pathway.',
      explanations: {
        a: 'Factor VIII belongs to the intrinsic pathway (activated when separated from von Willebrand factor by thrombin), not to the extrinsic sequence tissue thromboplastin starts.',
        b: 'Calcium is a cofactor throughout the cascade, but it does not itself activate factor VII — tissue thromboplastin does.',
        c: 'Correct. Tissue thromboplastin, released by damaged tissue, activates factor VII — the first step of the extrinsic pathway.',
        d: 'Factor IX is activated in the intrinsic pathway (by XIa) or, downstream, by the VIIa–thromboplastin complex — but factor VII is the extrinsic pathway\'s own first target, not IX.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q37',
      conceptKey: 'aspirin-platelet-aggregation-and-bleeding-time',
      difficulty: 'Moderate',
      questionType: 'Clinical correlation',
      learningObjective: 'Attribute a prolonged bleeding time to large-dose aspirin.',
      explanations: {
        a: 'Factor VIII deficiency (haemophilia A) prolongs *coagulation* time, not bleeding time — it is a clotting-factor defect, not a platelet-function one.',
        b: 'Vitamin K malabsorption prolongs coagulation time (fewer prothrombin-group factors), not bleeding time.',
        c: 'Liver disease prolongs coagulation time through reduced clotting-factor synthesis, not bleeding time specifically.',
        d: 'Correct. Large quantities of aspirin inhibit cyclooxygenase in platelets, suppressing thromboxane A2 and impairing platelet aggregation, which prolongs bleeding time — the platelet-dependent measure, distinct from coagulation time.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q38',
      conceptKey: 'thromboxane-a2-and-prostacyclin-balance',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that thromboxane A2 causes platelet aggregation.',
      explanations: {
        a: 'Correct. Thromboxane A2 is a powerful stimulant of platelet aggregation, alongside being a vasoconstrictor and a stimulator of the platelet release reaction.',
        b: 'Backwards. Thromboxane A2 and prostacyclin are two separate products of the same substrate and enzyme (arachidonic acid via cyclooxygenase) made in different cell types — thromboxane A2 is not metabolised into prostacyclin.',
        c: 'Backwards. Aspirin inhibits the cyclooxygenase enzyme that makes thromboxane A2, reducing its production — it does not bind and inactivate thromboxane A2 directly once formed.',
        d: 'Converting prothrombin to thrombin is a coagulation-cascade common-pathway step (via active factor X), not something thromboxane A2, a platelet-derived eicosanoid, does.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q39',
      conceptKey: 'platelet-plug-formation-steps-and-functions',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Recognise that platelets do not themselves supply high concentrations of calcium to the plasma.',
      explanations: {
        a: 'Releasing clotting-promoting factors (fibrinogen, factor V, von Willebrand factor, factor XIII from alpha granules) is a genuine way platelets help arrest bleeding, so it is not the exception.',
        b: 'Adhering together to form a plug when exposed to collagen is the adhesion step of platelet-plug formation, a genuine mechanism, so it is not the exception.',
        c: 'Correct — the exception. Platelets release calcium from their dense granules, but this reinforces further platelet activation and release locally, not a systemic liberation of "high concentrations" of calcium into the plasma — this option overstates what the release reaction achieves.',
        d: 'Releasing factors that cause vasoconstriction (serotonin, thromboxane A2) is a genuine platelet mechanism for arresting bleeding, so it is not the exception.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q40',
      conceptKey: 'vitamin-k-deficiency-bleeding-disorder',
      difficulty: 'Moderate',
      questionType: 'Clinical correlation',
      learningObjective: 'Attribute bile-duct-obstruction bleeding tendency to decreased hepatic prothrombin synthesis via vitamin K malabsorption.',
      explanations: {
        a: 'Factor XII is part of the contact group, activated by surface contact and not vitamin-K-dependent — bile duct obstruction does not act through factor XII.',
        b: 'Bile duct obstruction is not described as reducing the platelet count; its bleeding mechanism runs through vitamin K malabsorption and factor synthesis, not platelet numbers.',
        c: 'Vitamin K is *absorbed* using bile, not *synthesised* in the liver — the liver only uses the vitamin, once absorbed, to make the clotting factors. This option mislocates where vitamin K comes from.',
        d: 'Correct. Bile duct obstruction removes the bile needed to absorb the fat-soluble vitamin K, and the liver needs vitamin K to synthesise prothrombin (and the other vitamin-K-dependent factors) — so obstruction lowers prothrombin synthesis and raises bleeding tendency.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q41',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that contact with subendothelial collagen activates factor XII, starting the intrinsic pathway.',
      explanations: {
        a: 'Backwards. Contact with subendothelial collagen *activates* platelets (the adhesion step of primary haemostasis), it does not inhibit them.',
        b: 'Factor VII is activated by tissue thromboplastin in the *extrinsic* pathway, not by collagen contact, which triggers the intrinsic pathway instead.',
        c: 'Correct. Contact with exposed subendothelial collagen activates factor XII to XIIa — the first step of the intrinsic pathway.',
        d: 'Factor IX is activated further downstream in the intrinsic cascade (by XIa, after XII and XI), not directly by collagen contact itself.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p13-q42',
      conceptKey: 'aspirin-platelet-aggregation-and-bleeding-time',
      difficulty: 'Easy',
      questionType: 'Mechanism',
      learningObjective: 'State that aspirin impairs platelet aggregation.',
      explanations: {
        a: 'Correct. Aspirin inhibits cyclooxygenase, suppressing platelet thromboxane A2 and so impairing the aggregation step of platelet-plug formation.',
        b: 'Aspirin does not reduce platelet *count* — it impairs the function (aggregation) of the platelets that are present, which is a different kind of effect.',
        c: 'Backwards. Aspirin *prolongs* bleeding time (by impairing aggregation), it does not reduce it.',
        d: 'Aspirin does not shorten platelet lifespan — its effect (suppressed thromboxane A2, lasting the platelet\'s whole lifespan because platelets cannot resynthesise cyclooxygenase) is functional, not a change in how long platelets survive.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p14-q43',
      conceptKey: 'plasma-proteins-formation-and-functions',
      difficulty: 'Moderate',
      questionType: 'Clinical correlation',
      learningObjective: 'Attribute post-surgical excessive bleeding to depressed hepatic synthesis of clotting factors in liver disease.',
      explanations: {
        a: 'Gastrointestinal disease is not described in the book as directly depressing coagulation-factor synthesis the way liver disease is — its bleeding risk, where it exists, runs through malabsorption of fat-soluble vitamin K rather than a synthesis defect itself.',
        b: 'Heart disease is not connected in the book to depressed coagulation or excessive surgical bleeding.',
        c: 'Kidney disease is connected in the book to a *lowered* albumin/globulin ratio (protein lost in urine), not to depressed coagulation-factor synthesis.',
        d: 'Correct. The liver is the main site of synthesis of fibrinogen and the coagulation factors; liver disease depresses that synthesis directly, causing excessive bleeding after surgery.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p14-q44',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Hard',
      questionType: 'Mechanism',
      learningObjective: 'State that tissue thromboplastin complexes with factor VIIa to activate factor X.',
      explanations: {
        a: 'Tissue thromboplastin is not another name for factor V — it is the tissue-derived phospholipid that starts the extrinsic pathway by activating factor VII, a separate identity entirely.',
        b: 'Tissue thromboplastin is the trigger that activates factor VII, not a receptor that factor VIIa binds to on a cell surface.',
        c: 'Correct. Tissue thromboplastin, complexed with factor VIIa, activates factor X — the extrinsic pathway\'s route into the common pathway.',
        d: 'Backwards. Tissue thromboplastin is the defining trigger of the *extrinsic* pathway, not a component of the intrinsic one.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p14-q47',
      conceptKey: 'physiological-limitation-of-coagulation',
      difficulty: 'Hard',
      questionType: 'Mechanism',
      learningObjective: 'State that thrombomodulin binds thrombin to activate a pathway leading to reduced coagulation.',
      explanations: {
        a: 'Thrombomodulin is secreted by endothelial cells, not by red blood cells — RBCs play no part in this limiting mechanism.',
        b: 'Thrombomodulin is not activated by heparin — heparin\'s own anticoagulant action instead works through antithrombin III, a separate limiting mechanism entirely.',
        c: 'Thrombomodulin\'s role is to bind thrombin and, through the resulting complex, activate protein C — it does not itself activate platelets, which is instead what thrombin and ADP do earlier in primary haemostasis.',
        d: 'Correct. Thrombomodulin binds thrombin, and the thrombomodulin–thrombin complex activates protein C, which (with its cofactor protein S) inactivates factors V and VIII and frees fibrinolysis to proceed — one of the book\'s named physiological limits on coagulation. The book\'s own next sentence names protein C, with protein S as its cofactor, as what that complex activates.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p15-q49',
      conceptKey: 'physiological-limitation-of-coagulation',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Name heparin as increasing antithrombin III activity.',
      answerOverride: 'd',
      answerOverrideReason:
        'The two OCR passes disagreed between options A (aspirin) and D (heparin), but the module book directly names heparin\'s mechanism as combining with antithrombin III to inactivate factors IX, X, XI and XII (physical p140) — which is described as facilitating, i.e. increasing, antithrombin III\'s activity (also stated explicitly in the heparin-vs-dicumarol comparison table, physical p142: "Facilitates action of Antithrombin III"). Aspirin\'s mechanism (cyclooxygenase inhibition, affecting thromboxane A2 and prostacyclin) has no stated connection to antithrombin III anywhere in the book, so D is the only option the book supports.',
      explanations: {
        a: 'Aspirin\'s mechanism is cyclooxygenase inhibition, suppressing thromboxane A2 and prostacyclin — the book does not connect it to antithrombin III at all.',
        b: 'Citrate\'s anticoagulant action is chelating calcium, an entirely different mechanism from antithrombin III potentiation, and used only as an in vitro anticoagulant for stored blood.',
        c: 'Coumarin (warfarin) works by competitively inhibiting vitamin K in the liver, blocking synthesis of the vitamin-K-dependent factors — a different mechanism from antithrombin III, which acts on already-formed active factors rather than blocking new synthesis.',
        d: 'Correct. Heparin combines with antithrombin III to inactivate factors IXa, Xa, XIa and XIIa — the book\'s comparison table describes this explicitly as heparin "facilitating" antithrombin III\'s action, i.e. increasing its activity.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p15-q50',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Classification',
      learningObjective: 'Identify exposed endothelial collagen as the trigger for the intrinsic pathway.',
      explanations: {
        a: 'The extrinsic pathway begins with tissue thromboplastin release from damaged tissue, not with exposed endothelial collagen.',
        b: 'Correct. The intrinsic pathway begins when blood contacts exposed subendothelial collagen (activating factor XII), which is why it is described as beginning "inside" the vessel wall itself rather than from outside tissue damage.',
        c: 'The common pathway begins downstream, at active factor X forming the prothrombin activator — not at the point collagen is first exposed.',
        d: 'Fibrin stabilisation is the final step of the common pathway (factor XIII cross-linking fibrin), a different, later phase from where the cascade begins.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p15-q52',
      conceptKey: 'thromboxane-a2-and-prostacyclin-balance',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Name the thromboxane A2–prostacyclin balance as an anticlotting limiting reaction.',
      explanations: {
        a: 'Inactivation of factor XII is not a mechanism the book names among its physiological limiting reactions — the book\'s named contact-group inactivation route runs through the liver clearing activated factors generally, not a specific factor-XII inactivation step.',
        b: 'The book does not describe the kidney as removing activated clotting factors — that is the liver\'s named role among the limiting reactions.',
        c: 'The book names antithrombin III as binding factors IX, X, XI and XII, not VII — this option lists the wrong set of factors for antithrombin III\'s action.',
        d: 'Correct. The book names the balance between thromboxane A2 (a platelet-derived vasoconstrictor and aggregation stimulant) and prostacyclin (an endothelial vasodilator and aggregation inhibitor) as one of the mechanisms that limits the clot to the site of injury.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p16-q59',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that active factor X converts prothrombin to thrombin.',
      explanations: {
        a: 'Platelet activation is triggered earlier, by adhesion to collagen and von Willebrand factor — it is not what makes factor X important in the coagulation cascade.',
        b: 'Vasoconstriction of the injured vessel is an earlier, separate haemostasis step (driven by local myogenic contraction, nervous reflexes and platelet-released factors), not a function of active factor X.',
        c: 'Correct. Active factor X, together with phospholipid, Ca2+ and factor Va, forms the prothrombin activator that converts prothrombin to thrombin — the step at which the intrinsic and extrinsic pathways converge on the common pathway.',
        d: 'Backwards. Factor XI sits upstream of factor X in the intrinsic pathway (XII activates XI, which activates IX, which with VIIIa activates X) — factor X does not activate factor XI.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p16-q60',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that glass activates factor XII in vitro, initiating the intrinsic pathway.',
      explanations: {
        a: 'Tissue factor (thromboplastin) activating factor VII describes the extrinsic pathway, which the book states occurs only in vivo — a glass tube outside the body cannot supply tissue thromboplastin.',
        b: 'Blood clotting in a glass tube is *promotion* of fibrin formation, not prevention — this option states the opposite of what is observed.',
        c: 'Correct. The book states factor XII can be activated in vitro by exposure to electronegatively-charged wettable surfaces such as glass — silica activating factor XII is exactly this mechanism, and it is why the intrinsic pathway (unlike the extrinsic) occurs both in vivo and in vitro.',
        d: 'The book does not connect glass-tube clotting to vitamin K — vitamin K governs hepatic synthesis of certain factors over days, an entirely different timescale and mechanism from the immediate contact-activation seen in a test tube.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p17-q62',
      conceptKey: 'aspirin-platelet-aggregation-and-bleeding-time',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that aspirin causes bleeding tendency through cyclooxygenase inhibition.',
      explanations: {
        a: 'Correct. Aspirin inhibits cyclooxygenase, suppressing platelet thromboxane A2 production and so impairing platelet aggregation, which is the mechanism behind its bleeding-tendency side effect.',
        b: 'Aspirin does not act on plasmin — the fibrinolytic system\'s own regulation runs through tissue plasminogen activator and its inhibitors, a separate pathway from aspirin\'s cyclooxygenase target.',
        c: 'Aspirin does not inhibit heparin — the two act on entirely separate systems (cyclooxygenase/platelets vs antithrombin III/coagulation factors).',
        d: 'Aspirin does not inhibit fibrinolysins (plasmin and related enzymes) — inhibiting fibrinolysis would if anything reduce bleeding tendency by preserving clots, the opposite direction from aspirin\'s actual effect.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p17-q64',
      conceptKey: 'platelet-plug-formation-steps-and-functions',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'Order the steps of platelet-plug formation: adhesion, activation, release, aggregation, fusion.',
      explanations: {
        a: 'This order starts with release and ends with adhesion and activation — the reverse of the true sequence, since a platelet cannot release granule contents before it has adhered and been activated.',
        b: 'This order starts with fusion, which is the *final* step, not the first — fusion can only happen after platelets have already aggregated together.',
        c: 'This order repeats "activation" twice and omits adhesion, which must come first (a platelet has nothing to activate against until it has adhered to exposed collagen or von Willebrand factor).',
        d: 'Correct. The book\'s own sequence is: adhesion (to collagen/von Willebrand factor) → activation (shape change, pseudopodia) → release reaction (granule contents) → aggregation (fibrinogen bridges) → fusion (irreversible).',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p17-q66',
      conceptKey: 'vitamin-k-deficiency-bleeding-disorder',
      difficulty: 'Moderate',
      questionType: 'Clinical correlation',
      learningObjective: 'Not sittable as extracted.',
      explanations: {},
      exclude: true,
      excludeReason:
        'Identical content to `MCQ-102-2093c80b-p13-q40` — same stem ("Obstruction of common bile duct by a stone will increase bleeding tendency due to:"), same four options, same printed key (D, decreased synthesis of prothrombin), from the same source book (`src_2093c80b1f9c25f9c0a4`), printed twice under two different question numbers (40 and 66). Not flagged `duplicateOf` by the extractor because its dedup pass evidently runs across source books rather than within one, and this repeat sits within a single book. Kept as the row to exclude rather than the earlier one, so the surviving triaged copy is the first sighting.',
    },
    {
      key: 'MCQ-102-2093c80b-p18-q67',
      conceptKey: 'coagulation-cascade-intrinsic-extrinsic-common-pathways',
      difficulty: 'Moderate',
      questionType: 'Mechanism',
      learningObjective: 'State that factor VII initiates coagulation together with tissue thromboplastin.',
      explanations: {
        a: 'Factor VII belongs to the prothrombin group of the extrinsic/common pathway, not a cofactor in the intrinsic pathway — the intrinsic pathway\'s own contact-group members are XI and XII.',
        b: 'Correct. Factor VII, activated by tissue thromboplastin released from damaged tissue, initiates the extrinsic coagulation pathway.',
        c: 'Converting fibrinogen to fibrin is thrombin\'s job at the end of the common pathway, not factor VII\'s at the cascade\'s start.',
        d: 'Coagulation factors are produced by the liver (mainly beta globulins), not by platelets, though platelets do contribute phospholipid surface and some factors from their alpha granules — factor VII specifically is hepatic, not platelet-derived.',
      },
    },
    {
      key: 'MCQ-102-2093c80b-p18-q70',
      conceptKey: 'thrombocytopenic-purpura',
      difficulty: 'Easy',
      questionType: 'Clinical correlation',
      learningObjective: 'State that thrombocytopenia prolongs bleeding time.',
      explanations: {
        a: 'Backwards. A low platelet count *impairs* the platelet-dependent phase of haemostasis; blood coagulation (the clotting-factor cascade) is not increased by thrombocytopenia.',
        b: 'Excessive RBC haemolysis describes a haemolytic anaemia, an unrelated condition to a low platelet count.',
        c: 'Correct. Thrombocytopenia — platelet count below 50,000/mm3, or defective platelet function — is characterised by prolonged bleeding time and petechiae.',
        d: '"Thrombocytopenia" means a *decreased*, not increased, platelet number — the name itself states the opposite of this option.',
      },
    },
  ],
}
