package com.synapse.android.core.cache.entities

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import java.time.Instant
import kotlinx.coroutines.flow.Flow

/**
 * One piece of student work waiting to reach the server.
 *
 * `id` is autogenerated rather than keyed off [key] because a student can
 * queue more than one write for the same key before a drain runs — the
 * whole point of this table is to let writes queue up rather than
 * overwrite each other, and losing that ordering would lose the student's
 * most recent edit.
 */
@Entity(tableName = "outbox")
data class OutboxEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val key: String,
    val json: String,
    val savedAt: Instant,
    val attempts: Int = 0,
)

@Dao
interface OutboxDao {

    @Insert
    suspend fun insert(entity: OutboxEntity): Long

    /** Oldest first — the order writes should be replayed to the server in. */
    @Query("SELECT * FROM outbox ORDER BY id")
    suspend fun all(): List<OutboxEntity>

    /**
     * Deletes exactly one queued write, by id.
     *
     * Never "delete everything read so far": a write can be enqueued while a
     * drain of an earlier batch is still in flight, and a blanket delete
     * would discard it along with the batch that was actually sent.
     */
    @Query("DELETE FROM outbox WHERE id = :id")
    suspend fun deleteById(id: Long)

    @Query("SELECT COUNT(*) FROM outbox")
    fun count(): Flow<Int>
}
