/**
 * A corpus source index for the Alexandria University manifests.
 *
 *   node --experimental-strip-types scripts/alexandria/build-source-index.ts
 *
 * Adapted from scripts/kasr/build-source-index.ts (commit 6e6edf1) — Kasr's
 * file, not edited; this is Alexandria's own copy. `validate-content-batch.mjs`
 * looks for `corpus-source-index.json` beside the batch it is validating, in
 * the same schema Kasr's writes, so this produces the same shape:
 * `docs/Alexandria-Source-Imports/evidence/corpus-source-index.json`.
 *
 * The one real difference: Kasr has a single manifest file. Alexandria's
 * corpus tree was never moved (unlike Kasr's, which move.py rewrote into one
 * layout first), so it is described by **four** manifests — one per
 * `y1`/`y2`/`y3`/`General Resources` top folder — and this script reads all
 * four and merges them into one index, so a validator checking a `src_`
 * citation against ANY Alexandria module or year still finds it in one file.
 *
 * This mints nothing. Every ID, path and hash below is copied from the
 * manifests, which are themselves generated from the corpus files. An ID
 * that is not in a manifest is still an invented ID and still refused.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const REPO = process.cwd()
const MANIFESTS = [
  'docs/Alexandria-Source-Imports/manifest/au-y1-sources.json',
  'docs/Alexandria-Source-Imports/manifest/au-y2-sources.json',
  'docs/Alexandria-Source-Imports/manifest/au-y3-sources.json',
  'docs/Alexandria-Source-Imports/manifest/au-general-sources.json',
]
const OUT = 'docs/Alexandria-Source-Imports/evidence/corpus-source-index.json'

interface ManifestSource {
  sourceId: string
  corpusRelativePath: string
  sourceRelativePaths: string[]
  sha256: string
  probeStatus: string | null
  textLayer: string | null
  pageCount: number | null
  fileType: string
  exclusionReason: string | null
}

interface ManifestDoc {
  generatedOn: string
  count: number
  sources: ManifestSource[]
}

const manifestDocs = MANIFESTS.map((path) => ({
  path,
  doc: JSON.parse(readFileSync(join(REPO, path), 'utf8')) as ManifestDoc,
}))

/**
 * A sourceId is content-addressed (first 20 hex chars of a sha256), so the
 * same id appearing in more than one of the four manifests always means the
 * same bytes — which cannot happen here, since a file only lives under one of
 * y1/y2/y3/General Resources. Kept as a paths-set merge anyway (rather than
 * "last manifest wins") for the same reason Kasr's does: an arbitrary pick
 * that happens to be stable across regenerations still hides that it was a
 * flip, the day it stops being stable.
 */
const paths = new Map<string, Set<string>>()
for (const { doc } of manifestDocs) {
  for (const source of doc.sources) {
    const seen = paths.get(source.sourceId) ?? new Set<string>()
    for (const p of source.sourceRelativePaths) seen.add(p)
    paths.set(source.sourceId, seen)
  }
}

const sources: Record<string, unknown> = {}
let excluded = 0
let ambiguous = 0
let manifestGeneratedOn: string | undefined
for (const { doc } of manifestDocs) {
  manifestGeneratedOn = manifestGeneratedOn ?? doc.generatedOn
  for (const source of doc.sources) {
    if (source.exclusionReason && !sources[source.sourceId]) excluded += 1
    const all = [...(paths.get(source.sourceId) ?? [])].sort()
    if (all.length > 1 && !sources[source.sourceId]) ambiguous += 1
    sources[source.sourceId] = {
      sourceRelativePath: all.length === 1 ? all[0] : null,
      sourceRelativePaths: all,
      sha256: source.sha256,
      processingStatus: source.probeStatus,
      textLayer: source.textLayer,
      pageCount: source.pageCount ?? null,
      fileType: source.fileType,
      languages: [],
      exclusionReason: source.exclusionReason ?? null,
    }
  }
}

mkdirSync(dirname(join(REPO, OUT)), { recursive: true })
writeFileSync(join(REPO, OUT), `${JSON.stringify({
  note: 'Every source ID the Alexandria University y1/y2/y3/General Resources corpus '
    + 'contains, merged from its four manifests. A batch naming a src_ ID absent from here '
    + 'is naming a source that does not exist. Generated by '
    + 'scripts/alexandria/build-source-index.ts — do not hand-edit.',
  generatedFrom: MANIFESTS,
  manifestGeneratedOn,
  count: Object.keys(sources).length,
  sources,
}, null, 1)}\n`)

console.log(JSON.stringify({ sources: Object.keys(sources).length, excluded, ambiguous, out: OUT }, null, 1))
