import { pool } from '../src/db.js'
const [[l]] = await pool.query("SELECT v FROM app_state WHERE k='nishany-admin-content-ledger-v4'")
const [[g]] = await pool.query("SELECT v FROM app_state WHERE k='nishany-concept-graph-v2'")
const ledger = JSON.parse(l.v), graph = JSON.parse(g.v)
const VALID = new Set(['cvs','resp','renal','gi','neuro','endo','msk','pharm','fnd','dev','haem','imm','inf','obs','gyn','androl','psy','derm','mul','pop'])
const badItems = ledger.filter((i) => i.subjectId && !VALID.has(i.subjectId))
const badConcepts = (graph.concepts ?? []).filter((c) => c.subjectId && !VALID.has(c.subjectId))
const tally = (rows) => rows.reduce((a, r) => { a[r] = (a[r] ?? 0) + 1; return a }, {})
console.log('ledger items still on an invalid subject:', badItems.length, tally(badItems.map((i) => `${i.kind}:${i.subjectId}`)))
console.log('concepts still on an invalid subject:', badConcepts.length)
console.log('articles by subject:', tally(ledger.filter((i) => i.kind === 'article').map((i) => i.subjectId)))
const [[v]] = await pool.query("SELECT COUNT(*) AS n FROM app_state_versions WHERE actor_id LIKE 'migration:2026-08-13%'")
console.log('rollback snapshots written:', v.n)
const [m] = await pool.query("SELECT id FROM schema_migrations WHERE id LIKE '2026-08-13%'")
console.log('migration recorded:', m.map((r) => r.id))
await pool.end()
