import SwiftUI

/// "This app can use AI" — shown once, before the AI-backed surfaces (the
/// study assistant, adaptive study) are reached for the first time, and
/// re-openable afterwards from About/Legal.
///
/// Gated on `aiConsentAt` from `/api/me` rather than a local default: the
/// account is what should remember this, the same way it remembers which
/// language a student reads in, so re-installing the app does not ask again.
struct AIDisclaimerView: View {
    let api: SynapseAPI
    /// Called once consent is recorded, so the caller can dismiss the sheet
    /// and (on first launch) stop gating the rest of the app on it.
    var onAccept: () -> Void = {}

    @Environment(\.strings) private var strings
    @Environment(\.dismiss) private var dismiss

    @State private var isSaving = false
    @State private var failure: String?

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    Image(systemName: "sparkles")
                        .font(.system(size: 30))
                        .foregroundStyle(Theme.primary)

                    Text(strings("Nishany uses AI"))
                        .font(Theme.display(22))
                        .foregroundStyle(Theme.ink)

                    Text(strings("The study assistant and parts of adaptive study are generated by an AI model. It can be wrong — treat it as a study aid, not as a substitute for your course material or your instructors, and double-check anything before an exam depends on it."))
                        .font(Theme.ui(14))
                        .foregroundStyle(Theme.ink2)

                    Text(strings("Messages you send it are processed to generate a reply. Nothing here changes what the rest of the app does with your data."))
                        .font(Theme.ui(13))
                        .foregroundStyle(Theme.ink3)

                    if let failure {
                        Text(failure)
                            .font(Theme.ui(12.5))
                            .foregroundStyle(Theme.danger)
                    }

                    Button {
                        Task { await accept() }
                    } label: {
                        HStack {
                            if isSaving { ProgressView().controlSize(.small) }
                            Text(strings(isSaving ? "Saving…" : "I understand"))
                        }
                        .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.borderedProminent)
                    .tint(Theme.primary)
                    .disabled(isSaving)
                    .padding(.top, 4)
                }
                .padding(20)
            }
            .background(Theme.paper)
            .navigationTitle(strings("About AI in Nishany"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button(strings("Close")) { dismiss() }
                        .tint(Theme.primary)
                }
            }
        }
        .interactiveDismissDisabled(isSaving)
    }

    private func accept() async {
        isSaving = true
        failure = nil
        defer { isSaving = false }
        do {
            _ = try await api.setAIConsent()
            onAccept()
            dismiss()
        } catch {
            failure = strings("That could not be saved. Check your connection and try again.")
        }
    }
}
