/**
 * Authored medicine game packs.
 *
 * These packs are static content: gameplay code may shuffle, score and render
 * them, but it never invents medical facts. New packs should come from the
 * content/import pipeline and pass `validateMiniGamePack` before they are shown
 * to students.
 *
 * Pure module: no React, no storage, no clock.
 */

import { seededRandom, shuffle } from './seededRandom.ts'

export type MiniGameKind = 'clinical_sequence' | 'mechanism_chain' | 'red_flag_sort'

interface BasePack {
  id: string
  kind: MiniGameKind
  title: string
  subjectId: string
  topic: string
  summary: string
  source: {
    label: string
    reviewedBy: string
  }
}

export interface OrderedStep {
  id: string
  text: string
}

export interface OrderedMiniGamePack extends BasePack {
  kind: 'clinical_sequence' | 'mechanism_chain'
  prompt: string
  steps: OrderedStep[]
  explanation: string
}

export interface RedFlagFinding {
  id: string
  text: string
  lane: 'urgent' | 'routine'
  rationale: string
}

export interface RedFlagSortPack extends BasePack {
  kind: 'red_flag_sort'
  prompt: string
  lanes: Record<RedFlagFinding['lane'], string>
  findings: RedFlagFinding[]
}

export type MiniGamePack = OrderedMiniGamePack | RedFlagSortPack

export const MINI_GAME_PACKS: MiniGamePack[] = [
  {
    id: 'cs-basic-life-support-primary-survey',
    kind: 'clinical_sequence',
    title: 'Basic life support primary survey',
    subjectId: 'fnd',
    topic: 'Emergencies & red flags',
    summary: 'Order the first response steps for an unresponsive adult in a teaching scenario.',
    prompt: 'Place the actions in the order a responder should take before ongoing reassessment.',
    source: { label: 'Synapse authored emergency-skills seed pack', reviewedBy: 'Content operations' },
    steps: [
      { id: 'danger', text: 'Check the scene for danger before approaching.' },
      { id: 'response', text: 'Check responsiveness and call for help.' },
      { id: 'airway', text: 'Open the airway.' },
      { id: 'breathing', text: 'Check breathing.' },
      { id: 'compressions', text: 'Start chest compressions if breathing is absent or abnormal.' },
      { id: 'aed', text: 'Attach an AED as soon as it is available and follow prompts.' },
    ],
    explanation: 'The pack follows the authored primary-survey order; the game only asks students to reconstruct that order.',
  },
  {
    id: 'mc-heart-failure-compensation',
    kind: 'mechanism_chain',
    title: 'Heart failure compensation loop',
    subjectId: 'cvs',
    topic: 'Heart failure',
    summary: 'Order the authored cause-to-effect chain behind short-term compensation and longer-term worsening.',
    prompt: 'Arrange the mechanism from the initiating haemodynamic problem to the maladaptive outcome.',
    source: { label: 'Synapse authored CVS seed pack', reviewedBy: 'Content operations' },
    steps: [
      { id: 'low-output', text: 'Reduced effective cardiac output is sensed.' },
      { id: 'sympathetic', text: 'Sympathetic and renin–angiotensin activation increase.' },
      { id: 'retention', text: 'Salt and water retention raises filling pressures.' },
      { id: 'wall-stress', text: 'Higher wall stress increases myocardial workload.' },
      { id: 'remodelling', text: 'Progressive remodelling worsens pump function.' },
    ],
    explanation: 'Each step is authored as a fixed chain; no mechanism is generated by the app at runtime.',
  },
  {
    id: 'rf-respiratory-escalation',
    kind: 'red_flag_sort',
    title: 'Respiratory escalation signals',
    subjectId: 'res',
    topic: 'Respiratory safety',
    summary: 'Sort respiratory findings into urgent escalation versus routine review.',
    prompt: 'Classify each authored finding by the action it should trigger in this learning scenario.',
    source: { label: 'Synapse authored respiratory seed pack', reviewedBy: 'Content operations' },
    lanes: {
      urgent: 'Urgent escalation',
      routine: 'Routine review',
    },
    findings: [
      {
        id: 'silent-chest',
        text: 'Silent chest with marked breathlessness',
        lane: 'urgent',
        rationale: 'This is authored as an emergency-pattern finding in this pack.',
      },
      {
        id: 'cyanosis',
        text: 'Cyanosis or exhaustion',
        lane: 'urgent',
        rationale: 'This is authored as an urgent deterioration signal in this pack.',
      },
      {
        id: 'mild-cough',
        text: 'Mild cough with normal activity and no distress',
        lane: 'routine',
        rationale: 'This is authored here as appropriate for routine review.',
      },
      {
        id: 'inhaler-technique',
        text: 'Poor inhaler technique without acute distress',
        lane: 'routine',
        rationale: 'This pack classifies it as a routine education/review issue.',
      },
      {
        id: 'saba-overuse',
        text: 'Frequent SABA use without inhaled corticosteroid cover',
        lane: 'urgent',
        rationale: 'The authored library seed marks this as a red flag for poor control and exacerbation risk.',
      },
      {
        id: 'stable-wheeze',
        text: 'Occasional wheeze responding to the usual reliever plan',
        lane: 'routine',
        rationale: 'This pack treats the stable pattern as a routine follow-up finding.',
      },
    ],
  },
]

export function validateMiniGamePack(pack: MiniGamePack): string[] {
  const errors: string[] = []
  if (!pack.id.trim()) errors.push('id is required')
  if (!pack.title.trim()) errors.push(`${pack.id}: title is required`)
  if (!pack.subjectId.trim()) errors.push(`${pack.id}: subjectId is required`)
  if (!pack.source.label.trim() || !pack.source.reviewedBy.trim()) errors.push(`${pack.id}: reviewed source metadata is required`)

  if (pack.kind === 'red_flag_sort') {
    if (!pack.lanes.urgent.trim() || !pack.lanes.routine.trim()) errors.push(`${pack.id}: both red-flag lanes are required`)
    if (pack.findings.length < 4) errors.push(`${pack.id}: at least four findings are required`)
    const lanes = new Set(pack.findings.map((finding) => finding.lane))
    if (!lanes.has('urgent') || !lanes.has('routine')) errors.push(`${pack.id}: both urgent and routine findings are required`)
    for (const finding of pack.findings) {
      if (!finding.id.trim() || !finding.text.trim() || !finding.rationale.trim()) errors.push(`${pack.id}: every finding needs id, text and rationale`)
    }
    return errors
  }

  if (pack.steps.length < 3) errors.push(`${pack.id}: at least three ordered steps are required`)
  for (const step of pack.steps) {
    if (!step.id.trim() || !step.text.trim()) errors.push(`${pack.id}: every step needs id and text`)
  }
  if (new Set(pack.steps.map((step) => step.id)).size !== pack.steps.length) errors.push(`${pack.id}: step ids must be unique`)
  return errors
}

export function validMiniGamePacks(kind?: MiniGameKind): MiniGamePack[] {
  return MINI_GAME_PACKS.filter((pack) => (!kind || pack.kind === kind) && validateMiniGamePack(pack).length === 0)
}

export function shuffledStepIds(pack: OrderedMiniGamePack, seed: number): string[] {
  return shuffle(pack.steps.map((step) => step.id), seededRandom(seed))
}

export function scoreOrderedSteps(pack: OrderedMiniGamePack, submittedIds: string[]) {
  const correct = pack.steps.map((step) => step.id)
  let exactPositions = 0
  for (let i = 0; i < correct.length; i++) {
    if (submittedIds[i] === correct[i]) exactPositions++
  }
  return {
    exactPositions,
    total: correct.length,
    complete: submittedIds.length === correct.length && submittedIds.every((id) => correct.includes(id)),
    correct,
  }
}

export function scoreRedFlagSort(pack: RedFlagSortPack, placements: Record<string, RedFlagFinding['lane']>) {
  let correct = 0
  const results = pack.findings.map((finding) => {
    const selected = placements[finding.id]
    const matched = selected === finding.lane
    if (matched) correct++
    return { finding, selected, correct: matched }
  })
  return { correct, total: pack.findings.length, results }
}
